In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import datetime
%matplotlib inline

In [2]:
os.chdir("CRE Data")

In [9]:
dftarget=pd.read_excel("targetfull v2.xlsx")

In [10]:
dftarget

,DATE,CUST_NAME,FACILITY_NUM,FACILITY_NAME,CRR,MaxCrr,DowngradeMax,DowngradeMax Notch,UpgradeMax,UpgradeMax Notch,Downgrade,Downgrade Notch,NET_COMMIT_AMT,OUT_BAL,RE_RISK_PROPERTY_TYPE,RE_STATE_NAME,RE_COUNTY_NAME
33237,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0,0,0,0,0.0,0.0,567600.00,567600.00,INDUSTRIAL,CALIFORNIA,NaN
135959,2005-03-31,RANCHO MONTEREY LTD PARTNERSHIP,7.257413e+19,RANCHO MONTEREY LTD,3,3.0,0,0,0,0,0.0,0.0,5014170.84,5014170.84,APARTMENT,CALIFORNIA,ORANGE
135966,2005-03-31,RANCHO PARK ASSOCIATES,7.257458e+19,RANCHO PARK ASSOCIATES,6,6.0,0,0,0,0,0.0,0.0,31531.02,31531.02,APARTMENT,CALIFORNIA,SAN BENITO
83194,2005-03-31,RANDALL E KESSLER,5.061000e+19,RANDALL E KESSLER,5,5.0,0,0,0,0,0.0,0.0,662094.40,662094.40,OFFICE,CALIFORNIA,ALAMEDA
65107,2005-03-31,RANDELL S HANSEN,3.455089e+19,RANDELL S HANSEN,6,6.0,0,0,0,0,0.0,0.0,165839.94,165839.94,NaN,CALIFORNIA,SAN DIEGO
66846,2005-03-31,RANDHIR S HAYER,3.545888e+19,RANDHIR S HAYER,6,6.0,0,0,0,0,0.0,0.0,166727.48,166727.48,APARTMENT,CALIFORNIA,MERCED
45409,2005-03-31,EDEN GROUP LLC,2.425701e+19,EDEN GROUP LLC,6,6.0,0,0,0,0,0.0,0.0,5273892.16,5273892.16,NON-RES INCOME,CALIFORNIA,ORANGE
184192,2005-03-31,EDDIE KA KEUNG WONG,9.896967e+19,EDDIE KA KEUNG WONG,6,6.0,0,0,0,0,0.0,0.0,633508.01,633508.01,OFFICE,CALIFORNIA,SAN FRANCISCO
39877,2005-03-31,RANDY J DENHAM,2.031515e+19,RANDY J DENHAM,6,6.0,0,0,0,0,0.0,0.0,306844.24,306844.24,NON-RES INCOME,CALIFORNIA,SHASTA
46181,2005-03-31,RANDY S EIFLER,2.480701e+19,RANDY S EIFLER,5,5.0,0,0,0,0,0.0,0.0,551479.47,551479.47,INDUSTRIAL,CALIFORNIA,SAN DIEGO
44419,2005-03-31,EDD INVESTMENTS CO,2.387705e+19,E D D INVESTMENT CO,6,6.0,0,0,0,0,0.0,0.0,263983.18,263983.18,RETAIL,CALIFORNIA,ORANGE
115170,2005-03-31,RAPHAEL N NISSIM,6.579286e+19,RAPHAEL N NISSIM,8,8.0,0,0,0,0,0.0,0.0,185170.92,185170.92,INDUSTRIAL,CALIFORNIA,MARIN
156181,2005-03-31,RAPHAEL SAADIQ,8.449873e+19,RAPHAEL SAADIQ,6,6.0,0,0,0,0,0.0,0.0,731197.68,731197.68,RETAIL,CALIFORNIA,LOS ANGELES
45311,2005-03-31,ECHOPOD LLC,2.416647e+19,ECHOPOD LLC,6,6.0,0,0,0,0,0.0,0.0,884721.65,884721.65,OFFICE,CALIFORNIA,LOS ANGELES
136589,2005-03-31,RATTAN/FORTIE PROPERTIES LLC,7.270881e+19,RATTAN/FORTIE PROPERTIES LLC,5,5.0,0,0,0,0,0.0,0.0,851309.14,851309.14,OFFICE,CALIFORNIA,SAN DIEGO
136635,2005-03-31,RAUDMAN LIVING TRUST,7.271093e+19,RAUDMAN 1989 REVOCABLE LIVING,6,6.0,0,0,0,0,0.0,0.0,1330178.35,1330178.35,INDUSTRIAL,CALIFORNIA,SHASTA
108976,2005-03-31,RAUL J MORALES,6.361266e+19,RAUL J MORALES,6,6.0,0,0,0,0,0.0,0.0,438417.52,438417.52,APARTMENT,CALIFORNIA,SANTA CRUZ
182306,2005-03-31,WILBUR-PARTHENIA LLC,9.798985e+19,WILBUR-PARTHENIA LLC,4,4.0,0,0,0,0,0.0,0.0,2564719.88,2564719.88,INDUSTRIAL,CALIFORNIA,LOS ANGELES
45157,2005-03-31,EASTSHORE PROPERTIES LLC,2.404117e+19,EASTSHORE PROPERTIES LLC A,6,6.0,0,0,0,0,0.0,0.0,2624352.52,2624352.52,INDUSTRIAL,CALIFORNIA,CONTRA COSTA
45147,2005-03-31,EASTSHORE PROPERTIES LLC,2.404117e+19,EASTSHORE PROPERTIES LLC A,6,6.0,0,0,0,0,0.0,0.0,1412546.58,1412546.58,INDUSTRIAL,CALIFORNIA,CONTRA COSTA
136691,2005-03-31,RAVEN CLIFF ENTERPRISES LLC,7.271701e+19,RAVEN CLIFF ENTERPRISES LLC,6,6.0,0,0,0,0,0.0,0.0,3706811.84,3706811.84,OFFICE,CALIFORNIA,ALAMEDA
156087,2005-03-31,RAYMOND ADRIAN SMITH,8.446200e+19,RAYMOND ADRIAN SMITH,6,6.0,0,0,0,0,0.0,0.0,485334.31,485334.31,INDUSTRIAL,CALIFORNIA,ORANGE
44956,2005-03-31,EASTGATE MIRAMAR ASSOCIATES,2.404116e+19,EASTGATE MIRAMAR ASSOCIATES,4,5.0,0,0,0,0,0.0,0.0,3708035.69,3708035.69,INDUSTRIAL,CALIFORNIA,SAN DIEGO
44924,2005-03-31,EASTGATE MIRAMAR ASSOCIATES,2.404116e+19,EASTGATE MIRAMAR ASSOCIATES,5,5.0,0,0,0,0,0.0,0.0,14386365.92,14386365.92,INDUSTRIAL,CALIFORNIA,SAN DIEGO
44897,2005-03-31,EASTGATE MEDIA GROUP LLC,2.404115e+19,EASTGATE MEDIA GROUP LLC,6,6.0,0,0,0,0,0.0,0.0,2193299.30,2193299.30,INDUSTRIAL,CALIFORNIA,SAN DIEGO
182263,2005-03-31,WIDDES REVOCABLE TRUST,9.782619e+19,WIDDES REVOCABLE TRUST,6,6.0,0,0,0,0,0.0,0.0,562836.23,562836.23,INDUSTRIAL,CALIFORNIA,LOS ANGELES
182184,2005-03-31,WHITTIER NARROWS BUSINESS PRK,9.769592e+19,WHITTIER NARROWS BUSINESS PK,4,4.0,0,0,0,0,0.0,0.0,5152628.43,5152628.43,OFFICE,CALIFORNIA,LOS ANGELES
45199,2005-03-31,EASTER SEALS CENTRAL CALIFORNIA,2.404215e+19,EASTER SEALS CENTRAL,7,7.0,0,0,0,0,0.0,0.0,274000.00,272754.72,NaN,CALIFORNIA,SANTA CRUZ
45195,2005-03-31,EASTER SEALS CENTRAL CALIFORNIA,2.404215e+19,EASTER SEALS CENTRAL,7,7.0,0,0,0,0,0.0,0.0,149916.19,149916.19,OFFICE,CALIFORNIA,SANTA CRUZ
104120,2005-03-31,RAYMOND F MELISSA,6.074471e+19,MELISSA RAYMOND & ROBERTA,6,6.0,0,0,0,0,0.0,0.0,1130620.85,1130620.85,OFFICE,CALIFORNIA,ORANGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8821,2017-12-31,"AUBURN PARK FAMILY HOUSING, LLC",5.485478e+18,AUBURN PARK FAMILY HOUSING,5,5.0,0,0,0,0,0.0,0.0,1702919.06,1702919.06,APARTMENT,CALIFORNIA,SAN DIEGO (CA)
25873,2017-12-31,CELEBRATION SENIOR LIVING WEST,1.251820e+19,CELEBRATION SENIOR LIVING,5,5.0,0,0,0,0,0.0,0.0,21099999.88,20457761.31,APARTMENT,WASHINGTON,KING (WA)
194938,2017-12-31,"75 ROUNDTABLE, LLC",9.996801e+19,75 ROUNDTABLE LLC,5,5.0,0,0,0,0,0.0,0.0,972534.17,972534.17,APARTMENT,CALIFORNIA,SANTA CLARA (CA)
83436,2017-12-31,"KGP I, LLC",5.087065e+19,KGP I LLC,5,5.0,0,0,0,0,0.0,0.0,573599.71,573599.71,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
193253,2017-12-31,3423 FOREST LANE LLC,9.994509e+19,3423 FOREST LANE LLC,3,3.0,0,0,0,0,0.0,0.0,1920801.43,1920801.43,APARTMENT,TEXAS,DALLAS (TX)
44000,2017-12-31,"D.Y. PARTNERS, LLC",2.370116e+19,DY PARTNERS LLC,5,5.0,0,0,0,0,0.0,0.0,1168259.16,1168259.16,RETAIL,CALIFORNIA,LOS ANGELES (CA)
8890,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,780000.00,780000.00,INDUSTRIAL,CALIFORNIA,SAN JOAQUIN (CA)
8889,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,4600801.36,4600801.36,INDUSTRIAL,CALIFORNIA,KERN (CA)
8881,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,425530.26,425530.26,INDUSTRIAL,CALIFORNIA,FRESNO (CA)
8873,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,478886.84,478886.84,INDUSTRIAL,NORTH DAKOTA,NORTH DAKOTA
8860,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,501605.30,501605.30,INDUSTRIAL,TEXAS,HARRIS (TX)
21811,2017-12-31,"CALIFORNIA SKY INVESTMENT GROUP, LLC",1.078318e+19,CALIFORNIA SKY INVESTMENT,5,5.0,0,0,1,1,0.0,0.0,401152.70,401152.70,NON-RES INCOME,CALIFORNIA,LOS ANGELES (CA)
21820,2017-12-31,"CALIFORNIA SKY INVESTMENT GROUP, LLC",1.078318e+19,CALIFORNIA SKY INVESTMENT,5,5.0,0,0,0,0,0.0,0.0,474107.26,474107.26,NON-RES INCOME,CALIFORNIA,ORANGE (CA)
101233,2017-12-31,"MARYMEAD AFFORDABLE HOUSING, L.P.",5.978559e+19,MARYMEAD AFFORDABLE HOUSING,3,3.0,0,0,1,1,0.0,0.0,2005338.93,2005338.93,APARTMENT,CALIFORNIA,YUBA (CA)
10384,2017-12-31,JANICE SOOKYUNG BAE,5.843547e+18,JANICE SOOKYUNG BAE,6,6.0,0,0,0,0,0.0,0.0,2159132.68,2159132.68,RETAIL,CALIFORNIA,LOS ANGELES (CA)
123645,2017-12-31,"PARADIGM 20815 SHERMAN WAY, LLC",6.830293e+19,PARADIGM 20815 SHERMAN WAY,5,5.0,0,0,0,0,0.0,0.0,1863974.39,1863974.39,RETAIL,CALIFORNIA,ORANGE (CA)
21829,2017-12-31,"CALIFORNIA SKY INVESTMENT GROUP, LLC",1.078318e+19,CALIFORNIA SKY INVESTMENT,5,5.0,0,0,0,0,0.0,0.0,784345.72,784345.72,NON-RES INCOME,CALIFORNIA,ORANGE (CA)
8847,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,588771.76,588771.76,INDUSTRIAL,CALIFORNIA,VENTURA (CA)
124680,2017-12-31,"PARADIGM 6653 DARBY, LLC",6.892256e+19,PARADIGM 6653 DARBY LLC,4,4.0,0,0,0,0,0.0,0.0,910050.90,910050.90,RETAIL,CALIFORNIA,VENTURA (CA)
193241,2017-12-31,3401 S SUNFLOWER LLC,9.994490e+19,3401 S SUNFLOWER LLC,5,5.0,0,0,0,0,0.0,0.0,1595266.07,1595266.07,OFFICE,CALIFORNIA,ORANGE (CA)
191389,2017-12-31,2045 EAST WASHINGTON LLC,9.991683e+19,2045 EAST WASHINGTON LLC,4,4.0,0,0,0,0,0.0,0.0,6933330.08,6933330.08,INDUSTRIAL,CALIFORNIA,LOS ANGELES (CA)
44158,2017-12-31,"D1 SENIOR IRVINE HOUSING PARTNERS, L.P.",2.382640e+19,D1 SENIOR IRVINE HOUSING,5,5.0,0,0,0,0,0.0,0.0,12675605.28,9378484.99,APARTMENT,CALIFORNIA,ORANGE (CA)
160342,2017-12-31,"PREMIUM INVESTMENT PROPERTIES, LLC",8.706783e+19,PREMIUM INVESTMENT PROPERTIES,7,7.0,0,0,0,0,0.0,0.0,4811571.26,4811571.26,INDUSTRIAL,CALIFORNIA,LOS ANGELES (CA)
128265,2017-12-31,"PHYLLIS SCHROBSDORFF LIVING TRUST, DATED",7.076694e+19,PHYLLIS SCHROBSDORFF LIVING,6,6.0,0,0,0,0,0.0,0.0,1688615.77,1688615.77,APARTMENT,CALIFORNIA,SAN FRANCISCO (CA)
31715,2017-12-31,MARYTRESE COMER SEPARATE PROPERTY TRUST,1.537001e+19,MARYTRESE COMER SEPARATE,4,4.0,0,0,1,1,0.0,0.0,476943.10,476943.10,APARTMENT,CALIFORNIA,SAN DIEGO (CA)
76416,2017-12-31,"JANE'S HOUSE SQUARE, LLC",4.037953e+19,JANE'S HOUSE SQUARE LLC,4,4.0,0,0,0,0,0.0,0.0,1882699.64,1882699.64,RETAIL,CALIFORNIA,LOS ANGELES (CA)
123663,2017-12-31,"PARADIGM 7249 JORDAN, LLC",6.830319e+19,PARADIGM 7249 JORDAN LLC,3,3.0,0,0,0,0,0.0,0.0,913750.16,913750.16,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
85712,2017-12-31,GARY A MORSE EXEMPTION TRUST,5.100910e+19,GARY A MORSE EXEMPTION TRUST,5,5.0,0,0,0,0,0.0,0.0,1866199.08,1866199.08,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
1558,2017-12-31,AUDREY N. NEWTON TRUST DTD 12/3/04,6.875535e+17,THE AUDREY N NEWTON TRUST,5,5.0,0,0,1,1,0.0,0.0,983827.40,983827.40,RETAIL,CALIFORNIA,ORANGE (CA)
70808,2017-12-31,HOMELAND PROPERTIES LLC,3.675224e+19,HOMELAND PROPERTIES LLC,6,6.0,0,0,0,0,0.0,0.0,895992.03,895992.03,APARTMENT,CALIFORNIA,ORANGE (CA)

In [11]:
dftarget['DowngradeMax'].value_counts()

0    189600
1      6205
Name: DowngradeMax, dtype: int64

In [12]:
dftarget['UpgradeMax'].value_counts()

0    190118
1      5687
Name: UpgradeMax, dtype: int64

In [22]:
dftarget['RE_RISK_PROPERTY_TYPE'].value_counts()

APARTMENT                    81787
INDUSTRIAL                   36348
RETAIL                       25705
OFFICE                       22418
NON-RES INCOME               10734
OTHER                         4691
UNSECURED                     4556
SFR                           3202
OTHER REAL ESTATE SECURED     1407
LAND                          1261
FOR SALE                      1113
UNCATEGORIZED                  829
SECURED - NON RE               210
OTHER REAL ESTATE               16
UNKNOWN                          5
Name: RE_RISK_PROPERTY_TYPE, dtype: int64

In [13]:
os.chdir("..")

In [14]:
os.chdir("Updated Material")

In [15]:
dfMarket=pd.read_excel("dfVariable2WidedfDate.xlsx")

In [16]:
dfMarket

,Date,Geography_Code,Geography_Name,Property_Code,Property_Name,1+ Unit Permitting,1+ Unit Starts,2+ Unit Permitting,2+ Unit Starts,Cap Rate Spread,...,Price Growth,Rent Growth,Res. Invest. Share of GDP,Retail Sales Growth,RevPar Growth,Strip Rent Growth,Trade Emp. Growth,Trans. Emp. Growth,Trans. Vol. (Bil. $),Vacancy Rate
0,1982-03-31,ATLNA,Atlanta,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1982-03-31,ATLNA,Atlanta,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1982-03-31,ATLNA,Atlanta,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1982-03-31,ATLNA,Atlanta,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1982-03-31,BOSTN,Boston,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1982-03-31,BOSTN,Boston,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1982-03-31,BOSTN,Boston,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1982-03-31,BOSTN,Boston,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1982-03-31,BOSTN,Boston,OWN0,For-Sale,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1982-03-31,BOSTN,Boston,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1982-03-31,CHICG,Chicago,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1982-03-31,CHICG,Chicago,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1982-03-31,CHICG,Chicago,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1982-03-31,CHICG,Chicago,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1982-03-31,CHICG,Chicago,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1982-03-31,DALLS,Dallas,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1982-03-31,DALLS,Dallas,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1982-03-31,DALLS,Dallas,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1982-03-31,DALLS,Dallas,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1982-03-31,DENVR,Denver,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1982-03-31,ILEMP,Inland Empire,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1982-03-31,ILEMP,Inland Empire,OWN0,For-Sale,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1982-03-31,LSAGL,Los Angeles,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1982-03-31,LSAGL,Los Angeles,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1982-03-31,LSAGL,Los Angeles,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1982-03-31,LSAGL,Los Angeles,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1982-03-31,LSAGL,Los Angeles,OWN0,For-Sale,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1982-03-31,LSAGL,Los Angeles,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1982-03-31,MIAMI,Miami,OWN0,For-Sale,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1982-03-31,NYORK,New York,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10554,2018-12-31,SDIGO,San Diego,OFC0,Office,NaN,NaN,NaN,NaN,0.03725,...,NaN,0.020998,NaN,NaN,NaN,NaN,NaN,NaN,2.541578,0.118787
10555,2018-12-31,SDIGO,San Diego,OWN0,For-Sale,3992.318771,NaN,NaN,NaN,NaN,...,0.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10556,2018-12-31,SDIGO,San Diego,RET0,Retail,NaN,NaN,NaN,NaN,0.02715,...,NaN,-0.020000,NaN,NaN,NaN,NaN,NaN,NaN,1.664430,0.046271
10557,2018-12-31,SEATL,Seattle,APT0,Apartment,NaN,NaN,5256.339667,NaN,0.01860,...,NaN,0.046552,NaN,NaN,NaN,NaN,NaN,NaN,4.114950,NaN
10558,2018-12-31,SEATL,Seattle,IND0,Industrial,NaN,NaN,NaN,NaN,0.01350,...,NaN,0.090000,NaN,NaN,NaN,NaN,0.040297,0.021000,0.962553,0.042432
10559,2018-12-31,SEATL,Seattle,OFC0,Office,NaN,NaN,NaN,NaN,0.02885,...,NaN,0.010861,NaN,NaN,NaN,NaN,NaN,NaN,4.216027,0.075428
10560,2018-12-31,SEATL,Seattle,OWN0,For-Sale,6776.092488,NaN,NaN,NaN,NaN,...,0.132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10561,2018-12-31,SEATL,Seattle,RET0,Retail,NaN,NaN,NaN,NaN,0.02845,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.224054,0.046630
10562,2018-12-31,SFRAN,San Francisco,APT0,Apartment,NaN,NaN,1926.493240,NaN,0.00650,...,NaN,0.036056,NaN,NaN,NaN,NaN,NaN,NaN,1.610031,NaN
10563,2018-12-31,SFRAN,San Francisco,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10564,2018-12-31,SFRAN,San Francisco,OFC0,Office,NaN,NaN,NaN,NaN,0.02755,...,NaN,0.037195,NaN,NaN,NaN,NaN,NaN,NaN,4.375410,0.077355
10565,2018-12-31,SFRAN,San Francisco,OWN0,For-Sale,2046.102976,NaN,NaN,NaN,NaN,...,0.096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10566,2018-12-31,SFRAN,San Francisco,RET0,Retail,NaN,NaN,NaN,NaN,0.01585,...,NaN,0.035000,NaN,NaN,NaN,NaN,NaN,NaN,0.734318,0.017162
10567,2018-12-31,SJOSE,San Jose,APT0,Apartment,NaN,NaN,2065.242980,NaN,0.01330,...,NaN,0.043039,NaN,NaN,NaN,NaN,NaN,NaN,1.112461,NaN
10568,2018-12-31,SJOSE,San Jose,IND0,Industrial,NaN,NaN,NaN,NaN,0.02840,...,NaN,0.050000,NaN,NaN,NaN,NaN,0.008000,0.005000,2.791184,0.055322
10569,2018-12-31,SJOSE,San Jose,OFC0,Office,NaN,NaN,NaN,NaN,0.02995,...,NaN,0.040676,NaN,NaN,NaN,NaN,NaN,NaN,4.776058,0.087713
10570,2018-12-31,SJOSE,San Jose,OWN0,For-Sale,2785.382370,NaN,NaN,NaN,NaN,...,0.150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10571,2018-12-31,SJOSE,San Jose,RET0,Retail,NaN,NaN,NaN,NaN,0.02325,...,NaN,0.015000,NaN,NaN,NaN,NaN,NaN,NaN,1.169582,0.077628
10572,2018-12-31,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,80.47471,0.00970,...,NaN,0.024000,NaN,NaN,NaN,NaN,NaN,NaN,152.212809,NaN
10573,2018-12-31,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,0.03270,...,NaN,NaN,NaN,NaN,0.036,NaN,NaN,NaN,NaN,NaN
10574,2018-12-31,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,0.01210,...,NaN,0.055000,NaN,NaN,NaN,NaN,0.008676,0.016606,73.709479,0.049000
10575,2018-12-31,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,0.01355,...,NaN,0.029888,NaN,NaN,NaN,NaN,NaN,NaN,118.560772,0.136708
10576,2018-12-31,USTOT,United States,OWN0,For-Sale,NaN,311.395335,NaN,NaN,NaN,...,0.059,NaN,0.03909,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10577,2018-12-31,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,0.01835,...,NaN,NaN,NaN,0.066824,NaN,0.017,NaN,NaN,56.051777,0.069000
10578,2018-12-31,WASDC,Washington,APT0,Apartment,NaN,NaN,4084.503651,NaN,0.02140,...,NaN,0.020437,NaN,NaN,NaN,NaN,NaN,NaN,7.996256,NaN
10579,2018-12-31,WASDC,Washington,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10580,2018-12-31,WASDC,Washington,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,0.058821,NaN,NaN,NaN,NaN,0.029000,0.053000,3.752298,0.090912
10581,2018-12-31,WASDC,Washington,OFC0,Office,NaN,NaN,NaN,NaN,0.03455,...,NaN,0.016946,NaN,NaN,NaN,NaN,NaN,NaN,8.659220,0.174982
10582,2018-12-31,WASDC,Washington,OWN0,For-Sale,6872.866926,NaN,NaN,NaN,NaN,...,0.038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10583,2018-12-31,WASDC,Washington,RET0,Retail,NaN,NaN,NaN,NaN,0.03765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.812786,0.040924

In [18]:
dfMarket['Geography_Name'].value_counts()

Los Angeles      882
Washington       882
Boston           882
United States    882
San Jose         735
New York         735
Seattle          735
Chicago          735
San Francisco    735
San Diego        735
Dallas           588
Orange County    588
Atlanta          588
Inland Empire    294
Miami            147
Philadelphia     147
Denver           147
Phoenix          147
Name: Geography_Name, dtype: int64

In [24]:
dfMarket['Property_Name'].value_counts()

Retail        1911
Apartment     1911
Office        1911
Industrial    1911
For-Sale      1764
Hotel         1176
Name: Property_Name, dtype: int64

In [20]:
dfMarketUS=dfMarket.loc[dfMarket['Geography_Name']=='United States',:]

In [30]:
dfMarketUS

,Date,Geography_Code,Geography_Name,Property_Code,Property_Name,1+ Unit Permitting,1+ Unit Starts,2+ Unit Permitting,2+ Unit Starts,Cap Rate Spread,...,Price Growth,Rent Growth,Res. Invest. Share of GDP,Retail Sales Growth,RevPar Growth,Strip Rent Growth,Trade Emp. Growth,Trans. Emp. Growth,Trans. Vol. (Bil. $),Vacancy Rate
60,1982-03-31,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,1982-03-31,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,1982-03-31,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,1982-03-31,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,1982-03-31,USTOT,United States,OWN0,For-Sale,NaN,176.700000,NaN,NaN,NaN,...,0.037824,NaN,0.033503,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,1982-03-31,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,1982-06-30,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,1982-06-30,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,1982-06-30,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,1982-06-30,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,1982-06-30,USTOT,United States,OWN0,For-Sale,NaN,274.000000,NaN,NaN,NaN,...,0.025088,NaN,0.032323,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,1982-06-30,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,1982-09-30,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,1982-09-30,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,1982-09-30,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,1982-09-30,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,1982-09-30,USTOT,United States,OWN0,For-Sale,NaN,309.200000,NaN,NaN,NaN,...,0.013320,NaN,0.032202,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,1982-09-30,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,1982-12-31,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,1982-12-31,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,1982-12-31,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,1982-12-31,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,1982-12-31,USTOT,United States,OWN0,For-Sale,NaN,302.300000,NaN,NaN,NaN,...,0.019647,NaN,0.034532,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,1982-12-31,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,1983-03-31,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,1983-03-31,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,1983-03-31,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,1983-03-31,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,1983-03-31,USTOT,United States,OWN0,For-Sale,NaN,322.200000,NaN,NaN,NaN,...,0.024463,NaN,0.039874,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,1983-03-31,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10284,2017-09-30,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,89.30000,0.015767,...,NaN,0.027000,NaN,NaN,NaN,NaN,NaN,NaN,146.730898,NaN
10285,2017-09-30,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,0.034467,...,NaN,NaN,NaN,NaN,0.026,NaN,NaN,NaN,NaN,NaN
10286,2017-09-30,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,0.026767,...,NaN,0.041000,NaN,NaN,NaN,NaN,0.001676,0.028461,64.921637,0.050000
10287,2017-09-30,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,0.017367,...,NaN,0.028000,NaN,NaN,NaN,NaN,NaN,NaN,132.122507,0.140000
10288,2017-09-30,USTOT,United States,OWN0,For-Sale,NaN,319.300000,NaN,NaN,NaN,...,0.055671,NaN,0.038365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10289,2017-09-30,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,0.021967,...,NaN,NaN,NaN,0.043185,NaN,0.0169,NaN,NaN,58.461894,NaN
10356,2017-12-31,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,89.00000,0.016400,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
10357,2017-12-31,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,0.041800,...,NaN,NaN,NaN,NaN,0.030,NaN,NaN,NaN,NaN,NaN
10358,2017-12-31,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,0.022600,...,NaN,0.037000,NaN,NaN,NaN,NaN,0.002157,0.029359,65.693139,0.050000
10359,2017-12-31,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,0.019900,...,NaN,0.039000,NaN,NaN,NaN,NaN,NaN,NaN,127.077117,0.139000
10360,2017-12-31,USTOT,United States,OWN0,For-Sale,NaN,288.900000,NaN,NaN,NaN,...,0.052535,NaN,0.039200,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10361,2017-12-31,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,0.023500,...,NaN,NaN,NaN,0.058027,NaN,0.0180,NaN,NaN,55.240300,0.070000
10428,2018-03-31,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,93.70000,0.009800,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,154.498892,NaN
10429,2018-03-31,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,0.019200,...,NaN,NaN,NaN,NaN,0.035,NaN,NaN,NaN,NaN,NaN
10430,2018-03-31,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,0.020200,...,NaN,0.055000,NaN,NaN,NaN,NaN,0.004220,0.030162,70.844337,0.049000
10431,2018-03-31,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,0.013300,...,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,124.369689,0.141000
10432,2018-03-31,USTOT,United States,OWN0,For-Sale,NaN,288.500000,NaN,NaN,NaN,...,0.056712,NaN,0.039279,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10433,2018-03-31,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,0.017000,...,NaN,NaN,NaN,0.049211,NaN,0.0180,NaN,NaN,49.994289,NaN
10500,2018-06-30,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,94.10000,0.009500,...,NaN,0.025000,NaN,NaN,NaN,NaN,NaN,NaN,152.212809,NaN
10501,2018-06-30,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,0.033500,...,NaN,NaN,NaN,NaN,0.038,NaN,NaN,NaN,NaN,NaN
10502,2018-06-30,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,0.018200,...,NaN,0.072000,NaN,NaN,NaN,NaN,0.007153,0.030753,73.709479,0.049000
10503,2018-06-30,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,0.014000,...,NaN,0.002000,NaN,NaN,NaN,NaN,NaN,NaN,118.560772,0.142000
10504,2018-06-30,USTOT,United States,OWN0,For-Sale,NaN,351.800000,NaN,NaN,NaN,...,0.049602,NaN,0.039090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10505,2018-06-30,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,0.017300,...,NaN,NaN,NaN,0.062204,NaN,0.0170,NaN,NaN,56.051777,NaN
10572,2018-12-31,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,80.47471,0.009700,...,NaN,0.024000,NaN,NaN,NaN,NaN,NaN,NaN,152.212809,NaN
10573,2018-12-31,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,0.032700,...,NaN,NaN,NaN,NaN,0.036,NaN,NaN,NaN,NaN,NaN
10574,2018-12-31,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,0.012100,...,NaN,0.055000,NaN,NaN,NaN,NaN,0.008676,0.016606,73.709479,0.049000
10575,2018-12-31,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,0.013550,...,NaN,0.029888,NaN,NaN,NaN,NaN,NaN,NaN,118.560772,0.136708
10576,2018-12-31,USTOT,United States,OWN0,For-Sale,NaN,311.395335,NaN,NaN,NaN,...,0.059000,NaN,0.039090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10577,2018-12-31,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,0.018350,...,NaN,NaN,NaN,0.066824,NaN,0.0170,NaN,NaN,56.051777,0.069000

In [38]:
dfMarketUS.replace({'Retail':'RETAIL','Industrial':'INDUSTRIAL','Apartment':'APARTMENT','Office':'OFFICE','For-Sale':'FOR SALE','Hotel':'HOTEL'},inplace=True)

C:\Users\ru89110\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:3795: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  method=method)

In [39]:
dfMarketUS

,Date,Geography_Code,Geography_Name,Property_Code,Property_Name,1+ Unit Permitting,1+ Unit Starts,2+ Unit Permitting,2+ Unit Starts,Cap Rate Spread,...,Price Growth,Rent Growth,Res. Invest. Share of GDP,Retail Sales Growth,RevPar Growth,Strip Rent Growth,Trade Emp. Growth,Trans. Emp. Growth,Trans. Vol. (Bil. $),Vacancy Rate
60,1982-03-31,USTOT,United States,APT0,APARTMENT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,1982-03-31,USTOT,United States,HOT0,HOTEL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,1982-03-31,USTOT,United States,IND0,INDUSTRIAL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,1982-03-31,USTOT,United States,OFC0,OFFICE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,1982-03-31,USTOT,United States,OWN0,FOR SALE,NaN,176.700000,NaN,NaN,NaN,...,0.037824,NaN,0.033503,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,1982-03-31,USTOT,United States,RET0,RETAIL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,1982-06-30,USTOT,United States,APT0,APARTMENT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,1982-06-30,USTOT,United States,HOT0,HOTEL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,1982-06-30,USTOT,United States,IND0,INDUSTRIAL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,1982-06-30,USTOT,United States,OFC0,OFFICE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,1982-06-30,USTOT,United States,OWN0,FOR SALE,NaN,274.000000,NaN,NaN,NaN,...,0.025088,NaN,0.032323,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,1982-06-30,USTOT,United States,RET0,RETAIL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,1982-09-30,USTOT,United States,APT0,APARTMENT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,1982-09-30,USTOT,United States,HOT0,HOTEL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,1982-09-30,USTOT,United States,IND0,INDUSTRIAL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,1982-09-30,USTOT,United States,OFC0,OFFICE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,1982-09-30,USTOT,United States,OWN0,FOR SALE,NaN,309.200000,NaN,NaN,NaN,...,0.013320,NaN,0.032202,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,1982-09-30,USTOT,United States,RET0,RETAIL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,1982-12-31,USTOT,United States,APT0,APARTMENT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,1982-12-31,USTOT,United States,HOT0,HOTEL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,1982-12-31,USTOT,United States,IND0,INDUSTRIAL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,1982-12-31,USTOT,United States,OFC0,OFFICE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,1982-12-31,USTOT,United States,OWN0,FOR SALE,NaN,302.300000,NaN,NaN,NaN,...,0.019647,NaN,0.034532,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,1982-12-31,USTOT,United States,RET0,RETAIL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,1983-03-31,USTOT,United States,APT0,APARTMENT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,1983-03-31,USTOT,United States,HOT0,HOTEL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,1983-03-31,USTOT,United States,IND0,INDUSTRIAL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,1983-03-31,USTOT,United States,OFC0,OFFICE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,1983-03-31,USTOT,United States,OWN0,FOR SALE,NaN,322.200000,NaN,NaN,NaN,...,0.024463,NaN,0.039874,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,1983-03-31,USTOT,United States,RET0,RETAIL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10284,2017-09-30,USTOT,United States,APT0,APARTMENT,NaN,NaN,NaN,89.30000,0.015767,...,NaN,0.027000,NaN,NaN,NaN,NaN,NaN,NaN,146.730898,NaN
10285,2017-09-30,USTOT,United States,HOT0,HOTEL,NaN,NaN,NaN,NaN,0.034467,...,NaN,NaN,NaN,NaN,0.026,NaN,NaN,NaN,NaN,NaN
10286,2017-09-30,USTOT,United States,IND0,INDUSTRIAL,NaN,NaN,NaN,NaN,0.026767,...,NaN,0.041000,NaN,NaN,NaN,NaN,0.001676,0.028461,64.921637,0.050000
10287,2017-09-30,USTOT,United States,OFC0,OFFICE,NaN,NaN,NaN,NaN,0.017367,...,NaN,0.028000,NaN,NaN,NaN,NaN,NaN,NaN,132.122507,0.140000
10288,2017-09-30,USTOT,United States,OWN0,FOR SALE,NaN,319.300000,NaN,NaN,NaN,...,0.055671,NaN,0.038365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10289,2017-09-30,USTOT,United States,RET0,RETAIL,NaN,NaN,NaN,NaN,0.021967,...,NaN,NaN,NaN,0.043185,NaN,0.0169,NaN,NaN,58.461894,NaN
10356,2017-12-31,USTOT,United States,APT0,APARTMENT,NaN,NaN,NaN,89.00000,0.016400,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
10357,2017-12-31,USTOT,United States,HOT0,HOTEL,NaN,NaN,NaN,NaN,0.041800,...,NaN,NaN,NaN,NaN,0.030,NaN,NaN,NaN,NaN,NaN
10358,2017-12-31,USTOT,United States,IND0,INDUSTRIAL,NaN,NaN,NaN,NaN,0.022600,...,NaN,0.037000,NaN,NaN,NaN,NaN,0.002157,0.029359,65.693139,0.050000
10359,2017-12-31,USTOT,United States,OFC0,OFFICE,NaN,NaN,NaN,NaN,0.019900,...,NaN,0.039000,NaN,NaN,NaN,NaN,NaN,NaN,127.077117,0.139000
10360,2017-12-31,USTOT,United States,OWN0,FOR SALE,NaN,288.900000,NaN,NaN,NaN,...,0.052535,NaN,0.039200,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10361,2017-12-31,USTOT,United States,RET0,RETAIL,NaN,NaN,NaN,NaN,0.023500,...,NaN,NaN,NaN,0.058027,NaN,0.0180,NaN,NaN,55.240300,0.070000
10428,2018-03-31,USTOT,United States,APT0,APARTMENT,NaN,NaN,NaN,93.70000,0.009800,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,154.498892,NaN
10429,2018-03-31,USTOT,United States,HOT0,HOTEL,NaN,NaN,NaN,NaN,0.019200,...,NaN,NaN,NaN,NaN,0.035,NaN,NaN,NaN,NaN,NaN
10430,2018-03-31,USTOT,United States,IND0,INDUSTRIAL,NaN,NaN,NaN,NaN,0.020200,...,NaN,0.055000,NaN,NaN,NaN,NaN,0.004220,0.030162,70.844337,0.049000
10431,2018-03-31,USTOT,United States,OFC0,OFFICE,NaN,NaN,NaN,NaN,0.013300,...,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,124.369689,0.141000
10432,2018-03-31,USTOT,United States,OWN0,FOR SALE,NaN,288.500000,NaN,NaN,NaN,...,0.056712,NaN,0.039279,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10433,2018-03-31,USTOT,United States,RET0,RETAIL,NaN,NaN,NaN,NaN,0.017000,...,NaN,NaN,NaN,0.049211,NaN,0.0180,NaN,NaN,49.994289,NaN
10500,2018-06-30,USTOT,United States,APT0,APARTMENT,NaN,NaN,NaN,94.10000,0.009500,...,NaN,0.025000,NaN,NaN,NaN,NaN,NaN,NaN,152.212809,NaN
10501,2018-06-30,USTOT,United States,HOT0,HOTEL,NaN,NaN,NaN,NaN,0.033500,...,NaN,NaN,NaN,NaN,0.038,NaN,NaN,NaN,NaN,NaN
10502,2018-06-30,USTOT,United States,IND0,INDUSTRIAL,NaN,NaN,NaN,NaN,0.018200,...,NaN,0.072000,NaN,NaN,NaN,NaN,0.007153,0.030753,73.709479,0.049000
10503,2018-06-30,USTOT,United States,OFC0,OFFICE,NaN,NaN,NaN,NaN,0.014000,...,NaN,0.002000,NaN,NaN,NaN,NaN,NaN,NaN,118.560772,0.142000
10504,2018-06-30,USTOT,United States,OWN0,FOR SALE,NaN,351.800000,NaN,NaN,NaN,...,0.049602,NaN,0.039090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10505,2018-06-30,USTOT,United States,RET0,RETAIL,NaN,NaN,NaN,NaN,0.017300,...,NaN,NaN,NaN,0.062204,NaN,0.0170,NaN,NaN,56.051777,NaN
10572,2018-12-31,USTOT,United States,APT0,APARTMENT,NaN,NaN,NaN,80.47471,0.009700,...,NaN,0.024000,NaN,NaN,NaN,NaN,NaN,NaN,152.212809,NaN
10573,2018-12-31,USTOT,United States,HOT0,HOTEL,NaN,NaN,NaN,NaN,0.032700,...,NaN,NaN,NaN,NaN,0.036,NaN,NaN,NaN,NaN,NaN
10574,2018-12-31,USTOT,United States,IND0,INDUSTRIAL,NaN,NaN,NaN,NaN,0.012100,...,NaN,0.055000,NaN,NaN,NaN,NaN,0.008676,0.016606,73.709479,0.049000
10575,2018-12-31,USTOT,United States,OFC0,OFFICE,NaN,NaN,NaN,NaN,0.013550,...,NaN,0.029888,NaN,NaN,NaN,NaN,NaN,NaN,118.560772,0.136708
10576,2018-12-31,USTOT,United States,OWN0,FOR SALE,NaN,311.395335,NaN,NaN,NaN,...,0.059000,NaN,0.039090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10577,2018-12-31,USTOT,United States,RET0,RETAIL,NaN,NaN,NaN,NaN,0.018350,...,NaN,NaN,NaN,0.066824,NaN,0.0170,NaN,NaN,56.051777,0.069000

In [40]:
TargetMarket=pd.merge(dftarget,dfMarketUS,how='left',left_on=['DATE','RE_RISK_PROPERTY_TYPE'],right_on=['Date','Property_Name'])

In [42]:
TargetMarket

,DATE,CUST_NAME,FACILITY_NUM,FACILITY_NAME,CRR,MaxCrr,DowngradeMax,DowngradeMax Notch,UpgradeMax,UpgradeMax Notch,...,Price Growth,Rent Growth,Res. Invest. Share of GDP,Retail Sales Growth,RevPar Growth,Strip Rent Growth,Trade Emp. Growth,Trans. Emp. Growth,Trans. Vol. (Bil. $),Vacancy Rate
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
1,2005-03-31,RANCHO MONTEREY LTD PARTNERSHIP,7.257413e+19,RANCHO MONTEREY LTD,3,3.0,0,0,0,0,...,NaN,0.019000,NaN,NaN,NaN,NaN,NaN,NaN,63.030803,NaN
2,2005-03-31,RANCHO PARK ASSOCIATES,7.257458e+19,RANCHO PARK ASSOCIATES,6,6.0,0,0,0,0,...,NaN,0.019000,NaN,NaN,NaN,NaN,NaN,NaN,63.030803,NaN
3,2005-03-31,RANDALL E KESSLER,5.061000e+19,RANDALL E KESSLER,5,5.0,0,0,0,0,...,NaN,-0.003085,NaN,NaN,NaN,NaN,NaN,NaN,81.611725,0.1705
4,2005-03-31,RANDELL S HANSEN,3.455089e+19,RANDELL S HANSEN,6,6.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2005-03-31,RANDHIR S HAYER,3.545888e+19,RANDHIR S HAYER,6,6.0,0,0,0,0,...,NaN,0.019000,NaN,NaN,NaN,NaN,NaN,NaN,63.030803,NaN
6,2005-03-31,EDEN GROUP LLC,2.425701e+19,EDEN GROUP LLC,6,6.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2005-03-31,EDDIE KA KEUNG WONG,9.896967e+19,EDDIE KA KEUNG WONG,6,6.0,0,0,0,0,...,NaN,-0.003085,NaN,NaN,NaN,NaN,NaN,NaN,81.611725,0.1705
8,2005-03-31,RANDY J DENHAM,2.031515e+19,RANDY J DENHAM,6,6.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2005-03-31,RANDY S EIFLER,2.480701e+19,RANDY S EIFLER,5,5.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
10,2005-03-31,EDD INVESTMENTS CO,2.387705e+19,E D D INVESTMENT CO,6,6.0,0,0,0,0,...,NaN,NaN,NaN,0.069292,NaN,NaN,NaN,NaN,59.260102,NaN
11,2005-03-31,RAPHAEL N NISSIM,6.579286e+19,RAPHAEL N NISSIM,8,8.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
12,2005-03-31,RAPHAEL SAADIQ,8.449873e+19,RAPHAEL SAADIQ,6,6.0,0,0,0,0,...,NaN,NaN,NaN,0.069292,NaN,NaN,NaN,NaN,59.260102,NaN
13,2005-03-31,ECHOPOD LLC,2.416647e+19,ECHOPOD LLC,6,6.0,0,0,0,0,...,NaN,-0.003085,NaN,NaN,NaN,NaN,NaN,NaN,81.611725,0.1705
14,2005-03-31,RATTAN/FORTIE PROPERTIES LLC,7.270881e+19,RATTAN/FORTIE PROPERTIES LLC,5,5.0,0,0,0,0,...,NaN,-0.003085,NaN,NaN,NaN,NaN,NaN,NaN,81.611725,0.1705
15,2005-03-31,RAUDMAN LIVING TRUST,7.271093e+19,RAUDMAN 1989 REVOCABLE LIVING,6,6.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
16,2005-03-31,RAUL J MORALES,6.361266e+19,RAUL J MORALES,6,6.0,0,0,0,0,...,NaN,0.019000,NaN,NaN,NaN,NaN,NaN,NaN,63.030803,NaN
17,2005-03-31,WILBUR-PARTHENIA LLC,9.798985e+19,WILBUR-PARTHENIA LLC,4,4.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
18,2005-03-31,EASTSHORE PROPERTIES LLC,2.404117e+19,EASTSHORE PROPERTIES LLC A,6,6.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
19,2005-03-31,EASTSHORE PROPERTIES LLC,2.404117e+19,EASTSHORE PROPERTIES LLC A,6,6.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
20,2005-03-31,RAVEN CLIFF ENTERPRISES LLC,7.271701e+19,RAVEN CLIFF ENTERPRISES LLC,6,6.0,0,0,0,0,...,NaN,-0.003085,NaN,NaN,NaN,NaN,NaN,NaN,81.611725,0.1705
21,2005-03-31,RAYMOND ADRIAN SMITH,8.446200e+19,RAYMOND ADRIAN SMITH,6,6.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
22,2005-03-31,EASTGATE MIRAMAR ASSOCIATES,2.404116e+19,EASTGATE MIRAMAR ASSOCIATES,4,5.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
23,2005-03-31,EASTGATE MIRAMAR ASSOCIATES,2.404116e+19,EASTGATE MIRAMAR ASSOCIATES,5,5.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
24,2005-03-31,EASTGATE MEDIA GROUP LLC,2.404115e+19,EASTGATE MEDIA GROUP LLC,6,6.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
25,2005-03-31,WIDDES REVOCABLE TRUST,9.782619e+19,WIDDES REVOCABLE TRUST,6,6.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.013753,0.025901,26.565062,NaN
26,2005-03-31,WHITTIER NARROWS BUSINESS PRK,9.769592e+19,WHITTIER NARROWS BUSINESS PK,4,4.0,0,0,0,0,...,NaN,-0.003085,NaN,NaN,NaN,NaN,NaN,NaN,81.611725,0.1705
27,2005-03-31,EASTER SEALS CENTRAL CALIFORNIA,2.404215e+19,EASTER SEALS CENTRAL,7,7.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2005-03-31,EASTER SEALS CENTRAL CALIFORNIA,2.404215e+19,EASTER SEALS CENTRAL,7,7.0,0,0,0,0,...,NaN,-0.003085,NaN,NaN,NaN,NaN,NaN,NaN,81.611725,0.1705
29,2005-03-31,RAYMOND F MELISSA,6.074471e+19,MELISSA RAYMOND & ROBERTA,6,6.0,0,0,0,0,...,NaN,-0.003085,NaN,NaN,NaN,NaN,NaN,NaN,81.611725,0.1705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195775,2017-12-31,"AUBURN PARK FAMILY HOUSING, LLC",5.485478e+18,AUBURN PARK FAMILY HOUSING,5,5.0,0,0,0,0,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195776,2017-12-31,CELEBRATION SENIOR LIVING WEST,1.251820e+19,CELEBRATION SENIOR LIVING,5,5.0,0,0,0,0,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195777,2017-12-31,"75 ROUNDTABLE, LLC",9.996801e+19,75 ROUNDTABLE LLC,5,5.0,0,0,0,0,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195778,2017-12-31,"KGP I, LLC",5.087065e+19,KGP I LLC,5,5.0,0,0,0,0,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195779,2017-12-31,3423 FOREST LANE LLC,9.994509e+19,3423 FOREST LANE LLC,3,3.0,0,0,0,0,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195780,2017-12-31,"D.Y. PARTNERS, LLC",2.370116e+19,DY PARTNERS LLC,5,5.0,0,0,0,0,...,NaN,NaN,NaN,0.058027,NaN,0.018,NaN,NaN,55.240300,0.0700
195781,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,...,NaN,0.037000,NaN,NaN,NaN,NaN,0.002157,0.029359,65.693139,0.0500
195782,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,...,NaN,0.037000,NaN,NaN,NaN,NaN,0.002157,0.029359,65.693139,0.0500
195783,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,...,NaN,0.037000,NaN,NaN,NaN,NaN,0.002157,0.029359,65.693139,0.0500
195784,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,...,NaN,0.037000,NaN,NaN,NaN,NaN,0.002157,0.029359,65.693139,0.0500
195785,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,...,NaN,0.037000,NaN,NaN,NaN,NaN,0.002157,0.029359,65.693139,0.0500
195786,2017-12-31,"CALIFORNIA SKY INVESTMENT GROUP, LLC",1.078318e+19,CALIFORNIA SKY INVESTMENT,5,5.0,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195787,2017-12-31,"CALIFORNIA SKY INVESTMENT GROUP, LLC",1.078318e+19,CALIFORNIA SKY INVESTMENT,5,5.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195788,2017-12-31,"MARYMEAD AFFORDABLE HOUSING, L.P.",5.978559e+19,MARYMEAD AFFORDABLE HOUSING,3,3.0,0,0,1,1,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195789,2017-12-31,JANICE SOOKYUNG BAE,5.843547e+18,JANICE SOOKYUNG BAE,6,6.0,0,0,0,0,...,NaN,NaN,NaN,0.058027,NaN,0.018,NaN,NaN,55.240300,0.0700
195790,2017-12-31,"PARADIGM 20815 SHERMAN WAY, LLC",6.830293e+19,PARADIGM 20815 SHERMAN WAY,5,5.0,0,0,0,0,...,NaN,NaN,NaN,0.058027,NaN,0.018,NaN,NaN,55.240300,0.0700
195791,2017-12-31,"CALIFORNIA SKY INVESTMENT GROUP, LLC",1.078318e+19,CALIFORNIA SKY INVESTMENT,5,5.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195792,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,...,NaN,0.037000,NaN,NaN,NaN,NaN,0.002157,0.029359,65.693139,0.0500
195793,2017-12-31,"PARADIGM 6653 DARBY, LLC",6.892256e+19,PARADIGM 6653 DARBY LLC,4,4.0,0,0,0,0,...,NaN,NaN,NaN,0.058027,NaN,0.018,NaN,NaN,55.240300,0.0700
195794,2017-12-31,3401 S SUNFLOWER LLC,9.994490e+19,3401 S SUNFLOWER LLC,5,5.0,0,0,0,0,...,NaN,0.039000,NaN,NaN,NaN,NaN,NaN,NaN,127.077117,0.1390
195795,2017-12-31,2045 EAST WASHINGTON LLC,9.991683e+19,2045 EAST WASHINGTON LLC,4,4.0,0,0,0,0,...,NaN,0.037000,NaN,NaN,NaN,NaN,0.002157,0.029359,65.693139,0.0500
195796,2017-12-31,"D1 SENIOR IRVINE HOUSING PARTNERS, L.P.",2.382640e+19,D1 SENIOR IRVINE HOUSING,5,5.0,0,0,0,0,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195797,2017-12-31,"PREMIUM INVESTMENT PROPERTIES, LLC",8.706783e+19,PREMIUM INVESTMENT PROPERTIES,7,7.0,0,0,0,0,...,NaN,0.037000,NaN,NaN,NaN,NaN,0.002157,0.029359,65.693139,0.0500
195798,2017-12-31,"PHYLLIS SCHROBSDORFF LIVING TRUST, DATED",7.076694e+19,PHYLLIS SCHROBSDORFF LIVING,6,6.0,0,0,0,0,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195799,2017-12-31,MARYTRESE COMER SEPARATE PROPERTY TRUST,1.537001e+19,MARYTRESE COMER SEPARATE,4,4.0,0,0,1,1,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195800,2017-12-31,"JANE'S HOUSE SQUARE, LLC",4.037953e+19,JANE'S HOUSE SQUARE LLC,4,4.0,0,0,0,0,...,NaN,NaN,NaN,0.058027,NaN,0.018,NaN,NaN,55.240300,0.0700
195801,2017-12-31,"PARADIGM 7249 JORDAN, LLC",6.830319e+19,PARADIGM 7249 JORDAN LLC,3,3.0,0,0,0,0,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195802,2017-12-31,GARY A MORSE EXEMPTION TRUST,5.100910e+19,GARY A MORSE EXEMPTION TRUST,5,5.0,0,0,0,0,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN
195803,2017-12-31,AUDREY N. NEWTON TRUST DTD 12/3/04,6.875535e+17,THE AUDREY N NEWTON TRUST,5,5.0,0,0,1,1,...,NaN,NaN,NaN,0.058027,NaN,0.018,NaN,NaN,55.240300,0.0700
195804,2017-12-31,HOMELAND PROPERTIES LLC,3.675224e+19,HOMELAND PROPERTIES LLC,6,6.0,0,0,0,0,...,NaN,0.026000,NaN,NaN,NaN,NaN,NaN,NaN,146.946226,NaN

In [43]:
TargetMarket.to_excel('TargetMarket.xlsx')

In [ ]:
## Target data without market variables  
## NON-RES INCOME               10734
## OTHER                         4691
## UNSECURED                     4556
## SFR                           3202
## OTHER REAL ESTATE SECURED     1407
## LAND                          1261
## UNCATEGORIZED                  829
## SECURED - NON RE               210
## OTHER REAL ESTATE               16
## UNKNOWN                          5
## no type

In [ ]:
Markets=['ATLANTA'....]

In [45]:
dftargetIndustrial= dftarget.loc[dftarget['RE_RISK_PROPERTY_TYPE']=='INDUSTRIAL',:]

In [46]:
dftargetIndustrial

,DATE,CUST_NAME,FACILITY_NUM,FACILITY_NAME,CRR,MaxCrr,DowngradeMax,DowngradeMax Notch,UpgradeMax,UpgradeMax Notch,Downgrade,Downgrade Notch,NET_COMMIT_AMT,OUT_BAL,RE_RISK_PROPERTY_TYPE,RE_STATE_NAME,RE_COUNTY_NAME
33237,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0,0,0,0,0.0,0.0,567600.00,567600.00,INDUSTRIAL,CALIFORNIA,NaN
46181,2005-03-31,RANDY S EIFLER,2.480701e+19,RANDY S EIFLER,5,5.0,0,0,0,0,0.0,0.0,551479.47,551479.47,INDUSTRIAL,CALIFORNIA,SAN DIEGO
115170,2005-03-31,RAPHAEL N NISSIM,6.579286e+19,RAPHAEL N NISSIM,8,8.0,0,0,0,0,0.0,0.0,185170.92,185170.92,INDUSTRIAL,CALIFORNIA,MARIN
136635,2005-03-31,RAUDMAN LIVING TRUST,7.271093e+19,RAUDMAN 1989 REVOCABLE LIVING,6,6.0,0,0,0,0,0.0,0.0,1330178.35,1330178.35,INDUSTRIAL,CALIFORNIA,SHASTA
182306,2005-03-31,WILBUR-PARTHENIA LLC,9.798985e+19,WILBUR-PARTHENIA LLC,4,4.0,0,0,0,0,0.0,0.0,2564719.88,2564719.88,INDUSTRIAL,CALIFORNIA,LOS ANGELES
45157,2005-03-31,EASTSHORE PROPERTIES LLC,2.404117e+19,EASTSHORE PROPERTIES LLC A,6,6.0,0,0,0,0,0.0,0.0,2624352.52,2624352.52,INDUSTRIAL,CALIFORNIA,CONTRA COSTA
45147,2005-03-31,EASTSHORE PROPERTIES LLC,2.404117e+19,EASTSHORE PROPERTIES LLC A,6,6.0,0,0,0,0,0.0,0.0,1412546.58,1412546.58,INDUSTRIAL,CALIFORNIA,CONTRA COSTA
156087,2005-03-31,RAYMOND ADRIAN SMITH,8.446200e+19,RAYMOND ADRIAN SMITH,6,6.0,0,0,0,0,0.0,0.0,485334.31,485334.31,INDUSTRIAL,CALIFORNIA,ORANGE
44956,2005-03-31,EASTGATE MIRAMAR ASSOCIATES,2.404116e+19,EASTGATE MIRAMAR ASSOCIATES,4,5.0,0,0,0,0,0.0,0.0,3708035.69,3708035.69,INDUSTRIAL,CALIFORNIA,SAN DIEGO
44924,2005-03-31,EASTGATE MIRAMAR ASSOCIATES,2.404116e+19,EASTGATE MIRAMAR ASSOCIATES,5,5.0,0,0,0,0,0.0,0.0,14386365.92,14386365.92,INDUSTRIAL,CALIFORNIA,SAN DIEGO
44897,2005-03-31,EASTGATE MEDIA GROUP LLC,2.404115e+19,EASTGATE MEDIA GROUP LLC,6,6.0,0,0,0,0,0.0,0.0,2193299.30,2193299.30,INDUSTRIAL,CALIFORNIA,SAN DIEGO
182263,2005-03-31,WIDDES REVOCABLE TRUST,9.782619e+19,WIDDES REVOCABLE TRUST,6,6.0,0,0,0,0,0.0,0.0,562836.23,562836.23,INDUSTRIAL,CALIFORNIA,LOS ANGELES
61334,2005-03-31,EDIE N GOUR,3.321090e+19,EDIE N GOUR,6,6.0,0,0,0,0,0.0,0.0,163733.85,163733.85,INDUSTRIAL,NaN,NaN
56577,2005-03-31,EDUARDO P GARCIA,3.036895e+19,EDUARDO P GARCIA,6,6.0,0,0,0,0,0.0,0.0,141665.38,141665.38,INDUSTRIAL,CALIFORNIA,ALAMEDA
46037,2005-03-31,EFFKAY DOUGLAS ENTERPRISES,2.458378e+19,EFFKAY DOUGLAS ENTERPRISES,6,6.0,0,0,0,0,0.0,0.0,1209125.09,1209125.09,INDUSTRIAL,CALIFORNIA,LOS ANGELES
9047,2005-03-31,EDWIN H AUTENRIETH JR,5.551856e+18,EDWIN H AUTENRIETH JR,6,6.0,0,0,0,0,0.0,0.0,140050.80,140050.80,INDUSTRIAL,CALIFORNIA,RIVERSIDE
46007,2005-03-31,EDWARDS INVESTMENT COMPANY,2.446483e+19,EDWARDS INVESTMENT COMPANY,6,6.0,0,0,0,0,0.0,0.0,130006.56,130006.56,INDUSTRIAL,CALIFORNIA,LOS ANGELES
45993,2005-03-31,EDWARDS FAMILY TRUST,2.446182e+19,EDWARDS FAMILY TRUST,5,5.0,0,0,0,0,0.0,0.0,1113131.01,1113131.01,INDUSTRIAL,CALIFORNIA,LOS ANGELES
182459,2005-03-31,WILLGRO PROPERTIES,9.823523e+19,WILLGRO PROPERTIES,5,5.0,0,0,0,0,0.0,0.0,1212883.86,1212883.86,INDUSTRIAL,CALIFORNIA,ORANGE
182457,2005-03-31,WILLGRO PROPERTIES,9.823523e+19,WILLGRO PROPERTIES,5,5.0,0,0,0,0,0.0,0.0,1554979.29,1554979.29,INDUSTRIAL,CALIFORNIA,ORANGE
93804,2005-03-31,EDWARD R LITWIN,5.426990e+19,EDWARD R LITWIN,6,6.0,0,0,0,0,0.0,0.0,64594.24,64594.24,INDUSTRIAL,CALIFORNIA,SAN MATEO
125043,2005-03-31,RAJEN A PATEL,6.901701e+19,RAJEN PATEL,6,6.0,0,0,0,0,0.0,0.0,792981.45,792981.45,INDUSTRIAL,CALIFORNIA,LOS ANGELES
32926,2005-03-31,RALPH B COOMBER,1.587076e+19,RALPH B COOMBER,6,6.0,0,0,0,0,0.0,0.0,340399.29,340399.29,INDUSTRIAL,CALIFORNIA,RIVERSIDE
156108,2005-03-31,WILFRED E SMITH,8.448621e+19,WILFRED E SMITH,6,6.0,0,0,0,0,0.0,0.0,580982.81,580982.81,INDUSTRIAL,CALIFORNIA,SAN DIEGO
182408,2005-03-31,WILEM VAUGHN PROPERTIES LLC,9.807159e+19,WILEM VAUGHN PROPERTIES LLC,6,6.0,0,0,0,0,0.0,0.0,789463.94,789463.94,INDUSTRIAL,CALIFORNIA,ORANGE
182406,2005-03-31,WILEM VAUGHN PROPERTIES LLC,9.807159e+19,WILEM VAUGHN PROPERTIES LLC,6,6.0,0,0,0,0,0.0,0.0,808177.01,808177.01,INDUSTRIAL,CALIFORNIA,ORANGE
45714,2005-03-31,"EDW PROPERTIES, A CA LIMITED PARTNERSHIP",2.434802e+19,EDW PROPERTIES A CAL LP,5,5.0,0,0,0,0,0.0,0.0,4175000.00,3724045.16,INDUSTRIAL,CALIFORNIA,LOS ANGELES
45680,2005-03-31,"EDW PROPERTIES, A CA LIMITED PARTNERSHIP",2.434802e+19,EDW PROPERTIES A CAL LP,5,5.0,0,0,0,0,0.0,0.0,3950000.00,3950000.00,INDUSTRIAL,CALIFORNIA,LOS ANGELES
45651,2005-03-31,"EDW PROPERTIES, A CA LIMITED PARTNERSHIP",2.434802e+19,EDW PROPERTIES A CAL LP,5,5.0,0,0,0,0,0.0,0.0,2012008.70,2012008.70,INDUSTRIAL,CALIFORNIA,LOS ANGELES
13166,2005-03-31,REMO & AMI BELLI FAMILY TRUST,7.186307e+18,BELLI FAMILY TRUST,5,5.0,0,0,0,0,0.0,0.0,2973800.98,2973800.98,INDUSTRIAL,CALIFORNIA,LOS ANGELES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179538,2017-12-31,WCP ENTERPRISES LLC,9.616978e+19,WCP ENTERPRISES LLC,8,8.0,0,0,0,0,0.0,0.0,1357011.18,1357011.18,INDUSTRIAL,CALIFORNIA,ORANGE (CA)
195182,2017-12-31,"801 ACASO, LLC",9.997312e+19,801 ACASO LLC,4,4.0,0,0,0,0,0.0,0.0,2169268.62,2169268.62,INDUSTRIAL,CALIFORNIA,VENTURA (CA)
179547,2017-12-31,WCR REAL ESTATE HOLDINGS LLC,9.616978e+19,WCR REAL ESTATE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,1010013.03,1010013.03,INDUSTRIAL,CALIFORNIA,ORANGE (CA)
195220,2017-12-31,"807 PARKRIDGE, LLC",9.998119e+19,807 PARKRIDGE LLC,7,7.0,0,0,1,1,0.0,0.0,2412457.10,2412457.10,INDUSTRIAL,CALIFORNIA,RIVERSIDE (CA)
47976,2017-12-31,ERGONOM CORPORATION,2.637361e+19,ERGONOM CORPORATION,4,4.0,0,0,0,0,0.0,0.0,533858.08,533858.08,INDUSTRIAL,CALIFORNIA,VENTURA (CA)
132964,2017-12-31,PRICESMART INC,7.138346e+19,PRICESMART INC,4,4.0,0,0,0,0,0.0,0.0,35700000.00,35700000.00,INDUSTRIAL,FLORIDA,FLORIDA
75779,2017-12-31,DENNIS D JACOBSEN,4.017622e+19,DENNIS D JACOBSEN,4,4.0,0,0,0,0,0.0,0.0,1215282.08,1215282.08,INDUSTRIAL,CALIFORNIA,SAN BENITO (CA)
148228,2017-12-31,SATNAM INVESTMENTS LLC,8.200332e+19,SATNAM INVESTMENTS LLC,7,7.0,1,1,0,0,1.0,-1.0,1045028.04,1045028.04,INDUSTRIAL,CALIFORNIA,LOS ANGELES (CA)
9060,2017-12-31,"AVA ENTERPRISES, LLC",5.589289e+18,AVA ENTERPRISES LLC,4,4.0,0,0,0,0,0.0,0.0,3258230.79,3258230.79,INDUSTRIAL,CALIFORNIA,ORANGE (CA)
194814,2017-12-31,"7088 COMMERCE CIRCLE HOLDINGS, LLC",9.996790e+19,7088 COMMERCE CIRCLE HOLDINGS,4,4.0,0,0,0,0,0.0,0.0,1865242.00,1865242.00,INDUSTRIAL,CALIFORNIA,ALAMEDA (CA)
194842,2017-12-31,712 W FLORENCE LLC,9.996801e+19,712 W FLORENCE LLC,7,7.0,0,0,0,0,0.0,0.0,1047402.14,1047402.14,INDUSTRIAL,CALIFORNIA,LOS ANGELES (CA)
194849,2017-12-31,712 W FLORENCE LLC,9.996801e+19,712 W FLORENCE LLC,7,7.0,0,0,0,0,0.0,0.0,202052.36,202052.36,INDUSTRIAL,CALIFORNIA,LOS ANGELES (CA)
8910,2017-12-31,"AURO PHARMACIES, INC",5.526205e+18,AURO PHARMACIES INC,4,4.0,0,0,0,0,0.0,0.0,2318410.60,2318410.60,INDUSTRIAL,CALIFORNIA,ORANGE (CA)
62408,2017-12-31,"AUTOWERKS PROPERTIES, LLC",3.347410e+19,AUTOWERKS PROPERTIES LLC,5,5.0,0,0,1,1,0.0,0.0,4826318.15,4826318.15,INDUSTRIAL,CALIFORNIA,SAN DIEGO (CA)
123582,2017-12-31,"PAOLA PROPERTIES, L.L.C.",6.811432e+19,PAOLA PROPERTIES LLC,6,6.0,1,1,0,0,1.0,0.0,692159.01,692159.01,INDUSTRIAL,OREGON,MULTHOMAH (OR)
123590,2017-12-31,"PAOLA PROPERTIES, L.L.C.",6.811432e+19,PAOLA PROPERTIES LLC,6,6.0,0,0,0,0,1.0,0.0,733219.01,733219.01,INDUSTRIAL,OREGON,MULTHOMAH (OR)
50876,2017-12-31,"FELIX VALDEZ AVE., LLC",2.767995e+19,FELIX VALDEZ AVE LLC,5,5.0,0,0,1,2,0.0,0.0,419466.77,419466.77,INDUSTRIAL,CALIFORNIA,RIVERSIDE (CA)
106438,2017-12-31,WAYNE R MILLER,6.292027e+19,WAYNE R MILLER,7,7.0,0,0,0,0,0.0,0.0,506793.86,506793.86,INDUSTRIAL,CALIFORNIA,SANTA BARBARA (CA)
44171,2017-12-31,"D3KS-ELPH, LLC",2.382641e+19,D3KS-ELPH LLC,6,6.0,0,0,0,0,0.0,0.0,1534448.88,1534448.88,INDUSTRIAL,CALIFORNIA,SAN LUIS OBISPO (CA)
44172,2017-12-31,D3W PROPERTIES LLC,2.382642e+19,D3W PROPERTIES LLC,4,4.0,0,0,0,0,0.0,0.0,753744.00,753744.00,INDUSTRIAL,CALIFORNIA,SAN MATEO (CA)
8760,2017-12-31,"AUBURN HILLS COMMERCIAL, LLC",5.483035e+18,AUBURN HILLS COMMERCIAL LLC,6,6.0,0,0,0,0,0.0,0.0,8457995.65,8457995.65,INDUSTRIAL,MICHIGAN,MICHIGAN
132912,2017-12-31,"PRESS FORWARD PROPERTIES, LLC",7.133960e+19,PRESS FORWARD PROPERTIES LLC,6,6.0,0,0,0,0,0.0,0.0,917708.33,917708.33,INDUSTRIAL,CALIFORNIA,LOS ANGELES (CA)
8890,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,780000.00,780000.00,INDUSTRIAL,CALIFORNIA,SAN JOAQUIN (CA)
8889,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,4600801.36,4600801.36,INDUSTRIAL,CALIFORNIA,KERN (CA)
8881,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,425530.26,425530.26,INDUSTRIAL,CALIFORNIA,FRESNO (CA)
8873,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,478886.84,478886.84,INDUSTRIAL,NORTH DAKOTA,NORTH DAKOTA
8860,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,501605.30,501605.30,INDUSTRIAL,TEXAS,HARRIS (TX)
8847,2017-12-31,"AUDREY MARIE HOLDINGS, LLC",5.493868e+18,AUDREY MARIE HOLDINGS LLC,5,5.0,0,0,0,0,0.0,0.0,588771.76,588771.76,INDUSTRIAL,CALIFORNIA,VENTURA (CA)
191389,2017-12-31,2045 EAST WASHINGTON LLC,9.991683e+19,2045 EAST WASHINGTON LLC,4,4.0,0,0,0,0,0.0,0.0,6933330.08,6933330.08,INDUSTRIAL,CALIFORNIA,LOS ANGELES (CA)
160342,2017-12-31,"PREMIUM INVESTMENT PROPERTIES, LLC",8.706783e+19,PREMIUM INVESTMENT PROPERTIES,7,7.0,0,0,0,0,0.0,0.0,4811571.26,4811571.26,INDUSTRIAL,CALIFORNIA,LOS ANGELES (CA)

In [47]:
dftargetIndustrialcustomer=dftargetIndustrial.groupby(['DATE'])['CUST_NAME'].agg(['count'])

In [48]:
dftargetIndustrialDowngrade=dftargetIndustrial.groupby(['DATE'])['DowngradeMax'].agg(['mean'])

In [52]:
dftargetIndustrialUpgrade=dftargetIndustrial.groupby(['DATE'])['UpgradeMax'].agg(['mean'])

In [49]:
dftargetIndustrialcustomer

            count
DATE
2005-03-31    967
2005-06-30    955
2005-09-30    949
2005-12-31   1078
2006-03-31   1049
2006-06-30   1057
2006-09-30   1053
2006-12-31   1053
2007-03-31   1045
2007-06-30   1030
2007-09-30   1023
2007-12-31   1016
2008-03-31    999
2008-06-30    997
2008-09-30    994
2008-12-31    974
2009-03-31    951
2009-06-30    936
2009-09-30    907
2009-12-31    886
2010-03-31    872
2010-06-30    861
2010-09-30    581
2010-12-31    536
2011-03-31    526
2011-06-30    528
2011-09-30    516
2011-12-31    509
2012-03-31    499
2012-06-30    461
2012-09-30    421
2012-12-31    344
2013-03-31    297
2013-06-30    388
2013-09-30    392
2013-12-31    381
2014-03-31    379
2014-06-30    406
2014-09-30    434
2014-12-31    484
2015-03-31    502
2015-06-30    518
2015-09-30    534
2015-12-31    545
2016-03-31    568
2016-06-30    565
2016-09-30    572
2016-12-31    571
2017-03-31    574
2017-06-30    568
2017-09-30    556
2017-12-31    540

In [50]:
dftargetIndustrialDowngrade

                mean
DATE
2005-03-31  0.000000
2005-06-30  0.012565
2005-09-30  0.012645
2005-12-31  0.011132
2006-03-31  0.014299
2006-06-30  0.015137
2006-09-30  0.007597
2006-12-31  0.014245
2007-03-31  0.013397
2007-06-30  0.014563
2007-09-30  0.015640
2007-12-31  0.017717
2008-03-31  0.024024
2008-06-30  0.025075
2008-09-30  0.024145
2008-12-31  0.042094
2009-03-31  0.063091
2009-06-30  0.075855
2009-09-30  0.056229
2009-12-31  0.038375
2010-03-31  0.045872
2010-06-30  0.082462
2010-09-30  0.049914
2010-12-31  0.037313
2011-03-31  0.030418
2011-06-30  0.043561
2011-09-30  0.052326
2011-12-31  0.062868
2012-03-31  0.040080
2012-06-30  0.056399
2012-09-30  0.045131
2012-12-31  0.034884
2013-03-31  0.026936
2013-06-30  0.046392
2013-09-30  0.068878
2013-12-31  0.057743
2014-03-31  0.021108
2014-06-30  0.036946
2014-09-30  0.036866
2014-12-31  0.039256
2015-03-31  0.031873
2015-06-30  0.042471
2015-09-30  0.029963
2015-12-31  0.029358
2016-03-31  0.056338
2016-06-30  0.046018
2016-09-30  0.083916
2016-12-31  0.063047
2017-03-31  0.036585
2017-06-30  0.072183
2017-09-30  0.064748
2017-12-31  0.059259

In [53]:
dftargetIndustrialUpgrade

                mean
DATE
2005-03-31  0.000000
2005-06-30  0.015707
2005-09-30  0.021075
2005-12-31  0.016698
2006-03-31  0.013346
2006-06-30  0.011353
2006-09-30  0.013295
2006-12-31  0.024691
2007-03-31  0.008612
2007-06-30  0.018447
2007-09-30  0.009775
2007-12-31  0.010827
2008-03-31  0.003003
2008-06-30  0.013039
2008-09-30  0.014085
2008-12-31  0.009240
2009-03-31  0.002103
2009-06-30  0.003205
2009-09-30  0.009923
2009-12-31  0.012415
2010-03-31  0.021789
2010-06-30  0.040650
2010-09-30  0.029260
2010-12-31  0.039179
2011-03-31  0.032319
2011-06-30  0.051136
2011-09-30  0.042636
2011-12-31  0.064833
2012-03-31  0.038076
2012-06-30  0.058568
2012-09-30  0.042755
2012-12-31  0.029070
2013-03-31  0.043771
2013-06-30  0.054124
2013-09-30  0.056122
2013-12-31  0.065617
2014-03-31  0.052770
2014-06-30  0.054187
2014-09-30  0.039171
2014-12-31  0.039256
2015-03-31  0.025896
2015-06-30  0.059846
2015-09-30  0.050562
2015-12-31  0.049541
2016-03-31  0.042254
2016-06-30  0.093805
2016-09-30  0.047203
2016-12-31  0.054291
2017-03-31  0.047038
2017-06-30  0.054577
2017-09-30  0.043165
2017-12-31  0.068519

In [54]:
dftargetApartment= dftarget.loc[dftarget['RE_RISK_PROPERTY_TYPE']=='APARTMENT',:]

In [55]:
dftargetaPARTMENTcustomer=dftargetApartment.groupby(['DATE'])['CUST_NAME'].agg(['count'])

In [57]:
dftargetApartmentDowngrade=dftargetApartment.groupby(['DATE'])['DowngradeMax'].agg(['mean'])

In [58]:
dftargetApartmentUpgrade=dftargetApartment.groupby(['DATE'])['UpgradeMax'].agg(['mean'])

In [59]:
dftargetaPARTMENTcustomer

            count
DATE
2005-03-31    314
2005-06-30    311
2005-09-30    302
2005-12-31   1654
2006-03-31   1670
2006-06-30   1666
2006-09-30   1688
2006-12-31   1713
2007-03-31   1749
2007-06-30   1825
2007-09-30   1849
2007-12-31   1927
2008-03-31   1996
2008-06-30   2057
2008-09-30   2074
2008-12-31   2123
2009-03-31   2125
2009-06-30   2087
2009-09-30   2038
2009-12-31   2037
2010-03-31   2024
2010-06-30   2012
2010-09-30    870
2010-12-31    884
2011-03-31    912
2011-06-30    947
2011-09-30   1016
2011-12-31   1088
2012-03-31   1142
2012-06-30   1131
2012-09-30   1176
2012-12-31   1221
2013-03-31   1221
2013-06-30   1598
2013-09-30   1643
2013-12-31   1692
2014-03-31   1719
2014-06-30   1720
2014-09-30   1737
2014-12-31   1752
2015-03-31   1757
2015-06-30   1755
2015-09-30   1762
2015-12-31   1764
2016-03-31   1796
2016-06-30   1803
2016-09-30   1789
2016-12-31   1779
2017-03-31   1775
2017-06-30   1761
2017-09-30   1707
2017-12-31   1629

In [61]:
dftargetApartmentUpgrade

                mean
DATE
2005-03-31  0.000000
2005-06-30  0.000000
2005-09-30  0.013245
2005-12-31  0.002418
2006-03-31  0.001198
2006-06-30  0.003001
2006-09-30  0.002962
2006-12-31  0.002335
2007-03-31  0.000572
2007-06-30  0.002740
2007-09-30  0.004867
2007-12-31  0.004152
2008-03-31  0.001002
2008-06-30  0.002917
2008-09-30  0.000964
2008-12-31  0.000942
2009-03-31  0.002824
2009-06-30  0.002396
2009-09-30  0.007360
2009-12-31  0.005891
2010-03-31  0.035079
2010-06-30  0.063618
2010-09-30  0.065517
2010-12-31  0.049774
2011-03-31  0.017544
2011-06-30  0.034847
2011-09-30  0.029528
2011-12-31  0.024816
2012-03-31  0.053415
2012-06-30  0.056587
2012-09-30  0.045918
2012-12-31  0.067977
2013-03-31  0.071253
2013-06-30  0.057572
2013-09-30  0.055995
2013-12-31  0.072695
2014-03-31  0.041885
2014-06-30  0.066860
2014-09-30  0.054116
2014-12-31  0.039384
2015-03-31  0.042686
2015-06-30  0.051852
2015-09-30  0.040295
2015-12-31  0.048186
2016-03-31  0.043987
2016-06-30  0.046589
2016-09-30  0.027949
2016-12-31  0.033165
2017-03-31  0.019155
2017-06-30  0.023850
2017-09-30  0.082601
2017-12-31  0.175568

In [65]:
dftargetRETAIL= dftarget.loc[dftarget['RE_RISK_PROPERTY_TYPE']=='RETAIL',:]

In [66]:
dftargetRETAILcustomer=dftargetRETAIL.groupby(['DATE'])['CUST_NAME'].agg(['count'])

In [67]:
dftargetRETAILDowngrade=dftargetRETAIL.groupby(['DATE'])['DowngradeMax'].agg(['mean'])

In [68]:
dftargetRETAILUpgrade=dftargetRETAIL.groupby(['DATE'])['UpgradeMax'].agg(['mean'])

In [71]:
dftargetRETAILUpgrade

                mean
DATE
2005-03-31  0.000000
2005-06-30  0.007371
2005-09-30  0.020253
2005-12-31  0.013006
2006-03-31  0.000000
2006-06-30  0.004354
2006-09-30  0.007123
2006-12-31  0.004274
2007-03-31  0.005839
2007-06-30  0.007215
2007-09-30  0.008621
2007-12-31  0.012535
2008-03-31  0.001381
2008-06-30  0.005626
2008-09-30  0.007225
2008-12-31  0.002950
2009-03-31  0.002954
2009-06-30  0.003017
2009-09-30  0.006182
2009-12-31  0.009600
2010-03-31  0.042208
2010-06-30  0.057377
2010-09-30  0.065868
2010-12-31  0.030675
2011-03-31  0.024922
2011-06-30  0.044025
2011-09-30  0.038339
2011-12-31  0.049669
2012-03-31  0.064626
2012-06-30  0.089928
2012-09-30  0.060932
2012-12-31  0.025455
2013-03-31  0.062731
2013-06-30  0.030905
2013-09-30  0.079430
2013-12-31  0.058824
2014-03-31  0.050000
2014-06-30  0.040268
2014-09-30  0.056180
2014-12-31  0.062500
2015-03-31  0.038636
2015-06-30  0.063205
2015-09-30  0.039080
2015-12-31  0.046512
2016-03-31  0.034483
2016-06-30  0.049065
2016-09-30  0.033254
2016-12-31  0.070048
2017-03-31  0.034146
2017-06-30  0.021898
2017-09-30  0.076555
2017-12-31  0.126829

In [73]:
dftargetOFFICE= dftarget.loc[dftarget['RE_RISK_PROPERTY_TYPE']=='OFFICE',:]

In [74]:
dftargetOFFICEcustomer=dftargetOFFICE.groupby(['DATE'])['CUST_NAME'].agg(['count'])

In [75]:
dftargetOFFICEDowngrade=dftargetOFFICE.groupby(['DATE'])['DowngradeMax'].agg(['mean'])

In [76]:
dftargetOFFICEUpgrade=dftargetOFFICE.groupby(['DATE'])['UpgradeMax'].agg(['mean'])

In [80]:
dftargetOFFICEUpgrade

                mean
DATE
2005-03-31  0.000000
2005-06-30  0.013283
2005-09-30  0.011516
2005-12-31  0.013534
2006-03-31  0.001531
2006-06-30  0.018576
2006-09-30  0.010853
2006-12-31  0.004601
2007-03-31  0.012308
2007-06-30  0.010870
2007-09-30  0.003140
2007-12-31  0.006349
2008-03-31  0.006289
2008-06-30  0.012559
2008-09-30  0.004831
2008-12-31  0.003273
2009-03-31  0.005034
2009-06-30  0.006908
2009-09-30  0.001786
2009-12-31  0.012774
2010-03-31  0.030476
2010-06-30  0.039848
2010-09-30  0.059190
2010-12-31  0.040268
2011-03-31  0.038062
2011-06-30  0.046099
2011-09-30  0.049470
2011-12-31  0.042403
2012-03-31  0.050179
2012-06-30  0.048193
2012-09-30  0.031250
2012-12-31  0.050000
2013-03-31  0.048128
2013-06-30  0.055556
2013-09-30  0.073955
2013-12-31  0.063123
2014-03-31  0.030928
2014-06-30  0.055556
2014-09-30  0.066038
2014-12-31  0.038585
2015-03-31  0.049080
2015-06-30  0.065089
2015-09-30  0.055233
2015-12-31  0.063401
2016-03-31  0.043353
2016-06-30  0.068571
2016-09-30  0.071429
2016-12-31  0.042017
2017-03-31  0.028409
2017-06-30  0.053371
2017-09-30  0.089337
2017-12-31  0.090643

In [83]:
dftargetForSale= dftarget.loc[dftarget['RE_RISK_PROPERTY_TYPE']=='FOR SALE',:]

In [84]:
dftargetForSalecustomer=dftargetForSale.groupby(['DATE'])['CUST_NAME'].agg(['count'])

In [85]:
dftargetForSaleDowngrade=dftargetForSale.groupby(['DATE'])['DowngradeMax'].agg(['mean'])

In [86]:
dftargetForSaleUpgrade=dftargetForSale.groupby(['DATE'])['UpgradeMax'].agg(['mean'])

In [87]:
dftargetForSalecustomer

            count
DATE
2013-06-30      4
2013-09-30    143
2013-12-31    125
2014-03-31    106
2014-06-30     83
2014-09-30     60
2014-12-31     58
2015-03-31     57
2015-06-30     54
2015-09-30     51
2015-12-31     53
2016-03-31     51
2016-06-30     52
2016-09-30     43
2016-12-31     39
2017-03-31     38
2017-06-30     36
2017-09-30     30
2017-12-31     30

In [89]:
dftargetForSaleUpgrade

                mean
DATE
2013-06-30  0.000000
2013-09-30  0.027972
2013-12-31  0.040000
2014-03-31  0.028302
2014-06-30  0.084337
2014-09-30  0.016667
2014-12-31  0.051724
2015-03-31  0.052632
2015-06-30  0.018519
2015-09-30  0.098039
2015-12-31  0.037736
2016-03-31  0.039216
2016-06-30  0.038462
2016-09-30  0.023256
2016-12-31  0.076923
2017-03-31  0.026316
2017-06-30  0.166667
2017-09-30  0.066667
2017-12-31  0.100000

#### Analysis on market Variables

In [ ]:
### information gain