In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import datetime
%matplotlib inline

In [3]:
os.chdir("CRE Data")

#### Facility Level Data

In [4]:
df=pd.read_excel("CRE_08102018.xlsx")

In [5]:
df.head()

,MATCH_STATUS,MATCH_ID,PORTFOLIO,LOAN_NUM,FACILITY_NUM,DATE,ADD_QTR,DFT_LOAN_NUM,DFT_OBLIGOR,DFT_DATE,...,ead_mdl,ead_icrs,ead_union,exp_mdl,exp_icrs,exp_union,lag_exp_mdl,lag_exp_icrs,lag_exp_union,IN_SAMPLE
0,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2013-12-31,0.0,,NaN,NaT,...,NaN,NaN,NaN,1449999.98,1449999.98,1449999.98,NaN,NaN,NaN,1
1,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-03-31,0.0,,NaN,NaT,...,NaN,NaN,NaN,1433154.72,1433154.72,1433154.72,1449999.98,1449999.98,1449999.98,1
2,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-06-30,0.0,,NaN,NaT,...,NaN,NaN,NaN,1416113.63,1416113.63,1416113.63,1433154.72,1433154.72,1433154.72,1
3,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-09-30,0.0,,NaN,NaT,...,NaN,NaN,NaN,1398874.44,1398874.44,1398874.44,1416113.63,1416113.63,1416113.63,1
4,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-12-31,0.0,,NaN,NaT,...,NaN,NaN,NaN,1381434.86,1381434.86,1381434.86,1398874.44,1398874.44,1398874.44,1

In [7]:
list(df.columns)

['MATCH_STATUS',
 'MATCH_ID',
 'PORTFOLIO',
 'LOAN_NUM',
 'FACILITY_NUM',
 'DATE',
 'ADD_QTR',
 'DFT_LOAN_NUM',
 'DFT_OBLIGOR',
 'DFT_DATE',
 'CUST_NAME',
 'NET_COMMIT_AMT',
 'OUT_BAL',
 'NET_CHARGE_OFF_AMT',
 'TO_LAST_QTR',
 'LEVERAGED_IND',
 'REPORTING_PORTFOLIO',
 'FACILITY_CD',
 'NAICS_CD',
 'SIC_CD',
 'FEDERAL_RESERVE_CLASS_CD',
 'RPTG_RC_CD',
 'TIME_ID_MIN',
 'ACCT_CMMT_MAX',
 'PDRR',
 'RISK_GRADE',
 'CRR',
 'Downgrade',
 'Downgrade Notch',
 'ACQ_DT',
 'ACCRUAL_STATUS_TYPE',
 'ACCT_NUM',
 'ACQ_NAME',
 'ASSG_RC_CD_NAME',
 'COLLATERAL_CLASS_CD',
 'COLLATERAL_CLASS_DESC',
 'CURR_LOAN_TYPE_CD',
 'CURR_LOAN_TYPE_DESC',
 'CUST_NUM',
 'DIVISION_NAME',
 'FACILITY_CD_DESC',
 'LOAN_NUM_NAME',
 'LOAN_PURPOSE_CD',
 'NON_ACCRUAL_IND',
 'PARENT_FIN_CUST_NAME_NUM',
 'RC_CD',
 'REGION_NAME',
 'SECOND_OFF_NAME_NUM',
 'SOURCE_SYSTEM_CD',
 'ACCT_TYPE',
 'FACILITY_NAME',
 'ACQ_IND',
 'NON_PERFORMING_IND',
 'NOT_FOR_PROFIT_IND',
 'REAL_ESTATE_RISK_IND',
 'SAD_IND',
 'SNC_IND',
 'UBOC_SBA_IND',
 'RENEGOTIATED_IND',
 'SECURED_IND',
 'REGULATORY_RATING',
 'REVOLVING_IND',
 'LGD_RISK_RATING',
 'PROCESS_TYPE',
 'EXPOSURE_CATEGORY',
 'ACQ_CD',
 'PROCESS_TYPE_NAME',
 'RE_RISK_PROPERTY_TYPE',
 'RE_STATE_NAME',
 'RE_COUNTY_NAME',
 'ACTUAL_DELINQUENT_DAY_CNT',
 'CIC',
 'DFT_QTR_N',
 'DFT_QTR_T',
 'DFT_QTR_P',
 'LOAN_NUM_NEG_MATCH',
 'PRED_PERIOD',
 'CIC_GROUP',
 'CIC_GROUP2',
 'SDO_QTR',
 'GAP_QTR',
 'UTILIZATION_RATE',
 'Utilization_Orig',
 'Utilization_lag1',
 'Utilization_lag2',
 'Utilization_lag3',
 'Utilization_lag4',
 'Utilization_lag5',
 'Utilization_lag6',
 'Utilization_lag7',
 'Utilization_lag8',
 'Utilization_lag9',
 'Utilization_lag10',
 'Utilization_lag11',
 'Utilization_lag12',
 'Utilization_lag13',
 'CRR_ORIG',
 'CRR_lag1',
 'CRR_lag2',
 'CRR_lag3',
 'CRR_lag4',
 'CRR_lag5',
 'CRR_lag6',
 'CRR_lag7',
 'CRR_lag8',
 'CRR_lag9',
 'CRR_lag10',
 'CRR_lag11',
 'CRR_lag12',
 'CRR_lag13',
 'CRR_lag14',
 'CRR2_lag1',
 'CRR2_lag2',
 'CRR2_lag3',
 'CRR2_lag4',
 'CRR2_lag5',
 'CRR2_lag6',
 'CRR2_lag7',
 'CRR2_lag8',
 'CRR2_lag9',
 'CRR2_lag10',
 'CRR2_lag11',
 'CRR2_lag12',
 'CRR2_lag13',
 'CRR2_lag14',
 'RENEGOTIATED_lag1',
 'RENEGOTIATED_lag2',
 'RENEGOTIATED_lag3',
 'RENEGOTIATED_lag4',
 'RENEGOTIATED_lag5',
 'RENEGOTIATED_lag6',
 'RENEGOTIATED_lag7',
 'RENEGOTIATED_lag8',
 'RENEGOTIATED_lag9',
 'RENEGOTIATED_lag10',
 'RENEGOTIATED_lag11',
 'RENEGOTIATED_lag12',
 'RENEGOTIATED_lag13',
 'SAD_lag1',
 'SAD_lag2',
 'SAD_lag3',
 'SAD_lag4',
 'SAD_lag5',
 'SAD_lag6',
 'SAD_lag7',
 'SAD_lag8',
 'SAD_lag9',
 'SAD_lag10',
 'SAD_lag11',
 'SAD_lag12',
 'SAD_lag13',
 'pd_scorecard_name',
 'LN_RCD_CNT',
 'CREDIT_LINE_FLAG',
 'LOAN_RGN_KOREA',
 'LOAN_BOOK_AGE',
 'LOAN_AGE_FRM_BOARDING',
 'QTRS_TO_MATURITY',
 'QTRS_TO_MATURITY_MAX',
 'LOAN_BAL_MAX',
 'LOAN_CMMT_MAX',
 'OBLIGOR_AGE',
 'dpd90',
 'dft_mdl',
 'dft_icrs',
 'dft_union',
 'lag_dft_mdl',
 'lag_dft_icrs',
 'lag_dft_union',
 'dft_event_mdl',
 'dft_event_icrs',
 'dft_event_union',
 'ead_mdl',
 'ead_icrs',
 'ead_union',
 'exp_mdl',
 'exp_icrs',
 'exp_union',
 'lag_exp_mdl',
 'lag_exp_icrs',
 'lag_exp_union',
 'IN_SAMPLE']

In [40]:
df.RE_STATE_NAME.value_counts()

CALIFORNIA              154050
WASHINGTON               10637
ARIZONA                   6137
OREGON                    5412
TEXAS                     3750
NEVADA                    3732
COLORADO                   726
NEW YORK                   578
FLORIDA                    447
GEORGIA                    408
ILLINOIS                   328
VIRGINIA                   283
MARYLAND                   246
UTAH                       223
MULTI STATE                189
DISTRICT OF COLUMBIA       166
HAWAII                     145
NORTH CAROLINA             110
PENNSYLVANIA               110
MASSACHUSETTS               81
MULTI-STATE                 81
NEW MEXICO                  80
NEW JERSEY                  74
SOUTH CAROLINA              63
TENNESSEE                   57
MICHIGAN                    56
LOUISIANA                   46
OHIO                        45
MINNESOTA                   44
INDIANA                     42
IDAHO                       41
CONNECTICUT                 25
MISSISSIPPI                 22
ALABAMA                     18
ARKANSAS                    15
MISSOURI                    15
KENTUCKY                    14
NORTH DAKOTA                13
ALASKA                      12
WISCONSIN                   12
IOWA                        11
KANSAS                      11
SOUTH DAKOTA                 8
OKLAHOMA                     6
NEBRASKA                     5
DELAWARE                     5
Name: RE_STATE_NAME, dtype: int64

In [ ]:
##Four Regions
Northeast=['CONNECTICUT', 'MAINE', 'MASSACHUSETTES', 'NEW HAMPSHIRE', 'RHODE ISLAND','VERMONT','NEW JERSEY','NEW YORK','PENNSYLVANIA']
Midwest=['ILLINOIS','INDIANA','MICHIGAN','OHIO','WISCONSIN','IOWA','KANSAS','MINNESOTA','MISSOURI','NEBRASKA','NORTH DAKOTA','SOUTH DAKOTA']
South=['DELAWARE','FLORIDA','GEORGIA','MARYLAND','NORTH CAROLINA','SOUTH CAROLINA','VIRGINIA','DISTRICT OF COLUMBIA','WEST VIRGINIA','ALABAMA','KENTUCKY','MISSISSIPPI','TENNESSEE','ARKANSAS','LOUISIANA','OKLAHOMA','TEXAS']
West=['ARIZONA','COLORADO','IDAHO','MONTANA','NEVADA','']

In [ ]:
##Nine Devisions
NewEngland=['']
MidAtlantic=['']
EastNorthCentral=['']
WestNorthCentral=['']
SouthAtlantic=['']
EastSouthCentral=['']
WestSouthCentral=['']
Mountain=['']
Pacific=['']

In [ ]:

for i in range(len(df)):

In [8]:
df['Downgrade'].value_counts()

0    187695
1      8110
Name: Downgrade, dtype: int64

In [9]:
df['Downgrade Notch'].describe()

count    195805.000000
mean          0.051041
std           0.266265
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           5.000000
Name: Downgrade Notch, dtype: float64

#### Overall, will be able to see seperate info

In [11]:
df.groupby('DATE').agg(['count','min','max','mean'])

           MATCH_ID                   FACILITY_NUM                \
              count min max      mean        count           min
DATE
2005-03-31     2885   0   8  0.013172         2885  2.681988e+16
2005-06-30     2854   0   6  0.011212         2854  2.681988e+16
2005-09-30     2820   0   8  0.005319         2820  2.681988e+16
2005-12-31     4883   0   9  0.004096         4883  2.681988e+16
2006-03-31     4839   0   1  0.001240         4839  2.681988e+16
2006-06-30     4838   0   3  0.003307         4838  2.681988e+16
2006-09-30     4881   0   9  0.005532         4881  2.681988e+16
2006-12-31     4917   0   8  0.002441         4917  2.681988e+16
2007-03-31     4922   0   1  0.000610         4922  2.681988e+16
2007-06-30     4970   0   6  0.002414         4970  2.681988e+16
2007-09-30     4973   0   3  0.001609         4973  2.681988e+16
2007-12-31     5062   0   6  0.005729         5062  2.681988e+16
2008-03-31     5112   0   4  0.007042         5112  2.681988e+16
2008-06-30     5134   0   1  0.003116         5134  2.681988e+16
2008-09-30     5095   0   6  0.006673         5095  2.681988e+16
2008-12-31     5068   0   6  0.007893         5068  2.681988e+16
2009-03-31     5023   0   6  0.013936         5023  2.695665e+16
2009-06-30     4882   0   6  0.023351         4882  2.695665e+16
2009-09-30     4742   0   3  0.010966         4742  2.695665e+16
2009-12-31     4643   0   8  0.012061         4643  2.695665e+16
2010-03-31     4561   0   4  0.012059         4561  2.695665e+16
2010-06-30     4534   0   3  0.033083         4534  2.695665e+16
2010-09-30     2455   0   6  0.041955         2455  2.695665e+16
2010-12-31     2409   0   3  0.008302         2409  2.695665e+16
2011-03-31     2400   0   3  0.012917         2400  2.695665e+16
2011-06-30     2438   0   3  0.012305         2438  2.695665e+16
2011-09-30     2487   0   6  0.008846         2487  2.695665e+16
2011-12-31     2554   0   6  0.014879         2554  2.695665e+16
2012-03-31     2586   0   6  0.013148         2586  2.695665e+16
2012-06-30     2493   0   6  0.008022         2493  2.695665e+16
2012-09-30     2460   0   6  0.004065         2460  2.695665e+16
2012-12-31     2396   0   1  0.001252         2396  2.709342e+16
2013-03-31     2325   0   1  0.000860         2325  2.709342e+16
2013-06-30     3320   0   3  0.003313         3320  2.709342e+16
2013-09-30     3601   0   3  0.002777         3601  2.709342e+16
2013-12-31     3531   0   6  0.001699         3531  5.295440e+15
2014-03-31     3459   0   3  0.007517         3459  5.295440e+15
2014-06-30     3465   0   6  0.003752         3465  5.295440e+15
2014-09-30     3476   0   6  0.002877         3476  5.295440e+15
2014-12-31     3536   0   6  0.001697         3536  5.295440e+15
2015-03-31     3563   0   1  0.000561         3563  5.295440e+15
2015-06-30     3573   0   1  0.001399         3573  5.295440e+15
2015-09-30     3587   0   1  0.001394         3587  5.295440e+15
2015-12-31     3598   0   1  0.000278         3598  5.295440e+15
2016-03-31     3655   0   0  0.000000         3655  5.295440e+15
2016-06-30     3656   0   1  0.000821         3656  5.295440e+15
2016-09-30     3633   0   3  0.002202         3633  5.295440e+15
2016-12-31     3594   0   1  0.000556         3594  5.295440e+15
2017-03-31     3571   0   1  0.000280         3571  5.295440e+15
2017-06-30     3544   0   1  0.000282         3544  5.295440e+15
2017-09-30     3467   0   0  0.000000         3467  5.295440e+15
2017-12-31     3335   0   1  0.000300         3335  5.295440e+15

                                       ADD_QTR      ...   lag_exp_icrs  \
                     max          mean   count  min ...            max
DATE                                                ...
2005-03-31  9.999912e+19  5.256363e+19    2885  0.0 ...   5.755300e+07
2005-06-30  9.999912e+19  5.262190e+19    2854  0.0 ...   5.704707e+07
2005-09-30  9.999915e+19  5.271785e+19    2820  0.0 ...   7.500000e+07
2005-12-31  9.999915e+19  5.229967e+19    4883  0.0 ...   7.500000e+07
2006-03-31  9.999915e+19  5.223236e+19    4839  0.0 ...   7.500000e+07
2006-06-30  9.999915e+19  5.236421e+19    4838  0.0 ...   7.500000e+07
2006-09-30  9.999915e+19  5.232112e+19    4881  0.0 ...   1.193600e+08
2006-12-31  9.999915e+19  5.230667e+19    4917  0.0 ...   7.500000e+07
2007-03-31  9.999915e+19  5.255015e+19    4922  0.0 ...   7.500000e+07
2007-06-30  9.999915e+19  5.260336e+19    4970  0.0 ...   7.500000e+07
2007-09-30  9.999915e+19  5.257453e+19    4973  0.0 ...   7.500000e+07
2007-12-31  9.999915e+19  5.244949e+19    5062  0.0 ...   7.500000e+07
2008-03-31  9.999915e+19  5.234643e+19    5112  0.0 ...   7.500000e+07
2008-06-30  9.999915e+19  5.254827e+19    5134  0.0 ...   7.500000e+07
2008-09-30  9.999915e+19  5.263097e+19    5095  0.0 ...   7.775000e+07
2008-12-31  9.999915e+19  5.267916e+19    5068  0.0 ...   7.775000e+07
2009-03-31  9.999915e+19  5.272287e+19    5023  0.0 ...   7.925000e+07
2009-06-30  9.999915e+19  5.302943e+19    4882  0.0 ...   7.800000e+07
2009-09-30  9.999915e+19  5.313546e+19    4742  0.0 ...   7.800000e+07
2009-12-31  9.999915e+19  5.318220e+19    4643  0.0 ...   7.800000e+07
2010-03-31  9.999915e+19  5.324312e+19    4561  0.0 ...   7.800000e+07
2010-06-30  9.999915e+19  5.316898e+19    4534  0.0 ...   7.800000e+07
2010-09-30  9.999915e+19  5.366270e+19    2455  0.0 ...   7.800000e+07
2010-12-31  9.999912e+19  5.393427e+19    2409  0.0 ...   7.800000e+07
2011-03-31  9.999912e+19  5.400431e+19    2400  0.0 ...   7.800000e+07
2011-06-30  9.999912e+19  5.392694e+19    2438  0.0 ...   8.800000e+07
2011-09-30  9.999912e+19  5.393744e+19    2487  0.0 ...   8.800000e+07
2011-12-31  9.999912e+19  5.396701e+19    2554  0.0 ...   8.800000e+07
2012-03-31  9.999912e+19  5.394898e+19    2586  0.0 ...   9.997878e+07
2012-06-30  9.999912e+19  5.446035e+19    2493  0.0 ...   9.999600e+07
2012-09-30  9.999912e+19  5.462756e+19    2460  0.0 ...   9.999600e+07
2012-12-31  9.999912e+19  5.476112e+19    2396  0.0 ...   9.999600e+07
2013-03-31  9.999912e+19  5.468878e+19    2325  0.0 ...   9.999600e+07
2013-06-30  9.999912e+19  5.385534e+19    3320  0.0 ...   9.999524e+07
2013-09-30  9.999912e+19  5.324075e+19    3601  0.0 ...   2.000000e+08
2013-12-31  9.999912e+19  5.343746e+19    3531  0.0 ...   2.000000e+08
2014-03-31  9.999912e+19  5.359222e+19    3459  0.0 ...   2.000000e+08
2014-06-30  9.999912e+19  5.411390e+19    3465  0.0 ...   1.535000e+08
2014-09-30  9.999912e+19  5.414332e+19    3476  0.0 ...   1.500000e+08
2014-12-31  9.999912e+19  5.447944e+19    3536  0.0 ...   1.457143e+08
2015-03-31  9.999912e+19  5.445647e+19    3563  0.0 ...   1.403571e+08
2015-06-30  9.999912e+19  5.451152e+19    3573  0.0 ...   1.360714e+08
2015-09-30  9.999912e+19  5.450486e+19    3587  0.0 ...   9.999524e+07
2015-12-31  9.999912e+19  5.486027e+19    3598  0.0 ...   2.000000e+08
2016-03-31  9.999912e+19  5.500667e+19    3655  0.0 ...   1.976925e+08
2016-06-30  9.999912e+19  5.506891e+19    3656  0.0 ...   2.375000e+08
2016-09-30  9.999912e+19  5.517181e+19    3633  0.0 ...   2.125000e+08
2016-12-31  9.999912e+19  5.540224e+19    3594  0.0 ...   1.900000e+08
2017-03-31  9.999913e+19  5.531656e+19    3571  0.0 ...   1.716757e+08
2017-06-30  9.999913e+19  5.512721e+19    3544  0.0 ...   1.627020e+08
2017-09-30  9.999913e+19  5.474419e+19    3467  0.0 ...   1.500000e+08
2017-12-31  9.999913e+19  5.495840e+19    3335  0.0 ...   1.500000e+08

                         lag_exp_union                                   \
                    mean         count  min           max          mean
DATE
2005-03-31  2.017464e+06          2789  0.0  5.755300e+07  2.017464e+06
2005-06-30  2.131659e+06          2724  0.0  5.704707e+07  2.131659e+06
2005-09-30  2.271777e+06          2699  0.0  7.500000e+07  2.271777e+06
2005-12-31  2.358272e+06          2634  0.0  7.500000e+07  2.358272e+06
2006-03-31  1.686604e+06          4623  0.0  7.500000e+07  1.686604e+06
2006-06-30  1.777202e+06          4572  0.0  7.500000e+07  1.777202e+06
2006-09-30  1.801865e+06          4629  0.0  1.193600e+08  1.801865e+06
2006-12-31  1.812685e+06          4630  0.0  7.500000e+07  1.812685e+06
2007-03-31  1.854854e+06          4708  0.0  7.500000e+07  1.854854e+06
2007-06-30  1.824184e+06          4668  0.0  7.500000e+07  1.824184e+06
2007-09-30  1.829886e+06          4753  0.0  7.500000e+07  1.829886e+06
2007-12-31  1.881666e+06          4760  0.0  7.500000e+07  1.881666e+06
2008-03-31  1.976505e+06          4871  0.0  7.500000e+07  1.976505e+06
2008-06-30  2.092933e+06          4891  0.0  7.500000e+07  2.092933e+06
2008-09-30  2.137226e+06          4949  0.0  7.775000e+07  2.137226e+06
2008-12-31  2.208125e+06          4924  0.0  7.775000e+07  2.208125e+06
2009-03-31  2.242314e+06          4937  0.0  7.925000e+07  2.242314e+06
2009-06-30  2.284684e+06          4781  0.0  7.800000e+07  2.284684e+06
2009-09-30  2.267237e+06          4683  0.0  7.800000e+07  2.267237e+06
2009-12-31  2.243905e+06          4568  0.0  7.800000e+07  2.243905e+06
2010-03-31  2.202395e+06          4525  0.0  7.800000e+07  2.202395e+06
2010-06-30  2.122977e+06          4501  0.0  7.800000e+07  2.122977e+06
2010-09-30  3.374741e+06          2409  0.0  7.800000e+07  3.374741e+06
2010-12-31  3.392643e+06          2280  0.0  7.800000e+07  3.392643e+06
2011-03-31  3.281957e+06          2312  0.0  7.800000e+07  3.281957e+06
2011-06-30  3.244136e+06          2313  0.0  8.800000e+07  3.244136e+06
2011-09-30  3.199834e+06          2339  0.0  8.800000e+07  3.199834e+06
2011-12-31  3.178062e+06          2365  0.0  8.800000e+07  3.178062e+06
2012-03-31  3.283380e+06          2440  0.0  9.997878e+07  3.283380e+06
2012-06-30  3.261411e+06          2339  0.0  9.999600e+07  3.261411e+06
2012-09-30  3.307500e+06          2319  0.0  9.999600e+07  3.307500e+06
2012-12-31  3.314331e+06          2216  0.0  9.999600e+07  3.314331e+06
2013-03-31  3.408623e+06          2208  0.0  9.999600e+07  3.408623e+06
2013-06-30  3.532773e+06          2183  0.0  9.999524e+07  3.532773e+06
2013-09-30  3.837551e+06          3074  0.0  2.000000e+08  3.837551e+06
2013-12-31  3.686229e+06          3300  0.0  2.000000e+08  3.686229e+06
2014-03-31  3.848719e+06          3313  0.0  2.000000e+08  3.848719e+06
2014-06-30  4.159903e+06          3192  0.0  1.535000e+08  4.159903e+06
2014-09-30  4.283470e+06          3230  0.0  1.500000e+08  4.283470e+06
2014-12-31  4.346562e+06          3297  0.0  1.457143e+08  4.346562e+06
2015-03-31  4.487409e+06          3381  0.0  1.403571e+08  4.487409e+06
2015-06-30  4.442938e+06          3397  0.0  1.360714e+08  4.442938e+06
2015-09-30  4.424296e+06          3406  0.0  9.999524e+07  4.424296e+06
2015-12-31  4.511332e+06          3386  0.0  2.000000e+08  4.511332e+06
2016-03-31  4.603354e+06          3451  0.0  1.976925e+08  4.603354e+06
2016-06-30  4.758602e+06          3510  0.0  2.375000e+08  4.758602e+06
2016-09-30  4.912063e+06          3481  0.0  2.125000e+08  4.912063e+06
2016-12-31  4.770882e+06          3469  0.0  1.900000e+08  4.770882e+06
2017-03-31  4.630895e+06          3446  0.0  1.716757e+08  4.630895e+06
2017-06-30  4.596922e+06          3434  0.0  1.627020e+08  4.596922e+06
2017-09-30  4.565847e+06          3409  0.0  1.500000e+08  4.565847e+06
2017-12-31  4.402478e+06          3306  0.0  1.500000e+08  4.402478e+06

           IN_SAMPLE
               count min max mean
DATE
2005-03-31      2885   1   1    1
2005-06-30      2854   1   1    1
2005-09-30      2820   1   1    1
2005-12-31      4883   1   1    1
2006-03-31      4839   1   1    1
2006-06-30      4838   1   1    1
2006-09-30      4881   1   1    1
2006-12-31      4917   1   1    1
2007-03-31      4922   1   1    1
2007-06-30      4970   1   1    1
2007-09-30      4973   1   1    1
2007-12-31      5062   1   1    1
2008-03-31      5112   1   1    1
2008-06-30      5134   1   1    1
2008-09-30      5095   1   1    1
2008-12-31      5068   1   1    1
2009-03-31      5023   1   1    1
2009-06-30      4882   1   1    1
2009-09-30      4742   1   1    1
2009-12-31      4643   1   1    1
2010-03-31      4561   1   1    1
2010-06-30      4534   1   1    1
2010-09-30      2455   1   1    1
2010-12-31      2409   1   1    1
2011-03-31      2400   1   1    1
2011-06-30      2438   1   1    1
2011-09-30      2487   1   1    1
2011-12-31      2554   1   1    1
2012-03-31      2586   1   1    1
2012-06-30      2493   1   1    1
2012-09-30      2460   1   1    1
2012-12-31      2396   1   1    1
2013-03-31      2325   1   1    1
2013-06-30      3320   1   1    1
2013-09-30      3601   1   1    1
2013-12-31      3531   1   1    1
2014-03-31      3459   1   1    1
2014-06-30      3465   1   1    1
2014-09-30      3476   1   1    1
2014-12-31      3536   1   1    1
2015-03-31      3563   1   1    1
2015-06-30      3573   1   1    1
2015-09-30      3587   1   1    1
2015-12-31      3598   1   1    1
2016-03-31      3655   1   1    1
2016-06-30      3656   1   1    1
2016-09-30      3633   1   1    1
2016-12-31      3594   1   1    1
2017-03-31      3571   1   1    1
2017-06-30      3544   1   1    1
2017-09-30      3467   1   1    1
2017-12-31      3335   1   1    1

[52 rows x 440 columns]

#### Pivot Table

In [12]:
pd.pivot_table(df,index=['ACCT_NUM'])

,ACCT_CMMT_MAX,ACCT_TYPE,ACQ_CD,ACTUAL_DELINQUENT_DAY_CNT,ADD_QTR,CREDIT_LINE_FLAG,CRR,CRR2_lag1,CRR2_lag10,CRR2_lag11,...,ead_union,exp_icrs,exp_mdl,exp_union,lag_dft_icrs,lag_dft_mdl,lag_dft_union,lag_exp_icrs,lag_exp_mdl,lag_exp_union
ACCT_NUM,,,,,,,,,,,,,,,,,,,,,
-1,25000000.00,-1.000000,NaN,0.0,0.000000,0.000000,6.000000,-1.000000,-1.000000,-1.000000,...,NaN,8.750000e+05,8.750000e+05,8.750000e+05,0.000000,0.0,0.000000,NaN,NaN,NaN
529544,6312100.80,710.000000,0.000000,0.0,0.000000,0.000000,4.037037,3.703704,1.018519,0.740741,...,NaN,1.420715e+06,1.420715e+06,1.420715e+06,0.000000,0.0,0.000000,1.411410e+06,1.411410e+06,1.411410e+06
2681988,585138.55,89.187500,NaN,0.0,0.062500,0.000000,6.000000,6.000000,6.000000,5.562500,...,NaN,4.859628e+05,4.859628e+05,4.859628e+05,0.000000,0.0,0.000000,4.920244e+05,4.920244e+05,4.920244e+05
2695665,2464133.44,260.000000,0.000000,0.0,0.000000,0.000000,5.000000,4.647059,1.470588,1.117647,...,NaN,2.129604e+06,2.129604e+06,2.129604e+06,0.000000,0.0,0.000000,2.152310e+06,2.152310e+06,2.152310e+06
2709342,8260159.32,250.809859,21.847826,0.0,0.000000,0.042254,5.316901,5.105634,3.316901,3.154930,...,NaN,1.903047e+06,1.903047e+06,1.903047e+06,0.000000,0.0,0.000000,1.956021e+06,1.956021e+06,1.956021e+06
3900841,1082027.01,260.000000,0.000000,0.0,0.000000,0.000000,5.142857,4.785714,1.000000,0.500000,...,NaN,1.045661e+06,1.045661e+06,1.045661e+06,0.000000,0.0,0.000000,1.048609e+06,1.048609e+06,1.048609e+06
3901864,219375.00,260.000000,NaN,0.0,0.000000,0.000000,6.000000,5.416667,0.166667,-0.416667,...,NaN,2.076543e+05,2.076543e+05,2.076543e+05,0.000000,0.0,0.000000,2.088379e+05,2.088379e+05,2.088379e+05
3903928,350000.00,110.000000,NaN,0.0,0.000000,0.000000,6.000000,5.611111,2.111111,1.722222,...,NaN,3.390623e+05,3.390623e+05,3.390623e+05,0.000000,0.0,0.000000,3.397754e+05,3.397754e+05,3.397754e+05
3907002,1323777.70,260.000000,18.000000,0.0,0.000000,0.000000,4.470588,4.176471,1.470588,1.117647,...,NaN,1.274862e+06,1.274862e+06,1.274862e+06,0.058824,0.0,0.058824,1.278090e+06,1.278090e+06,1.278090e+06
6502453,4390346.00,47.400000,NaN,0.0,0.000000,1.000000,3.600000,3.200000,3.000000,2.200000,...,NaN,3.778319e+06,3.778319e+06,3.778319e+06,0.000000,0.0,0.000000,3.788388e+06,3.788388e+06,3.788388e+06
6513393,641504.57,179.750000,NaN,0.0,0.083333,1.000000,6.000000,6.000000,1.916667,1.333333,...,NaN,3.976886e+05,3.976886e+05,3.976886e+05,0.000000,0.0,0.000000,3.995658e+05,3.995658e+05,3.995658e+05
8240292,1130485.14,11.000000,18.000000,0.0,0.000000,0.000000,6.000000,-1.000000,-1.000000,-1.000000,...,NaN,1.130485e+06,1.130485e+06,1.130485e+06,0.000000,0.0,0.000000,NaN,NaN,NaN
8264912,1457526.18,12.000000,18.000000,0.0,0.000000,0.000000,6.444444,5.666667,-1.000000,-1.000000,...,NaN,1.424868e+06,1.424868e+06,1.424868e+06,0.000000,0.0,0.000000,1.429101e+06,1.429101e+06,1.429101e+06
8273137,1497231.26,710.000000,0.000000,0.0,0.000000,0.000000,5.428571,4.928571,1.000000,0.500000,...,NaN,1.440399e+06,1.440399e+06,1.440399e+06,0.000000,0.0,0.000000,1.444965e+06,1.444965e+06,1.444965e+06
8319674,356863.18,175.470588,NaN,0.0,0.000000,0.000000,6.000000,5.588235,1.882353,1.470588,...,NaN,3.472139e+05,3.472139e+05,3.472139e+05,0.000000,0.0,0.000000,3.479107e+05,3.479107e+05,3.479107e+05
9299404,2046623.24,260.000000,0.000000,0.0,0.000000,0.000000,5.662651,5.518072,4.168675,4.000000,...,NaN,9.605007e+05,9.605007e+05,9.605007e+05,0.000000,0.0,0.000000,9.626708e+05,9.626708e+05,9.626708e+05
10987070,20916999.94,-1.000000,NaN,0.0,0.000000,0.000000,6.000000,6.000000,6.000000,3.666667,...,NaN,4.975767e+06,4.975767e+06,4.975767e+06,0.000000,0.0,0.000000,5.003697e+06,5.003697e+06,5.003697e+06
11288791,1570765.24,207.136364,NaN,0.0,0.000000,0.000000,3.181818,3.136364,3.000000,2.818182,...,NaN,8.492281e+05,8.492281e+05,8.492281e+05,0.000000,0.0,0.000000,9.070751e+05,9.070751e+05,9.070751e+05
11599536,3096931.60,260.000000,0.000000,0.0,0.023810,0.000000,4.380952,4.261905,3.095238,2.952381,...,NaN,2.849590e+06,2.849590e+06,2.849590e+06,0.000000,0.0,0.000000,2.857354e+06,2.857354e+06,2.857354e+06
12035639,1415000.00,260.000000,0.000000,0.0,0.000000,0.000000,5.000000,4.000000,-1.000000,-1.000000,...,NaN,1.394965e+06,1.394965e+06,1.394965e+06,0.000000,0.0,0.000000,1.399418e+06,1.399418e+06,1.399418e+06
12698451,24137500.00,260.000000,NaN,0.0,0.000000,1.000000,5.285714,4.285714,-1.000000,-1.000000,...,NaN,8.809278e+06,8.809278e+06,8.809278e+06,0.000000,0.0,0.000000,8.893600e+06,8.893600e+06,8.893600e+06
12731278,1222345.04,110.000000,18.000000,0.0,0.000000,0.000000,4.857143,4.000000,-1.000000,-1.000000,...,NaN,1.204961e+06,1.204961e+06,1.204961e+06,0.000000,0.0,0.000000,1.207907e+06,1.207907e+06,1.207907e+06
12779178,48956395.93,260.000000,19.000000,5.6,0.000000,0.000000,4.400000,3.200000,-1.000000,-1.000000,...,NaN,4.846268e+07,4.846268e+07,4.846268e+07,0.000000,0.0,0.000000,4.857784e+07,4.857784e+07,4.857784e+07
12786033,566257.08,260.000000,NaN,0.0,0.000000,0.000000,6.000000,4.600000,-1.000000,-1.000000,...,NaN,5.609940e+05,5.609940e+05,5.609940e+05,0.000000,0.0,0.000000,5.623607e+05,5.623607e+05,5.623607e+05
15814733,1350000.00,240.425000,0.000000,0.0,0.025000,0.000000,6.075000,6.050000,4.450000,4.300000,...,NaN,1.209744e+06,1.209744e+06,1.209744e+06,0.000000,0.0,0.000000,1.208600e+06,1.208600e+06,1.208600e+06
16208356,2675000.00,260.000000,30.923077,0.0,0.000000,0.000000,5.615385,5.153846,0.615385,0.076923,...,NaN,2.579959e+06,2.579959e+06,2.579959e+06,0.000000,0.0,0.000000,2.588550e+06,2.588550e+06,2.588550e+06
17389452,698119.29,12.000000,333.000000,0.0,0.007241,0.000000,7.379310,7.344828,7.241379,7.172414,...,NaN,3.167236e+05,3.167236e+05,3.167236e+05,0.000000,0.0,0.000000,3.231664e+05,3.231664e+05,3.231664e+05
17394197,2409047.00,260.000000,0.000000,0.0,0.000000,0.000000,4.666667,3.000000,-1.000000,-1.000000,...,NaN,9.852120e+05,9.852120e+05,9.852120e+05,0.000000,0.0,0.000000,9.886830e+05,9.886830e+05,9.886830e+05
17395152,4992525.64,260.000000,0.000000,0.0,0.000000,0.000000,4.266667,3.933333,0.933333,0.600000,...,NaN,4.832068e+06,4.832068e+06,4.832068e+06,0.000000,0.0,0.000000,4.844029e+06,4.844029e+06,4.844029e+06
17402974,666900.63,12.000000,NaN,0.0,0.000000,0.000000,6.000000,5.631579,2.315789,1.947368,...,NaN,5.988865e+05,5.988865e+05,5.988865e+05,0.000000,0.0,0.000000,6.034674e+05,6.034674e+05,6.034674e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9998799829,786300.00,260.000000,0.000000,0.0,0.000000,0.000000,5.333333,4.166667,-1.000000,-1.000000,...,NaN,7.406155e+05,7.406155e+05,7.406155e+05,0.000000,0.0,0.000000,7.559784e+05,7.559784e+05,7.559784e+05
9998801260,1900000.00,260.000000,0.000000,0.0,0.000000,0.000000,6.285714,5.714286,1.000000,0.500000,...,NaN,1.838809e+06,1.838809e+06,1.838809e+06,0.000000,0.0,0.000000,1.843964e+06,1.843964e+06,1.843964e+06
9998804165,7000000.00,260.000000,0.000000,0.0,0.000000,0.000000,6.571429,5.285714,-1.000000,-1.000000,...,NaN,6.878353e+06,6.878353e+06,6.878353e+06,0.000000,0.0,0.000000,6.900694e+06,6.900694e+06,6.900694e+06
9998805600,2200000.00,120.000000,0.000000,0.0,0.000000,0.000000,4.800000,3.800000,-1.000000,-1.000000,...,NaN,2.152911e+06,2.152911e+06,2.152911e+06,0.000000,0.0,0.000000,2.166157e+06,2.166157e+06,2.166157e+06
9998807069,2900000.00,120.000000,0.000000,0.0,0.000000,0.000000,5.000000,4.500000,0.000000,-0.500000,...,NaN,2.824399e+06,2.824399e+06,2.824399e+06,0.000000,0.0,0.000000,2.831485e+06,2.831485e+06,2.831485e+06
9998808505,2016500.00,260.000000,0.000000,0.0,0.000000,0.000000,4.000000,3.285714,-1.000000,-1.000000,...,NaN,1.978763e+06,1.978763e+06,1.978763e+06,0.000000,0.0,0.000000,1.985144e+06,1.985144e+06,1.985144e+06
9998815740,2262500.00,260.000000,0.000000,0.0,0.000000,0.000000,5.750000,5.375000,1.625000,1.187500,...,NaN,1.889026e+06,1.889026e+06,1.889026e+06,0.000000,0.0,0.000000,1.901413e+06,1.901413e+06,1.901413e+06
9999064736,7424462.00,260.000000,0.000000,0.0,0.000000,1.000000,4.750000,4.125000,-1.000000,-1.000000,...,NaN,2.913908e+06,2.913908e+06,2.913908e+06,0.000000,0.0,0.000000,2.284591e+06,2.284591e+06,2.284591e+06
9999188253,1900000.00,710.000000,NaN,0.0,0.000000,0.000000,6.285714,5.285714,-1.000000,-1.000000,...,NaN,1.584889e+06,1.584889e+06,1.584889e+06,0.000000,0.0,0.000000,1.849038e+06,1.849038e+06,1.849038e+06
9999460280,1122874.40,260.000000,0.000000,5.0,0.000000,0.000000,5.666667,4.500000,-1.000000,-1.000000,...,NaN,1.106858e+06,1.106858e+06,1.106858e+06,0.000000,0.0,0.000000,1.110351e+06,1.110351e+06,1.110351e+06
9999461767,1250000.00,260.000000,0.000000,0.0,0.000000,0.000000,6.000000,5.125000,-1.000000,-1.000000,...,NaN,1.228366e+06,1.228366e+06,1.228366e+06,0.000000,0.0,0.000000,1.231362e+06,1.231362e+06,1.231362e+06
9999464704,3995303.86,260.000000,0.000000,0.0,0.000000,0.000000,5.111111,4.833333,1.888889,1.555556,...,NaN,3.865823e+06,3.865823e+06,3.865823e+06,0.000000,0.0,0.000000,3.873977e+06,3.873977e+06,3.873977e+06
9999467640,1350000.00,260.000000,0.000000,0.0,0.000000,0.000000,5.833333,5.666667,-1.000000,-1.000000,...,NaN,1.291456e+06,1.291456e+06,1.291456e+06,0.000000,0.0,0.000000,1.308325e+06,1.308325e+06,1.308325e+06
9999470586,1673250.00,260.000000,0.000000,0.0,0.000000,0.000000,5.200000,4.000000,-1.000000,-1.000000,...,NaN,1.655188e+06,1.655188e+06,1.655188e+06,0.000000,0.0,0.000000,1.659756e+06,1.659756e+06,1.659756e+06
9999471303,10400000.00,260.000000,0.000000,0.0,0.000000,1.000000,4.333333,3.666667,-1.000000,-1.000000,...,NaN,9.480100e+06,9.480100e+06,9.480100e+06,0.000000,0.0,0.000000,9.437129e+06,9.437129e+06,9.437129e+06
9999472046,33815244.00,120.000000,0.000000,0.0,0.000000,1.000000,3.888889,3.444444,-1.000000,-1.000000,...,NaN,2.807985e+07,2.807985e+07,2.807985e+07,0.000000,0.0,0.000000,2.807620e+07,2.807620e+07,2.807620e+07
9999476468,1650000.00,260.000000,0.000000,0.0,0.000000,0.000000,5.000000,4.647059,1.470588,1.117647,...,NaN,1.597031e+06,1.597031e+06,1.597031e+06,0.000000,0.0,0.000000,1.601132e+06,1.601132e+06,1.601132e+06
9999505860,9744498.80,233.000000,0.000000,0.0,0.000000,0.620690,5.724138,5.241379,1.000000,0.551724,...,NaN,7.691141e+06,7.691141e+06,7.691141e+06,0.000000,0.0,0.000000,7.689995e+06,7.689995e+06,7.689995e+06
9999531049,3162000.00,260.000000,0.000000,0.0,0.000000,0.000000,5.666667,5.083333,0.166667,-0.416667,...,NaN,3.090375e+06,3.090375e+06,3.090375e+06,0.000000,0.0,0.000000,3.097135e+06,3.097135e+06,3.097135e+06
9999556228,2013133.70,260.000000,0.000000,0.0,0.000000,0.000000,6.133333,5.900000,3.566667,3.300000,...,NaN,1.919487e+06,1.919487e+06,1.919487e+06,0.000000,0.0,0.000000,1.923287e+06,1.923287e+06,1.923287e+06
9999581408,9035816.49,260.000000,0.000000,0.0,0.090909,1.000000,5.454545,4.818182,-0.454545,-1.000000,...,NaN,1.855483e+06,1.855483e+06,1.855483e+06,0.000000,0.0,0.000000,1.470258e+06,1.470258e+06,1.470258e+06
9999606585,20670000.00,120.000000,0.000000,0.0,0.000000,0.263158,5.000000,4.368421,0.263158,-0.052632,...,NaN,1.699622e+07,1.699622e+07,1.699622e+07,0.000000,0.0,0.000000,1.687803e+07,1.687803e+07,1.687803e+07
9999707326,599495.93,260.000000,NaN,0.0,0.000000,0.000000,5.727273,5.090909,-0.636364,-1.000000,...,NaN,5.914373e+05,5.914373e+05,5.914373e+05,0.000000,0.0,0.000000,5.922856e+05,5.922856e+05,5.922856e+05
9999911001,1337735.00,244.942308,0.000000,0.0,0.000000,0.000000,3.942308,3.923077,3.788462,3.692308,...,NaN,1.110146e+06,1.110146e+06,1.110146e+06,0.000000,0.0,0.000000,1.116898e+06,1.116898e+06,1.116898e+06
9999911548,1200000.00,254.882353,0.000000,0.0,0.019608,0.176471,4.450980,4.254902,2.588235,2.490196,...,NaN,1.104616e+06,1.104616e+06,1.104616e+06,0.000000,0.0,0.000000,1.105828e+06,1.105828e+06,1.105828e+06
9999911688,1714999.98,120.000000,0.000000,0.0,0.000000,0.000000,4.800000,3.800000,-1.000000,-1.000000,...,NaN,1.678292e+06,1.678292e+06,1.678292e+06,0.000000,0.0,0.000000,1.688618e+06,1.688618e+06,1.688618e+06
9999912108,560000.00,111.146341,0.000000,0.0,0.024390,0.000000,5.560976,5.414634,3.365854,3.146341,...,NaN,5.174473e+05,5.174473e+05,5.174473e+05,0.000000,0.0,0.000000,5.187430e+05,5.187430e+05,5.187430e+05
9999912363,1500000.00,260.000000,0.000000,0.0,0.200000,0.000000,6.000000,4.600000,-1.000000,-1.000000,...,NaN,1.100809e+06,1.100809e+06,1.100809e+06,0.000000,0.0,0.000000,1.250505e+06,1.250505e+06,1.250505e+06
9999913320,514200.00,260.000000,0.000000,0.0,0.000000,0.000000,7.000000,5.000000,-1.000000,-1.000000,...,NaN,5.127245e+05,5.127245e+05,5.127245e+05,0.000000,0.0,0.000000,5.136332e+05,5.136332e+05,5.136332e+05
9999915408,825000.00,247.571429,NaN,0.0,0.047619,0.000000,6.190476,5.761905,2.666667,2.333333,...,NaN,7.843519e+05,7.843519e+05,7.843519e+05,0.000000,0.0,0.000000,7.869257e+05,7.869257e+05,7.869257e+05

In [27]:
pd.pivot_table(df,index=['FACILITY_NUM']).to_excel('FacilityPivot.xlsx', index  = True) ### FACILITY LEVEL DATA

In [28]:
pd.pivot_table(df,index=['DATE']).to_excel('DATEPivot.xlsx', index  = True) ### FACILITY LEVEL DATA

In [30]:
pd.pivot_table(df,index=['DATE','RE_STATE_NAME','RE_COUNTY_NAME']).to_excel('DATEStateCountyPivot.xlsx', index  = True)

In [31]:
pd.pivot_table(df,index=['DATE','RE_STATE_NAME']).to_excel('DATEStatePivot.xlsx', index  = True)   ###difficult to plot ts  using columns in the dataframe pivot table

In [34]:
pd.pivot_table(df,index=['DATE'],values=['CRR','Downgrade','Downgrade Notch'],columns=['RE_STATE_NAME'],aggfunc=[np.mean]).to_excel('TSDATEStatePivot.xlsx', index  = True)

In [24]:
A=pd.DataFrame(pd.pivot_table(df,index=['FACILITY_NUM']))

In [26]:
A.DATE

AttributeError: 'DataFrame' object has no attribute 'DATE'

In [21]:
.groupby('DATE').agg(['mean'])

KeyError: 'As of Date'

In [45]:
df.describe()

,MATCH_ID,FACILITY_NUM,ADD_QTR,DFT_OBLIGOR,NET_COMMIT_AMT,OUT_BAL,NET_CHARGE_OFF_AMT,TO_LAST_QTR,FACILITY_CD,NAICS_CD,...,ead_mdl,ead_icrs,ead_union,exp_mdl,exp_icrs,exp_union,lag_exp_mdl,lag_exp_icrs,lag_exp_union,IN_SAMPLE
count,195805.000000,1.958050e+05,195805.000000,7.480000e+02,1.958050e+05,1.958050e+05,195300.000000,195805.000000,195805.000000,195805.000000,...,7.460000e+02,1.286000e+03,1.482000e+03,1.958050e+05,1.958050e+05,1.958050e+05,1.840240e+05,1.840240e+05,1.840240e+05,195805.0
mean,0.006461,5.350175e+19,0.008896,4.987208e+09,3.814710e+06,3.067054e+06,0.003175,27.149531,733.916034,456560.011700,...,2.911742e+06,2.480773e+06,2.411063e+06,3.055961e+06,3.024714e+06,3.022758e+06,3.037595e+06,3.009109e+06,3.009109e+06,1.0
std,0.139874,3.071923e+19,0.088978,3.041524e+09,9.546990e+06,7.502905e+06,0.154243,15.181161,257.680847,192442.688712,...,5.398768e+06,6.373509e+06,6.106882e+06,7.497887e+06,7.474397e+06,7.473912e+06,7.379716e+06,7.362405e+06,7.362405e+06,0.0
min,0.000000,5.295440e+15,0.000000,5.822689e+07,0.000000e+00,0.000000e+00,0.000000,0.000000,-1.000000,-1.000000,...,0.000000e+00,2.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
25%,0.000000,2.707339e+19,0.000000,2.329527e+09,5.203030e+05,4.991836e+05,0.000000,13.000000,822.000000,488410.000000,...,4.929274e+05,3.088021e+05,3.293343e+05,4.959218e+05,4.816189e+05,4.805700e+05,5.011648e+05,4.888525e+05,4.888525e+05,1.0
50%,0.000000,5.648695e+19,0.000000,5.113781e+09,1.091737e+06,1.052121e+06,0.000000,30.000000,822.000000,531110.000000,...,1.049735e+06,6.983673e+05,7.044224e+05,1.046748e+06,1.027789e+06,1.026517e+06,1.057831e+06,1.039845e+06,1.039845e+06,1.0
75%,0.000000,8.155438e+19,0.000000,7.344093e+09,2.550539e+06,2.384527e+06,0.000000,40.000000,825.000000,531120.000000,...,2.244454e+06,1.668956e+06,1.609816e+06,2.376135e+06,2.354400e+06,2.352631e+06,2.389692e+06,2.370213e+06,2.370213e+06,1.0
max,9.000000,9.999915e+19,2.000000,9.993134e+09,4.131000e+08,2.375000e+08,27.799700,51.000000,910.000000,999990.000000,...,3.735105e+07,6.700284e+07,6.700284e+07,2.375000e+08,2.375000e+08,2.375000e+08,2.375000e+08,2.375000e+08,2.375000e+08,1.0

In [49]:
df1=df.iloc[0:30000,:].to_excel('data1.xlsx', index  = True)

In [50]:
df2=df.iloc[30000:60000,:].to_excel('data2.xlsx', index  = True)

In [51]:
df3=df.iloc[60000:90000,:].to_excel('data3.xlsx', index  = True)

In [52]:
df4=df.iloc[90000:120000,:].to_excel('data4.xlsx', index  = True)

In [53]:
df5=df.iloc[120000:150000,:].to_excel('data5.xlsx', index  = True)

In [54]:
df6=df.iloc[150000:180000,:].to_excel('data6.xlsx', index  = True)

In [55]:
df7=df.iloc[180000:195805,:].to_excel('data7.xlsx', index  = True)

### Visualization of CRR and Downgrade