In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import datetime
%matplotlib inline

In [91]:
os.chdir("CRE Data")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'CRE Data'

In [5]:
dfCustFacility=pd.read_excel("dFacility1010.xlsx")

In [9]:
dfCustFacility

,DATE,CUST_NAME,FACILITY_NUM,CRR,CRR MAX,check,Downgrade,Downgrade Notch
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6.000000,6.000000,0,0.000000,0.000000
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5.000000,5.000000,0,0.000000,0.000000
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6.000000,6.000000,0,0.000000,0.000000
3,2005-03-31,"""MAJ, LLC""",5.648696e+19,5.000000,5.000000,0,0.000000,0.000000
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4.000000,4.000000,0,0.000000,0.000000
5,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5.000000,5.000000,0,0.000000,0.000000
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6.000000,6.000000,0,0.000000,0.000000
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4.000000,4.000000,0,0.000000,0.000000
8,2005-03-31,120 S DOHENY LLC,9.987914e+19,6.000000,6.000000,0,0.000000,0.000000
9,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6.000000,6.000000,0,0.000000,0.000000
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4.000000,4.000000,0,0.000000,0.000000
11,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6.000000,6.000000,0,0.000000,0.000000
12,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5.000000,5.000000,0,0.000000,0.000000
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5.000000,5.000000,0,0.000000,0.000000
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8.000000,8.000000,0,0.000000,0.000000
15,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6.000000,6.000000,0,0.000000,0.000000
16,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.000000,5.000000,0,0.000000,0.000000
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5.000000,5.000000,0,0.000000,0.000000
18,2005-03-31,17422 DERIAN,9.988906e+19,5.000000,5.000000,0,0.000000,0.000000
19,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3.000000,3.000000,0,0.000000,0.000000
20,2005-03-31,18061 FITCH L P,9.988938e+19,5.000000,5.000000,0,0.000000,0.000000
21,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6.000000,6.000000,0,0.000000,0.000000
22,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5.000000,5.000000,0,0.000000,0.000000
23,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6.000000,6.000000,0,0.000000,0.000000
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,2.477465e+17,5.000000,5.000000,0,0.000000,0.000000
25,2005-03-31,1992 KINCAID TRUST,9.990123e+19,6.000000,6.000000,0,0.000000,0.000000
26,2005-03-31,1997 SCHON REVOCABLE TRUST,9.580994e+19,6.000000,6.000000,0,0.000000,0.000000
27,2005-03-31,1999 K AND P OFFEL REV TRUST,6.673201e+19,1.000000,1.000000,0,0.000000,0.000000
28,2005-03-31,2000 STEWART REV TRUST,9.990205e+19,6.000000,6.000000,0,0.000000,0.000000
29,2005-03-31,2002 DAVIS PROPERTY L P,9.991648e+19,6.000000,6.000000,0,0.000000,0.000000
...,...,...,...,...,...,...,...,...
171093,2017-12-31,"YACHT HARBOR MHP, LLC",9.918958e+19,7.000000,7.000000,0,0.000000,0.000000
171094,2017-12-31,"YAZDANI PROPERTIES, LLC",9.924259e+19,4.000000,4.000000,0,0.000000,0.000000
171095,2017-12-31,YECHIEL ROSENFELD,7.960316e+19,3.000000,3.000000,0,0.000000,0.000000
171096,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,9.928020e+19,4.000000,4.000000,0,0.000000,0.000000
171097,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,9.928097e+19,7.000000,7.000000,0,0.000000,0.000000
171098,2017-12-31,YEUNG AE KIM,5.091376e+19,7.000000,7.000000,0,0.000000,0.000000
171099,2017-12-31,"YIPPEE HI HO CALLE, LLC",9.928289e+19,6.000000,6.000000,0,0.000000,0.000000
171100,2017-12-31,YOKO NAGATA REVOCABLE TRUST,6.449569e+19,3.000000,3.000000,0,0.800000,1.200000
171101,2017-12-31,YONG JA KIM,5.091380e+19,4.000000,4.000000,0,0.000000,0.000000
171102,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",9.935714e+19,5.000000,5.000000,0,0.000000,0.000000
171103,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",9.938586e+19,4.666667,4.666667,0,0.333333,0.333333
171104,2017-12-31,YOUNG MOBILE HOME PARK LLC,9.940133e+19,4.000000,4.000000,0,0.000000,0.000000
171105,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6.000000,6.000000,0,0.000000,0.000000
171106,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4.000000,4.000000,0,0.000000,0.000000
171107,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.000000,5.000000,0,0.000000,0.000000
171108,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6.000000,6.000000,0,0.000000,0.000000
171109,2017-12-31,YUAN SHEN,8.344497e+19,3.000000,5.000000,1,1.000000,2.000000
171110,2017-12-31,YUAN SHEN,8.344497e+19,5.000000,5.000000,0,0.000000,0.000000
171111,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5.000000,5.000000,0,0.000000,0.000000
171112,2017-12-31,YUREN ZHANG,9.957227e+19,4.000000,4.000000,0,0.000000,0.000000
171113,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5.000000,5.000000,0,0.000000,0.000000
171114,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4.000000,4.000000,0,0.000000,0.000000
171115,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4.000000,4.000000,0,0.000000,0.000000
171116,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4.000000,4.000000,0,0.000000,0.000000
171117,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5.000000,5.000000,0,0.000000,0.000000
171118,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5.000000,5.000000,0,0.000000,0.000000
171119,2017-12-31,"ZMZ, LLC",9.969613e+19,4.000000,4.000000,0,0.000000,0.000000
171120,2017-12-31,ZOREH MARASHI,5.685696e+19,4.000000,4.000000,0,0.000000,0.000000
171121,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5.000000,5.000000,0,0.000000,0.000000
171122,2017-12-31,ZUMA TRADING INC,9.976658e+19,3.000000,3.000000,0,0.000000,0.000000

### Facility Level Aggregation (Max)

In [10]:
df=pd.read_excel("CRE_08102018small.xlsx")

In [14]:
df

,MATCH_STATUS,MATCH_ID,PORTFOLIO,LOAN_NUM,FACILITY_NUM,DATE,DATE.1,ADD_QTR,DFT_LOAN_NUM,DFT_OBLIGOR,...,ead_mdl,ead_icrs,ead_union,exp_mdl,exp_icrs,exp_union,lag_exp_mdl,lag_exp_icrs,lag_exp_union,IN_SAMPLE
0,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2013-12-31,2013-12-31,0.0,,NaN,...,NaN,NaN,NaN,1449999.98,1449999.98,1449999.98,NaN,NaN,NaN,1
1,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-03-31,2014-03-31,0.0,,NaN,...,NaN,NaN,NaN,1433154.72,1433154.72,1433154.72,1449999.98,1449999.98,1449999.98,1
2,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-06-30,2014-06-30,0.0,,NaN,...,NaN,NaN,NaN,1416113.63,1416113.63,1416113.63,1433154.72,1433154.72,1433154.72,1
3,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-09-30,2014-09-30,0.0,,NaN,...,NaN,NaN,NaN,1398874.44,1398874.44,1398874.44,1416113.63,1416113.63,1416113.63,1
4,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-12-31,2014-12-31,0.0,,NaN,...,NaN,NaN,NaN,1381434.86,1381434.86,1381434.86,1398874.44,1398874.44,1398874.44,1
5,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-03-31,2015-03-31,0.0,,NaN,...,NaN,NaN,NaN,1363792.54,1363792.54,1363792.54,1381434.86,1381434.86,1381434.86,1
6,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-06-30,2015-06-30,0.0,,NaN,...,NaN,NaN,NaN,1345945.13,1345945.13,1345945.13,1363792.54,1363792.54,1363792.54,1
7,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-09-30,2015-09-30,0.0,,NaN,...,NaN,NaN,NaN,1327890.25,1327890.25,1327890.25,1345945.13,1345945.13,1345945.13,1
8,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-12-31,2015-12-31,0.0,,NaN,...,NaN,NaN,NaN,1309625.49,1309625.49,1309625.49,1327890.25,1327890.25,1327890.25,1
9,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-03-31,2016-03-31,0.0,,NaN,...,NaN,NaN,NaN,1291148.40,1291148.40,1291148.40,1309625.49,1309625.49,1309625.49,1
10,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-06-30,2016-06-30,0.0,,NaN,...,NaN,NaN,NaN,1272456.53,1272456.53,1272456.53,1291148.40,1291148.40,1291148.40,1
11,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-09-30,2016-09-30,0.0,,NaN,...,NaN,NaN,NaN,1253547.36,1253547.36,1253547.36,1272456.53,1272456.53,1272456.53,1
12,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-12-31,2016-12-31,0.0,,NaN,...,NaN,NaN,NaN,1234418.38,1234418.38,1234418.38,1253547.36,1253547.36,1253547.36,1
13,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-03-31,2017-03-31,0.0,,NaN,...,NaN,NaN,NaN,1215067.03,1215067.03,1215067.03,1234418.38,1234418.38,1234418.38,1
14,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-06-30,2017-06-30,0.0,,NaN,...,NaN,NaN,NaN,1195490.73,1195490.73,1195490.73,1215067.03,1215067.03,1215067.03,1
15,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-09-30,2017-09-30,0.0,,NaN,...,NaN,NaN,NaN,1175686.85,1175686.85,1175686.85,1195490.73,1195490.73,1195490.73,1
16,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-12-31,2017-12-31,0.0,,NaN,...,NaN,NaN,NaN,1155652.77,1155652.77,1155652.77,1175686.85,1175686.85,1175686.85,1
17,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2013-12-31,2013-12-31,0.0,,NaN,...,NaN,NaN,NaN,2100000.00,2100000.00,2100000.00,NaN,NaN,NaN,1
18,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-03-31,2014-03-31,0.0,,NaN,...,NaN,NaN,NaN,2075715.27,2075715.27,2075715.27,2100000.00,2100000.00,2100000.00,1
19,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-06-30,2014-06-30,0.0,,NaN,...,NaN,NaN,NaN,2051144.80,2051144.80,2051144.80,2075715.27,2075715.27,2075715.27,1
20,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-09-30,2014-09-30,0.0,,NaN,...,NaN,NaN,NaN,2026285.24,2026285.24,2026285.24,2051144.80,2051144.80,2051144.80,1
21,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-12-31,2014-12-31,0.0,,NaN,...,NaN,NaN,NaN,2001133.19,2001133.19,2001133.19,2026285.24,2026285.24,2026285.24,1
22,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-03-31,2015-03-31,0.0,,NaN,...,NaN,NaN,NaN,1975685.20,1975685.20,1975685.20,2001133.19,2001133.19,2001133.19,1
23,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-06-30,2015-06-30,0.0,,NaN,...,NaN,NaN,NaN,1949937.80,1949937.80,1949937.80,1975685.20,1975685.20,1975685.20,1
24,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-09-30,2015-09-30,0.0,,NaN,...,NaN,NaN,NaN,1923887.45,1923887.45,1923887.45,1949937.80,1949937.80,1949937.80,1
25,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-12-31,2015-12-31,0.0,,NaN,...,NaN,NaN,NaN,1897530.61,1897530.61,1897530.61,1923887.45,1923887.45,1923887.45,1
26,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-03-31,2016-03-31,0.0,,NaN,...,NaN,NaN,NaN,1870863.65,1870863.65,1870863.65,1897530.61,1897530.61,1897530.61,1
27,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-06-30,2016-06-30,0.0,,NaN,...,NaN,NaN,NaN,1843882.93,1843882.93,1843882.93,1870863.65,1870863.65,1870863.65,1
28,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-09-30,2016-09-30,0.0,,NaN,...,NaN,NaN,NaN,1816584.76,1816584.76,1816584.76,1843882.93,1843882.93,1843882.93,1
29,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-12-31,2016-12-31,0.0,,NaN,...,NaN,NaN,NaN,1788965.40,1788965.40,1788965.40,1816584.76,1816584.76,1816584.76,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195775,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-03-31,2015-03-31,0.0,,NaN,...,NaN,NaN,NaN,1500000.00,1500000.00,1500000.00,NaN,NaN,NaN,1
195776,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-06-30,2015-06-30,0.0,,NaN,...,NaN,NaN,NaN,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1
195777,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-09-30,2015-09-30,0.0,,NaN,...,NaN,NaN,NaN,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1
195778,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-12-31,2015-12-31,0.0,,NaN,...,NaN,NaN,NaN,502021.59,502021.59,502021.59,1500000.00,1500000.00,1500000.00,1
195779,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2016-03-31,2016-03-31,1.0,,NaN,...,NaN,NaN,NaN,502021.59,502021.59,502021.59,502021.59,502021.59,502021.59,1
195780,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-03-31,2017-03-31,0.0,,NaN,...,NaN,NaN,NaN,514200.00,514200.00,514200.00,NaN,NaN,NaN,1
195781,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-06-30,2017-06-30,0.0,,NaN,...,NaN,NaN,NaN,514200.00,514200.00,514200.00,514200.00,514200.00,514200.00,1
195782,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-09-30,2017-09-30,0.0,,NaN,...,NaN,NaN,NaN,512499.55,512499.55,512499.55,514200.00,514200.00,514200.00,1
195783,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-12-31,2017-12-31,0.0,,NaN,...,NaN,NaN,NaN,509998.60,509998.60,509998.60,512499.55,512499.55,512499.55,1
195784,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2005-09-30,2005-09-30,0.0,,NaN,...,NaN,NaN,NaN,825000.00,825000.00,825000.00,NaN,NaN,NaN,1
195785,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2005-12-31,2005-12-31,0.0,,NaN,...,NaN,NaN,NaN,822302.19,822302.19,822302.19,825000.00,825000.00,825000.00,1
195786,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-03-31,2006-03-31,0.0,,NaN,...,NaN,NaN,NaN,818604.86,818604.86,818604.86,822302.19,822302.19,822302.19,1
195787,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-06-30,2006-06-30,0.0,,NaN,...,NaN,NaN,NaN,815076.34,815076.34,815076.34,818604.86,818604.86,818604.86,1
195788,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-09-30,2006-09-30,0.0,,NaN,...,NaN,NaN,NaN,811685.61,811685.61,811685.61,815076.34,815076.34,815076.34,1
195789,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-12-31,2006-12-31,0.0,,NaN,...,NaN,NaN,NaN,808343.26,808343.26,808343.26,811685.61,811685.61,811685.61,1
195790,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-03-31,2007-03-31,0.0,,NaN,...,NaN,NaN,NaN,804928.07,804928.07,804928.07,808343.26,808343.26,808343.26,1
195791,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-06-30,2007-06-30,0.0,,NaN,...,NaN,NaN,NaN,801448.82,801448.82,801448.82,804928.07,804928.07,804928.07,1
195792,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-09-30,2007-09-30,0.0,,NaN,...,NaN,NaN,NaN,797909.56,797909.56,797909.56,801448.82,801448.82,801448.82,1
195793,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-12-31,2007-12-31,0.0,,NaN,...,NaN,NaN,NaN,794400.90,794400.90,794400.90,797909.56,797909.56,797909.56,1
195794,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-03-31,2008-03-31,0.0,,NaN,...,NaN,NaN,NaN,790592.74,790592.74,790592.74,794400.90,794400.90,794400.90,1
195795,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-06-30,2008-06-30,0.0,,NaN,...,NaN,NaN,NaN,785542.56,785542.56,785542.56,790592.74,790592.74,790592.74,1
195796,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-09-30,2008-09-30,0.0,,NaN,...,NaN,NaN,NaN,780139.59,780139.59,780139.59,785542.56,785542.56,785542.56,1
195797,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-12-31,2008-12-31,0.0,,NaN,...,NaN,NaN,NaN,774788.97,774788.97,774788.97,780139.59,780139.59,780139.59,1
195798,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-03-31,2009-03-31,0.0,,NaN,...,NaN,NaN,NaN,768947.02,768947.02,768947.02,774788.97,774788.97,774788.97,1
195799,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-06-30,2009-06-30,0.0,,NaN,...,NaN,NaN,NaN,762369.88,762369.88,762369.88,768947.02,768947.02,768947.02,1
195800,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-09-30,2009-09-30,0.0,,NaN,...,NaN,NaN,NaN,755273.64,755273.64,755273.64,762369.88,762369.88,762369.88,1
195801,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-12-31,2009-12-31,0.0,,NaN,...,NaN,NaN,NaN,747885.15,747885.15,747885.15,755273.64,755273.64,755273.64,1
195802,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2010-03-31,2010-03-31,0.0,,NaN,...,NaN,NaN,NaN,740398.61,740398.61,740398.61,747885.15,747885.15,747885.15,1
195803,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2010-06-30,2010-06-30,0.0,,NaN,...,NaN,NaN,NaN,732876.25,732876.25,732876.25,740398.61,740398.61,740398.61,1
195804,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2010-09-30,2010-09-30,1.0,,NaN,...,NaN,NaN,NaN,732876.25,732876.25,732876.25,732876.25,732876.25,732876.25,1

In [21]:
dfFacility=pd.read_excel("dFacility.xlsx")

In [22]:
dfFacility

,DATE,CUST_NAME,FACILITY_NUM,CRR,Downgrade,Downgrade Notch
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6.000000,0.000000,0.000000
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5.000000,0.000000,0.000000
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6.000000,0.000000,0.000000
3,2005-03-31,"""MAJ, LLC""",5.648696e+19,5.000000,0.000000,0.000000
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4.000000,0.000000,0.000000
5,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5.000000,0.000000,0.000000
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6.000000,0.000000,0.000000
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4.000000,0.000000,0.000000
8,2005-03-31,120 S DOHENY LLC,9.987914e+19,6.000000,0.000000,0.000000
9,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6.000000,0.000000,0.000000
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4.000000,0.000000,0.000000
11,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6.000000,0.000000,0.000000
12,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5.000000,0.000000,0.000000
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5.000000,0.000000,0.000000
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8.000000,0.000000,0.000000
15,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6.000000,0.000000,0.000000
16,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.000000,0.000000,0.000000
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5.000000,0.000000,0.000000
18,2005-03-31,17422 DERIAN,9.988906e+19,5.000000,0.000000,0.000000
19,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3.000000,0.000000,0.000000
20,2005-03-31,18061 FITCH L P,9.988938e+19,5.000000,0.000000,0.000000
21,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6.000000,0.000000,0.000000
22,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5.000000,0.000000,0.000000
23,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6.000000,0.000000,0.000000
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,2.477465e+17,5.000000,0.000000,0.000000
25,2005-03-31,1992 KINCAID TRUST,9.990123e+19,6.000000,0.000000,0.000000
26,2005-03-31,1997 SCHON REVOCABLE TRUST,9.580994e+19,6.000000,0.000000,0.000000
27,2005-03-31,1999 K AND P OFFEL REV TRUST,6.673201e+19,1.000000,0.000000,0.000000
28,2005-03-31,2000 STEWART REV TRUST,9.990205e+19,6.000000,0.000000,0.000000
29,2005-03-31,2002 DAVIS PROPERTY L P,9.991648e+19,6.000000,0.000000,0.000000
...,...,...,...,...,...,...
171093,2017-12-31,"YACHT HARBOR MHP, LLC",9.918958e+19,7.000000,0.000000,0.000000
171094,2017-12-31,"YAZDANI PROPERTIES, LLC",9.924259e+19,4.000000,0.000000,0.000000
171095,2017-12-31,YECHIEL ROSENFELD,7.960316e+19,3.000000,0.000000,0.000000
171096,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,9.928020e+19,4.000000,0.000000,0.000000
171097,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,9.928097e+19,7.000000,0.000000,0.000000
171098,2017-12-31,YEUNG AE KIM,5.091376e+19,7.000000,0.000000,0.000000
171099,2017-12-31,"YIPPEE HI HO CALLE, LLC",9.928289e+19,6.000000,0.000000,0.000000
171100,2017-12-31,YOKO NAGATA REVOCABLE TRUST,6.449569e+19,3.000000,0.800000,1.200000
171101,2017-12-31,YONG JA KIM,5.091380e+19,4.000000,0.000000,0.000000
171102,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",9.935714e+19,5.000000,0.000000,0.000000
171103,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",9.938586e+19,4.666667,0.333333,0.333333
171104,2017-12-31,YOUNG MOBILE HOME PARK LLC,9.940133e+19,4.000000,0.000000,0.000000
171105,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6.000000,0.000000,0.000000
171106,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4.000000,0.000000,0.000000
171107,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.000000,0.000000,0.000000
171108,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6.000000,0.000000,0.000000
171109,2017-12-31,YUAN SHEN,8.344497e+19,3.000000,1.000000,2.000000
171110,2017-12-31,YUAN SHEN,8.344497e+19,5.000000,0.000000,0.000000
171111,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5.000000,0.000000,0.000000
171112,2017-12-31,YUREN ZHANG,9.957227e+19,4.000000,0.000000,0.000000
171113,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5.000000,0.000000,0.000000
171114,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4.000000,0.000000,0.000000
171115,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4.000000,0.000000,0.000000
171116,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4.000000,0.000000,0.000000
171117,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5.000000,0.000000,0.000000
171118,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5.000000,0.000000,0.000000
171119,2017-12-31,"ZMZ, LLC",9.969613e+19,4.000000,0.000000,0.000000
171120,2017-12-31,ZOREH MARASHI,5.685696e+19,4.000000,0.000000,0.000000
171121,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5.000000,0.000000,0.000000
171122,2017-12-31,ZUMA TRADING INC,9.976658e+19,3.000000,0.000000,0.000000

#### insights: 171123 rows, unique facilities from original dataset is only 12313 rows

### Focusing on multiple stats

In [11]:
def get_stats(group):
    return{'min':group.min(),'max':group.max(),'count':group.count(),'mean':group.mean()}

In [ ]:
###df['postTestScore'].groupby(df['categories']).apply(get_stats).unstack()

### Focusing on one stat

In [30]:
a=(pd.DataFrame(df.groupby(['FACILITY_NUM','DATE'])['CRR'].agg(['max']))).reset_index().rename_axis(None,axis=1)##Append this one to the riginal dataset

In [32]:
a

        FACILITY_NUM       DATE  max
0       5.295440e+15 2013-12-31    5
1       5.295440e+15 2014-03-31    5
2       5.295440e+15 2014-06-30    5
3       5.295440e+15 2014-09-30    5
4       5.295440e+15 2014-12-31    4
5       5.295440e+15 2015-03-31    4
6       5.295440e+15 2015-06-30    4
7       5.295440e+15 2015-09-30    4
8       5.295440e+15 2015-12-31    4
9       5.295440e+15 2016-03-31    4
10      5.295440e+15 2016-06-30    4
11      5.295440e+15 2016-09-30    4
12      5.295440e+15 2016-12-31    4
13      5.295440e+15 2017-03-31    4
14      5.295440e+15 2017-06-30    4
15      5.295440e+15 2017-09-30    4
16      5.295440e+15 2017-12-31    4
17      2.681988e+16 2005-03-31    6
18      2.681988e+16 2005-06-30    6
19      2.681988e+16 2005-09-30    6
20      2.681988e+16 2005-12-31    6
21      2.681988e+16 2006-03-31    6
22      2.681988e+16 2006-06-30    6
23      2.681988e+16 2006-09-30    6
24      2.681988e+16 2006-12-31    6
25      2.681988e+16 2007-03-31    6
26      2.681988e+16 2007-06-30    6
27      2.681988e+16 2007-09-30    6
28      2.681988e+16 2007-12-31    6
29      2.681988e+16 2008-03-31    6
...              ...        ...  ...
171045  9.999912e+19 2015-03-31    6
171046  9.999912e+19 2015-06-30    6
171047  9.999912e+19 2015-09-30    6
171048  9.999912e+19 2015-12-31    6
171049  9.999912e+19 2016-03-31    6
171050  9.999913e+19 2017-03-31    7
171051  9.999913e+19 2017-06-30    7
171052  9.999913e+19 2017-09-30    7
171053  9.999913e+19 2017-12-31    7
171054  9.999915e+19 2005-09-30    6
171055  9.999915e+19 2005-12-31    6
171056  9.999915e+19 2006-03-31    6
171057  9.999915e+19 2006-06-30    6
171058  9.999915e+19 2006-09-30    6
171059  9.999915e+19 2006-12-31    6
171060  9.999915e+19 2007-03-31    6
171061  9.999915e+19 2007-06-30    6
171062  9.999915e+19 2007-09-30    6
171063  9.999915e+19 2007-12-31    6
171064  9.999915e+19 2008-03-31    6
171065  9.999915e+19 2008-06-30    6
171066  9.999915e+19 2008-09-30    6
171067  9.999915e+19 2008-12-31    6
171068  9.999915e+19 2009-03-31    6
171069  9.999915e+19 2009-06-30    6
171070  9.999915e+19 2009-09-30    6
171071  9.999915e+19 2009-12-31    6
171072  9.999915e+19 2010-03-31    6
171073  9.999915e+19 2010-06-30    8
171074  9.999915e+19 2010-09-30    8

[171075 rows x 3 columns]

#### merge dataframe a and dataframe df

In [20]:
a

       FACILITY_NUM  max
0      5.295440e+15    5
1      2.681988e+16    6
2      2.695665e+16    5
3      2.709342e+16    6
4      2.709342e+16    6
5      3.900841e+16    6
6      3.901864e+16    6
7      3.903928e+16    6
8      3.907002e+16    5
9      6.502453e+16    5
10     6.513393e+16    6
11     8.240292e+16    6
12     8.264912e+16    7
13     8.273137e+16    6
14     8.319674e+16    6
15     9.299404e+16    7
16     1.098707e+17    6
17     1.128879e+17    4
18     1.159954e+17    5
19     1.203564e+17    5
20     1.269845e+17    6
21     1.269845e+17    6
22     1.273128e+17    5
23     1.277918e+17    5
24     1.278603e+17    6
25     1.581473e+17    7
26     1.620836e+17    6
27     1.738945e+17    8
28     1.739420e+17    6
29     1.739515e+17    5
...             ...  ...
12283  9.998806e+19    5
12284  9.998807e+19    5
12285  9.998809e+19    4
12286  9.998816e+19    6
12287  9.999065e+19    5
12288  9.999188e+19    7
12289  9.999460e+19    6
12290  9.999462e+19    6
12291  9.999465e+19    6
12292  9.999468e+19    6
12293  9.999471e+19    6
12294  9.999471e+19    6
12295  9.999472e+19    4
12296  9.999476e+19    5
12297  9.999506e+19    6
12298  9.999506e+19    6
12299  9.999531e+19    6
12300  9.999556e+19    7
12301  9.999581e+19    6
12302  9.999607e+19    5
12303  9.999607e+19    5
12304  9.999707e+19    6
12305  9.999911e+19    5
12306  9.999912e+19    6
12307  9.999912e+19    4
12308  9.999912e+19    5
12309  9.999912e+19    8
12310  9.999912e+19    6
12311  9.999913e+19    7
12312  9.999915e+19    8

[12313 rows x 2 columns]

In [35]:
dfCustMaxCrr=pd.merge(dfFacility,a,on =['FACILITY_NUM','DATE'],how='left')

In [36]:
dfCustMaxCrr

,DATE,CUST_NAME,FACILITY_NUM,CRR,Downgrade,Downgrade Notch,max
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6.000000,0.000000,0.000000,6
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5.000000,0.000000,0.000000,5
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6.000000,0.000000,0.000000,6
3,2005-03-31,"""MAJ, LLC""",5.648696e+19,5.000000,0.000000,0.000000,5
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4.000000,0.000000,0.000000,4
5,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5.000000,0.000000,0.000000,5
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6.000000,0.000000,0.000000,6
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4.000000,0.000000,0.000000,4
8,2005-03-31,120 S DOHENY LLC,9.987914e+19,6.000000,0.000000,0.000000,6
9,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6.000000,0.000000,0.000000,6
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4.000000,0.000000,0.000000,4
11,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6.000000,0.000000,0.000000,6
12,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5.000000,0.000000,0.000000,5
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5.000000,0.000000,0.000000,5
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8.000000,0.000000,0.000000,8
15,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6.000000,0.000000,0.000000,6
16,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.000000,0.000000,0.000000,5
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5.000000,0.000000,0.000000,5
18,2005-03-31,17422 DERIAN,9.988906e+19,5.000000,0.000000,0.000000,5
19,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3.000000,0.000000,0.000000,3
20,2005-03-31,18061 FITCH L P,9.988938e+19,5.000000,0.000000,0.000000,5
21,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6.000000,0.000000,0.000000,6
22,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5.000000,0.000000,0.000000,5
23,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6.000000,0.000000,0.000000,6
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,2.477465e+17,5.000000,0.000000,0.000000,5
25,2005-03-31,1992 KINCAID TRUST,9.990123e+19,6.000000,0.000000,0.000000,6
26,2005-03-31,1997 SCHON REVOCABLE TRUST,9.580994e+19,6.000000,0.000000,0.000000,6
27,2005-03-31,1999 K AND P OFFEL REV TRUST,6.673201e+19,1.000000,0.000000,0.000000,1
28,2005-03-31,2000 STEWART REV TRUST,9.990205e+19,6.000000,0.000000,0.000000,6
29,2005-03-31,2002 DAVIS PROPERTY L P,9.991648e+19,6.000000,0.000000,0.000000,6
...,...,...,...,...,...,...,...
171093,2017-12-31,"YACHT HARBOR MHP, LLC",9.918958e+19,7.000000,0.000000,0.000000,7
171094,2017-12-31,"YAZDANI PROPERTIES, LLC",9.924259e+19,4.000000,0.000000,0.000000,4
171095,2017-12-31,YECHIEL ROSENFELD,7.960316e+19,3.000000,0.000000,0.000000,3
171096,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,9.928020e+19,4.000000,0.000000,0.000000,4
171097,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,9.928097e+19,7.000000,0.000000,0.000000,7
171098,2017-12-31,YEUNG AE KIM,5.091376e+19,7.000000,0.000000,0.000000,7
171099,2017-12-31,"YIPPEE HI HO CALLE, LLC",9.928289e+19,6.000000,0.000000,0.000000,6
171100,2017-12-31,YOKO NAGATA REVOCABLE TRUST,6.449569e+19,3.000000,0.800000,1.200000,3
171101,2017-12-31,YONG JA KIM,5.091380e+19,4.000000,0.000000,0.000000,4
171102,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",9.935714e+19,5.000000,0.000000,0.000000,5
171103,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",9.938586e+19,4.666667,0.333333,0.333333,5
171104,2017-12-31,YOUNG MOBILE HOME PARK LLC,9.940133e+19,4.000000,0.000000,0.000000,4
171105,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6.000000,0.000000,0.000000,6
171106,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4.000000,0.000000,0.000000,4
171107,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.000000,0.000000,0.000000,5
171108,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6.000000,0.000000,0.000000,6
171109,2017-12-31,YUAN SHEN,8.344497e+19,3.000000,1.000000,2.000000,3
171110,2017-12-31,YUAN SHEN,8.344497e+19,5.000000,0.000000,0.000000,5
171111,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5.000000,0.000000,0.000000,5
171112,2017-12-31,YUREN ZHANG,9.957227e+19,4.000000,0.000000,0.000000,4
171113,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5.000000,0.000000,0.000000,5
171114,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4.000000,0.000000,0.000000,4
171115,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4.000000,0.000000,0.000000,4
171116,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4.000000,0.000000,0.000000,4
171117,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5.000000,0.000000,0.000000,5
171118,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5.000000,0.000000,0.000000,5
171119,2017-12-31,"ZMZ, LLC",9.969613e+19,4.000000,0.000000,0.000000,4
171120,2017-12-31,ZOREH MARASHI,5.685696e+19,4.000000,0.000000,0.000000,4
171121,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5.000000,0.000000,0.000000,5
171122,2017-12-31,ZUMA TRADING INC,9.976658e+19,3.000000,0.000000,0.000000,3

In [37]:
dfCustMaxCrr.to_excel('dfCustMaxCrr.xlsx', index  = True)

### Include more target variable information

In [41]:
Frr=pd.pivot_table(df,index=['DATE','CUST_NAME','FACILITY_NUM'],values=['CRR','Downgrade','Downgrade Notch','NET_COMMIT_AMT','OUT_BAL','RE_RISK_PROPERTY_TYPE','RE_STATE_NAME','RE_COUNTY_NAME'])

In [44]:
dfFacilityCom=Frr.reset_index().rename_axis(None,axis=1)

In [45]:
dfCustMaxCrrCom=pd.merge(dfFacilityCom,a,on =['FACILITY_NUM','DATE'],how='left')

In [47]:
dfCustMaxCrrCom.to_excel('dfCustMaxCrrCom.xlsx', index  = True)

In [48]:
dfCustMaxCrrCom

,DATE,CUST_NAME,FACILITY_NUM,CRR,Downgrade,Downgrade Notch,NET_COMMIT_AMT,OUT_BAL,max
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6.000000,0.000000,0.000000,5.676000e+05,5.676000e+05,6
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5.000000,0.000000,0.000000,8.131556e+06,8.131556e+06,5
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6.000000,0.000000,0.000000,5.456056e+05,5.456056e+05,6
3,2005-03-31,"""MAJ, LLC""",5.648696e+19,5.000000,0.000000,0.000000,1.263000e+06,1.263000e+06,5
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4.000000,0.000000,0.000000,3.048930e+06,3.048930e+06,4
5,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5.000000,0.000000,0.000000,3.963909e+06,3.963909e+06,5
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6.000000,0.000000,0.000000,2.715611e+06,2.715611e+06,6
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4.000000,0.000000,0.000000,2.025248e+06,2.025248e+06,4
8,2005-03-31,120 S DOHENY LLC,9.987914e+19,6.000000,0.000000,0.000000,1.802838e+06,1.802838e+06,6
9,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6.000000,0.000000,0.000000,6.309734e+05,6.309734e+05,6
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4.000000,0.000000,0.000000,1.044431e+06,1.044431e+06,4
11,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6.000000,0.000000,0.000000,5.587259e+05,5.587259e+05,6
12,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5.000000,0.000000,0.000000,6.730704e+06,6.730704e+06,5
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5.000000,0.000000,0.000000,5.358257e+05,5.358257e+05,5
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8.000000,0.000000,0.000000,7.021508e+05,7.021508e+05,8
15,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6.000000,0.000000,0.000000,1.178464e+06,1.178464e+06,6
16,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.000000,0.000000,0.000000,2.595037e+06,2.595037e+06,5
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5.000000,0.000000,0.000000,4.481224e+06,4.481224e+06,5
18,2005-03-31,17422 DERIAN,9.988906e+19,5.000000,0.000000,0.000000,8.127320e+06,8.127320e+06,5
19,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3.000000,0.000000,0.000000,2.035613e+06,2.035613e+06,3
20,2005-03-31,18061 FITCH L P,9.988938e+19,5.000000,0.000000,0.000000,2.842245e+06,2.842245e+06,5
21,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6.000000,0.000000,0.000000,2.850000e+06,2.850000e+06,6
22,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5.000000,0.000000,0.000000,5.250000e+06,5.250000e+06,5
23,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6.000000,0.000000,0.000000,1.277419e+05,1.277419e+05,6
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,2.477465e+17,5.000000,0.000000,0.000000,1.971134e+06,1.971134e+06,5
25,2005-03-31,1992 KINCAID TRUST,9.990123e+19,6.000000,0.000000,0.000000,1.081544e+05,1.081544e+05,6
26,2005-03-31,1997 SCHON REVOCABLE TRUST,9.580994e+19,6.000000,0.000000,0.000000,5.170076e+05,5.170076e+05,6
27,2005-03-31,1999 K AND P OFFEL REV TRUST,6.673201e+19,1.000000,0.000000,0.000000,3.254755e+05,3.254755e+05,1
28,2005-03-31,2000 STEWART REV TRUST,9.990205e+19,6.000000,0.000000,0.000000,9.000000e+05,9.000000e+05,6
29,2005-03-31,2002 DAVIS PROPERTY L P,9.991648e+19,6.000000,0.000000,0.000000,6.384479e+05,6.384479e+05,6
...,...,...,...,...,...,...,...,...,...
171093,2017-12-31,"YACHT HARBOR MHP, LLC",9.918958e+19,7.000000,0.000000,0.000000,2.672491e+06,2.672491e+06,7
171094,2017-12-31,"YAZDANI PROPERTIES, LLC",9.924259e+19,4.000000,0.000000,0.000000,8.373381e+05,8.373381e+05,4
171095,2017-12-31,YECHIEL ROSENFELD,7.960316e+19,3.000000,0.000000,0.000000,8.028064e+05,8.028064e+05,3
171096,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,9.928020e+19,4.000000,0.000000,0.000000,2.344330e+06,2.344330e+06,4
171097,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,9.928097e+19,7.000000,0.000000,0.000000,5.092405e+06,5.092405e+06,7
171098,2017-12-31,YEUNG AE KIM,5.091376e+19,7.000000,0.000000,0.000000,1.722004e+06,1.722004e+06,7
171099,2017-12-31,"YIPPEE HI HO CALLE, LLC",9.928289e+19,6.000000,0.000000,0.000000,8.809604e+05,8.809604e+05,6
171100,2017-12-31,YOKO NAGATA REVOCABLE TRUST,6.449569e+19,3.000000,0.800000,1.200000,1.168964e+06,1.168964e+06,3
171101,2017-12-31,YONG JA KIM,5.091380e+19,4.000000,0.000000,0.000000,2.217899e+06,2.217899e+06,4
171102,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",9.935714e+19,5.000000,0.000000,0.000000,5.411331e+06,5.411331e+06,5
171103,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",9.938586e+19,4.666667,0.333333,0.333333,9.129412e+05,9.129412e+05,5
171104,2017-12-31,YOUNG MOBILE HOME PARK LLC,9.940133e+19,4.000000,0.000000,0.000000,1.549733e+06,1.549733e+06,4
171105,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6.000000,0.000000,0.000000,5.649676e+06,5.649676e+06,6
171106,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4.000000,0.000000,0.000000,3.528716e+06,3.528716e+06,4
171107,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.000000,0.000000,0.000000,1.989961e+06,1.989961e+06,5
171108,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6.000000,0.000000,0.000000,5.900470e+05,5.900470e+05,6
171109,2017-12-31,YUAN SHEN,8.344497e+19,3.000000,1.000000,2.000000,1.919702e+06,1.919702e+06,3
171110,2017-12-31,YUAN SHEN,8.344497e+19,5.000000,0.000000,0.000000,4.292902e+06,4.292902e+06,5
171111,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5.000000,0.000000,0.000000,1.125106e+06,1.125106e+06,5
171112,2017-12-31,YUREN ZHANG,9.957227e+19,4.000000,0.000000,0.000000,9.643488e+05,9.643488e+05,4
171113,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5.000000,0.000000,0.000000,2.447101e+06,2.447101e+06,5
171114,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4.000000,0.000000,0.000000,2.427111e+06,2.427111e+06,4
171115,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4.000000,0.000000,0.000000,4.979214e+06,4.979214e+06,4
171116,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4.000000,0.000000,0.000000,1.297024e+06,1.297024e+06,4
171117,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5.000000,0.000000,0.000000,3.272500e+06,3.272500e+06,5
171118,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5.000000,0.000000,0.000000,2.415867e+06,2.415867e+06,5
171119,2017-12-31,"ZMZ, LLC",9.969613e+19,4.000000,0.000000,0.000000,2.107293e+06,2.107293e+06,4
171120,2017-12-31,ZOREH MARASHI,5.685696e+19,4.000000,0.000000,0.000000,1.185458e+06,1.185458e+06,4
171121,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5.000000,0.000000,0.000000,1.445115e+06,1.445115e+06,5
171122,2017-12-31,ZUMA TRADING INC,9.976658e+19,3.000000,0.000000,0.000000,4.862138e+06,4.862138e+06,3

In [49]:
df

,MATCH_STATUS,MATCH_ID,PORTFOLIO,LOAN_NUM,FACILITY_NUM,DATE,DATE.1,ADD_QTR,DFT_LOAN_NUM,DFT_OBLIGOR,...,ead_mdl,ead_icrs,ead_union,exp_mdl,exp_icrs,exp_union,lag_exp_mdl,lag_exp_icrs,lag_exp_union,IN_SAMPLE
0,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2013-12-31,2013-12-31,0.0,,NaN,...,NaN,NaN,NaN,1449999.98,1449999.98,1449999.98,NaN,NaN,NaN,1
1,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-03-31,2014-03-31,0.0,,NaN,...,NaN,NaN,NaN,1433154.72,1433154.72,1433154.72,1449999.98,1449999.98,1449999.98,1
2,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-06-30,2014-06-30,0.0,,NaN,...,NaN,NaN,NaN,1416113.63,1416113.63,1416113.63,1433154.72,1433154.72,1433154.72,1
3,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-09-30,2014-09-30,0.0,,NaN,...,NaN,NaN,NaN,1398874.44,1398874.44,1398874.44,1416113.63,1416113.63,1416113.63,1
4,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-12-31,2014-12-31,0.0,,NaN,...,NaN,NaN,NaN,1381434.86,1381434.86,1381434.86,1398874.44,1398874.44,1398874.44,1
5,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-03-31,2015-03-31,0.0,,NaN,...,NaN,NaN,NaN,1363792.54,1363792.54,1363792.54,1381434.86,1381434.86,1381434.86,1
6,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-06-30,2015-06-30,0.0,,NaN,...,NaN,NaN,NaN,1345945.13,1345945.13,1345945.13,1363792.54,1363792.54,1363792.54,1
7,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-09-30,2015-09-30,0.0,,NaN,...,NaN,NaN,NaN,1327890.25,1327890.25,1327890.25,1345945.13,1345945.13,1345945.13,1
8,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-12-31,2015-12-31,0.0,,NaN,...,NaN,NaN,NaN,1309625.49,1309625.49,1309625.49,1327890.25,1327890.25,1327890.25,1
9,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-03-31,2016-03-31,0.0,,NaN,...,NaN,NaN,NaN,1291148.40,1291148.40,1291148.40,1309625.49,1309625.49,1309625.49,1
10,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-06-30,2016-06-30,0.0,,NaN,...,NaN,NaN,NaN,1272456.53,1272456.53,1272456.53,1291148.40,1291148.40,1291148.40,1
11,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-09-30,2016-09-30,0.0,,NaN,...,NaN,NaN,NaN,1253547.36,1253547.36,1253547.36,1272456.53,1272456.53,1272456.53,1
12,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-12-31,2016-12-31,0.0,,NaN,...,NaN,NaN,NaN,1234418.38,1234418.38,1234418.38,1253547.36,1253547.36,1253547.36,1
13,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-03-31,2017-03-31,0.0,,NaN,...,NaN,NaN,NaN,1215067.03,1215067.03,1215067.03,1234418.38,1234418.38,1234418.38,1
14,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-06-30,2017-06-30,0.0,,NaN,...,NaN,NaN,NaN,1195490.73,1195490.73,1195490.73,1215067.03,1215067.03,1215067.03,1
15,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-09-30,2017-09-30,0.0,,NaN,...,NaN,NaN,NaN,1175686.85,1175686.85,1175686.85,1195490.73,1195490.73,1195490.73,1
16,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-12-31,2017-12-31,0.0,,NaN,...,NaN,NaN,NaN,1155652.77,1155652.77,1155652.77,1175686.85,1175686.85,1175686.85,1
17,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2013-12-31,2013-12-31,0.0,,NaN,...,NaN,NaN,NaN,2100000.00,2100000.00,2100000.00,NaN,NaN,NaN,1
18,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-03-31,2014-03-31,0.0,,NaN,...,NaN,NaN,NaN,2075715.27,2075715.27,2075715.27,2100000.00,2100000.00,2100000.00,1
19,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-06-30,2014-06-30,0.0,,NaN,...,NaN,NaN,NaN,2051144.80,2051144.80,2051144.80,2075715.27,2075715.27,2075715.27,1
20,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-09-30,2014-09-30,0.0,,NaN,...,NaN,NaN,NaN,2026285.24,2026285.24,2026285.24,2051144.80,2051144.80,2051144.80,1
21,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-12-31,2014-12-31,0.0,,NaN,...,NaN,NaN,NaN,2001133.19,2001133.19,2001133.19,2026285.24,2026285.24,2026285.24,1
22,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-03-31,2015-03-31,0.0,,NaN,...,NaN,NaN,NaN,1975685.20,1975685.20,1975685.20,2001133.19,2001133.19,2001133.19,1
23,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-06-30,2015-06-30,0.0,,NaN,...,NaN,NaN,NaN,1949937.80,1949937.80,1949937.80,1975685.20,1975685.20,1975685.20,1
24,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-09-30,2015-09-30,0.0,,NaN,...,NaN,NaN,NaN,1923887.45,1923887.45,1923887.45,1949937.80,1949937.80,1949937.80,1
25,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-12-31,2015-12-31,0.0,,NaN,...,NaN,NaN,NaN,1897530.61,1897530.61,1897530.61,1923887.45,1923887.45,1923887.45,1
26,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-03-31,2016-03-31,0.0,,NaN,...,NaN,NaN,NaN,1870863.65,1870863.65,1870863.65,1897530.61,1897530.61,1897530.61,1
27,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-06-30,2016-06-30,0.0,,NaN,...,NaN,NaN,NaN,1843882.93,1843882.93,1843882.93,1870863.65,1870863.65,1870863.65,1
28,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-09-30,2016-09-30,0.0,,NaN,...,NaN,NaN,NaN,1816584.76,1816584.76,1816584.76,1843882.93,1843882.93,1843882.93,1
29,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-12-31,2016-12-31,0.0,,NaN,...,NaN,NaN,NaN,1788965.40,1788965.40,1788965.40,1816584.76,1816584.76,1816584.76,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195775,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-03-31,2015-03-31,0.0,,NaN,...,NaN,NaN,NaN,1500000.00,1500000.00,1500000.00,NaN,NaN,NaN,1
195776,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-06-30,2015-06-30,0.0,,NaN,...,NaN,NaN,NaN,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1
195777,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-09-30,2015-09-30,0.0,,NaN,...,NaN,NaN,NaN,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1
195778,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-12-31,2015-12-31,0.0,,NaN,...,NaN,NaN,NaN,502021.59,502021.59,502021.59,1500000.00,1500000.00,1500000.00,1
195779,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2016-03-31,2016-03-31,1.0,,NaN,...,NaN,NaN,NaN,502021.59,502021.59,502021.59,502021.59,502021.59,502021.59,1
195780,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-03-31,2017-03-31,0.0,,NaN,...,NaN,NaN,NaN,514200.00,514200.00,514200.00,NaN,NaN,NaN,1
195781,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-06-30,2017-06-30,0.0,,NaN,...,NaN,NaN,NaN,514200.00,514200.00,514200.00,514200.00,514200.00,514200.00,1
195782,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-09-30,2017-09-30,0.0,,NaN,...,NaN,NaN,NaN,512499.55,512499.55,512499.55,514200.00,514200.00,514200.00,1
195783,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-12-31,2017-12-31,0.0,,NaN,...,NaN,NaN,NaN,509998.60,509998.60,509998.60,512499.55,512499.55,512499.55,1
195784,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2005-09-30,2005-09-30,0.0,,NaN,...,NaN,NaN,NaN,825000.00,825000.00,825000.00,NaN,NaN,NaN,1
195785,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2005-12-31,2005-12-31,0.0,,NaN,...,NaN,NaN,NaN,822302.19,822302.19,822302.19,825000.00,825000.00,825000.00,1
195786,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-03-31,2006-03-31,0.0,,NaN,...,NaN,NaN,NaN,818604.86,818604.86,818604.86,822302.19,822302.19,822302.19,1
195787,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-06-30,2006-06-30,0.0,,NaN,...,NaN,NaN,NaN,815076.34,815076.34,815076.34,818604.86,818604.86,818604.86,1
195788,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-09-30,2006-09-30,0.0,,NaN,...,NaN,NaN,NaN,811685.61,811685.61,811685.61,815076.34,815076.34,815076.34,1
195789,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-12-31,2006-12-31,0.0,,NaN,...,NaN,NaN,NaN,808343.26,808343.26,808343.26,811685.61,811685.61,811685.61,1
195790,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-03-31,2007-03-31,0.0,,NaN,...,NaN,NaN,NaN,804928.07,804928.07,804928.07,808343.26,808343.26,808343.26,1
195791,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-06-30,2007-06-30,0.0,,NaN,...,NaN,NaN,NaN,801448.82,801448.82,801448.82,804928.07,804928.07,804928.07,1
195792,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-09-30,2007-09-30,0.0,,NaN,...,NaN,NaN,NaN,797909.56,797909.56,797909.56,801448.82,801448.82,801448.82,1
195793,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-12-31,2007-12-31,0.0,,NaN,...,NaN,NaN,NaN,794400.90,794400.90,794400.90,797909.56,797909.56,797909.56,1
195794,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-03-31,2008-03-31,0.0,,NaN,...,NaN,NaN,NaN,790592.74,790592.74,790592.74,794400.90,794400.90,794400.90,1
195795,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-06-30,2008-06-30,0.0,,NaN,...,NaN,NaN,NaN,785542.56,785542.56,785542.56,790592.74,790592.74,790592.74,1
195796,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-09-30,2008-09-30,0.0,,NaN,...,NaN,NaN,NaN,780139.59,780139.59,780139.59,785542.56,785542.56,785542.56,1
195797,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-12-31,2008-12-31,0.0,,NaN,...,NaN,NaN,NaN,774788.97,774788.97,774788.97,780139.59,780139.59,780139.59,1
195798,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-03-31,2009-03-31,0.0,,NaN,...,NaN,NaN,NaN,768947.02,768947.02,768947.02,774788.97,774788.97,774788.97,1
195799,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-06-30,2009-06-30,0.0,,NaN,...,NaN,NaN,NaN,762369.88,762369.88,762369.88,768947.02,768947.02,768947.02,1
195800,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-09-30,2009-09-30,0.0,,NaN,...,NaN,NaN,NaN,755273.64,755273.64,755273.64,762369.88,762369.88,762369.88,1
195801,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-12-31,2009-12-31,0.0,,NaN,...,NaN,NaN,NaN,747885.15,747885.15,747885.15,755273.64,755273.64,755273.64,1
195802,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2010-03-31,2010-03-31,0.0,,NaN,...,NaN,NaN,NaN,740398.61,740398.61,740398.61,747885.15,747885.15,747885.15,1
195803,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2010-06-30,2010-06-30,0.0,,NaN,...,NaN,NaN,NaN,732876.25,732876.25,732876.25,740398.61,740398.61,740398.61,1
195804,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2010-09-30,2010-09-30,1.0,,NaN,...,NaN,NaN,NaN,732876.25,732876.25,732876.25,732876.25,732876.25,732876.25,1

In [50]:
list(df.columns)

['MATCH_STATUS',
 'MATCH_ID',
 'PORTFOLIO',
 'LOAN_NUM',
 'FACILITY_NUM',
 'DATE',
 'DATE.1',
 'ADD_QTR',
 'DFT_LOAN_NUM',
 'DFT_OBLIGOR',
 'DFT_DATE',
 'CUST_NAME',
 'NET_COMMIT_AMT',
 'OUT_BAL',
 'NET_CHARGE_OFF_AMT',
 'TO_LAST_QTR',
 'LEVERAGED_IND',
 'REPORTING_PORTFOLIO',
 'FACILITY_CD',
 'NAICS_CD',
 'SIC_CD',
 'FEDERAL_RESERVE_CLASS_CD',
 'RPTG_RC_CD',
 'TIME_ID_MIN',
 'ACCT_CMMT_MAX',
 'PDRR',
 'RISK_GRADE',
 'CRR',
 'Downgrade',
 'Downgrade Notch',
 'ACQ_DT',
 'ACCRUAL_STATUS_TYPE',
 'ACCT_NUM',
 'ACQ_NAME',
 'ASSG_RC_CD_NAME',
 'COLLATERAL_CLASS_CD',
 'COLLATERAL_CLASS_DESC',
 'CURR_LOAN_TYPE_CD',
 'CURR_LOAN_TYPE_DESC',
 'CUST_NUM',
 'DIVISION_NAME',
 'FACILITY_CD_DESC',
 'LOAN_NUM_NAME',
 'LOAN_PURPOSE_CD',
 'NON_ACCRUAL_IND',
 'PARENT_FIN_CUST_NAME_NUM',
 'RC_CD',
 'REGION_NAME',
 'SECOND_OFF_NAME_NUM',
 'SOURCE_SYSTEM_CD',
 'ACCT_TYPE',
 'FACILITY_NAME',
 'ACQ_IND',
 'NON_PERFORMING_IND',
 'NOT_FOR_PROFIT_IND',
 'REAL_ESTATE_RISK_IND',
 'SAD_IND',
 'SNC_IND',
 'UBOC_SBA_IND',
 'RENEGOTIATED_IND',
 'SECURED_IND',
 'REGULATORY_RATING',
 'REVOLVING_IND',
 'LGD_RISK_RATING',
 'PROCESS_TYPE',
 'EXPOSURE_CATEGORY',
 'ACQ_CD',
 'PROCESS_TYPE_NAME',
 'RE_RISK_PROPERTY_TYPE',
 'RE_STATE_NAME',
 'RE_COUNTY_NAME',
 'ACTUAL_DELINQUENT_DAY_CNT',
 'CIC',
 'DFT_QTR_N',
 'DFT_QTR_T',
 'DFT_QTR_P',
 'LOAN_NUM_NEG_MATCH',
 'PRED_PERIOD',
 'CIC_GROUP',
 'CIC_GROUP2',
 'SDO_QTR',
 'GAP_QTR',
 'UTILIZATION_RATE',
 'Utilization_Orig',
 'Utilization_lag1',
 'Utilization_lag2',
 'Utilization_lag3',
 'Utilization_lag4',
 'Utilization_lag5',
 'Utilization_lag6',
 'Utilization_lag7',
 'Utilization_lag8',
 'Utilization_lag9',
 'Utilization_lag10',
 'Utilization_lag11',
 'Utilization_lag12',
 'Utilization_lag13',
 'CRR_ORIG',
 'CRR_lag1',
 'CRR_lag2',
 'CRR_lag3',
 'CRR_lag4',
 'CRR_lag5',
 'CRR_lag6',
 'CRR_lag7',
 'CRR_lag8',
 'CRR_lag9',
 'CRR_lag10',
 'CRR_lag11',
 'CRR_lag12',
 'CRR_lag13',
 'CRR_lag14',
 'CRR2_lag1',
 'CRR2_lag2',
 'CRR2_lag3',
 'CRR2_lag4',
 'CRR2_lag5',
 'CRR2_lag6',
 'CRR2_lag7',
 'CRR2_lag8',
 'CRR2_lag9',
 'CRR2_lag10',
 'CRR2_lag11',
 'CRR2_lag12',
 'CRR2_lag13',
 'CRR2_lag14',
 'RENEGOTIATED_lag1',
 'RENEGOTIATED_lag2',
 'RENEGOTIATED_lag3',
 'RENEGOTIATED_lag4',
 'RENEGOTIATED_lag5',
 'RENEGOTIATED_lag6',
 'RENEGOTIATED_lag7',
 'RENEGOTIATED_lag8',
 'RENEGOTIATED_lag9',
 'RENEGOTIATED_lag10',
 'RENEGOTIATED_lag11',
 'RENEGOTIATED_lag12',
 'RENEGOTIATED_lag13',
 'SAD_lag1',
 'SAD_lag2',
 'SAD_lag3',
 'SAD_lag4',
 'SAD_lag5',
 'SAD_lag6',
 'SAD_lag7',
 'SAD_lag8',
 'SAD_lag9',
 'SAD_lag10',
 'SAD_lag11',
 'SAD_lag12',
 'SAD_lag13',
 'pd_scorecard_name',
 'LN_RCD_CNT',
 'CREDIT_LINE_FLAG',
 'LOAN_RGN_KOREA',
 'LOAN_BOOK_AGE',
 'LOAN_AGE_FRM_BOARDING',
 'QTRS_TO_MATURITY',
 'QTRS_TO_MATURITY_MAX',
 'LOAN_BAL_MAX',
 'LOAN_CMMT_MAX',
 'OBLIGOR_AGE',
 'dpd90',
 'dft_mdl',
 'dft_icrs',
 'dft_union',
 'lag_dft_mdl',
 'lag_dft_icrs',
 'lag_dft_union',
 'dft_event_mdl',
 'dft_event_icrs',
 'dft_event_union',
 'ead_mdl',
 'ead_icrs',
 'ead_union',
 'exp_mdl',
 'exp_icrs',
 'exp_union',
 'lag_exp_mdl',
 'lag_exp_icrs',
 'lag_exp_union',
 'IN_SAMPLE']

In [ ]:
##Append the region info to the target variable info dataset

##dfCustMaxCrrCom=pd.merge(dfFacilityCom,a,on =['FACILITY_NUM','DATE'],how='left')

In [72]:
dfCustMaxCrrCom

,DATE,CUST_NAME,FACILITY_NUM,CRR,Downgrade,Downgrade Notch,NET_COMMIT_AMT,OUT_BAL,max
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6.000000,0.000000,0.000000,5.676000e+05,5.676000e+05,6
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5.000000,0.000000,0.000000,8.131556e+06,8.131556e+06,5
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6.000000,0.000000,0.000000,5.456056e+05,5.456056e+05,6
3,2005-03-31,"""MAJ, LLC""",5.648696e+19,5.000000,0.000000,0.000000,1.263000e+06,1.263000e+06,5
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4.000000,0.000000,0.000000,3.048930e+06,3.048930e+06,4
5,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5.000000,0.000000,0.000000,3.963909e+06,3.963909e+06,5
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6.000000,0.000000,0.000000,2.715611e+06,2.715611e+06,6
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4.000000,0.000000,0.000000,2.025248e+06,2.025248e+06,4
8,2005-03-31,120 S DOHENY LLC,9.987914e+19,6.000000,0.000000,0.000000,1.802838e+06,1.802838e+06,6
9,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6.000000,0.000000,0.000000,6.309734e+05,6.309734e+05,6
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4.000000,0.000000,0.000000,1.044431e+06,1.044431e+06,4
11,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6.000000,0.000000,0.000000,5.587259e+05,5.587259e+05,6
12,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5.000000,0.000000,0.000000,6.730704e+06,6.730704e+06,5
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5.000000,0.000000,0.000000,5.358257e+05,5.358257e+05,5
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8.000000,0.000000,0.000000,7.021508e+05,7.021508e+05,8
15,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6.000000,0.000000,0.000000,1.178464e+06,1.178464e+06,6
16,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.000000,0.000000,0.000000,2.595037e+06,2.595037e+06,5
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5.000000,0.000000,0.000000,4.481224e+06,4.481224e+06,5
18,2005-03-31,17422 DERIAN,9.988906e+19,5.000000,0.000000,0.000000,8.127320e+06,8.127320e+06,5
19,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3.000000,0.000000,0.000000,2.035613e+06,2.035613e+06,3
20,2005-03-31,18061 FITCH L P,9.988938e+19,5.000000,0.000000,0.000000,2.842245e+06,2.842245e+06,5
21,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6.000000,0.000000,0.000000,2.850000e+06,2.850000e+06,6
22,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5.000000,0.000000,0.000000,5.250000e+06,5.250000e+06,5
23,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6.000000,0.000000,0.000000,1.277419e+05,1.277419e+05,6
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,2.477465e+17,5.000000,0.000000,0.000000,1.971134e+06,1.971134e+06,5
25,2005-03-31,1992 KINCAID TRUST,9.990123e+19,6.000000,0.000000,0.000000,1.081544e+05,1.081544e+05,6
26,2005-03-31,1997 SCHON REVOCABLE TRUST,9.580994e+19,6.000000,0.000000,0.000000,5.170076e+05,5.170076e+05,6
27,2005-03-31,1999 K AND P OFFEL REV TRUST,6.673201e+19,1.000000,0.000000,0.000000,3.254755e+05,3.254755e+05,1
28,2005-03-31,2000 STEWART REV TRUST,9.990205e+19,6.000000,0.000000,0.000000,9.000000e+05,9.000000e+05,6
29,2005-03-31,2002 DAVIS PROPERTY L P,9.991648e+19,6.000000,0.000000,0.000000,6.384479e+05,6.384479e+05,6
...,...,...,...,...,...,...,...,...,...
171093,2017-12-31,"YACHT HARBOR MHP, LLC",9.918958e+19,7.000000,0.000000,0.000000,2.672491e+06,2.672491e+06,7
171094,2017-12-31,"YAZDANI PROPERTIES, LLC",9.924259e+19,4.000000,0.000000,0.000000,8.373381e+05,8.373381e+05,4
171095,2017-12-31,YECHIEL ROSENFELD,7.960316e+19,3.000000,0.000000,0.000000,8.028064e+05,8.028064e+05,3
171096,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,9.928020e+19,4.000000,0.000000,0.000000,2.344330e+06,2.344330e+06,4
171097,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,9.928097e+19,7.000000,0.000000,0.000000,5.092405e+06,5.092405e+06,7
171098,2017-12-31,YEUNG AE KIM,5.091376e+19,7.000000,0.000000,0.000000,1.722004e+06,1.722004e+06,7
171099,2017-12-31,"YIPPEE HI HO CALLE, LLC",9.928289e+19,6.000000,0.000000,0.000000,8.809604e+05,8.809604e+05,6
171100,2017-12-31,YOKO NAGATA REVOCABLE TRUST,6.449569e+19,3.000000,0.800000,1.200000,1.168964e+06,1.168964e+06,3
171101,2017-12-31,YONG JA KIM,5.091380e+19,4.000000,0.000000,0.000000,2.217899e+06,2.217899e+06,4
171102,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",9.935714e+19,5.000000,0.000000,0.000000,5.411331e+06,5.411331e+06,5
171103,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",9.938586e+19,4.666667,0.333333,0.333333,9.129412e+05,9.129412e+05,5
171104,2017-12-31,YOUNG MOBILE HOME PARK LLC,9.940133e+19,4.000000,0.000000,0.000000,1.549733e+06,1.549733e+06,4
171105,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6.000000,0.000000,0.000000,5.649676e+06,5.649676e+06,6
171106,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4.000000,0.000000,0.000000,3.528716e+06,3.528716e+06,4
171107,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.000000,0.000000,0.000000,1.989961e+06,1.989961e+06,5
171108,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6.000000,0.000000,0.000000,5.900470e+05,5.900470e+05,6
171109,2017-12-31,YUAN SHEN,8.344497e+19,3.000000,1.000000,2.000000,1.919702e+06,1.919702e+06,3
171110,2017-12-31,YUAN SHEN,8.344497e+19,5.000000,0.000000,0.000000,4.292902e+06,4.292902e+06,5
171111,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5.000000,0.000000,0.000000,1.125106e+06,1.125106e+06,5
171112,2017-12-31,YUREN ZHANG,9.957227e+19,4.000000,0.000000,0.000000,9.643488e+05,9.643488e+05,4
171113,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5.000000,0.000000,0.000000,2.447101e+06,2.447101e+06,5
171114,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4.000000,0.000000,0.000000,2.427111e+06,2.427111e+06,4
171115,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4.000000,0.000000,0.000000,4.979214e+06,4.979214e+06,4
171116,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4.000000,0.000000,0.000000,1.297024e+06,1.297024e+06,4
171117,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5.000000,0.000000,0.000000,3.272500e+06,3.272500e+06,5
171118,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5.000000,0.000000,0.000000,2.415867e+06,2.415867e+06,5
171119,2017-12-31,"ZMZ, LLC",9.969613e+19,4.000000,0.000000,0.000000,2.107293e+06,2.107293e+06,4
171120,2017-12-31,ZOREH MARASHI,5.685696e+19,4.000000,0.000000,0.000000,1.185458e+06,1.185458e+06,4
171121,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5.000000,0.000000,0.000000,1.445115e+06,1.445115e+06,5
171122,2017-12-31,ZUMA TRADING INC,9.976658e+19,3.000000,0.000000,0.000000,4.862138e+06,4.862138e+06,3

In [85]:
IndustryLookup=df.loc[:,['CUST_NAME','RE_RISK_PROPERTY_TYPE','RE_STATE_NAME','RE_COUNTY_NAME']]

In [86]:
IndustryLookup  ###195805 rows

,CUST_NAME,RE_RISK_PROPERTY_TYPE,RE_STATE_NAME,RE_COUNTY_NAME
0,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES
1,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
2,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
3,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
4,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
5,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
6,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
7,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
8,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
9,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
10,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
11,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
12,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
13,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
14,RAY PELLEGRINO TRUST,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
15,RAY PELLEGRINO TRUST,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
16,RAY PELLEGRINO TRUST,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
17,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES
18,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
19,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
20,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
21,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
22,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
23,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
24,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
25,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
26,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
27,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
28,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
29,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
...,...,...,...,...
195775,989 41ST STREET LLC,LAND,CALIFORNIA,ALAMEDA (CA)
195776,989 41ST STREET LLC,LAND,CALIFORNIA,ALAMEDA (CA)
195777,989 41ST STREET LLC,LAND,CALIFORNIA,ALAMEDA (CA)
195778,989 41ST STREET LLC,LAND,CALIFORNIA,ALAMEDA (CA)
195779,989 41ST STREET LLC,LAND,CALIFORNIA,ALAMEDA (CA)
195780,"9925-29 CHANNEL ROAD, LLC",OFFICE,CALIFORNIA,SAN DIEGO (CA)
195781,"9925-29 CHANNEL ROAD, LLC",OFFICE,CALIFORNIA,SAN DIEGO (CA)
195782,"9925-29 CHANNEL ROAD, LLC",OFFICE,CALIFORNIA,SAN DIEGO (CA)
195783,"9925-29 CHANNEL ROAD, LLC",OFFICE,CALIFORNIA,SAN DIEGO (CA)
195784,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195785,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195786,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195787,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195788,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195789,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195790,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195791,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195792,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195793,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195794,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195795,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195796,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195797,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195798,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195799,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195800,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195801,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195802,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195803,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195804,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA

In [88]:
IndLookUpNoDup=IndustryLookup.drop_duplicates()  ##16228 rows

In [89]:
IndLookUpNoDup.to_excel('IndLookUpNoDup.xlsx', index  = True)

In [79]:
dfCrrIndustry=pd.merge(dfFacilityCom,df[['RE_RISK_PROPERTY_TYPE','RE_STATE_NAME','RE_COUNTY_NAME']],on =['CUST_NAME','DATE'],how='left')

KeyError: 'CUST_NAME'

In [77]:
list(df.columns)

['MATCH_STATUS',
 'MATCH_ID',
 'PORTFOLIO',
 'LOAN_NUM',
 'FACILITY_NUM',
 'DATE',
 'DATE.1',
 'ADD_QTR',
 'DFT_LOAN_NUM',
 'DFT_OBLIGOR',
 'DFT_DATE',
 'CUST_NAME',
 'NET_COMMIT_AMT',
 'OUT_BAL',
 'NET_CHARGE_OFF_AMT',
 'TO_LAST_QTR',
 'LEVERAGED_IND',
 'REPORTING_PORTFOLIO',
 'FACILITY_CD',
 'NAICS_CD',
 'SIC_CD',
 'FEDERAL_RESERVE_CLASS_CD',
 'RPTG_RC_CD',
 'TIME_ID_MIN',
 'ACCT_CMMT_MAX',
 'PDRR',
 'RISK_GRADE',
 'CRR',
 'Downgrade',
 'Downgrade Notch',
 'ACQ_DT',
 'ACCRUAL_STATUS_TYPE',
 'ACCT_NUM',
 'ACQ_NAME',
 'ASSG_RC_CD_NAME',
 'COLLATERAL_CLASS_CD',
 'COLLATERAL_CLASS_DESC',
 'CURR_LOAN_TYPE_CD',
 'CURR_LOAN_TYPE_DESC',
 'CUST_NUM',
 'DIVISION_NAME',
 'FACILITY_CD_DESC',
 'LOAN_NUM_NAME',
 'LOAN_PURPOSE_CD',
 'NON_ACCRUAL_IND',
 'PARENT_FIN_CUST_NAME_NUM',
 'RC_CD',
 'REGION_NAME',
 'SECOND_OFF_NAME_NUM',
 'SOURCE_SYSTEM_CD',
 'ACCT_TYPE',
 'FACILITY_NAME',
 'ACQ_IND',
 'NON_PERFORMING_IND',
 'NOT_FOR_PROFIT_IND',
 'REAL_ESTATE_RISK_IND',
 'SAD_IND',
 'SNC_IND',
 'UBOC_SBA_IND',
 'RENEGOTIATED_IND',
 'SECURED_IND',
 'REGULATORY_RATING',
 'REVOLVING_IND',
 'LGD_RISK_RATING',
 'PROCESS_TYPE',
 'EXPOSURE_CATEGORY',
 'ACQ_CD',
 'PROCESS_TYPE_NAME',
 'RE_RISK_PROPERTY_TYPE',
 'RE_STATE_NAME',
 'RE_COUNTY_NAME',
 'ACTUAL_DELINQUENT_DAY_CNT',
 'CIC',
 'DFT_QTR_N',
 'DFT_QTR_T',
 'DFT_QTR_P',
 'LOAN_NUM_NEG_MATCH',
 'PRED_PERIOD',
 'CIC_GROUP',
 'CIC_GROUP2',
 'SDO_QTR',
 'GAP_QTR',
 'UTILIZATION_RATE',
 'Utilization_Orig',
 'Utilization_lag1',
 'Utilization_lag2',
 'Utilization_lag3',
 'Utilization_lag4',
 'Utilization_lag5',
 'Utilization_lag6',
 'Utilization_lag7',
 'Utilization_lag8',
 'Utilization_lag9',
 'Utilization_lag10',
 'Utilization_lag11',
 'Utilization_lag12',
 'Utilization_lag13',
 'CRR_ORIG',
 'CRR_lag1',
 'CRR_lag2',
 'CRR_lag3',
 'CRR_lag4',
 'CRR_lag5',
 'CRR_lag6',
 'CRR_lag7',
 'CRR_lag8',
 'CRR_lag9',
 'CRR_lag10',
 'CRR_lag11',
 'CRR_lag12',
 'CRR_lag13',
 'CRR_lag14',
 'CRR2_lag1',
 'CRR2_lag2',
 'CRR2_lag3',
 'CRR2_lag4',
 'CRR2_lag5',
 'CRR2_lag6',
 'CRR2_lag7',
 'CRR2_lag8',
 'CRR2_lag9',
 'CRR2_lag10',
 'CRR2_lag11',
 'CRR2_lag12',
 'CRR2_lag13',
 'CRR2_lag14',
 'RENEGOTIATED_lag1',
 'RENEGOTIATED_lag2',
 'RENEGOTIATED_lag3',
 'RENEGOTIATED_lag4',
 'RENEGOTIATED_lag5',
 'RENEGOTIATED_lag6',
 'RENEGOTIATED_lag7',
 'RENEGOTIATED_lag8',
 'RENEGOTIATED_lag9',
 'RENEGOTIATED_lag10',
 'RENEGOTIATED_lag11',
 'RENEGOTIATED_lag12',
 'RENEGOTIATED_lag13',
 'SAD_lag1',
 'SAD_lag2',
 'SAD_lag3',
 'SAD_lag4',
 'SAD_lag5',
 'SAD_lag6',
 'SAD_lag7',
 'SAD_lag8',
 'SAD_lag9',
 'SAD_lag10',
 'SAD_lag11',
 'SAD_lag12',
 'SAD_lag13',
 'pd_scorecard_name',
 'LN_RCD_CNT',
 'CREDIT_LINE_FLAG',
 'LOAN_RGN_KOREA',
 'LOAN_BOOK_AGE',
 'LOAN_AGE_FRM_BOARDING',
 'QTRS_TO_MATURITY',
 'QTRS_TO_MATURITY_MAX',
 'LOAN_BAL_MAX',
 'LOAN_CMMT_MAX',
 'OBLIGOR_AGE',
 'dpd90',
 'dft_mdl',
 'dft_icrs',
 'dft_union',
 'lag_dft_mdl',
 'lag_dft_icrs',
 'lag_dft_union',
 'dft_event_mdl',
 'dft_event_icrs',
 'dft_event_union',
 'ead_mdl',
 'ead_icrs',
 'ead_union',
 'exp_mdl',
 'exp_icrs',
 'exp_union',
 'lag_exp_mdl',
 'lag_exp_icrs',
 'lag_exp_union',
 'IN_SAMPLE']

In [ ]:
#171123 rows  ##11695 unique customers

In [64]:
TEST=dfCustMaxCrrCom.groupby(['DATE'])['CUST_NAME'].agg(['count'])

In [67]:
TestDowngrade=dfCustMaxCrrCom.groupby(['DATE'])['Downgrade'].agg(['mean'])

In [71]:
pd.DataFrame(TestDowngrade)

                mean
DATE
2005-03-31  0.009960
2005-06-30  0.012628
2005-09-30  0.019059
2005-12-31  0.011013
2006-03-31  0.010513
2006-06-30  0.015466
2006-09-30  0.016395
2006-12-31  0.013448
2007-03-31  0.018087
2007-06-30  0.017070
2007-09-30  0.029449
2007-12-31  0.054737
2008-03-31  0.037605
2008-06-30  0.032310
2008-09-30  0.059353
2008-12-31  0.069641
2009-03-31  0.089296
2009-06-30  0.052094
2009-09-30  0.034323
2009-12-31  0.049393
2010-03-31  0.063574
2010-06-30  0.025540
2010-09-30  0.045152
2010-12-31  0.060282
2011-03-31  0.087364
2011-06-30  0.068919
2011-09-30  0.072289
2011-12-31  0.079608
2012-03-31  0.066124
2012-06-30  0.042703
2012-09-30  0.046757
2012-12-31  0.029623
2013-03-31  0.035616
2013-06-30  0.073722
2013-09-30  0.051054
2013-12-31  0.033134
2014-03-31  0.038810
2014-06-30  0.027527
2014-09-30  0.031983
2014-12-31  0.025596
2015-03-31  0.033009
2015-06-30  0.024017
2015-09-30  0.030426
2015-12-31  0.033432
2016-03-31  0.043067
2016-06-30  0.058168
2016-09-30  0.043304
2016-12-31  0.049271
2017-03-31  0.060872
2017-06-30  0.038770
2017-09-30  0.038231
2017-12-31  0.056066

In [66]:
TEST.to_excel('CustomerCountsAcrossDates.xlsx', index  = True)

In [70]:
TEST

            count
DATE
2005-03-31   2577
2005-06-30   2534
2005-09-30   2501
2005-12-31   4283
2006-03-31   4233
2006-06-30   4235
2006-09-30   4290
2006-12-31   4313
2007-03-31   4331
2007-06-30   4384
2007-09-30   4376
2007-12-31   4469
2008-03-31   4514
2008-06-30   4542
2008-09-30   4506
2008-12-31   4489
2009-03-31   4453
2009-06-30   4360
2009-09-30   4248
2009-12-31   4158
2010-03-31   4080
2010-06-30   4054
2010-09-30   2080
2010-12-31   2024
2011-03-31   2018
2011-06-30   2051
2011-09-30   2109
2011-12-31   2170
2012-03-31   2201
2012-06-30   2104
2012-09-30   2071
2012-12-31   2025
2013-03-31   1971
2013-06-30   2790
2013-09-30   3061
2013-12-31   3008
2014-03-31   2946
2014-06-30   2969
2014-09-30   2988
2014-12-31   3053
2015-03-31   3087
2015-06-30   3102
2015-09-30   3124
2015-12-31   3160
2016-03-31   3226
2016-06-30   3222
2016-09-30   3207
2016-12-31   3180
2017-03-31   3152
2017-06-30   3121
2017-09-30   3041
2017-12-31   2932