In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import datetime
%matplotlib inline

In [80]:
os.chdir("CRE Data")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'CRE Data'

In [81]:
df=pd.read_excel("CRE_08102018smallchangeDowngradecalculation.xlsx")

In [71]:
###see the unique amount of customer name
pd.DataFrame(df['CUST_NAME'].unique())

                                              0
0            RAY PELLEGRINO TRUST U/D/O 2/16/89
1                          RAY PELLEGRINO TRUST
2                             A & D INVESTMENTS
3          A & E GONZALEZ PROPERTIES NO. 4, LLC
4                         A & F PROPERTIES LLC.
5                        A & J INVESTMENTS, LLC
6                  A & J SOCIAL SERVICES L.L.C.
7                           A & K PARTNERSHIP A
8      A & N INZERILLO FAMILY TRUST DTD 5/12/00
9                            A & R PARCEL THREE
10                         A & R TARPAULINS INC
11                                PIERRE LAFOND
12                           ARTHUR L LAFRANCHI
13                              THE LAGER TRUST
14                       ADOLPHUS WENDELL LAGES
15                    A G A PROPERTY MTG LLC AN
16                  A G SPANOS CONSTRUCTION INC
17                               A H REALTY INC
18                           A&J SUNSET VILLAGE
19                      A&J SUNSET VILLAGE, LLC
20                   A M & SONS PROPERTIES, LLC
21                           A MURPHY RANCH LLC
22                                 A/P PROP LTD
23         A-R HHC ORLANDO CONVENTION HOTEL LLC
24               A N N RESOURCES L L C A NEVADA
25                                A SQUARE, LLC
26                      A/STORAGE PLACE, L.L.C.
27                       A TO Z PRINTING CO INC
28                              A W DIRECT, LLC
29                                  A WOODS LLC
...                                         ...
11666                          88 PROPERTY, LLC
11667                      8800 BURTON WAY, LLC
11668                          8801 LIMITED LLC
11669         8808-8816 ARTESIA BOULEVARD, L.P.
11670           888 SATICOY LIMITED PARTNERSHIP
11671                    8899 OLYMPIC BLVD, LLC
11672                  8960 LURLINE AVENUE, LLC
11673                         9TH & STEWART LLC
11674               90 HUDSON ROAD REALTY TRUST
11675                     900 NORTH WESTERN LLC
11676                      900 S MANSFIELD, LLC
11677                           9000 BOLSA, LLC
11678               9012 SOUTH 208TH STREET LLC
11679                         9046 SORENSEN LLC
11680                             906 NEWCO LLC
11681                       9090 WILSHIRE, L.P.
11682                           911 WALNUT, LLC
11683                        9136 SEPULVEDA LLC
11684                       916 CARONDELET, LLC
11685              917 MAIN LLC A TEXAS LIMITED
11686              92ND AND 3RD ASSOCIATES, LLC
11687                             920 HEINZ, LP
11688              921 GARDNER LLC A CALIFORNIA
11689                            97 GASLAMP LLC
11690                           98 CRESCENT LLC
11691             9823-9827 WALNUT STREET, L.P.
11692                            986 W 17TH L P
11693                       989 41ST STREET LLC
11694                 9925-29 CHANNEL ROAD, LLC
11695               953 INDUSTRIAL HOLDINGS LLC

[11696 rows x 1 columns]

In [116]:
G=pd.DataFrame(df.groupby(['DATE','CUST_NAME','FACILITY_NUM'])['CRR'].max()).reset_index().rename_axis(None,axis=1)  #### FACILITY LEVEL

In [117]:
G

,DATE,CUST_NAME,FACILITY_NUM,CRR
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6
3,2005-03-31,"""MAJ, LLC""",5.648696e+19,5
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4
5,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4
8,2005-03-31,120 S DOHENY LLC,9.987914e+19,6
9,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4
11,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6
12,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8
15,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6
16,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5
18,2005-03-31,17422 DERIAN,9.988906e+19,5
19,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3
20,2005-03-31,18061 FITCH L P,9.988938e+19,5
21,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6
22,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5
23,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,2.477465e+17,5
25,2005-03-31,1992 KINCAID TRUST,9.990123e+19,6
26,2005-03-31,1997 SCHON REVOCABLE TRUST,9.580994e+19,6
27,2005-03-31,1999 K AND P OFFEL REV TRUST,6.673201e+19,1
28,2005-03-31,2000 STEWART REV TRUST,9.990205e+19,6
29,2005-03-31,2002 DAVIS PROPERTY L P,9.991648e+19,6
...,...,...,...,...
171093,2017-12-31,"YACHT HARBOR MHP, LLC",9.918958e+19,7
171094,2017-12-31,"YAZDANI PROPERTIES, LLC",9.924259e+19,4
171095,2017-12-31,YECHIEL ROSENFELD,7.960316e+19,3
171096,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,9.928020e+19,4
171097,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,9.928097e+19,7
171098,2017-12-31,YEUNG AE KIM,5.091376e+19,7
171099,2017-12-31,"YIPPEE HI HO CALLE, LLC",9.928289e+19,6
171100,2017-12-31,YOKO NAGATA REVOCABLE TRUST,6.449569e+19,3
171101,2017-12-31,YONG JA KIM,5.091380e+19,4
171102,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",9.935714e+19,5
171103,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",9.938586e+19,5
171104,2017-12-31,YOUNG MOBILE HOME PARK LLC,9.940133e+19,4
171105,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6
171106,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4
171107,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5
171108,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6
171109,2017-12-31,YUAN SHEN,8.344497e+19,3
171110,2017-12-31,YUAN SHEN,8.344497e+19,5
171111,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5
171112,2017-12-31,YUREN ZHANG,9.957227e+19,4
171113,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5
171114,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4
171115,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4
171116,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4
171117,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5
171118,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5
171119,2017-12-31,"ZMZ, LLC",9.969613e+19,4
171120,2017-12-31,ZOREH MARASHI,5.685696e+19,4
171121,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5
171122,2017-12-31,ZUMA TRADING INC,9.976658e+19,3

In [112]:
Gtest2=pd.DataFrame(df.groupby(['DATE','CUST_NAME'])['CRR'].max()).reset_index().rename_axis(None,axis=1)  #### CUSTOMER LEVEL

In [113]:
Gtest2

             DATE                                  CUST_NAME  CRR
0      2005-03-31                           "CORAM DEO, LLC"    6
1      2005-03-31  "DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB"    5
2      2005-03-31               "GREAT WEST PROPERTIES, LLC"    6
3      2005-03-31                                 "MAJ, LLC"    5
4      2005-03-31         1050 BATTERY STREET ASSOCIATES LLC    4
5      2005-03-31                      10519 E STOCKTON, LLC    5
6      2005-03-31              1060 SHERBOURNE ASSOCIATES LP    6
7      2005-03-31       12 STONES FAMILY LIMITED PARTNERSHIP    4
8      2005-03-31                           120 S DOHENY LLC    6
9      2005-03-31                         12K PROPERTIES LLC    6
10     2005-03-31               1340 OLD BAYSHORE ASSOCIATES    4
11     2005-03-31                    14023 NE 8TH STREET LLC    6
12     2005-03-31                        1431 VIA PLATA, LLC    5
13     2005-03-31              144 NORTH SAN MATEO DRIVE LLC    5
14     2005-03-31               1550 E MC FADDEN ENTERPRISES    8
15     2005-03-31                          1634 SW ALDER LLC    6
16     2005-03-31                   17 PASTEUR INVESTORS LLC    5
17     2005-03-31                1723 CLOVERFIELD PTNERS LLC    5
18     2005-03-31                               17422 DERIAN    5
19     2005-03-31                  17834 BURBANK INVESTMENTS    3
20     2005-03-31                            18061 FITCH L P    5
21     2005-03-31                            1811 QUAIL, LLC    6
22     2005-03-31                     1873 WP PROPERTIES LLC    5
23     2005-03-31                      1950 A KELLOGG AVENUE    6
24     2005-03-31       1988  ABBASSI LIVING TR DATED 4/8/88    5
25     2005-03-31                         1992 KINCAID TRUST    6
26     2005-03-31                 1997 SCHON REVOCABLE TRUST    6
27     2005-03-31               1999 K AND P OFFEL REV TRUST    1
28     2005-03-31                     2000 STEWART REV TRUST    6
29     2005-03-31                    2002 DAVIS PROPERTY L P    6
...           ...                                        ...  ...
163216 2017-12-31             Y.S. SADDLEBACK INVESTORS L.P.    5
163217 2017-12-31                      YACHT HARBOR MHP, LLC    7
163218 2017-12-31                    YAZDANI PROPERTIES, LLC    4
163219 2017-12-31                          YECHIEL ROSENFELD    3
163220 2017-12-31          YEPREMIAN FAMILY DISCLAIMER TRUST    4
163221 2017-12-31             YESHIVATH TORATH EMETH ACADEMY    7
163222 2017-12-31                               YEUNG AE KIM    7
163223 2017-12-31                    YIPPEE HI HO CALLE, LLC    6
163224 2017-12-31                YOKO NAGATA REVOCABLE TRUST    3
163225 2017-12-31                                YONG JA KIM    4
163226 2017-12-31          YOSHIDA REAL ESTATE HOLDINGS, LLC    5
163227 2017-12-31    YOUNG FAMILY TRUST DATED AUGUST 4, 2011    5
163228 2017-12-31                 YOUNG MOBILE HOME PARK LLC    4
163229 2017-12-31                       YOUNG'S HOLDINGS INC    6
163230 2017-12-31              YOURITAN CONSTRUCTION COMPANY    4
163231 2017-12-31                         YS PROPERTIES, LLC    5
163232 2017-12-31                    YTURRALDE BUILDING, LLC    6
163233 2017-12-31                                  YUAN SHEN    5
163234 2017-12-31                             YULE3.SP.1.LLC    5
163235 2017-12-31                                YUREN ZHANG    4
163236 2017-12-31                     YVMHC LLC A CALIFORNIA    5
163237 2017-12-31                       Z & A ASSOCIATES INC    4
163238 2017-12-31                        ZADRO PARTNERS, LLC    4
163239 2017-12-31                       ZAMIR INVESTMENT LLC    4
163240 2017-12-31                        ZIP-O-LOG MILLS INC    5
163241 2017-12-31               ZK LIVERMORE PROPERTIES, LLC    5
163242 2017-12-31                                   ZMZ, LLC    4
163243 2017-12-31                              ZOREH MARASHI    4
163244 2017-12-31                       ZUMA 8TH STREET, LLC    5
163245 2017-12-31                           ZUMA TRADING INC    3

[163246 rows x 3 columns]

In [118]:
Gtest2.columns.values[2] = 'MaxCrr'

In [119]:
Gtest2

             DATE                                  CUST_NAME  MaxCrr
0      2005-03-31                           "CORAM DEO, LLC"       6
1      2005-03-31  "DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB"       5
2      2005-03-31               "GREAT WEST PROPERTIES, LLC"       6
3      2005-03-31                                 "MAJ, LLC"       5
4      2005-03-31         1050 BATTERY STREET ASSOCIATES LLC       4
5      2005-03-31                      10519 E STOCKTON, LLC       5
6      2005-03-31              1060 SHERBOURNE ASSOCIATES LP       6
7      2005-03-31       12 STONES FAMILY LIMITED PARTNERSHIP       4
8      2005-03-31                           120 S DOHENY LLC       6
9      2005-03-31                         12K PROPERTIES LLC       6
10     2005-03-31               1340 OLD BAYSHORE ASSOCIATES       4
11     2005-03-31                    14023 NE 8TH STREET LLC       6
12     2005-03-31                        1431 VIA PLATA, LLC       5
13     2005-03-31              144 NORTH SAN MATEO DRIVE LLC       5
14     2005-03-31               1550 E MC FADDEN ENTERPRISES       8
15     2005-03-31                          1634 SW ALDER LLC       6
16     2005-03-31                   17 PASTEUR INVESTORS LLC       5
17     2005-03-31                1723 CLOVERFIELD PTNERS LLC       5
18     2005-03-31                               17422 DERIAN       5
19     2005-03-31                  17834 BURBANK INVESTMENTS       3
20     2005-03-31                            18061 FITCH L P       5
21     2005-03-31                            1811 QUAIL, LLC       6
22     2005-03-31                     1873 WP PROPERTIES LLC       5
23     2005-03-31                      1950 A KELLOGG AVENUE       6
24     2005-03-31       1988  ABBASSI LIVING TR DATED 4/8/88       5
25     2005-03-31                         1992 KINCAID TRUST       6
26     2005-03-31                 1997 SCHON REVOCABLE TRUST       6
27     2005-03-31               1999 K AND P OFFEL REV TRUST       1
28     2005-03-31                     2000 STEWART REV TRUST       6
29     2005-03-31                    2002 DAVIS PROPERTY L P       6
...           ...                                        ...     ...
163216 2017-12-31             Y.S. SADDLEBACK INVESTORS L.P.       5
163217 2017-12-31                      YACHT HARBOR MHP, LLC       7
163218 2017-12-31                    YAZDANI PROPERTIES, LLC       4
163219 2017-12-31                          YECHIEL ROSENFELD       3
163220 2017-12-31          YEPREMIAN FAMILY DISCLAIMER TRUST       4
163221 2017-12-31             YESHIVATH TORATH EMETH ACADEMY       7
163222 2017-12-31                               YEUNG AE KIM       7
163223 2017-12-31                    YIPPEE HI HO CALLE, LLC       6
163224 2017-12-31                YOKO NAGATA REVOCABLE TRUST       3
163225 2017-12-31                                YONG JA KIM       4
163226 2017-12-31          YOSHIDA REAL ESTATE HOLDINGS, LLC       5
163227 2017-12-31    YOUNG FAMILY TRUST DATED AUGUST 4, 2011       5
163228 2017-12-31                 YOUNG MOBILE HOME PARK LLC       4
163229 2017-12-31                       YOUNG'S HOLDINGS INC       6
163230 2017-12-31              YOURITAN CONSTRUCTION COMPANY       4
163231 2017-12-31                         YS PROPERTIES, LLC       5
163232 2017-12-31                    YTURRALDE BUILDING, LLC       6
163233 2017-12-31                                  YUAN SHEN       5
163234 2017-12-31                             YULE3.SP.1.LLC       5
163235 2017-12-31                                YUREN ZHANG       4
163236 2017-12-31                     YVMHC LLC A CALIFORNIA       5
163237 2017-12-31                       Z & A ASSOCIATES INC       4
163238 2017-12-31                        ZADRO PARTNERS, LLC       4
163239 2017-12-31                       ZAMIR INVESTMENT LLC       4
163240 2017-12-31                        ZIP-O-LOG MILLS INC       5
163241 2017-12-31               ZK LIVERMORE PROPERTIES, LLC       5
163242 2017-12-31                                   ZMZ, LLC       4
163243 2017-12-31                              ZOREH MARASHI       4
163244 2017-12-31                       ZUMA 8TH STREET, LLC       5
163245 2017-12-31                           ZUMA TRADING INC       3

[163246 rows x 3 columns]

In [122]:
dfwMaxRateCustomerLevel=pd.merge(df,Gtest2,how='left',left_on=['DATE','CUST_NAME'],right_on=['DATE','CUST_NAME'])

In [135]:
list(dfwMaxRateCustomerLevel.columns)

['MATCH_STATUS',
 'MATCH_ID',
 'PORTFOLIO',
 'LOAN_NUM',
 'FACILITY_NUM',
 'DATE',
 'DATE.1',
 'ADD_QTR',
 'DFT_LOAN_NUM',
 'DFT_OBLIGOR',
 'DFT_DATE',
 'CUST_NAME',
 'NET_COMMIT_AMT',
 'OUT_BAL',
 'NET_CHARGE_OFF_AMT',
 'TO_LAST_QTR',
 'LEVERAGED_IND',
 'REPORTING_PORTFOLIO',
 'FACILITY_CD',
 'NAICS_CD',
 'SIC_CD',
 'FEDERAL_RESERVE_CLASS_CD',
 'RPTG_RC_CD',
 'TIME_ID_MIN',
 'ACCT_CMMT_MAX',
 'PDRR',
 'RISK_GRADE',
 'CRR',
 'Downgrade',
 'Downgrade Notch',
 'ACQ_DT',
 'ACCRUAL_STATUS_TYPE',
 'ACCT_NUM',
 'ACQ_NAME',
 'ASSG_RC_CD_NAME',
 'COLLATERAL_CLASS_CD',
 'COLLATERAL_CLASS_DESC',
 'CURR_LOAN_TYPE_CD',
 'CURR_LOAN_TYPE_DESC',
 'CUST_NUM',
 'DIVISION_NAME',
 'FACILITY_CD_DESC',
 'LOAN_NUM_NAME',
 'LOAN_PURPOSE_CD',
 'NON_ACCRUAL_IND',
 'PARENT_FIN_CUST_NAME_NUM',
 'RC_CD',
 'REGION_NAME',
 'SECOND_OFF_NAME_NUM',
 'SOURCE_SYSTEM_CD',
 'ACCT_TYPE',
 'FACILITY_NAME',
 'ACQ_IND',
 'NON_PERFORMING_IND',
 'NOT_FOR_PROFIT_IND',
 'REAL_ESTATE_RISK_IND',
 'SAD_IND',
 'SNC_IND',
 'UBOC_SBA_IND',
 'RENEGOTIATED_IND',
 'SECURED_IND',
 'REGULATORY_RATING',
 'REVOLVING_IND',
 'LGD_RISK_RATING',
 'PROCESS_TYPE',
 'EXPOSURE_CATEGORY',
 'ACQ_CD',
 'PROCESS_TYPE_NAME',
 'RE_RISK_PROPERTY_TYPE',
 'RE_STATE_NAME',
 'RE_COUNTY_NAME',
 'ACTUAL_DELINQUENT_DAY_CNT',
 'CIC',
 'DFT_QTR_N',
 'DFT_QTR_T',
 'DFT_QTR_P',
 'LOAN_NUM_NEG_MATCH',
 'PRED_PERIOD',
 'CIC_GROUP',
 'CIC_GROUP2',
 'SDO_QTR',
 'GAP_QTR',
 'UTILIZATION_RATE',
 'Utilization_Orig',
 'Utilization_lag1',
 'Utilization_lag2',
 'Utilization_lag3',
 'Utilization_lag4',
 'Utilization_lag5',
 'Utilization_lag6',
 'Utilization_lag7',
 'Utilization_lag8',
 'Utilization_lag9',
 'Utilization_lag10',
 'Utilization_lag11',
 'Utilization_lag12',
 'Utilization_lag13',
 'CRR_ORIG',
 'CRR_lag1',
 'CRR_lag2',
 'CRR_lag3',
 'CRR_lag4',
 'CRR_lag5',
 'CRR_lag6',
 'CRR_lag7',
 'CRR_lag8',
 'CRR_lag9',
 'CRR_lag10',
 'CRR_lag11',
 'CRR_lag12',
 'CRR_lag13',
 'CRR_lag14',
 'CRR2_lag1',
 'CRR2_lag2',
 'CRR2_lag3',
 'CRR2_lag4',
 'CRR2_lag5',
 'CRR2_lag6',
 'CRR2_lag7',
 'CRR2_lag8',
 'CRR2_lag9',
 'CRR2_lag10',
 'CRR2_lag11',
 'CRR2_lag12',
 'CRR2_lag13',
 'CRR2_lag14',
 'RENEGOTIATED_lag1',
 'RENEGOTIATED_lag2',
 'RENEGOTIATED_lag3',
 'RENEGOTIATED_lag4',
 'RENEGOTIATED_lag5',
 'RENEGOTIATED_lag6',
 'RENEGOTIATED_lag7',
 'RENEGOTIATED_lag8',
 'RENEGOTIATED_lag9',
 'RENEGOTIATED_lag10',
 'RENEGOTIATED_lag11',
 'RENEGOTIATED_lag12',
 'RENEGOTIATED_lag13',
 'SAD_lag1',
 'SAD_lag2',
 'SAD_lag3',
 'SAD_lag4',
 'SAD_lag5',
 'SAD_lag6',
 'SAD_lag7',
 'SAD_lag8',
 'SAD_lag9',
 'SAD_lag10',
 'SAD_lag11',
 'SAD_lag12',
 'SAD_lag13',
 'pd_scorecard_name',
 'LN_RCD_CNT',
 'CREDIT_LINE_FLAG',
 'LOAN_RGN_KOREA',
 'LOAN_BOOK_AGE',
 'LOAN_AGE_FRM_BOARDING',
 'QTRS_TO_MATURITY',
 'QTRS_TO_MATURITY_MAX',
 'LOAN_BAL_MAX',
 'LOAN_CMMT_MAX',
 'OBLIGOR_AGE',
 'dpd90',
 'dft_mdl',
 'dft_icrs',
 'dft_union',
 'lag_dft_mdl',
 'lag_dft_icrs',
 'lag_dft_union',
 'dft_event_mdl',
 'dft_event_icrs',
 'dft_event_union',
 'ead_mdl',
 'ead_icrs',
 'ead_union',
 'exp_mdl',
 'exp_icrs',
 'exp_union',
 'lag_exp_mdl',
 'lag_exp_icrs',
 'lag_exp_union',
 'IN_SAMPLE',
 'MaxCrr']

In [126]:
dd=dfwMaxRateCustomerLevel.sort_values(['CUST_NAME','DATE'],ascending=[True,True])

In [142]:
dd.to_excel('dd.xlsx',index=True)

KeyboardInterrupt:

In [147]:
ddtest=dd.loc[:,['DATE','CUST_NAME','FACILITY_NUM','FACILITY_NAME','CRR','MaxCrr','Downgrade','Downgrade Notch','NET_COMMIT_AMT','OUT_BAL'
,'RE_RISK_PROPERTY_TYPE','RE_STATE_NAME','RE_COUNTY_NAME']]

In [150]:
ddtest.to_excel('ddtest.xlsx',index=True)

In [151]:
ddtest

,DATE,CUST_NAME,FACILITY_NUM,FACILITY_NAME,CRR,MaxCrr,Downgrade,Downgrade Notch,NET_COMMIT_AMT,OUT_BAL,RE_RISK_PROPERTY_TYPE,RE_STATE_NAME,RE_COUNTY_NAME
33237,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0.0,0.0,567600.00,567600.00,INDUSTRIAL,CALIFORNIA,NaN
33238,2005-06-30,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0.0,0.0,567600.00,567600.00,INDUSTRIAL,CALIFORNIA,NaN
33239,2005-09-30,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0.0,0.0,567600.00,567600.00,INDUSTRIAL,CALIFORNIA,NaN
33240,2005-12-31,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0.0,0.0,567600.00,567600.00,INDUSTRIAL,CALIFORNIA,NaN
40087,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,DP INDUSTRIAL LLC A DELAWARE,5,5.0,0.0,0.0,8131556.00,8131556.00,INDUSTRIAL,NaN,NaN
40088,2005-06-30,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,DP INDUSTRIAL LLC A DELAWARE,5,5.0,0.0,0.0,8131556.00,8131556.00,INDUSTRIAL,NaN,NaN
40089,2005-09-30,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,DP INDUSTRIAL LLC A DELAWARE,5,5.0,0.0,0.0,8131556.00,8131556.00,INDUSTRIAL,NaN,NaN
40090,2005-12-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,DP INDUSTRIAL LLC A DELAWARE,5,5.0,0.0,0.0,8131556.00,8131556.00,INDUSTRIAL,NaN,NaN
40091,2006-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,DP INDUSTRIAL LLC A DELAWARE,5,5.0,0.0,0.0,8131556.00,8131556.00,INDUSTRIAL,NaN,NaN
62032,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,GREAT WEST PROPERTIES LLC,6,6.0,0.0,0.0,545605.61,545605.61,INDUSTRIAL,CALIFORNIA,NaN
62033,2005-06-30,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,GREAT WEST PROPERTIES LLC,6,6.0,0.0,0.0,545605.61,545605.61,INDUSTRIAL,CALIFORNIA,NaN
62034,2005-09-30,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,GREAT WEST PROPERTIES LLC,6,6.0,0.0,0.0,545605.61,545605.61,INDUSTRIAL,CALIFORNIA,NaN
62035,2005-12-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,GREAT WEST PROPERTIES LLC,6,6.0,0.0,0.0,545605.61,545605.61,INDUSTRIAL,CALIFORNIA,NaN
98015,2005-03-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98016,2005-06-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98017,2005-09-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98018,2005-12-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98019,2006-03-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98020,2006-06-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98021,2006-09-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98022,2006-12-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98023,2007-03-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98024,2007-06-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98025,2007-09-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98026,2007-12-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98027,2008-03-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98028,2008-06-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98029,2008-09-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98030,2008-12-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
98031,2009-03-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144754,2005-09-30,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0.0,0.0,792011.08,792011.08,INDUSTRIAL,CALIFORNIA,ORANGE
144755,2005-12-31,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0.0,0.0,671551.16,671551.16,INDUSTRIAL,CALIFORNIA,ORANGE
144756,2006-03-31,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0.0,0.0,549728.60,549728.60,INDUSTRIAL,CALIFORNIA,ORANGE
144757,2006-06-30,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0.0,0.0,426283.84,426283.84,INDUSTRIAL,CALIFORNIA,ORANGE
144758,2006-09-30,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0.0,0.0,300962.51,300962.51,INDUSTRIAL,CALIFORNIA,ORANGE
144759,2006-12-31,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0.0,0.0,173477.72,173477.72,INDUSTRIAL,CALIFORNIA,ORANGE
144760,2007-03-31,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0.0,0.0,43744.75,43744.75,INDUSTRIAL,CALIFORNIA,ORANGE
144761,2007-06-30,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0.0,0.0,43744.75,43744.75,INDUSTRIAL,CALIFORNIA,ORANGE
103806,2005-03-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,619048.87,619048.87,INDUSTRIAL,CALIFORNIA,SAN DIEGO
103807,2005-06-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1150000.00,1150000.00,OFFICE,CALIFORNIA,SAN DIEGO
103808,2005-09-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1138177.83,1138177.83,OFFICE,CALIFORNIA,SAN DIEGO
103809,2005-12-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1126174.46,1126174.46,OFFICE,CALIFORNIA,SAN DIEGO
103810,2006-03-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1113987.11,1113987.11,OFFICE,CALIFORNIA,SAN DIEGO
103811,2006-06-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1101612.96,1101612.96,OFFICE,CALIFORNIA,SAN DIEGO
103812,2006-09-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1089049.13,1089049.13,OFFICE,CALIFORNIA,SAN DIEGO
103813,2006-12-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1076292.74,1076292.74,OFFICE,CALIFORNIA,SAN DIEGO
103814,2007-03-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1063340.81,1063340.81,OFFICE,CALIFORNIA,SAN DIEGO
103815,2007-06-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1050190.37,1050190.37,OFFICE,CALIFORNIA,SAN DIEGO
103816,2007-09-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1036838.36,1036838.36,OFFICE,CALIFORNIA,SAN DIEGO
103817,2007-12-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1023281.69,1023281.69,OFFICE,CALIFORNIA,SAN DIEGO
103818,2008-03-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,1009517.24,1009517.24,OFFICE,CALIFORNIA,SAN DIEGO
103819,2008-06-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,995541.80,995541.80,OFFICE,CALIFORNIA,SAN DIEGO
103820,2008-09-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,981352.16,981352.16,OFFICE,CALIFORNIA,SAN DIEGO
103821,2008-12-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,966945.02,966945.02,OFFICE,CALIFORNIA,SAN DIEGO
103822,2009-03-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,952317.05,952317.05,OFFICE,CALIFORNIA,SAN DIEGO
103823,2009-06-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,937464.88,937464.88,OFFICE,CALIFORNIA,SAN DIEGO
103824,2009-09-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,922385.05,922385.05,OFFICE,CALIFORNIA,SAN DIEGO
103825,2009-12-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,907074.08,907074.08,OFFICE,CALIFORNIA,SAN DIEGO
103826,2010-03-31,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,891528.44,891528.44,OFFICE,CALIFORNIA,SAN DIEGO
103827,2010-06-30,NaN,6.066846e+19,NaN,6,NaN,NaN,NaN,875744.51,875744.51,OFFICE,CALIFORNIA,SAN DIEGO

In [152]:
TESTcustomer=ddtest.groupby(['DATE'])['CUST_NAME'].agg(['count'])

In [153]:
TESTcustomer

            count
DATE
2005-03-31   2884
2005-06-30   2853
2005-09-30   2819
2005-12-31   4882
2006-03-31   4838
2006-06-30   4837
2006-09-30   4880
2006-12-31   4916
2007-03-31   4921
2007-06-30   4969
2007-09-30   4972
2007-12-31   5061
2008-03-31   5111
2008-06-30   5133
2008-09-30   5094
2008-12-31   5067
2009-03-31   5022
2009-06-30   4881
2009-09-30   4741
2009-12-31   4642
2010-03-31   4560
2010-06-30   4533
2010-09-30   2455
2010-12-31   2409
2011-03-31   2400
2011-06-30   2438
2011-09-30   2487
2011-12-31   2554
2012-03-31   2586
2012-06-30   2493
2012-09-30   2460
2012-12-31   2396
2013-03-31   2325
2013-06-30   3320
2013-09-30   3601
2013-12-31   3531
2014-03-31   3459
2014-06-30   3465
2014-09-30   3476
2014-12-31   3536
2015-03-31   3563
2015-06-30   3573
2015-09-30   3587
2015-12-31   3598
2016-03-31   3655
2016-06-30   3656
2016-09-30   3633
2016-12-31   3594
2017-03-31   3571
2017-06-30   3544
2017-09-30   3467
2017-12-31   3335

In [208]:
ddDowngradeMax=pd.read_excel('ddtestAnalysis.xlsx')

In [210]:
ddDowngradeMax['DowngradeMax'].value_counts()

0    189600
1      6205
Name: DowngradeMax, dtype: int64

In [211]:
ddDowngradeMax['UpgradeMax'].value_counts()

0    190118
1      5687
Name: UpgradeMax, dtype: int64

In [158]:
ddTestDowngrade=ddDowngradeMax.groupby(['DATE'])['DowngradeMax'].agg(['mean'])

In [159]:
ddTestDowngrade

                mean
DATE
2005-03-31  0.000000
2005-06-30  0.009460
2005-09-30  0.010284
2005-12-31  0.008601
2006-03-31  0.008679
2006-06-30  0.008061
2006-09-30  0.010449
2006-12-31  0.013626
2007-03-31  0.010158
2007-06-30  0.012676
2007-09-30  0.012266
2007-12-31  0.020150
2008-03-31  0.039515
2008-06-30  0.029801
2008-09-30  0.025319
2008-12-31  0.046961
2009-03-31  0.059327
2009-06-30  0.079680
2009-09-30  0.046816
2009-12-31  0.031445
2010-03-31  0.043412
2010-06-30  0.054698
2010-09-30  0.039919
2010-12-31  0.037360
2011-03-31  0.050000
2011-06-30  0.070550
2011-09-30  0.055086
2011-12-31  0.058340
2012-03-31  0.065739
2012-06-30  0.054152
2012-09-30  0.032520
2012-12-31  0.034641
2013-03-31  0.022366
2013-06-30  0.021386
2013-09-30  0.053596
2013-12-31  0.043047
2014-03-31  0.026308
2014-06-30  0.030303
2014-09-30  0.020713
2014-12-31  0.025735
2015-03-31  0.021050
2015-06-30  0.024629
2015-09-30  0.017285
2015-12-31  0.022790
2016-03-31  0.024077
2016-06-30  0.032823
2016-09-30  0.044041
2016-12-31  0.037563
2017-03-31  0.038645
2017-06-30  0.050790
2017-09-30  0.032593
2017-12-31  0.032084

In [214]:
ddTestUpgrade=ddDowngradeMax.groupby(['DATE'])['UpgradeMax'].agg(['mean'])

In [215]:
ddTestUpgrade

                mean
DATE
2005-03-31  0.000000
2005-06-30  0.010862
2005-09-30  0.017376
2005-12-31  0.009625
2006-03-31  0.007026
2006-06-30  0.007441
2006-09-30  0.007785
2006-12-31  0.008745
2007-03-31  0.005486
2007-06-30  0.008249
2007-09-30  0.007239
2007-12-31  0.006914
2008-03-31  0.002739
2008-06-30  0.007986
2008-09-30  0.005496
2008-12-31  0.003552
2009-03-31  0.002986
2009-06-30  0.003687
2009-09-30  0.006959
2009-12-31  0.009046
2010-03-31  0.033107
2010-06-30  0.054036
2010-09-30  0.050102
2010-12-31  0.044832
2011-03-31  0.028750
2011-06-30  0.045119
2011-09-30  0.038199
2011-12-31  0.039546
2012-03-31  0.051431
2012-06-30  0.055355
2012-09-30  0.044309
2012-12-31  0.050083
2013-03-31  0.057204
2013-06-30  0.046084
2013-09-30  0.060261
2013-12-31  0.064288
2014-03-31  0.039607
2014-06-30  0.056854
2014-09-30  0.052359
2014-12-31  0.041572
2015-03-31  0.037609
2015-06-30  0.052057
2015-09-30  0.042096
2015-12-31  0.046693
2016-03-31  0.041587
2016-06-30  0.057166
2016-09-30  0.036884
2016-12-31  0.041736
2017-03-31  0.026323
2017-06-30  0.033578
2017-09-30  0.069224
2017-12-31  0.128636

In [111]:
#test=df.pivot_table(index=['DATE','CUST_NAME','FACILITY_NUM'],columns=['CRR'],aggfunc=max)

KeyboardInterrupt:

In [86]:
G.columns.values[3] = 'MaxCrr'  #change the name of crr

In [87]:
G   ##same to a below

,DATE,CUST_NAME,FACILITY_NUM,MaxCrr
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6
3,2005-03-31,"""MAJ, LLC""",5.648696e+19,5
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4
5,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4
8,2005-03-31,120 S DOHENY LLC,9.987914e+19,6
9,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4
11,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6
12,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8
15,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6
16,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5
18,2005-03-31,17422 DERIAN,9.988906e+19,5
19,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3
20,2005-03-31,18061 FITCH L P,9.988938e+19,5
21,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6
22,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5
23,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,2.477465e+17,5
25,2005-03-31,1992 KINCAID TRUST,9.990123e+19,6
26,2005-03-31,1997 SCHON REVOCABLE TRUST,9.580994e+19,6
27,2005-03-31,1999 K AND P OFFEL REV TRUST,6.673201e+19,1
28,2005-03-31,2000 STEWART REV TRUST,9.990205e+19,6
29,2005-03-31,2002 DAVIS PROPERTY L P,9.991648e+19,6
...,...,...,...,...
171093,2017-12-31,"YACHT HARBOR MHP, LLC",9.918958e+19,7
171094,2017-12-31,"YAZDANI PROPERTIES, LLC",9.924259e+19,4
171095,2017-12-31,YECHIEL ROSENFELD,7.960316e+19,3
171096,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,9.928020e+19,4
171097,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,9.928097e+19,7
171098,2017-12-31,YEUNG AE KIM,5.091376e+19,7
171099,2017-12-31,"YIPPEE HI HO CALLE, LLC",9.928289e+19,6
171100,2017-12-31,YOKO NAGATA REVOCABLE TRUST,6.449569e+19,3
171101,2017-12-31,YONG JA KIM,5.091380e+19,4
171102,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",9.935714e+19,5
171103,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",9.938586e+19,5
171104,2017-12-31,YOUNG MOBILE HOME PARK LLC,9.940133e+19,4
171105,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6
171106,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4
171107,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5
171108,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6
171109,2017-12-31,YUAN SHEN,8.344497e+19,3
171110,2017-12-31,YUAN SHEN,8.344497e+19,5
171111,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5
171112,2017-12-31,YUREN ZHANG,9.957227e+19,4
171113,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5
171114,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4
171115,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4
171116,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4
171117,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5
171118,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5
171119,2017-12-31,"ZMZ, LLC",9.969613e+19,4
171120,2017-12-31,ZOREH MARASHI,5.685696e+19,4
171121,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5
171122,2017-12-31,ZUMA TRADING INC,9.976658e+19,3

In [115]:
Gtest2.loc[Gtest2['CUST_NAME']== 'RAY PELLEGRINO TRUST U/D/O 2/16/89']

             DATE                           CUST_NAME  CRR
115475 2013-12-31  RAY PELLEGRINO TRUST U/D/O 2/16/89    5
118280 2014-03-31  RAY PELLEGRINO TRUST U/D/O 2/16/89    5
121073 2014-06-30  RAY PELLEGRINO TRUST U/D/O 2/16/89    5
123897 2014-09-30  RAY PELLEGRINO TRUST U/D/O 2/16/89    5
126753 2014-12-31  RAY PELLEGRINO TRUST U/D/O 2/16/89    4
129676 2015-03-31  RAY PELLEGRINO TRUST U/D/O 2/16/89    4
132605 2015-06-30  RAY PELLEGRINO TRUST U/D/O 2/16/89    4
135548 2015-09-30  RAY PELLEGRINO TRUST U/D/O 2/16/89    4
138506 2015-12-31  RAY PELLEGRINO TRUST U/D/O 2/16/89    4
141536 2016-03-31  RAY PELLEGRINO TRUST U/D/O 2/16/89    4
144591 2016-06-30  RAY PELLEGRINO TRUST U/D/O 2/16/89    4
147638 2016-09-30  RAY PELLEGRINO TRUST U/D/O 2/16/89    4
150666 2016-12-31  RAY PELLEGRINO TRUST U/D/O 2/16/89    4
153685 2017-03-31  RAY PELLEGRINO TRUST U/D/O 2/16/89    4

In [105]:
df.loc[df['CUST_NAME']== 'RAY PELLEGRINO TRUST U/D/O 2/16/89',['DATE','CRR','CUST_NAME','FACILITY_NAME','FACILITY_NUM']]

,DATE,CRR,CUST_NAME,FACILITY_NAME,FACILITY_NUM
0,2013-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
1,2014-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
2,2014-06-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
3,2014-09-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
4,2014-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
5,2015-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
6,2015-06-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
7,2015-09-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
8,2015-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
9,2016-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
10,2016-06-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
11,2016-09-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
12,2016-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
13,2017-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
17,2013-12-31,5,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
18,2014-03-31,5,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
19,2014-06-30,5,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
20,2014-09-30,5,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
21,2014-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
22,2015-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
23,2015-06-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
24,2015-09-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
25,2015-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
26,2016-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
27,2016-06-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
28,2016-09-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
29,2016-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
30,2017-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
34,2013-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
35,2014-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
36,2014-06-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
37,2014-09-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
38,2014-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
39,2015-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
40,2015-06-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
41,2015-09-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
42,2015-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
43,2016-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
44,2016-06-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
45,2016-09-30,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
46,2016-12-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15
47,2017-03-31,4,RAY PELLEGRINO TRUST U/D/O 2/16/89,RAY PELLEGRINO TRUST,5.295440e+15

In [88]:
dfwMaxRate=pd.merge(df,G,how='left',left_on=['DATE','CUST_NAME','FACILITY_NUM'],right_on=['DATE','CUST_NAME','FACILITY_NUM'])

In [90]:
dfwMaxRate

,MATCH_STATUS,MATCH_ID,PORTFOLIO,LOAN_NUM,FACILITY_NUM,DATE,DATE.1,ADD_QTR,DFT_LOAN_NUM,DFT_OBLIGOR,...,ead_icrs,ead_union,exp_mdl,exp_icrs,exp_union,lag_exp_mdl,lag_exp_icrs,lag_exp_union,IN_SAMPLE,MaxCrr
0,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2013-12-31,2013-12-31,0.0,,NaN,...,NaN,NaN,1449999.98,1449999.98,1449999.98,NaN,NaN,NaN,1,5.0
1,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-03-31,2014-03-31,0.0,,NaN,...,NaN,NaN,1433154.72,1433154.72,1433154.72,1449999.98,1449999.98,1449999.98,1,5.0
2,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-06-30,2014-06-30,0.0,,NaN,...,NaN,NaN,1416113.63,1416113.63,1416113.63,1433154.72,1433154.72,1433154.72,1,5.0
3,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-09-30,2014-09-30,0.0,,NaN,...,NaN,NaN,1398874.44,1398874.44,1398874.44,1416113.63,1416113.63,1416113.63,1,5.0
4,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2014-12-31,2014-12-31,0.0,,NaN,...,NaN,NaN,1381434.86,1381434.86,1381434.86,1398874.44,1398874.44,1398874.44,1,4.0
5,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-03-31,2015-03-31,0.0,,NaN,...,NaN,NaN,1363792.54,1363792.54,1363792.54,1381434.86,1381434.86,1381434.86,1,4.0
6,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-06-30,2015-06-30,0.0,,NaN,...,NaN,NaN,1345945.13,1345945.13,1345945.13,1363792.54,1363792.54,1363792.54,1,4.0
7,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-09-30,2015-09-30,0.0,,NaN,...,NaN,NaN,1327890.25,1327890.25,1327890.25,1345945.13,1345945.13,1345945.13,1,4.0
8,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2015-12-31,2015-12-31,0.0,,NaN,...,NaN,NaN,1309625.49,1309625.49,1309625.49,1327890.25,1327890.25,1327890.25,1,4.0
9,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-03-31,2016-03-31,0.0,,NaN,...,NaN,NaN,1291148.40,1291148.40,1291148.40,1309625.49,1309625.49,1309625.49,1,4.0
10,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-06-30,2016-06-30,0.0,,NaN,...,NaN,NaN,1272456.53,1272456.53,1272456.53,1291148.40,1291148.40,1291148.40,1,4.0
11,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-09-30,2016-09-30,0.0,,NaN,...,NaN,NaN,1253547.36,1253547.36,1253547.36,1272456.53,1272456.53,1272456.53,1,4.0
12,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2016-12-31,2016-12-31,0.0,,NaN,...,NaN,NaN,1234418.38,1234418.38,1234418.38,1253547.36,1253547.36,1253547.36,1,4.0
13,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-03-31,2017-03-31,0.0,,NaN,...,NaN,NaN,1215067.03,1215067.03,1215067.03,1234418.38,1234418.38,1234418.38,1,4.0
14,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-06-30,2017-06-30,0.0,,NaN,...,NaN,NaN,1195490.73,1195490.73,1195490.73,1215067.03,1215067.03,1215067.03,1,4.0
15,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-09-30,2017-09-30,0.0,,NaN,...,NaN,NaN,1175686.85,1175686.85,1175686.85,1195490.73,1195490.73,1195490.73,1,4.0
16,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000001,5.295440e+15,2017-12-31,2017-12-31,0.0,,NaN,...,NaN,NaN,1155652.77,1155652.77,1155652.77,1175686.85,1175686.85,1175686.85,1,4.0
17,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2013-12-31,2013-12-31,0.0,,NaN,...,NaN,NaN,2100000.00,2100000.00,2100000.00,NaN,NaN,NaN,1,5.0
18,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-03-31,2014-03-31,0.0,,NaN,...,NaN,NaN,2075715.27,2075715.27,2075715.27,2100000.00,2100000.00,2100000.00,1,5.0
19,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-06-30,2014-06-30,0.0,,NaN,...,NaN,NaN,2051144.80,2051144.80,2051144.80,2075715.27,2075715.27,2075715.27,1,5.0
20,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-09-30,2014-09-30,0.0,,NaN,...,NaN,NaN,2026285.24,2026285.24,2026285.24,2051144.80,2051144.80,2051144.80,1,5.0
21,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2014-12-31,2014-12-31,0.0,,NaN,...,NaN,NaN,2001133.19,2001133.19,2001133.19,2026285.24,2026285.24,2026285.24,1,4.0
22,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-03-31,2015-03-31,0.0,,NaN,...,NaN,NaN,1975685.20,1975685.20,1975685.20,2001133.19,2001133.19,2001133.19,1,4.0
23,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-06-30,2015-06-30,0.0,,NaN,...,NaN,NaN,1949937.80,1949937.80,1949937.80,1975685.20,1975685.20,1975685.20,1,4.0
24,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-09-30,2015-09-30,0.0,,NaN,...,NaN,NaN,1923887.45,1923887.45,1923887.45,1949937.80,1949937.80,1949937.80,1,4.0
25,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2015-12-31,2015-12-31,0.0,,NaN,...,NaN,NaN,1897530.61,1897530.61,1897530.61,1923887.45,1923887.45,1923887.45,1,4.0
26,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-03-31,2016-03-31,0.0,,NaN,...,NaN,NaN,1870863.65,1870863.65,1870863.65,1897530.61,1897530.61,1897530.61,1,4.0
27,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-06-30,2016-06-30,0.0,,NaN,...,NaN,NaN,1843882.93,1843882.93,1843882.93,1870863.65,1870863.65,1870863.65,1,4.0
28,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-09-30,2016-09-30,0.0,,NaN,...,NaN,NaN,1816584.76,1816584.76,1816584.76,1843882.93,1843882.93,1843882.93,1,4.0
29,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ00005295440000000002,5.295440e+15,2016-12-31,2016-12-31,0.0,,NaN,...,NaN,NaN,1788965.40,1788965.40,1788965.40,1816584.76,1816584.76,1816584.76,1,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195775,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-03-31,2015-03-31,0.0,,NaN,...,NaN,NaN,1500000.00,1500000.00,1500000.00,NaN,NaN,NaN,1,6.0
195776,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-06-30,2015-06-30,0.0,,NaN,...,NaN,NaN,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1,6.0
195777,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-09-30,2015-09-30,0.0,,NaN,...,NaN,NaN,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1500000.00,1,6.0
195778,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2015-12-31,2015-12-31,0.0,,NaN,...,NaN,NaN,502021.59,502021.59,502021.59,1500000.00,1500000.00,1500000.00,1,6.0
195779,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999123630080000000,9.999912e+19,2016-03-31,2016-03-31,1.0,,NaN,...,NaN,NaN,502021.59,502021.59,502021.59,502021.59,502021.59,502021.59,1,6.0
195780,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-03-31,2017-03-31,0.0,,NaN,...,NaN,NaN,514200.00,514200.00,514200.00,NaN,NaN,NaN,1,7.0
195781,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-06-30,2017-06-30,0.0,,NaN,...,NaN,NaN,514200.00,514200.00,514200.00,514200.00,514200.00,514200.00,1,7.0
195782,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-09-30,2017-09-30,0.0,,NaN,...,NaN,NaN,512499.55,512499.55,512499.55,514200.00,514200.00,514200.00,1,7.0
195783,UNMATCH - ICRS,0,OO CRE,ZZZ99999133200000000001,9.999913e+19,2017-12-31,2017-12-31,0.0,,NaN,...,NaN,NaN,509998.60,509998.60,509998.60,512499.55,512499.55,512499.55,1,7.0
195784,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2005-09-30,2005-09-30,0.0,,NaN,...,NaN,NaN,825000.00,825000.00,825000.00,NaN,NaN,NaN,1,6.0
195785,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2005-12-31,2005-12-31,0.0,,NaN,...,NaN,NaN,822302.19,822302.19,822302.19,825000.00,825000.00,825000.00,1,6.0
195786,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-03-31,2006-03-31,0.0,,NaN,...,NaN,NaN,818604.86,818604.86,818604.86,822302.19,822302.19,822302.19,1,6.0
195787,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-06-30,2006-06-30,0.0,,NaN,...,NaN,NaN,815076.34,815076.34,815076.34,818604.86,818604.86,818604.86,1,6.0
195788,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-09-30,2006-09-30,0.0,,NaN,...,NaN,NaN,811685.61,811685.61,811685.61,815076.34,815076.34,815076.34,1,6.0
195789,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2006-12-31,2006-12-31,0.0,,NaN,...,NaN,NaN,808343.26,808343.26,808343.26,811685.61,811685.61,811685.61,1,6.0
195790,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-03-31,2007-03-31,0.0,,NaN,...,NaN,NaN,804928.07,804928.07,804928.07,808343.26,808343.26,808343.26,1,6.0
195791,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-06-30,2007-06-30,0.0,,NaN,...,NaN,NaN,801448.82,801448.82,801448.82,804928.07,804928.07,804928.07,1,6.0
195792,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-09-30,2007-09-30,0.0,,NaN,...,NaN,NaN,797909.56,797909.56,797909.56,801448.82,801448.82,801448.82,1,6.0
195793,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2007-12-31,2007-12-31,0.0,,NaN,...,NaN,NaN,794400.90,794400.90,794400.90,797909.56,797909.56,797909.56,1,6.0
195794,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-03-31,2008-03-31,0.0,,NaN,...,NaN,NaN,790592.74,790592.74,790592.74,794400.90,794400.90,794400.90,1,6.0
195795,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-06-30,2008-06-30,0.0,,NaN,...,NaN,NaN,785542.56,785542.56,785542.56,790592.74,790592.74,790592.74,1,6.0
195796,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-09-30,2008-09-30,0.0,,NaN,...,NaN,NaN,780139.59,780139.59,780139.59,785542.56,785542.56,785542.56,1,6.0
195797,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2008-12-31,2008-12-31,0.0,,NaN,...,NaN,NaN,774788.97,774788.97,774788.97,780139.59,780139.59,780139.59,1,6.0
195798,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-03-31,2009-03-31,0.0,,NaN,...,NaN,NaN,768947.02,768947.02,768947.02,774788.97,774788.97,774788.97,1,6.0
195799,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-06-30,2009-06-30,0.0,,NaN,...,NaN,NaN,762369.88,762369.88,762369.88,768947.02,768947.02,768947.02,1,6.0
195800,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-09-30,2009-09-30,0.0,,NaN,...,NaN,NaN,755273.64,755273.64,755273.64,762369.88,762369.88,762369.88,1,6.0
195801,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2009-12-31,2009-12-31,0.0,,NaN,...,NaN,NaN,747885.15,747885.15,747885.15,755273.64,755273.64,755273.64,1,6.0
195802,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2010-03-31,2010-03-31,0.0,,NaN,...,NaN,NaN,740398.61,740398.61,740398.61,747885.15,747885.15,747885.15,1,6.0
195803,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2010-06-30,2010-06-30,0.0,,NaN,...,NaN,NaN,732876.25,732876.25,732876.25,740398.61,740398.61,740398.61,1,8.0
195804,UNMATCH - ICRS,0,"NON-OO CRE(Perm,Const,Land,REF)",ZZZ99999154080000000001,9.999915e+19,2010-09-30,2010-09-30,1.0,,NaN,...,NaN,NaN,732876.25,732876.25,732876.25,732876.25,732876.25,732876.25,1,8.0

In [91]:
#dfwMaxRate.to_excel('dfwMaxRate.xlsx', index  = True)

In [ ]:
### downgrade cases is calculated in the excel spreadsheet as it is a loop over all rows in the dataframe

In [92]:
dfwMaxRate['Downgrade'].value_counts()   ###new downgrade calculation, less downgrade

0.0    187784
1.0      7998
Name: Downgrade, dtype: int64

In [93]:
dfwMaxRate['Downgrade Notch'].describe()

count    195782.000000
mean         -0.007452
std           0.186889
min          -7.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           4.000000
Name: Downgrade Notch, dtype: float64

In [ ]:
dfwMaxRate

In [ ]:
df.groupby(['DATE','CUST_NAME',''])

In [168]:
ddDowngradeMaxpivot=pd.pivot_table(ddDowngradeMax,index=['DATE','CUST_NAME'],values=['CRR','MaxCrr','Downgrade','Downgrade Notch','DowngradeMax','DowngradeMax Notch','NET_COMMIT_AMT','OUT_BAL'])

In [186]:
ddDowngradeMax['DowngradeMax'].value_counts()

0    189600
1      6205
Name: DowngradeMax, dtype: int64

In [187]:
ddDowngradeMax ##from original dataset

,DATE,CUST_NAME,FACILITY_NUM,FACILITY_NAME,CRR,MaxCrr,CRRTracking,Downgrade,Downgrade Notch,NET_COMMIT_AMT,OUT_BAL,RE_RISK_PROPERTY_TYPE,RE_STATE_NAME,RE_COUNTY_NAME,DowngradeMax,DowngradeMax Notch
33237,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0,0.0,0.0,567600.00,567600.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
33238,2005-06-30,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0,0.0,0.0,567600.00,567600.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
33239,2005-09-30,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0,0.0,0.0,567600.00,567600.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
33240,2005-12-31,"""CORAM DEO, LLC""",1.592124e+19,CORAM DEO LLC,6,6.0,0,0.0,0.0,567600.00,567600.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
40087,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,DP INDUSTRIAL LLC A DELAWARE,5,5.0,0,0.0,0.0,8131556.00,8131556.00,INDUSTRIAL,NaN,NaN,0,NaN
40088,2005-06-30,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,DP INDUSTRIAL LLC A DELAWARE,5,5.0,0,0.0,0.0,8131556.00,8131556.00,INDUSTRIAL,NaN,NaN,0,NaN
40089,2005-09-30,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,DP INDUSTRIAL LLC A DELAWARE,5,5.0,0,0.0,0.0,8131556.00,8131556.00,INDUSTRIAL,NaN,NaN,0,NaN
40090,2005-12-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,DP INDUSTRIAL LLC A DELAWARE,5,5.0,0,0.0,0.0,8131556.00,8131556.00,INDUSTRIAL,NaN,NaN,0,NaN
40091,2006-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,DP INDUSTRIAL LLC A DELAWARE,5,5.0,0,0.0,0.0,8131556.00,8131556.00,INDUSTRIAL,NaN,NaN,0,NaN
62032,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,GREAT WEST PROPERTIES LLC,6,6.0,0,0.0,0.0,545605.61,545605.61,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
62033,2005-06-30,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,GREAT WEST PROPERTIES LLC,6,6.0,0,0.0,0.0,545605.61,545605.61,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
62034,2005-09-30,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,GREAT WEST PROPERTIES LLC,6,6.0,0,0.0,0.0,545605.61,545605.61,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
62035,2005-12-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,GREAT WEST PROPERTIES LLC,6,6.0,0,0.0,0.0,545605.61,545605.61,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98015,2005-03-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98016,2005-06-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98017,2005-09-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98018,2005-12-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98019,2006-03-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98020,2006-06-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98021,2006-09-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98022,2006-12-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98023,2007-03-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98024,2007-06-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98025,2007-09-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98026,2007-12-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98027,2008-03-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98028,2008-06-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98029,2008-09-30,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98030,2008-12-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
98031,2009-03-31,"""MAJ, LLC""",5.648696e+19,MAJ LLC,5,5.0,0,0.0,0.0,1263000.00,1263000.00,INDUSTRIAL,CALIFORNIA,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144754,2005-09-30,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0,0.0,0.0,792011.08,792011.08,INDUSTRIAL,CALIFORNIA,ORANGE,0,NaN
144755,2005-12-31,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0,0.0,0.0,671551.16,671551.16,INDUSTRIAL,CALIFORNIA,ORANGE,0,NaN
144756,2006-03-31,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0,0.0,0.0,549728.60,549728.60,INDUSTRIAL,CALIFORNIA,ORANGE,0,NaN
144757,2006-06-30,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0,0.0,0.0,426283.84,426283.84,INDUSTRIAL,CALIFORNIA,ORANGE,0,NaN
144758,2006-09-30,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0,0.0,0.0,300962.51,300962.51,INDUSTRIAL,CALIFORNIA,ORANGE,0,NaN
144759,2006-12-31,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0,0.0,0.0,173477.72,173477.72,INDUSTRIAL,CALIFORNIA,ORANGE,0,NaN
144760,2007-03-31,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0,0.0,0.0,43744.75,43744.75,INDUSTRIAL,CALIFORNIA,ORANGE,0,NaN
144761,2007-06-30,ZVI RYZMAN,8.082878e+19,ZVI RYZMAN,4,4.0,0,0.0,0.0,43744.75,43744.75,INDUSTRIAL,CALIFORNIA,ORANGE,0,NaN
103806,2005-03-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,619048.87,619048.87,INDUSTRIAL,CALIFORNIA,SAN DIEGO,0,NaN
103807,2005-06-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1150000.00,1150000.00,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103808,2005-09-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1138177.83,1138177.83,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103809,2005-12-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1126174.46,1126174.46,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103810,2006-03-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1113987.11,1113987.11,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103811,2006-06-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1101612.96,1101612.96,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103812,2006-09-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1089049.13,1089049.13,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103813,2006-12-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1076292.74,1076292.74,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103814,2007-03-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1063340.81,1063340.81,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103815,2007-06-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1050190.37,1050190.37,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103816,2007-09-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1036838.36,1036838.36,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103817,2007-12-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1023281.69,1023281.69,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103818,2008-03-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,1009517.24,1009517.24,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103819,2008-06-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,995541.80,995541.80,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103820,2008-09-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,981352.16,981352.16,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103821,2008-12-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,966945.02,966945.02,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103822,2009-03-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,952317.05,952317.05,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103823,2009-06-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,937464.88,937464.88,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103824,2009-09-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,922385.05,922385.05,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103825,2009-12-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,907074.08,907074.08,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103826,2010-03-31,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,891528.44,891528.44,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN
103827,2010-06-30,NaN,6.066846e+19,NaN,6,NaN,1,NaN,NaN,875744.51,875744.51,OFFICE,CALIFORNIA,SAN DIEGO,0,NaN

In [216]:
##no pivot table only sorting
ddDowngradeMaxDate=ddDowngradeMax.sort_values(['DATE'],ascending=True)

In [218]:
ddDowngradeMaxDate['UpgradeMax']

33237     0
135959    0
135966    0
83194     0
65107     0
66846     0
45409     0
184192    0
39877     0
46181     0
44419     0
115170    0
156181    0
45311     0
136589    0
136635    0
108976    0
182306    0
45157     0
45147     0
136691    0
156087    0
44956     0
44924     0
44897     0
182263    0
182184    0
45199     0
45195     0
104120    0
         ..
8821      0
25873     0
194938    0
83436     0
193253    0
44000     0
8890      0
8889      0
8881      0
8873      0
8860      0
21811     1
21820     0
101233    1
10384     0
123645    0
21829     0
8847      0
124680    0
193241    0
191389    0
44158     0
160342    0
128265    0
31715     1
76416     0
123663    0
85712     0
1558      1
70808     0
Name: UpgradeMax, Length: 195805, dtype: int64

In [219]:
ddDowngradeMaxDate.columns

Index(['DATE', 'CUST_NAME', 'FACILITY_NUM', 'FACILITY_NAME', 'CRR', 'MaxCrr',
       'CRRTracking', 'Downgrade', 'Downgrade Notch', 'NET_COMMIT_AMT',
       'OUT_BAL', 'RE_RISK_PROPERTY_TYPE', 'RE_STATE_NAME', 'RE_COUNTY_NAME',
       'DowngradeMax', 'DowngradeMax Notch', 'UpgradeMax', 'UpgradeMax Notch'],
      dtype='object')

In [220]:
targetfullv2=ddDowngradeMaxDate.loc[:,['DATE','CUST_NAME','FACILITY_NUM','FACILITY_NAME','CRR','MaxCrr','DowngradeMax', 'DowngradeMax Notch','UpgradeMax','UpgradeMax Notch','Downgrade','Downgrade Notch','NET_COMMIT_AMT','OUT_BAL'
,'RE_RISK_PROPERTY_TYPE','RE_STATE_NAME','RE_COUNTY_NAME']]

In [221]:
targetfullv2.to_excel('targetfull v2.xlsx')

In [185]:
###the datasize and value change after pivoting
ddDowngradeMaxpivot['DowngradeMax'].value_counts()

0.000000    157041
1.000000      5233
0.500000       644
0.333333       190
0.250000        77
0.200000        27
0.166667        14
0.125000         5
0.111111         3
0.100000         2
0.052632         2
0.142857         1
0.041667         1
0.090909         1
0.083333         1
0.020833         1
0.055556         1
0.071429         1
0.047619         1
Name: DowngradeMax, dtype: int64

In [171]:
targetVariable=ddDowngradeMaxpivot.reset_index().rename_axis(None,axis=1)

In [170]:
targetVariable

,DATE,CUST_NAME,CRR,Downgrade,Downgrade Notch,DowngradeMax,MaxCrr,NET_COMMIT_AMT,OUT_BAL
0,2005-03-31,"""CORAM DEO, LLC""",6.000000,0.0,0.0,0.0,6.0,5.676000e+05,5.676000e+05
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",5.000000,0.0,0.0,0.0,5.0,8.131556e+06,8.131556e+06
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",6.000000,0.0,0.0,0.0,6.0,5.456056e+05,5.456056e+05
3,2005-03-31,"""MAJ, LLC""",5.000000,0.0,0.0,0.0,5.0,1.263000e+06,1.263000e+06
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,4.000000,0.0,0.0,0.0,4.0,3.048930e+06,3.048930e+06
5,2005-03-31,"10519 E STOCKTON, LLC",5.000000,0.0,0.0,0.0,5.0,3.963909e+06,3.963909e+06
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,6.000000,0.0,0.0,0.0,6.0,2.715611e+06,2.715611e+06
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,4.000000,0.0,0.0,0.0,4.0,2.025248e+06,2.025248e+06
8,2005-03-31,120 S DOHENY LLC,6.000000,0.0,0.0,0.0,6.0,1.802838e+06,1.802838e+06
9,2005-03-31,12K PROPERTIES LLC,6.000000,0.0,0.0,0.0,6.0,6.309734e+05,6.309734e+05
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,4.000000,0.0,0.0,0.0,4.0,1.044431e+06,1.044431e+06
11,2005-03-31,14023 NE 8TH STREET LLC,6.000000,0.0,0.0,0.0,6.0,5.587259e+05,5.587259e+05
12,2005-03-31,"1431 VIA PLATA, LLC",5.000000,0.0,0.0,0.0,5.0,6.730704e+06,6.730704e+06
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,5.000000,0.0,0.0,0.0,5.0,5.358257e+05,5.358257e+05
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,8.000000,0.0,0.0,0.0,8.0,7.021508e+05,7.021508e+05
15,2005-03-31,1634 SW ALDER LLC,6.000000,0.0,0.0,0.0,6.0,1.178464e+06,1.178464e+06
16,2005-03-31,17 PASTEUR INVESTORS LLC,5.000000,0.0,0.0,0.0,5.0,2.595037e+06,2.595037e+06
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,5.000000,0.0,0.0,0.0,5.0,4.481224e+06,4.481224e+06
18,2005-03-31,17422 DERIAN,5.000000,0.0,0.0,0.0,5.0,8.127320e+06,8.127320e+06
19,2005-03-31,17834 BURBANK INVESTMENTS,3.000000,0.0,0.0,0.0,3.0,2.035613e+06,2.035613e+06
20,2005-03-31,18061 FITCH L P,5.000000,0.0,0.0,0.0,5.0,2.842245e+06,2.842245e+06
21,2005-03-31,"1811 QUAIL, LLC",6.000000,0.0,0.0,0.0,6.0,2.850000e+06,2.850000e+06
22,2005-03-31,1873 WP PROPERTIES LLC,5.000000,0.0,0.0,0.0,5.0,5.250000e+06,5.250000e+06
23,2005-03-31,1950 A KELLOGG AVENUE,6.000000,0.0,0.0,0.0,6.0,1.277419e+05,1.277419e+05
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,5.000000,0.0,0.0,0.0,5.0,1.971134e+06,1.971134e+06
25,2005-03-31,1992 KINCAID TRUST,6.000000,0.0,0.0,0.0,6.0,1.081544e+05,1.081544e+05
26,2005-03-31,1997 SCHON REVOCABLE TRUST,6.000000,0.0,0.0,0.0,6.0,5.170076e+05,5.170076e+05
27,2005-03-31,1999 K AND P OFFEL REV TRUST,1.000000,0.0,0.0,0.0,1.0,3.254755e+05,3.254755e+05
28,2005-03-31,2000 STEWART REV TRUST,6.000000,0.0,0.0,0.0,6.0,9.000000e+05,9.000000e+05
29,2005-03-31,2002 DAVIS PROPERTY L P,6.000000,0.0,0.0,0.0,6.0,6.384479e+05,6.384479e+05
...,...,...,...,...,...,...,...,...,...
163216,2017-12-31,Y.S. SADDLEBACK INVESTORS L.P.,5.000000,0.0,0.0,0.0,5.0,2.914273e+06,2.914273e+06
163217,2017-12-31,"YACHT HARBOR MHP, LLC",7.000000,1.0,-3.0,1.0,7.0,2.672491e+06,2.672491e+06
163218,2017-12-31,"YAZDANI PROPERTIES, LLC",4.000000,0.0,0.0,0.0,4.0,8.373381e+05,8.373381e+05
163219,2017-12-31,YECHIEL ROSENFELD,3.000000,0.0,0.0,0.0,3.0,8.028064e+05,8.028064e+05
163220,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,4.000000,0.0,0.0,0.0,4.0,2.344330e+06,2.344330e+06
163221,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,7.000000,0.0,0.0,0.0,7.0,5.092405e+06,5.092405e+06
163222,2017-12-31,YEUNG AE KIM,7.000000,0.0,0.0,0.0,7.0,1.722004e+06,1.722004e+06
163223,2017-12-31,"YIPPEE HI HO CALLE, LLC",6.000000,0.0,0.0,0.0,6.0,8.809604e+05,8.809604e+05
163224,2017-12-31,YOKO NAGATA REVOCABLE TRUST,3.000000,0.0,0.0,0.0,3.0,1.168964e+06,1.168964e+06
163225,2017-12-31,YONG JA KIM,4.000000,0.0,0.0,0.0,4.0,2.217899e+06,2.217899e+06
163226,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",5.000000,0.0,0.0,0.0,5.0,5.411331e+06,5.411331e+06
163227,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",4.666667,0.0,0.0,0.0,5.0,9.129412e+05,9.129412e+05
163228,2017-12-31,YOUNG MOBILE HOME PARK LLC,4.000000,0.0,0.0,0.0,4.0,1.549733e+06,1.549733e+06
163229,2017-12-31,YOUNG'S HOLDINGS INC,6.000000,0.0,0.0,0.0,6.0,5.649676e+06,5.649676e+06
163230,2017-12-31,YOURITAN CONSTRUCTION COMPANY,4.000000,0.0,0.0,0.0,4.0,3.528716e+06,3.528716e+06
163231,2017-12-31,"YS PROPERTIES, LLC",5.000000,0.0,0.0,0.0,5.0,1.989961e+06,1.989961e+06
163232,2017-12-31,"YTURRALDE BUILDING, LLC",6.000000,0.0,0.0,0.0,6.0,5.900470e+05,5.900470e+05
163233,2017-12-31,YUAN SHEN,4.000000,0.0,0.0,0.0,5.0,3.106302e+06,3.106302e+06
163234,2017-12-31,YULE3.SP.1.LLC,5.000000,0.0,0.0,0.0,5.0,1.125106e+06,1.125106e+06
163235,2017-12-31,YUREN ZHANG,4.000000,0.0,0.0,0.0,4.0,9.643488e+05,9.643488e+05
163236,2017-12-31,YVMHC LLC A CALIFORNIA,5.000000,0.0,0.0,0.0,5.0,2.447101e+06,2.447101e+06
163237,2017-12-31,Z & A ASSOCIATES INC,4.000000,0.0,0.0,0.0,4.0,2.427111e+06,2.427111e+06
163238,2017-12-31,"ZADRO PARTNERS, LLC",4.000000,0.0,0.0,0.0,4.0,4.979214e+06,4.979214e+06
163239,2017-12-31,ZAMIR INVESTMENT LLC,4.000000,0.0,0.0,0.0,4.0,1.297024e+06,1.297024e+06
163240,2017-12-31,ZIP-O-LOG MILLS INC,5.000000,0.0,0.0,0.0,5.0,3.272500e+06,3.272500e+06
163241,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",5.000000,0.0,0.0,0.0,5.0,2.415867e+06,2.415867e+06
163242,2017-12-31,"ZMZ, LLC",4.000000,0.0,0.0,0.0,4.0,2.107293e+06,2.107293e+06
163243,2017-12-31,ZOREH MARASHI,4.000000,0.0,0.0,0.0,4.0,1.185458e+06,1.185458e+06
163244,2017-12-31,"ZUMA 8TH STREET, LLC",5.000000,0.0,0.0,0.0,5.0,1.445115e+06,1.445115e+06
163245,2017-12-31,ZUMA TRADING INC,3.000000,0.0,0.0,0.0,3.0,4.862138e+06,4.862138e+06

In [172]:
targetVariable.to_excel('targetVariable.xlsx')

In [192]:
targetVariable   ##change to 163246 rows why?????

,DATE,CUST_NAME,CRR,Downgrade,Downgrade Notch,DowngradeMax,MaxCrr,NET_COMMIT_AMT,OUT_BAL
0,2005-03-31,"""CORAM DEO, LLC""",6.000000,0.0,0.0,0.0,6.0,5.676000e+05,5.676000e+05
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",5.000000,0.0,0.0,0.0,5.0,8.131556e+06,8.131556e+06
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",6.000000,0.0,0.0,0.0,6.0,5.456056e+05,5.456056e+05
3,2005-03-31,"""MAJ, LLC""",5.000000,0.0,0.0,0.0,5.0,1.263000e+06,1.263000e+06
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,4.000000,0.0,0.0,0.0,4.0,3.048930e+06,3.048930e+06
5,2005-03-31,"10519 E STOCKTON, LLC",5.000000,0.0,0.0,0.0,5.0,3.963909e+06,3.963909e+06
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,6.000000,0.0,0.0,0.0,6.0,2.715611e+06,2.715611e+06
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,4.000000,0.0,0.0,0.0,4.0,2.025248e+06,2.025248e+06
8,2005-03-31,120 S DOHENY LLC,6.000000,0.0,0.0,0.0,6.0,1.802838e+06,1.802838e+06
9,2005-03-31,12K PROPERTIES LLC,6.000000,0.0,0.0,0.0,6.0,6.309734e+05,6.309734e+05
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,4.000000,0.0,0.0,0.0,4.0,1.044431e+06,1.044431e+06
11,2005-03-31,14023 NE 8TH STREET LLC,6.000000,0.0,0.0,0.0,6.0,5.587259e+05,5.587259e+05
12,2005-03-31,"1431 VIA PLATA, LLC",5.000000,0.0,0.0,0.0,5.0,6.730704e+06,6.730704e+06
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,5.000000,0.0,0.0,0.0,5.0,5.358257e+05,5.358257e+05
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,8.000000,0.0,0.0,0.0,8.0,7.021508e+05,7.021508e+05
15,2005-03-31,1634 SW ALDER LLC,6.000000,0.0,0.0,0.0,6.0,1.178464e+06,1.178464e+06
16,2005-03-31,17 PASTEUR INVESTORS LLC,5.000000,0.0,0.0,0.0,5.0,2.595037e+06,2.595037e+06
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,5.000000,0.0,0.0,0.0,5.0,4.481224e+06,4.481224e+06
18,2005-03-31,17422 DERIAN,5.000000,0.0,0.0,0.0,5.0,8.127320e+06,8.127320e+06
19,2005-03-31,17834 BURBANK INVESTMENTS,3.000000,0.0,0.0,0.0,3.0,2.035613e+06,2.035613e+06
20,2005-03-31,18061 FITCH L P,5.000000,0.0,0.0,0.0,5.0,2.842245e+06,2.842245e+06
21,2005-03-31,"1811 QUAIL, LLC",6.000000,0.0,0.0,0.0,6.0,2.850000e+06,2.850000e+06
22,2005-03-31,1873 WP PROPERTIES LLC,5.000000,0.0,0.0,0.0,5.0,5.250000e+06,5.250000e+06
23,2005-03-31,1950 A KELLOGG AVENUE,6.000000,0.0,0.0,0.0,6.0,1.277419e+05,1.277419e+05
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,5.000000,0.0,0.0,0.0,5.0,1.971134e+06,1.971134e+06
25,2005-03-31,1992 KINCAID TRUST,6.000000,0.0,0.0,0.0,6.0,1.081544e+05,1.081544e+05
26,2005-03-31,1997 SCHON REVOCABLE TRUST,6.000000,0.0,0.0,0.0,6.0,5.170076e+05,5.170076e+05
27,2005-03-31,1999 K AND P OFFEL REV TRUST,1.000000,0.0,0.0,0.0,1.0,3.254755e+05,3.254755e+05
28,2005-03-31,2000 STEWART REV TRUST,6.000000,0.0,0.0,0.0,6.0,9.000000e+05,9.000000e+05
29,2005-03-31,2002 DAVIS PROPERTY L P,6.000000,0.0,0.0,0.0,6.0,6.384479e+05,6.384479e+05
...,...,...,...,...,...,...,...,...,...
163216,2017-12-31,Y.S. SADDLEBACK INVESTORS L.P.,5.000000,0.0,0.0,0.0,5.0,2.914273e+06,2.914273e+06
163217,2017-12-31,"YACHT HARBOR MHP, LLC",7.000000,1.0,-3.0,1.0,7.0,2.672491e+06,2.672491e+06
163218,2017-12-31,"YAZDANI PROPERTIES, LLC",4.000000,0.0,0.0,0.0,4.0,8.373381e+05,8.373381e+05
163219,2017-12-31,YECHIEL ROSENFELD,3.000000,0.0,0.0,0.0,3.0,8.028064e+05,8.028064e+05
163220,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,4.000000,0.0,0.0,0.0,4.0,2.344330e+06,2.344330e+06
163221,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,7.000000,0.0,0.0,0.0,7.0,5.092405e+06,5.092405e+06
163222,2017-12-31,YEUNG AE KIM,7.000000,0.0,0.0,0.0,7.0,1.722004e+06,1.722004e+06
163223,2017-12-31,"YIPPEE HI HO CALLE, LLC",6.000000,0.0,0.0,0.0,6.0,8.809604e+05,8.809604e+05
163224,2017-12-31,YOKO NAGATA REVOCABLE TRUST,3.000000,0.0,0.0,0.0,3.0,1.168964e+06,1.168964e+06
163225,2017-12-31,YONG JA KIM,4.000000,0.0,0.0,0.0,4.0,2.217899e+06,2.217899e+06
163226,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",5.000000,0.0,0.0,0.0,5.0,5.411331e+06,5.411331e+06
163227,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",4.666667,0.0,0.0,0.0,5.0,9.129412e+05,9.129412e+05
163228,2017-12-31,YOUNG MOBILE HOME PARK LLC,4.000000,0.0,0.0,0.0,4.0,1.549733e+06,1.549733e+06
163229,2017-12-31,YOUNG'S HOLDINGS INC,6.000000,0.0,0.0,0.0,6.0,5.649676e+06,5.649676e+06
163230,2017-12-31,YOURITAN CONSTRUCTION COMPANY,4.000000,0.0,0.0,0.0,4.0,3.528716e+06,3.528716e+06
163231,2017-12-31,"YS PROPERTIES, LLC",5.000000,0.0,0.0,0.0,5.0,1.989961e+06,1.989961e+06
163232,2017-12-31,"YTURRALDE BUILDING, LLC",6.000000,0.0,0.0,0.0,6.0,5.900470e+05,5.900470e+05
163233,2017-12-31,YUAN SHEN,4.000000,0.0,0.0,0.0,5.0,3.106302e+06,3.106302e+06
163234,2017-12-31,YULE3.SP.1.LLC,5.000000,0.0,0.0,0.0,5.0,1.125106e+06,1.125106e+06
163235,2017-12-31,YUREN ZHANG,4.000000,0.0,0.0,0.0,4.0,9.643488e+05,9.643488e+05
163236,2017-12-31,YVMHC LLC A CALIFORNIA,5.000000,0.0,0.0,0.0,5.0,2.447101e+06,2.447101e+06
163237,2017-12-31,Z & A ASSOCIATES INC,4.000000,0.0,0.0,0.0,4.0,2.427111e+06,2.427111e+06
163238,2017-12-31,"ZADRO PARTNERS, LLC",4.000000,0.0,0.0,0.0,4.0,4.979214e+06,4.979214e+06
163239,2017-12-31,ZAMIR INVESTMENT LLC,4.000000,0.0,0.0,0.0,4.0,1.297024e+06,1.297024e+06
163240,2017-12-31,ZIP-O-LOG MILLS INC,5.000000,0.0,0.0,0.0,5.0,3.272500e+06,3.272500e+06
163241,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",5.000000,0.0,0.0,0.0,5.0,2.415867e+06,2.415867e+06
163242,2017-12-31,"ZMZ, LLC",4.000000,0.0,0.0,0.0,4.0,2.107293e+06,2.107293e+06
163243,2017-12-31,ZOREH MARASHI,4.000000,0.0,0.0,0.0,4.0,1.185458e+06,1.185458e+06
163244,2017-12-31,"ZUMA 8TH STREET, LLC",5.000000,0.0,0.0,0.0,5.0,1.445115e+06,1.445115e+06
163245,2017-12-31,ZUMA TRADING INC,3.000000,0.0,0.0,0.0,3.0,4.862138e+06,4.862138e+06

### DETECT WHY 2017 6/30  DI is high

In [179]:
targetVariable.loc[targetVariable['DATE'].isin(['2017-06-30','2017-03-31']),:].to_excel('detect.xlsx')  ##find issue in target varibletable in detecting part

In [203]:
targetfull.loc[targetfull['DATE'].isin(['2017-06-30','2017-03-31']),:].to_excel('detect2.xlsx')

#### Categorizing the data by date and customer
### look deep into the facility and customer_name

In [43]:
Frrtest=pd.pivot_table(df,index=['DATE','CUST_NAME'],values=['CRR','Downgrade','Downgrade Notch','NET_COMMIT_AMT','OUT_BAL'])

In [ ]:
pd.pivot_table(df,index=['DATE','CUST_NAME'],values=['CRR','Downgrade','Downgrade Notch','NET_COMMIT_AMT','OUT_BAL'])

In [44]:
Frrtest

                                                           CRR  Downgrade  \
DATE       CUST_NAME
2005-03-31 "CORAM DEO, LLC"                           6.000000        0.0
           "DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB"  5.000000        0.0
           "GREAT WEST PROPERTIES, LLC"               6.000000        0.0
           "MAJ, LLC"                                 5.000000        0.0
           1050 BATTERY STREET ASSOCIATES LLC         4.000000        0.0
           10519 E STOCKTON, LLC                      5.000000        0.0
           1060 SHERBOURNE ASSOCIATES LP              6.000000        0.0
           12 STONES FAMILY LIMITED PARTNERSHIP       4.000000        0.0
           120 S DOHENY LLC                           6.000000        0.0
           12K PROPERTIES LLC                         6.000000        0.0
           1340 OLD BAYSHORE ASSOCIATES               4.000000        0.0
           14023 NE 8TH STREET LLC                    6.000000        0.0
           1431 VIA PLATA, LLC                        5.000000        0.0
           144 NORTH SAN MATEO DRIVE LLC              5.000000        0.0
           1550 E MC FADDEN ENTERPRISES               8.000000        0.0
           1634 SW ALDER LLC                          6.000000        0.0
           17 PASTEUR INVESTORS LLC                   5.000000        0.0
           1723 CLOVERFIELD PTNERS LLC                5.000000        0.0
           17422 DERIAN                               5.000000        0.0
           17834 BURBANK INVESTMENTS                  3.000000        0.0
           18061 FITCH L P                            5.000000        0.0
           1811 QUAIL, LLC                            6.000000        0.0
           1873 WP PROPERTIES LLC                     5.000000        0.0
           1950 A KELLOGG AVENUE                      6.000000        0.0
           1988  ABBASSI LIVING TR DATED 4/8/88       5.000000        0.0
           1992 KINCAID TRUST                         6.000000        0.0
           1997 SCHON REVOCABLE TRUST                 6.000000        0.0
           1999 K AND P OFFEL REV TRUST               1.000000        0.0
           2000 STEWART REV TRUST                     6.000000        0.0
           2002 DAVIS PROPERTY L P                    6.000000        0.0
...                                                        ...        ...
2017-12-31 Y.S. SADDLEBACK INVESTORS L.P.             5.000000        0.0
           YACHT HARBOR MHP, LLC                      7.000000        0.0
           YAZDANI PROPERTIES, LLC                    4.000000        0.0
           YECHIEL ROSENFELD                          3.000000        0.0
           YEPREMIAN FAMILY DISCLAIMER TRUST          4.000000        0.0
           YESHIVATH TORATH EMETH ACADEMY             7.000000        0.0
           YEUNG AE KIM                               7.000000        0.0
           YIPPEE HI HO CALLE, LLC                    6.000000        0.0
           YOKO NAGATA REVOCABLE TRUST                3.000000        0.8
           YONG JA KIM                                4.000000        0.0
           YOSHIDA REAL ESTATE HOLDINGS, LLC          5.000000        0.0
           YOUNG FAMILY TRUST DATED AUGUST 4, 2011    4.666667        0.0
           YOUNG MOBILE HOME PARK LLC                 4.000000        0.0
           YOUNG'S HOLDINGS INC                       6.000000        0.0
           YOURITAN CONSTRUCTION COMPANY              4.000000        0.0
           YS PROPERTIES, LLC                         5.000000        0.0
           YTURRALDE BUILDING, LLC                    6.000000        0.0
           YUAN SHEN                                  4.000000        0.5
           YULE3.SP.1.LLC                             5.000000        0.0
           YUREN ZHANG                                4.000000        0.0
           YVMHC LLC A CALIFORNIA                     5.000000        0.0
           Z & A ASSOCIATES INC                       4.000000        0.0
           ZADRO PARTNERS, LLC                        4.000000        0.0
           ZAMIR INVESTMENT LLC                       4.000000        0.0
           ZIP-O-LOG MILLS INC                        5.000000        0.0
           ZK LIVERMORE PROPERTIES, LLC               5.000000        0.0
           ZMZ, LLC                                   4.000000        0.0
           ZOREH MARASHI                              4.000000        0.0
           ZUMA 8TH STREET, LLC                       5.000000        0.0
           ZUMA TRADING INC                           3.000000        0.0

                                                      Downgrade Notch  \
DATE       CUST_NAME
2005-03-31 "CORAM DEO, LLC"                                       0.0
           "DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB"              0.0
           "GREAT WEST PROPERTIES, LLC"                           0.0
           "MAJ, LLC"                                             0.0
           1050 BATTERY STREET ASSOCIATES LLC                     0.0
           10519 E STOCKTON, LLC                                  0.0
           1060 SHERBOURNE ASSOCIATES LP                          0.0
           12 STONES FAMILY LIMITED PARTNERSHIP                   0.0
           120 S DOHENY LLC                                       0.0
           12K PROPERTIES LLC                                     0.0
           1340 OLD BAYSHORE ASSOCIATES                           0.0
           14023 NE 8TH STREET LLC                                0.0
           1431 VIA PLATA, LLC                                    0.0
           144 NORTH SAN MATEO DRIVE LLC                          0.0
           1550 E MC FADDEN ENTERPRISES                           0.0
           1634 SW ALDER LLC                                      0.0
           17 PASTEUR INVESTORS LLC                               0.0
           1723 CLOVERFIELD PTNERS LLC                            0.0
           17422 DERIAN                                           0.0
           17834 BURBANK INVESTMENTS                              0.0
           18061 FITCH L P                                        0.0
           1811 QUAIL, LLC                                        0.0
           1873 WP PROPERTIES LLC                                 0.0
           1950 A KELLOGG AVENUE                                  0.0
           1988  ABBASSI LIVING TR DATED 4/8/88                   0.0
           1992 KINCAID TRUST                                     0.0
           1997 SCHON REVOCABLE TRUST                             0.0
           1999 K AND P OFFEL REV TRUST                           0.0
           2000 STEWART REV TRUST                                 0.0
           2002 DAVIS PROPERTY L P                                0.0
...                                                               ...
2017-12-31 Y.S. SADDLEBACK INVESTORS L.P.                         0.0
           YACHT HARBOR MHP, LLC                                  0.0
           YAZDANI PROPERTIES, LLC                                0.0
           YECHIEL ROSENFELD                                      0.0
           YEPREMIAN FAMILY DISCLAIMER TRUST                      0.0
           YESHIVATH TORATH EMETH ACADEMY                         0.0
           YEUNG AE KIM                                           0.0
           YIPPEE HI HO CALLE, LLC                                0.0
           YOKO NAGATA REVOCABLE TRUST                            1.2
           YONG JA KIM                                            0.0
           YOSHIDA REAL ESTATE HOLDINGS, LLC                      0.0
           YOUNG FAMILY TRUST DATED AUGUST 4, 2011                0.0
           YOUNG MOBILE HOME PARK LLC                             0.0
           YOUNG'S HOLDINGS INC                                   0.0
           YOURITAN CONSTRUCTION COMPANY                          0.0
           YS PROPERTIES, LLC                                     0.0
           YTURRALDE BUILDING, LLC                                0.0
           YUAN SHEN                                              1.0
           YULE3.SP.1.LLC                                         0.0
           YUREN ZHANG                                            0.0
           YVMHC LLC A CALIFORNIA                                 0.0
           Z & A ASSOCIATES INC                                   0.0
           ZADRO PARTNERS, LLC                                    0.0
           ZAMIR INVESTMENT LLC                                   0.0
           ZIP-O-LOG MILLS INC                                    0.0
           ZK LIVERMORE PROPERTIES, LLC                           0.0
           ZMZ, LLC                                               0.0
           ZOREH MARASHI                                          0.0
           ZUMA 8TH STREET, LLC                                   0.0
           ZUMA TRADING INC                                       0.0

                                                      NET_COMMIT_AMT  \
DATE       CUST_NAME
2005-03-31 "CORAM DEO, LLC"                             5.676000e+05
           "DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB"    8.131556e+06
           "GREAT WEST PROPERTIES, LLC"                 5.456056e+05
           "MAJ, LLC"                                   1.263000e+06
           1050 BATTERY STREET ASSOCIATES LLC           3.048930e+06
           10519 E STOCKTON, LLC                        3.963909e+06
           1060 SHERBOURNE ASSOCIATES LP                2.715611e+06
           12 STONES FAMILY LIMITED PARTNERSHIP         2.025248e+06
           120 S DOHENY LLC                             1.802838e+06
           12K PROPERTIES LLC                           6.309734e+05
           1340 OLD BAYSHORE ASSOCIATES                 1.044431e+06
           14023 NE 8TH STREET LLC                      5.587259e+05
           1431 VIA PLATA, LLC                          6.730704e+06
           144 NORTH SAN MATEO DRIVE LLC                5.358257e+05
           1550 E MC FADDEN ENTERPRISES                 7.021508e+05
           1634 SW ALDER LLC                            1.178464e+06
           17 PASTEUR INVESTORS LLC                     2.595037e+06
           1723 CLOVERFIELD PTNERS LLC                  4.481224e+06
           17422 DERIAN                                 8.127320e+06
           17834 BURBANK INVESTMENTS                    2.035613e+06
           18061 FITCH L P                              2.842245e+06
           1811 QUAIL, LLC                              2.850000e+06
           1873 WP PROPERTIES LLC                       5.250000e+06
           1950 A KELLOGG AVENUE                        1.277419e+05
           1988  ABBASSI LIVING TR DATED 4/8/88         1.971134e+06
           1992 KINCAID TRUST                           1.081544e+05
           1997 SCHON REVOCABLE TRUST                   5.170076e+05
           1999 K AND P OFFEL REV TRUST                 3.254755e+05
           2000 STEWART REV TRUST                       9.000000e+05
           2002 DAVIS PROPERTY L P                      6.384479e+05
...                                                              ...
2017-12-31 Y.S. SADDLEBACK INVESTORS L.P.               2.914273e+06
           YACHT HARBOR MHP, LLC                        2.672491e+06
           YAZDANI PROPERTIES, LLC                      8.373381e+05
           YECHIEL ROSENFELD                            8.028064e+05
           YEPREMIAN FAMILY DISCLAIMER TRUST            2.344330e+06
           YESHIVATH TORATH EMETH ACADEMY               5.092405e+06
           YEUNG AE KIM                                 1.722004e+06
           YIPPEE HI HO CALLE, LLC                      8.809604e+05
           YOKO NAGATA REVOCABLE TRUST                  1.168964e+06
           YONG JA KIM                                  2.217899e+06
           YOSHIDA REAL ESTATE HOLDINGS, LLC            5.411331e+06
           YOUNG FAMILY TRUST DATED AUGUST 4, 2011      9.129412e+05
           YOUNG MOBILE HOME PARK LLC                   1.549733e+06
           YOUNG'S HOLDINGS INC                         5.649676e+06
           YOURITAN CONSTRUCTION COMPANY                3.528716e+06
           YS PROPERTIES, LLC                           1.989961e+06
           YTURRALDE BUILDING, LLC                      5.900470e+05
           YUAN SHEN                                    3.106302e+06
           YULE3.SP.1.LLC                               1.125106e+06
           YUREN ZHANG                                  9.643488e+05
           YVMHC LLC A CALIFORNIA                       2.447101e+06
           Z & A ASSOCIATES INC                         2.427111e+06
           ZADRO PARTNERS, LLC                          4.979214e+06
           ZAMIR INVESTMENT LLC                         1.297024e+06
           ZIP-O-LOG MILLS INC                          3.272500e+06
           ZK LIVERMORE PROPERTIES, LLC                 2.415867e+06
           ZMZ, LLC                                     2.107293e+06
           ZOREH MARASHI                                1.185458e+06
           ZUMA 8TH STREET, LLC                         1.445115e+06
           ZUMA TRADING INC                             4.862138e+06

                                                           OUT_BAL
DATE       CUST_NAME
2005-03-31 "CORAM DEO, LLC"                           5.676000e+05
           "DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB"  8.131556e+06
           "GREAT WEST PROPERTIES, LLC"               5.456056e+05
           "MAJ, LLC"                                 1.263000e+06
           1050 BATTERY STREET ASSOCIATES LLC         3.048930e+06
           10519 E STOCKTON, LLC                      3.963909e+06
           1060 SHERBOURNE ASSOCIATES LP              2.715611e+06
           12 STONES FAMILY LIMITED PARTNERSHIP       2.025248e+06
           120 S DOHENY LLC                           1.802838e+06
           12K PROPERTIES LLC                         6.309734e+05
           1340 OLD BAYSHORE ASSOCIATES               1.044431e+06
           14023 NE 8TH STREET LLC                    5.587259e+05
           1431 VIA PLATA, LLC                        6.730704e+06
           144 NORTH SAN MATEO DRIVE LLC              5.358257e+05
           1550 E MC FADDEN ENTERPRISES               7.021508e+05
           1634 SW ALDER LLC                          1.178464e+06
           17 PASTEUR INVESTORS LLC                   2.595037e+06
           1723 CLOVERFIELD PTNERS LLC                4.481224e+06
           17422 DERIAN                               8.127320e+06
           17834 BURBANK INVESTMENTS                  2.035613e+06
           18061 FITCH L P                            2.842245e+06
           1811 QUAIL, LLC                            2.850000e+06
           1873 WP PROPERTIES LLC                     5.250000e+06
           1950 A KELLOGG AVENUE                      1.277419e+05
           1988  ABBASSI LIVING TR DATED 4/8/88       1.971134e+06
           1992 KINCAID TRUST                         1.081544e+05
           1997 SCHON REVOCABLE TRUST                 5.170076e+05
           1999 K AND P OFFEL REV TRUST               3.254755e+05
           2000 STEWART REV TRUST                     9.000000e+05
           2002 DAVIS PROPERTY L P                    6.384479e+05
...                                                            ...
2017-12-31 Y.S. SADDLEBACK INVESTORS L.P.             2.914273e+06
           YACHT HARBOR MHP, LLC                      2.672491e+06
           YAZDANI PROPERTIES, LLC                    8.373381e+05
           YECHIEL ROSENFELD                          8.028064e+05
           YEPREMIAN FAMILY DISCLAIMER TRUST          2.344330e+06
           YESHIVATH TORATH EMETH ACADEMY             5.092405e+06
           YEUNG AE KIM                               1.722004e+06
           YIPPEE HI HO CALLE, LLC                    8.809604e+05
           YOKO NAGATA REVOCABLE TRUST                1.168964e+06
           YONG JA KIM                                2.217899e+06
           YOSHIDA REAL ESTATE HOLDINGS, LLC          5.411331e+06
           YOUNG FAMILY TRUST DATED AUGUST 4, 2011    9.129412e+05
           YOUNG MOBILE HOME PARK LLC                 1.549733e+06
           YOUNG'S HOLDINGS INC                       5.649676e+06
           YOURITAN CONSTRUCTION COMPANY              3.528716e+06
           YS PROPERTIES, LLC                         1.989961e+06
           YTURRALDE BUILDING, LLC                    5.900470e+05
           YUAN SHEN                                  3.106302e+06
           YULE3.SP.1.LLC                             1.125106e+06
           YUREN ZHANG                                9.643488e+05
           YVMHC LLC A CALIFORNIA                     2.447101e+06
           Z & A ASSOCIATES INC                       2.427111e+06
           ZADRO PARTNERS, LLC                        4.979214e+06
           ZAMIR INVESTMENT LLC                       1.297024e+06
           ZIP-O-LOG MILLS INC                        3.272500e+06
           ZK LIVERMORE PROPERTIES, LLC               2.415867e+06
           ZMZ, LLC                                   2.107293e+06
           ZOREH MARASHI                              1.185458e+06
           ZUMA 8TH STREET, LLC                       1.445115e+06
           ZUMA TRADING INC                           4.862138e+06

[163246 rows x 5 columns]

In [36]:
Frr2=pd.pivot_table(df,index=['DATE','CUST_NAME','FACILITY_NUM'],values=['CRR','Downgrade','Downgrade Notch','NET_COMMIT_AMT','OUT_BAL'])

In [8]:
dfFacilityCom2=Frr2.reset_index().rename_axis(None,axis=1)

In [38]:
Frr2

                                                                        CRR  \
DATE       CUST_NAME                                 FACILITY_NUM
2005-03-31 "CORAM DEO, LLC"                          1.592124e+19  6.000000
           "DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB" 2.051581e+19  5.000000
           "GREAT WEST PROPERTIES, LLC"              3.341848e+19  6.000000
           "MAJ, LLC"                                5.648696e+19  5.000000
           1050 BATTERY STREET ASSOCIATES LLC        9.987780e+19  4.000000
           10519 E STOCKTON, LLC                     9.987783e+19  5.000000
           1060 SHERBOURNE ASSOCIATES LP             9.987785e+19  6.000000
           12 STONES FAMILY LIMITED PARTNERSHIP      9.987830e+19  4.000000
           120 S DOHENY LLC                          9.987914e+19  6.000000
           12K PROPERTIES LLC                        9.987839e+19  6.000000
           1340 OLD BAYSHORE ASSOCIATES              9.988132e+19  4.000000
           14023 NE 8TH STREET LLC                   9.988593e+19  6.000000
           1431 VIA PLATA, LLC                       9.988599e+19  5.000000
           144 NORTH SAN MATEO DRIVE LLC             9.988608e+19  5.000000
           1550 E MC FADDEN ENTERPRISES              9.988849e+19  8.000000
           1634 SW ALDER LLC                         9.988270e+19  6.000000
           17 PASTEUR INVESTORS LLC                  9.988901e+19  5.000000
           1723 CLOVERFIELD PTNERS LLC               9.988904e+19  5.000000
           17422 DERIAN                              9.988906e+19  5.000000
           17834 BURBANK INVESTMENTS                 9.988933e+19  3.000000
           18061 FITCH L P                           9.988938e+19  5.000000
           1811 QUAIL, LLC                           9.988940e+19  6.000000
           1873 WP PROPERTIES LLC                    9.989030e+19  5.000000
           1950 A KELLOGG AVENUE                     5.793132e+17  6.000000
           1988  ABBASSI LIVING TR DATED 4/8/88      2.477465e+17  5.000000
           1992 KINCAID TRUST                        9.990123e+19  6.000000
           1997 SCHON REVOCABLE TRUST                9.580994e+19  6.000000
           1999 K AND P OFFEL REV TRUST              6.673201e+19  1.000000
           2000 STEWART REV TRUST                    9.990205e+19  6.000000
           2002 DAVIS PROPERTY L P                   9.991648e+19  6.000000
...                                                                     ...
2017-12-31 YACHT HARBOR MHP, LLC                     9.918958e+19  7.000000
           YAZDANI PROPERTIES, LLC                   9.924259e+19  4.000000
           YECHIEL ROSENFELD                         7.960316e+19  3.000000
           YEPREMIAN FAMILY DISCLAIMER TRUST         9.928020e+19  4.000000
           YESHIVATH TORATH EMETH ACADEMY            9.928097e+19  7.000000
           YEUNG AE KIM                              5.091376e+19  7.000000
           YIPPEE HI HO CALLE, LLC                   9.928289e+19  6.000000
           YOKO NAGATA REVOCABLE TRUST               6.449569e+19  3.000000
           YONG JA KIM                               5.091380e+19  4.000000
           YOSHIDA REAL ESTATE HOLDINGS, LLC         9.935714e+19  5.000000
           YOUNG FAMILY TRUST DATED AUGUST 4, 2011   9.938586e+19  4.666667
           YOUNG MOBILE HOME PARK LLC                9.940133e+19  4.000000
           YOUNG'S HOLDINGS INC                      9.941714e+19  6.000000
           YOURITAN CONSTRUCTION COMPANY             9.942249e+19  4.000000
           YS PROPERTIES, LLC                        9.944069e+19  5.000000
           YTURRALDE BUILDING, LLC                   9.944095e+19  6.000000
           YUAN SHEN                                 8.344497e+19  3.000000
                                                     8.344497e+19  5.000000
           YULE3.SP.1.LLC                            9.947724e+19  5.000000
           YUREN ZHANG                               9.957227e+19  4.000000
           YVMHC LLC A CALIFORNIA                    9.948691e+19  5.000000
           Z & A ASSOCIATES INC                      9.949226e+19  4.000000
           ZADRO PARTNERS, LLC                       9.949760e+19  4.000000
           ZAMIR INVESTMENT LLC                      9.951604e+19  4.000000
           ZIP-O-LOG MILLS INC                       9.965038e+19  5.000000
           ZK LIVERMORE PROPERTIES, LLC              9.969488e+19  5.000000
           ZMZ, LLC                                  9.969613e+19  4.000000
           ZOREH MARASHI                             5.685696e+19  4.000000
           ZUMA 8TH STREET, LLC                      9.976717e+19  5.000000
           ZUMA TRADING INC                          9.976658e+19  3.000000

                                                                   Downgrade  \
DATE       CUST_NAME                                 FACILITY_NUM
2005-03-31 "CORAM DEO, LLC"                          1.592124e+19        0.0
           "DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB" 2.051581e+19        0.0
           "GREAT WEST PROPERTIES, LLC"              3.341848e+19        0.0
           "MAJ, LLC"                                5.648696e+19        0.0
           1050 BATTERY STREET ASSOCIATES LLC        9.987780e+19        0.0
           10519 E STOCKTON, LLC                     9.987783e+19        0.0
           1060 SHERBOURNE ASSOCIATES LP             9.987785e+19        0.0
           12 STONES FAMILY LIMITED PARTNERSHIP      9.987830e+19        0.0
           120 S DOHENY LLC                          9.987914e+19        0.0
           12K PROPERTIES LLC                        9.987839e+19        0.0
           1340 OLD BAYSHORE ASSOCIATES              9.988132e+19        0.0
           14023 NE 8TH STREET LLC                   9.988593e+19        0.0
           1431 VIA PLATA, LLC                       9.988599e+19        0.0
           144 NORTH SAN MATEO DRIVE LLC             9.988608e+19        0.0
           1550 E MC FADDEN ENTERPRISES              9.988849e+19        0.0
           1634 SW ALDER LLC                         9.988270e+19        0.0
           17 PASTEUR INVESTORS LLC                  9.988901e+19        0.0
           1723 CLOVERFIELD PTNERS LLC               9.988904e+19        0.0
           17422 DERIAN                              9.988906e+19        0.0
           17834 BURBANK INVESTMENTS                 9.988933e+19        0.0
           18061 FITCH L P                           9.988938e+19        0.0
           1811 QUAIL, LLC                           9.988940e+19        0.0
           1873 WP PROPERTIES LLC                    9.989030e+19        0.0
           1950 A KELLOGG AVENUE                     5.793132e+17        0.0
           1988  ABBASSI LIVING TR DATED 4/8/88      2.477465e+17        0.0
           1992 KINCAID TRUST                        9.990123e+19        0.0
           1997 SCHON REVOCABLE TRUST                9.580994e+19        0.0
           1999 K AND P OFFEL REV TRUST              6.673201e+19        0.0
           2000 STEWART REV TRUST                    9.990205e+19        0.0
           2002 DAVIS PROPERTY L P                   9.991648e+19        0.0
...                                                                      ...
2017-12-31 YACHT HARBOR MHP, LLC                     9.918958e+19        0.0
           YAZDANI PROPERTIES, LLC                   9.924259e+19        0.0
           YECHIEL ROSENFELD                         7.960316e+19        0.0
           YEPREMIAN FAMILY DISCLAIMER TRUST         9.928020e+19        0.0
           YESHIVATH TORATH EMETH ACADEMY            9.928097e+19        0.0
           YEUNG AE KIM                              5.091376e+19        0.0
           YIPPEE HI HO CALLE, LLC                   9.928289e+19        0.0
           YOKO NAGATA REVOCABLE TRUST               6.449569e+19        0.8
           YONG JA KIM                               5.091380e+19        0.0
           YOSHIDA REAL ESTATE HOLDINGS, LLC         9.935714e+19        0.0
           YOUNG FAMILY TRUST DATED AUGUST 4, 2011   9.938586e+19        0.0
           YOUNG MOBILE HOME PARK LLC                9.940133e+19        0.0
           YOUNG'S HOLDINGS INC                      9.941714e+19        0.0
           YOURITAN CONSTRUCTION COMPANY             9.942249e+19        0.0
           YS PROPERTIES, LLC                        9.944069e+19        0.0
           YTURRALDE BUILDING, LLC                   9.944095e+19        0.0
           YUAN SHEN                                 8.344497e+19        1.0
                                                     8.344497e+19        0.0
           YULE3.SP.1.LLC                            9.947724e+19        0.0
           YUREN ZHANG                               9.957227e+19        0.0
           YVMHC LLC A CALIFORNIA                    9.948691e+19        0.0
           Z & A ASSOCIATES INC                      9.949226e+19        0.0
           ZADRO PARTNERS, LLC                       9.949760e+19        0.0
           ZAMIR INVESTMENT LLC                      9.951604e+19        0.0
           ZIP-O-LOG MILLS INC                       9.965038e+19        0.0
           ZK LIVERMORE PROPERTIES, LLC              9.969488e+19        0.0
           ZMZ, LLC                                  9.969613e+19        0.0
           ZOREH MARASHI                             5.685696e+19        0.0
           ZUMA 8TH STREET, LLC                      9.976717e+19        0.0
           ZUMA TRADING INC                          9.976658e+19        0.0

                                                                   Downgrade Notch  \
DATE       CUST_NAME                                 FACILITY_NUM
2005-03-31 "CORAM DEO, LLC"                          1.592124e+19              0.0
           "DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB" 2.051581e+19              0.0
           "GREAT WEST PROPERTIES, LLC"              3.341848e+19              0.0
           "MAJ, LLC"                                5.648696e+19              0.0
           1050 BATTERY STREET ASSOCIATES LLC        9.987780e+19              0.0
           10519 E STOCKTON, LLC                     9.987783e+19              0.0
           1060 SHERBOURNE ASSOCIATES LP             9.987785e+19              0.0
           12 STONES FAMILY LIMITED PARTNERSHIP      9.987830e+19              0.0
           120 S DOHENY LLC                          9.987914e+19              0.0
           12K PROPERTIES LLC                        9.987839e+19              0.0
           1340 OLD BAYSHORE ASSOCIATES              9.988132e+19              0.0
           14023 NE 8TH STREET LLC                   9.988593e+19              0.0
           1431 VIA PLATA, LLC                       9.988599e+19              0.0
           144 NORTH SAN MATEO DRIVE LLC             9.988608e+19              0.0
           1550 E MC FADDEN ENTERPRISES              9.988849e+19              0.0
           1634 SW ALDER LLC                         9.988270e+19              0.0
           17 PASTEUR INVESTORS LLC                  9.988901e+19              0.0
           1723 CLOVERFIELD PTNERS LLC               9.988904e+19              0.0
           17422 DERIAN                              9.988906e+19              0.0
           17834 BURBANK INVESTMENTS                 9.988933e+19              0.0
           18061 FITCH L P                           9.988938e+19              0.0
           1811 QUAIL, LLC                           9.988940e+19              0.0
           1873 WP PROPERTIES LLC                    9.989030e+19              0.0
           1950 A KELLOGG AVENUE                     5.793132e+17              0.0
           1988  ABBASSI LIVING TR DATED 4/8/88      2.477465e+17              0.0
           1992 KINCAID TRUST                        9.990123e+19              0.0
           1997 SCHON REVOCABLE TRUST                9.580994e+19              0.0
           1999 K AND P OFFEL REV TRUST              6.673201e+19              0.0
           2000 STEWART REV TRUST                    9.990205e+19              0.0
           2002 DAVIS PROPERTY L P                   9.991648e+19              0.0
...                                                                            ...
2017-12-31 YACHT HARBOR MHP, LLC                     9.918958e+19              0.0
           YAZDANI PROPERTIES, LLC                   9.924259e+19              0.0
           YECHIEL ROSENFELD                         7.960316e+19              0.0
           YEPREMIAN FAMILY DISCLAIMER TRUST         9.928020e+19              0.0
           YESHIVATH TORATH EMETH ACADEMY            9.928097e+19              0.0
           YEUNG AE KIM                              5.091376e+19              0.0
           YIPPEE HI HO CALLE, LLC                   9.928289e+19              0.0
           YOKO NAGATA REVOCABLE TRUST               6.449569e+19              1.2
           YONG JA KIM                               5.091380e+19              0.0
           YOSHIDA REAL ESTATE HOLDINGS, LLC         9.935714e+19              0.0
           YOUNG FAMILY TRUST DATED AUGUST 4, 2011   9.938586e+19              0.0
           YOUNG MOBILE HOME PARK LLC                9.940133e+19              0.0
           YOUNG'S HOLDINGS INC                      9.941714e+19              0.0
           YOURITAN CONSTRUCTION COMPANY             9.942249e+19              0.0
           YS PROPERTIES, LLC                        9.944069e+19              0.0
           YTURRALDE BUILDING, LLC                   9.944095e+19              0.0
           YUAN SHEN                                 8.344497e+19              2.0
                                                     8.344497e+19              0.0
           YULE3.SP.1.LLC                            9.947724e+19              0.0
           YUREN ZHANG                               9.957227e+19              0.0
           YVMHC LLC A CALIFORNIA                    9.948691e+19              0.0
           Z & A ASSOCIATES INC                      9.949226e+19              0.0
           ZADRO PARTNERS, LLC                       9.949760e+19              0.0
           ZAMIR INVESTMENT LLC                      9.951604e+19              0.0
           ZIP-O-LOG MILLS INC                       9.965038e+19              0.0
           ZK LIVERMORE PROPERTIES, LLC              9.969488e+19              0.0
           ZMZ, LLC                                  9.969613e+19              0.0
           ZOREH MARASHI                             5.685696e+19              0.0
           ZUMA 8TH STREET, LLC                      9.976717e+19              0.0
           ZUMA TRADING INC                          9.976658e+19              0.0

                                                                   NET_COMMIT_AMT  \
DATE       CUST_NAME                                 FACILITY_NUM
2005-03-31 "CORAM DEO, LLC"                          1.592124e+19    5.676000e+05
           "DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB" 2.051581e+19    8.131556e+06
           "GREAT WEST PROPERTIES, LLC"              3.341848e+19    5.456056e+05
           "MAJ, LLC"                                5.648696e+19    1.263000e+06
           1050 BATTERY STREET ASSOCIATES LLC        9.987780e+19    3.048930e+06
           10519 E STOCKTON, LLC                     9.987783e+19    3.963909e+06
           1060 SHERBOURNE ASSOCIATES LP             9.987785e+19    2.715611e+06
           12 STONES FAMILY LIMITED PARTNERSHIP      9.987830e+19    2.025248e+06
           120 S DOHENY LLC                          9.987914e+19    1.802838e+06
           12K PROPERTIES LLC                        9.987839e+19    6.309734e+05
           1340 OLD BAYSHORE ASSOCIATES              9.988132e+19    1.044431e+06
           14023 NE 8TH STREET LLC                   9.988593e+19    5.587259e+05
           1431 VIA PLATA, LLC                       9.988599e+19    6.730704e+06
           144 NORTH SAN MATEO DRIVE LLC             9.988608e+19    5.358257e+05
           1550 E MC FADDEN ENTERPRISES              9.988849e+19    7.021508e+05
           1634 SW ALDER LLC                         9.988270e+19    1.178464e+06
           17 PASTEUR INVESTORS LLC                  9.988901e+19    2.595037e+06
           1723 CLOVERFIELD PTNERS LLC               9.988904e+19    4.481224e+06
           17422 DERIAN                              9.988906e+19    8.127320e+06
           17834 BURBANK INVESTMENTS                 9.988933e+19    2.035613e+06
           18061 FITCH L P                           9.988938e+19    2.842245e+06
           1811 QUAIL, LLC                           9.988940e+19    2.850000e+06
           1873 WP PROPERTIES LLC                    9.989030e+19    5.250000e+06
           1950 A KELLOGG AVENUE                     5.793132e+17    1.277419e+05
           1988  ABBASSI LIVING TR DATED 4/8/88      2.477465e+17    1.971134e+06
           1992 KINCAID TRUST                        9.990123e+19    1.081544e+05
           1997 SCHON REVOCABLE TRUST                9.580994e+19    5.170076e+05
           1999 K AND P OFFEL REV TRUST              6.673201e+19    3.254755e+05
           2000 STEWART REV TRUST                    9.990205e+19    9.000000e+05
           2002 DAVIS PROPERTY L P                   9.991648e+19    6.384479e+05
...                                                                           ...
2017-12-31 YACHT HARBOR MHP, LLC                     9.918958e+19    2.672491e+06
           YAZDANI PROPERTIES, LLC                   9.924259e+19    8.373381e+05
           YECHIEL ROSENFELD                         7.960316e+19    8.028064e+05
           YEPREMIAN FAMILY DISCLAIMER TRUST         9.928020e+19    2.344330e+06
           YESHIVATH TORATH EMETH ACADEMY            9.928097e+19    5.092405e+06
           YEUNG AE KIM                              5.091376e+19    1.722004e+06
           YIPPEE HI HO CALLE, LLC                   9.928289e+19    8.809604e+05
           YOKO NAGATA REVOCABLE TRUST               6.449569e+19    1.168964e+06
           YONG JA KIM                               5.091380e+19    2.217899e+06
           YOSHIDA REAL ESTATE HOLDINGS, LLC         9.935714e+19    5.411331e+06
           YOUNG FAMILY TRUST DATED AUGUST 4, 2011   9.938586e+19    9.129412e+05
           YOUNG MOBILE HOME PARK LLC                9.940133e+19    1.549733e+06
           YOUNG'S HOLDINGS INC                      9.941714e+19    5.649676e+06
           YOURITAN CONSTRUCTION COMPANY             9.942249e+19    3.528716e+06
           YS PROPERTIES, LLC                        9.944069e+19    1.989961e+06
           YTURRALDE BUILDING, LLC                   9.944095e+19    5.900470e+05
           YUAN SHEN                                 8.344497e+19    1.919702e+06
                                                     8.344497e+19    4.292902e+06
           YULE3.SP.1.LLC                            9.947724e+19    1.125106e+06
           YUREN ZHANG                               9.957227e+19    9.643488e+05
           YVMHC LLC A CALIFORNIA                    9.948691e+19    2.447101e+06
           Z & A ASSOCIATES INC                      9.949226e+19    2.427111e+06
           ZADRO PARTNERS, LLC                       9.949760e+19    4.979214e+06
           ZAMIR INVESTMENT LLC                      9.951604e+19    1.297024e+06
           ZIP-O-LOG MILLS INC                       9.965038e+19    3.272500e+06
           ZK LIVERMORE PROPERTIES, LLC              9.969488e+19    2.415867e+06
           ZMZ, LLC                                  9.969613e+19    2.107293e+06
           ZOREH MARASHI                             5.685696e+19    1.185458e+06
           ZUMA 8TH STREET, LLC                      9.976717e+19    1.445115e+06
           ZUMA TRADING INC                          9.976658e+19    4.862138e+06


In [9]:
dfFacilityCom2

,DATE,CUST_NAME,FACILITY_NUM,CRR,Downgrade,Downgrade Notch,NET_COMMIT_AMT,OUT_BAL
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6.000000,0.0,0.0,5.676000e+05,5.676000e+05
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5.000000,0.0,0.0,8.131556e+06,8.131556e+06
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6.000000,0.0,0.0,5.456056e+05,5.456056e+05
3,2005-03-31,"""MAJ, LLC""",5.648696e+19,5.000000,0.0,0.0,1.263000e+06,1.263000e+06
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4.000000,0.0,0.0,3.048930e+06,3.048930e+06
5,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5.000000,0.0,0.0,3.963909e+06,3.963909e+06
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6.000000,0.0,0.0,2.715611e+06,2.715611e+06
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4.000000,0.0,0.0,2.025248e+06,2.025248e+06
8,2005-03-31,120 S DOHENY LLC,9.987914e+19,6.000000,0.0,0.0,1.802838e+06,1.802838e+06
9,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6.000000,0.0,0.0,6.309734e+05,6.309734e+05
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4.000000,0.0,0.0,1.044431e+06,1.044431e+06
11,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6.000000,0.0,0.0,5.587259e+05,5.587259e+05
12,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5.000000,0.0,0.0,6.730704e+06,6.730704e+06
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5.000000,0.0,0.0,5.358257e+05,5.358257e+05
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8.000000,0.0,0.0,7.021508e+05,7.021508e+05
15,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6.000000,0.0,0.0,1.178464e+06,1.178464e+06
16,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.000000,0.0,0.0,2.595037e+06,2.595037e+06
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5.000000,0.0,0.0,4.481224e+06,4.481224e+06
18,2005-03-31,17422 DERIAN,9.988906e+19,5.000000,0.0,0.0,8.127320e+06,8.127320e+06
19,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3.000000,0.0,0.0,2.035613e+06,2.035613e+06
20,2005-03-31,18061 FITCH L P,9.988938e+19,5.000000,0.0,0.0,2.842245e+06,2.842245e+06
21,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6.000000,0.0,0.0,2.850000e+06,2.850000e+06
22,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5.000000,0.0,0.0,5.250000e+06,5.250000e+06
23,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6.000000,0.0,0.0,1.277419e+05,1.277419e+05
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,2.477465e+17,5.000000,0.0,0.0,1.971134e+06,1.971134e+06
25,2005-03-31,1992 KINCAID TRUST,9.990123e+19,6.000000,0.0,0.0,1.081544e+05,1.081544e+05
26,2005-03-31,1997 SCHON REVOCABLE TRUST,9.580994e+19,6.000000,0.0,0.0,5.170076e+05,5.170076e+05
27,2005-03-31,1999 K AND P OFFEL REV TRUST,6.673201e+19,1.000000,0.0,0.0,3.254755e+05,3.254755e+05
28,2005-03-31,2000 STEWART REV TRUST,9.990205e+19,6.000000,0.0,0.0,9.000000e+05,9.000000e+05
29,2005-03-31,2002 DAVIS PROPERTY L P,9.991648e+19,6.000000,0.0,0.0,6.384479e+05,6.384479e+05
...,...,...,...,...,...,...,...,...
171093,2017-12-31,"YACHT HARBOR MHP, LLC",9.918958e+19,7.000000,0.0,0.0,2.672491e+06,2.672491e+06
171094,2017-12-31,"YAZDANI PROPERTIES, LLC",9.924259e+19,4.000000,0.0,0.0,8.373381e+05,8.373381e+05
171095,2017-12-31,YECHIEL ROSENFELD,7.960316e+19,3.000000,0.0,0.0,8.028064e+05,8.028064e+05
171096,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,9.928020e+19,4.000000,0.0,0.0,2.344330e+06,2.344330e+06
171097,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,9.928097e+19,7.000000,0.0,0.0,5.092405e+06,5.092405e+06
171098,2017-12-31,YEUNG AE KIM,5.091376e+19,7.000000,0.0,0.0,1.722004e+06,1.722004e+06
171099,2017-12-31,"YIPPEE HI HO CALLE, LLC",9.928289e+19,6.000000,0.0,0.0,8.809604e+05,8.809604e+05
171100,2017-12-31,YOKO NAGATA REVOCABLE TRUST,6.449569e+19,3.000000,0.8,1.2,1.168964e+06,1.168964e+06
171101,2017-12-31,YONG JA KIM,5.091380e+19,4.000000,0.0,0.0,2.217899e+06,2.217899e+06
171102,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",9.935714e+19,5.000000,0.0,0.0,5.411331e+06,5.411331e+06
171103,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",9.938586e+19,4.666667,0.0,0.0,9.129412e+05,9.129412e+05
171104,2017-12-31,YOUNG MOBILE HOME PARK LLC,9.940133e+19,4.000000,0.0,0.0,1.549733e+06,1.549733e+06
171105,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6.000000,0.0,0.0,5.649676e+06,5.649676e+06
171106,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4.000000,0.0,0.0,3.528716e+06,3.528716e+06
171107,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.000000,0.0,0.0,1.989961e+06,1.989961e+06
171108,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6.000000,0.0,0.0,5.900470e+05,5.900470e+05
171109,2017-12-31,YUAN SHEN,8.344497e+19,3.000000,1.0,2.0,1.919702e+06,1.919702e+06
171110,2017-12-31,YUAN SHEN,8.344497e+19,5.000000,0.0,0.0,4.292902e+06,4.292902e+06
171111,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5.000000,0.0,0.0,1.125106e+06,1.125106e+06
171112,2017-12-31,YUREN ZHANG,9.957227e+19,4.000000,0.0,0.0,9.643488e+05,9.643488e+05
171113,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5.000000,0.0,0.0,2.447101e+06,2.447101e+06
171114,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4.000000,0.0,0.0,2.427111e+06,2.427111e+06
171115,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4.000000,0.0,0.0,4.979214e+06,4.979214e+06
171116,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4.000000,0.0,0.0,1.297024e+06,1.297024e+06
171117,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5.000000,0.0,0.0,3.272500e+06,3.272500e+06
171118,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5.000000,0.0,0.0,2.415867e+06,2.415867e+06
171119,2017-12-31,"ZMZ, LLC",9.969613e+19,4.000000,0.0,0.0,2.107293e+06,2.107293e+06
171120,2017-12-31,ZOREH MARASHI,5.685696e+19,4.000000,0.0,0.0,1.185458e+06,1.185458e+06
171121,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5.000000,0.0,0.0,1.445115e+06,1.445115e+06
171122,2017-12-31,ZUMA TRADING INC,9.976658e+19,3.000000,0.0,0.0,4.862138e+06,4.862138e+06

In [45]:
a=(pd.DataFrame(df.groupby(['CUST_NAME','FACILITY_NUM','DATE'])['CRR'].agg(['max']))).reset_index().rename_axis(None,axis=1)##Append this one to the riginal dataset

In [46]:
a

,CUST_NAME,FACILITY_NUM,DATE,max
0,"""CORAM DEO, LLC""",1.592124e+19,2005-03-31,6
1,"""CORAM DEO, LLC""",1.592124e+19,2005-06-30,6
2,"""CORAM DEO, LLC""",1.592124e+19,2005-09-30,6
3,"""CORAM DEO, LLC""",1.592124e+19,2005-12-31,6
4,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,2005-03-31,5
5,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,2005-06-30,5
6,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,2005-09-30,5
7,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,2005-12-31,5
8,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,2006-03-31,5
9,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,2005-03-31,6
10,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,2005-06-30,6
11,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,2005-09-30,6
12,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,2005-12-31,6
13,"""MAJ, LLC""",5.648696e+19,2005-03-31,5
14,"""MAJ, LLC""",5.648696e+19,2005-06-30,5
15,"""MAJ, LLC""",5.648696e+19,2005-09-30,5
16,"""MAJ, LLC""",5.648696e+19,2005-12-31,5
17,"""MAJ, LLC""",5.648696e+19,2006-03-31,5
18,"""MAJ, LLC""",5.648696e+19,2006-06-30,5
19,"""MAJ, LLC""",5.648696e+19,2006-09-30,5
20,"""MAJ, LLC""",5.648696e+19,2006-12-31,5
21,"""MAJ, LLC""",5.648696e+19,2007-03-31,5
22,"""MAJ, LLC""",5.648696e+19,2007-06-30,5
23,"""MAJ, LLC""",5.648696e+19,2007-09-30,5
24,"""MAJ, LLC""",5.648696e+19,2007-12-31,5
25,"""MAJ, LLC""",5.648696e+19,2008-03-31,5
26,"""MAJ, LLC""",5.648696e+19,2008-06-30,5
27,"""MAJ, LLC""",5.648696e+19,2008-09-30,5
28,"""MAJ, LLC""",5.648696e+19,2008-12-31,5
29,"""MAJ, LLC""",5.648696e+19,2009-03-31,5
...,...,...,...,...
171093,ZUMA TRADING INC,9.976658e+19,2010-03-31,3
171094,ZUMA TRADING INC,9.976658e+19,2010-06-30,4
171095,ZUMA TRADING INC,9.976658e+19,2010-09-30,4
171096,ZUMA TRADING INC,9.976658e+19,2010-12-31,4
171097,ZUMA TRADING INC,9.976658e+19,2011-03-31,4
171098,ZUMA TRADING INC,9.976658e+19,2011-06-30,4
171099,ZUMA TRADING INC,9.976658e+19,2011-09-30,4
171100,ZUMA TRADING INC,9.976658e+19,2011-12-31,4
171101,ZUMA TRADING INC,9.976658e+19,2012-03-31,4
171102,ZUMA TRADING INC,9.976658e+19,2012-06-30,3
171103,ZUMA TRADING INC,9.976658e+19,2012-09-30,3
171104,ZUMA TRADING INC,9.976658e+19,2014-03-31,3
171105,ZUMA TRADING INC,9.976658e+19,2014-06-30,3
171106,ZUMA TRADING INC,9.976658e+19,2014-09-30,3
171107,ZUMA TRADING INC,9.976658e+19,2014-12-31,3
171108,ZUMA TRADING INC,9.976658e+19,2015-03-31,3
171109,ZUMA TRADING INC,9.976658e+19,2015-06-30,3
171110,ZUMA TRADING INC,9.976658e+19,2015-09-30,3
171111,ZUMA TRADING INC,9.976658e+19,2015-12-31,3
171112,ZUMA TRADING INC,9.976658e+19,2016-03-31,3
171113,ZVI RYZMAN,8.082878e+19,2005-03-31,4
171114,ZVI RYZMAN,8.082878e+19,2005-06-30,4
171115,ZVI RYZMAN,8.082878e+19,2005-09-30,4
171116,ZVI RYZMAN,8.082878e+19,2005-12-31,4
171117,ZVI RYZMAN,8.082878e+19,2006-03-31,4
171118,ZVI RYZMAN,8.082878e+19,2006-06-30,4
171119,ZVI RYZMAN,8.082878e+19,2006-09-30,4
171120,ZVI RYZMAN,8.082878e+19,2006-12-31,4
171121,ZVI RYZMAN,8.082878e+19,2007-03-31,4
171122,ZVI RYZMAN,8.082878e+19,2007-06-30,4

In [47]:
dfCustMaxCrrCom2=pd.merge(dfFacilityCom2,a,on =['FACILITY_NUM','DATE'],how='left')

In [48]:
dfCustMaxCrrCom2

,DATE,CUST_NAME_x,FACILITY_NUM,CRR,Downgrade,Downgrade Notch,NET_COMMIT_AMT,OUT_BAL,CUST_NAME_y,max
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6.000000,0.0,0.0,5.676000e+05,5.676000e+05,"""CORAM DEO, LLC""",6
1,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6.000000,0.0,0.0,5.676000e+05,5.676000e+05,"CORAM DEO, LLC",6
2,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5.000000,0.0,0.0,8.131556e+06,8.131556e+06,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",5
3,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6.000000,0.0,0.0,5.456056e+05,5.456056e+05,"""GREAT WEST PROPERTIES, LLC""",6
4,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6.000000,0.0,0.0,5.456056e+05,5.456056e+05,"GREAT WEST PROPERTIES, LLC",6
5,2005-03-31,"""MAJ, LLC""",5.648696e+19,5.000000,0.0,0.0,1.263000e+06,1.263000e+06,"""MAJ, LLC""",5
6,2005-03-31,"""MAJ, LLC""",5.648696e+19,5.000000,0.0,0.0,1.263000e+06,1.263000e+06,"MAJ, LLC",5
7,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4.000000,0.0,0.0,3.048930e+06,3.048930e+06,1050 BATTERY STREET ASSOCIATES LLC,4
8,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5.000000,0.0,0.0,3.963909e+06,3.963909e+06,"10519 E STOCKTON, LLC",5
9,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6.000000,0.0,0.0,2.715611e+06,2.715611e+06,1060 SHERBOURNE ASSOCIATES LP,6
10,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4.000000,0.0,0.0,2.025248e+06,2.025248e+06,12 STONES FAMILY LIMITED PARTNERSHIP,4
11,2005-03-31,120 S DOHENY LLC,9.987914e+19,6.000000,0.0,0.0,1.802838e+06,1.802838e+06,120 S DOHENY LLC,6
12,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6.000000,0.0,0.0,6.309734e+05,6.309734e+05,12K PROPERTIES LLC,6
13,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4.000000,0.0,0.0,1.044431e+06,1.044431e+06,1340 OLD BAYSHORE ASSOCIATES,4
14,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6.000000,0.0,0.0,5.587259e+05,5.587259e+05,14023 NE 8TH STREET LLC,6
15,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5.000000,0.0,0.0,6.730704e+06,6.730704e+06,"1431 VIA PLATA, LLC",5
16,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5.000000,0.0,0.0,5.358257e+05,5.358257e+05,144 NORTH SAN MATEO DRIVE LLC,5
17,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8.000000,0.0,0.0,7.021508e+05,7.021508e+05,1550 E MC FADDEN ENTERPRISES,8
18,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6.000000,0.0,0.0,1.178464e+06,1.178464e+06,1634 SW ALDER LLC,6
19,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.000000,0.0,0.0,2.595037e+06,2.595037e+06,17 PASTEUR INVESTORS LLC,5
20,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5.000000,0.0,0.0,4.481224e+06,4.481224e+06,1723 CLOVERFIELD PTNERS LLC,5
21,2005-03-31,17422 DERIAN,9.988906e+19,5.000000,0.0,0.0,8.127320e+06,8.127320e+06,17422 DERIAN,5
22,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3.000000,0.0,0.0,2.035613e+06,2.035613e+06,17834 BURBANK INVESTMENTS,3
23,2005-03-31,18061 FITCH L P,9.988938e+19,5.000000,0.0,0.0,2.842245e+06,2.842245e+06,18061 FITCH L P,5
24,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6.000000,0.0,0.0,2.850000e+06,2.850000e+06,"1811 QUAIL, LLC",6
25,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5.000000,0.0,0.0,5.250000e+06,5.250000e+06,1873 WP PROPERTIES LLC,5
26,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6.000000,0.0,0.0,1.277419e+05,1.277419e+05,1950 A KELLOGG AVENUE,6
27,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,2.477465e+17,5.000000,0.0,0.0,1.971134e+06,1.971134e+06,1988 ABBASSI LIVING TR DATED 4/8/88,5
28,2005-03-31,1992 KINCAID TRUST,9.990123e+19,6.000000,0.0,0.0,1.081544e+05,1.081544e+05,1992 KINCAID TRUST,6
29,2005-03-31,1997 SCHON REVOCABLE TRUST,9.580994e+19,6.000000,0.0,0.0,5.170076e+05,5.170076e+05,1997 SCHON REVOCABLE TRUST,6
...,...,...,...,...,...,...,...,...,...,...
171233,2017-12-31,"YACHT HARBOR MHP, LLC",9.918958e+19,7.000000,0.0,0.0,2.672491e+06,2.672491e+06,"YACHT HARBOR MHP, LLC",7
171234,2017-12-31,"YAZDANI PROPERTIES, LLC",9.924259e+19,4.000000,0.0,0.0,8.373381e+05,8.373381e+05,"YAZDANI PROPERTIES, LLC",4
171235,2017-12-31,YECHIEL ROSENFELD,7.960316e+19,3.000000,0.0,0.0,8.028064e+05,8.028064e+05,YECHIEL ROSENFELD,3
171236,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,9.928020e+19,4.000000,0.0,0.0,2.344330e+06,2.344330e+06,YEPREMIAN FAMILY DISCLAIMER TRUST,4
171237,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,9.928097e+19,7.000000,0.0,0.0,5.092405e+06,5.092405e+06,YESHIVATH TORATH EMETH ACADEMY,7
171238,2017-12-31,YEUNG AE KIM,5.091376e+19,7.000000,0.0,0.0,1.722004e+06,1.722004e+06,YEUNG AE KIM,7
171239,2017-12-31,"YIPPEE HI HO CALLE, LLC",9.928289e+19,6.000000,0.0,0.0,8.809604e+05,8.809604e+05,"YIPPEE HI HO CALLE, LLC",6
171240,2017-12-31,YOKO NAGATA REVOCABLE TRUST,6.449569e+19,3.000000,0.8,1.2,1.168964e+06,1.168964e+06,YOKO NAGATA REVOCABLE TRUST,3
171241,2017-12-31,YONG JA KIM,5.091380e+19,4.000000,0.0,0.0,2.217899e+06,2.217899e+06,YONG JA KIM,4
171242,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",9.935714e+19,5.000000,0.0,0.0,5.411331e+06,5.411331e+06,"YOSHIDA REAL ESTATE HOLDINGS, LLC",5
171243,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",9.938586e+19,4.666667,0.0,0.0,9.129412e+05,9.129412e+05,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",5
171244,2017-12-31,YOUNG MOBILE HOME PARK LLC,9.940133e+19,4.000000,0.0,0.0,1.549733e+06,1.549733e+06,YOUNG MOBILE HOME PARK LLC,4
171245,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6.000000,0.0,0.0,5.649676e+06,5.649676e+06,YOUNG'S HOLDINGS INC,6
171246,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4.000000,0.0,0.0,3.528716e+06,3.528716e+06,YOURITAN CONSTRUCTION COMPANY,4
171247,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.000000,0.0,0.0,1.989961e+06,1.989961e+06,"YS PROPERTIES, LLC",5
171248,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6.000000,0.0,0.0,5.900470e+05,5.900470e+05,"YTURRALDE BUILDING, LLC",6
171249,2017-12-31,YUAN SHEN,8.344497e+19,3.000000,1.0,2.0,1.919702e+06,1.919702e+06,YUAN SHEN,3
171250,2017-12-31,YUAN SHEN,8.344497e+19,5.000000,0.0,0.0,4.292902e+06,4.292902e+06,YUAN SHEN,5
171251,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5.000000,0.0,0.0,1.125106e+06,1.125106e+06,YULE3.SP.1.LLC,5
171252,2017-12-31,YUREN ZHANG,9.957227e+19,4.000000,0.0,0.0,9.643488e+05,9.643488e+05,YUREN ZHANG,4
171253,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5.000000,0.0,0.0,2.447101e+06,2.447101e+06,YVMHC LLC A CALIFORNIA,5
171254,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4.000000,0.0,0.0,2.427111e+06,2.427111e+06,Z & A ASSOCIATES INC,4
171255,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4.000000,0.0,0.0,4.979214e+06,4.979214e+06,"ZADRO PARTNERS, LLC",4
171256,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4.000000,0.0,0.0,1.297024e+06,1.297024e+06,ZAMIR INVESTMENT LLC,4
171257,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5.000000,0.0,0.0,3.272500e+06,3.272500e+06,ZIP-O-LOG MILLS INC,5
171258,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5.000000,0.0,0.0,2.415867e+06,2.415867e+06,"ZK LIVERMORE PROPERTIES, LLC",5
171259,2017-12-31,"ZMZ, LLC",9.969613e+19,4.000000,0.0,0.0,2.107293e+06,2.107293e+06,"ZMZ, LLC",4
171260,2017-12-31,ZOREH MARASHI,5.685696e+19,4.000000,0.0,0.0,1.185458e+06,1.185458e+06,ZOREH MARASHI,4
171261,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5.000000,0.0,0.0,1.445115e+06,1.445115e+06,"ZUMA 8TH STREET, LLC",5
171262,2017-12-31,ZUMA TRADING INC,9.976658e+19,3.000000,0.0,0.0,4.862138e+06,4.862138e+06,ZUMA TRADING INC,3

In [13]:
dfCustMaxCrrCom2.to_excel('dfCustMaxCrrCom2.xlsx', index  = True)   ## Target Variable dataset

#### Analysis for Dongrade Intensity

In [14]:
TESTCustNum=dfCustMaxCrrCom2.groupby(['DATE'])['CUST_NAME'].agg(['count'])

In [15]:
TESTCustNum  ##same

            count
DATE
2005-03-31   2577
2005-06-30   2534
2005-09-30   2501
2005-12-31   4283
2006-03-31   4233
2006-06-30   4235
2006-09-30   4290
2006-12-31   4313
2007-03-31   4331
2007-06-30   4384
2007-09-30   4376
2007-12-31   4469
2008-03-31   4514
2008-06-30   4542
2008-09-30   4506
2008-12-31   4489
2009-03-31   4453
2009-06-30   4360
2009-09-30   4248
2009-12-31   4158
2010-03-31   4080
2010-06-30   4054
2010-09-30   2080
2010-12-31   2024
2011-03-31   2018
2011-06-30   2051
2011-09-30   2109
2011-12-31   2170
2012-03-31   2201
2012-06-30   2104
2012-09-30   2071
2012-12-31   2025
2013-03-31   1971
2013-06-30   2790
2013-09-30   3061
2013-12-31   3008
2014-03-31   2946
2014-06-30   2969
2014-09-30   2988
2014-12-31   3053
2015-03-31   3087
2015-06-30   3102
2015-09-30   3124
2015-12-31   3160
2016-03-31   3226
2016-06-30   3222
2016-09-30   3207
2016-12-31   3180
2017-03-31   3152
2017-06-30   3121
2017-09-30   3041
2017-12-31   2932

In [16]:
TestDowngrade2=dfCustMaxCrrCom2.groupby(['DATE'])['Downgrade'].agg(['mean'])

In [17]:
pd.DataFrame(TestDowngrade2)

                mean
DATE
2005-03-31  0.009960
2005-06-30  0.012628
2005-09-30  0.019059
2005-12-31  0.010079
2006-03-31  0.010040
2006-06-30  0.014522
2006-09-30  0.016162
2006-12-31  0.013216
2007-03-31  0.017740
2007-06-30  0.016842
2007-09-30  0.029220
2007-12-31  0.054737
2008-03-31  0.037605
2008-06-30  0.032089
2008-09-30  0.059242
2008-12-31  0.069418
2009-03-31  0.089072
2009-06-30  0.051865
2009-09-30  0.034323
2009-12-31  0.049033
2010-03-31  0.063329
2010-06-30  0.025294
2010-09-30  0.044671
2010-12-31  0.060282
2011-03-31  0.087611
2011-06-30  0.068594
2011-09-30  0.071815
2011-12-31  0.079608
2012-03-31  0.066124
2012-06-30  0.042228
2012-09-30  0.045791
2012-12-31  0.029623
2013-03-31  0.034347
2013-06-30  0.073602
2013-09-30  0.050074
2013-12-31  0.033134
2014-03-31  0.038640
2014-06-30  0.027190
2014-09-30  0.031983
2014-12-31  0.025596
2015-03-31  0.032631
2015-06-30  0.024017
2015-09-30  0.029786
2015-12-31  0.032395
2016-03-31  0.041569
2016-06-30  0.056926
2016-09-30  0.043070
2016-12-31  0.047804
2017-03-31  0.059524
2017-06-30  0.038342
2017-09-30  0.038231
2017-12-31  0.051167

#### Industry Lookup Table

In [28]:
IndustryLookup=df.loc[:,['CUST_NAME','RE_RISK_PROPERTY_TYPE','RE_STATE_NAME','RE_COUNTY_NAME']]   ##ADDING DATE

In [29]:
IndustryLookup  ###195805 rows

,CUST_NAME,RE_RISK_PROPERTY_TYPE,RE_STATE_NAME,RE_COUNTY_NAME
0,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES
1,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
2,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
3,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
4,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
5,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
6,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
7,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
8,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
9,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
10,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
11,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
12,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
13,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
14,RAY PELLEGRINO TRUST,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
15,RAY PELLEGRINO TRUST,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
16,RAY PELLEGRINO TRUST,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
17,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES
18,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
19,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
20,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
21,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
22,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
23,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
24,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
25,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
26,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
27,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
28,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
29,RAY PELLEGRINO TRUST U/D/O 2/16/89,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
...,...,...,...,...
195775,989 41ST STREET LLC,LAND,CALIFORNIA,ALAMEDA (CA)
195776,989 41ST STREET LLC,LAND,CALIFORNIA,ALAMEDA (CA)
195777,989 41ST STREET LLC,LAND,CALIFORNIA,ALAMEDA (CA)
195778,989 41ST STREET LLC,LAND,CALIFORNIA,ALAMEDA (CA)
195779,989 41ST STREET LLC,LAND,CALIFORNIA,ALAMEDA (CA)
195780,"9925-29 CHANNEL ROAD, LLC",OFFICE,CALIFORNIA,SAN DIEGO (CA)
195781,"9925-29 CHANNEL ROAD, LLC",OFFICE,CALIFORNIA,SAN DIEGO (CA)
195782,"9925-29 CHANNEL ROAD, LLC",OFFICE,CALIFORNIA,SAN DIEGO (CA)
195783,"9925-29 CHANNEL ROAD, LLC",OFFICE,CALIFORNIA,SAN DIEGO (CA)
195784,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195785,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195786,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195787,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195788,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195789,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195790,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195791,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195792,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195793,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195794,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195795,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195796,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195797,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195798,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195799,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195800,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195801,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195802,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195803,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA
195804,953 INDUSTRIAL HOLDINGS LLC,OFFICE,CALIFORNIA,SANTA CLARA

In [30]:
IndLookUpNoDup=IndustryLookup.drop_duplicates()  ##16228 rows

In [31]:
dfCustMaxCrrCom2

,DATE,CUST_NAME,FACILITY_NUM,CRR,Downgrade,Downgrade Notch,NET_COMMIT_AMT,OUT_BAL,max
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6.000000,0.0,0.0,5.676000e+05,5.676000e+05,6
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5.000000,0.0,0.0,8.131556e+06,8.131556e+06,5
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6.000000,0.0,0.0,5.456056e+05,5.456056e+05,6
3,2005-03-31,"""MAJ, LLC""",5.648696e+19,5.000000,0.0,0.0,1.263000e+06,1.263000e+06,5
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4.000000,0.0,0.0,3.048930e+06,3.048930e+06,4
5,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5.000000,0.0,0.0,3.963909e+06,3.963909e+06,5
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6.000000,0.0,0.0,2.715611e+06,2.715611e+06,6
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4.000000,0.0,0.0,2.025248e+06,2.025248e+06,4
8,2005-03-31,120 S DOHENY LLC,9.987914e+19,6.000000,0.0,0.0,1.802838e+06,1.802838e+06,6
9,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6.000000,0.0,0.0,6.309734e+05,6.309734e+05,6
10,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4.000000,0.0,0.0,1.044431e+06,1.044431e+06,4
11,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6.000000,0.0,0.0,5.587259e+05,5.587259e+05,6
12,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5.000000,0.0,0.0,6.730704e+06,6.730704e+06,5
13,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5.000000,0.0,0.0,5.358257e+05,5.358257e+05,5
14,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8.000000,0.0,0.0,7.021508e+05,7.021508e+05,8
15,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6.000000,0.0,0.0,1.178464e+06,1.178464e+06,6
16,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.000000,0.0,0.0,2.595037e+06,2.595037e+06,5
17,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5.000000,0.0,0.0,4.481224e+06,4.481224e+06,5
18,2005-03-31,17422 DERIAN,9.988906e+19,5.000000,0.0,0.0,8.127320e+06,8.127320e+06,5
19,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3.000000,0.0,0.0,2.035613e+06,2.035613e+06,3
20,2005-03-31,18061 FITCH L P,9.988938e+19,5.000000,0.0,0.0,2.842245e+06,2.842245e+06,5
21,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6.000000,0.0,0.0,2.850000e+06,2.850000e+06,6
22,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5.000000,0.0,0.0,5.250000e+06,5.250000e+06,5
23,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6.000000,0.0,0.0,1.277419e+05,1.277419e+05,6
24,2005-03-31,1988 ABBASSI LIVING TR DATED 4/8/88,2.477465e+17,5.000000,0.0,0.0,1.971134e+06,1.971134e+06,5
25,2005-03-31,1992 KINCAID TRUST,9.990123e+19,6.000000,0.0,0.0,1.081544e+05,1.081544e+05,6
26,2005-03-31,1997 SCHON REVOCABLE TRUST,9.580994e+19,6.000000,0.0,0.0,5.170076e+05,5.170076e+05,6
27,2005-03-31,1999 K AND P OFFEL REV TRUST,6.673201e+19,1.000000,0.0,0.0,3.254755e+05,3.254755e+05,1
28,2005-03-31,2000 STEWART REV TRUST,9.990205e+19,6.000000,0.0,0.0,9.000000e+05,9.000000e+05,6
29,2005-03-31,2002 DAVIS PROPERTY L P,9.991648e+19,6.000000,0.0,0.0,6.384479e+05,6.384479e+05,6
...,...,...,...,...,...,...,...,...,...
171093,2017-12-31,"YACHT HARBOR MHP, LLC",9.918958e+19,7.000000,0.0,0.0,2.672491e+06,2.672491e+06,7
171094,2017-12-31,"YAZDANI PROPERTIES, LLC",9.924259e+19,4.000000,0.0,0.0,8.373381e+05,8.373381e+05,4
171095,2017-12-31,YECHIEL ROSENFELD,7.960316e+19,3.000000,0.0,0.0,8.028064e+05,8.028064e+05,3
171096,2017-12-31,YEPREMIAN FAMILY DISCLAIMER TRUST,9.928020e+19,4.000000,0.0,0.0,2.344330e+06,2.344330e+06,4
171097,2017-12-31,YESHIVATH TORATH EMETH ACADEMY,9.928097e+19,7.000000,0.0,0.0,5.092405e+06,5.092405e+06,7
171098,2017-12-31,YEUNG AE KIM,5.091376e+19,7.000000,0.0,0.0,1.722004e+06,1.722004e+06,7
171099,2017-12-31,"YIPPEE HI HO CALLE, LLC",9.928289e+19,6.000000,0.0,0.0,8.809604e+05,8.809604e+05,6
171100,2017-12-31,YOKO NAGATA REVOCABLE TRUST,6.449569e+19,3.000000,0.8,1.2,1.168964e+06,1.168964e+06,3
171101,2017-12-31,YONG JA KIM,5.091380e+19,4.000000,0.0,0.0,2.217899e+06,2.217899e+06,4
171102,2017-12-31,"YOSHIDA REAL ESTATE HOLDINGS, LLC",9.935714e+19,5.000000,0.0,0.0,5.411331e+06,5.411331e+06,5
171103,2017-12-31,"YOUNG FAMILY TRUST DATED AUGUST 4, 2011",9.938586e+19,4.666667,0.0,0.0,9.129412e+05,9.129412e+05,5
171104,2017-12-31,YOUNG MOBILE HOME PARK LLC,9.940133e+19,4.000000,0.0,0.0,1.549733e+06,1.549733e+06,4
171105,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6.000000,0.0,0.0,5.649676e+06,5.649676e+06,6
171106,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4.000000,0.0,0.0,3.528716e+06,3.528716e+06,4
171107,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.000000,0.0,0.0,1.989961e+06,1.989961e+06,5
171108,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6.000000,0.0,0.0,5.900470e+05,5.900470e+05,6
171109,2017-12-31,YUAN SHEN,8.344497e+19,3.000000,1.0,2.0,1.919702e+06,1.919702e+06,3
171110,2017-12-31,YUAN SHEN,8.344497e+19,5.000000,0.0,0.0,4.292902e+06,4.292902e+06,5
171111,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5.000000,0.0,0.0,1.125106e+06,1.125106e+06,5
171112,2017-12-31,YUREN ZHANG,9.957227e+19,4.000000,0.0,0.0,9.643488e+05,9.643488e+05,4
171113,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5.000000,0.0,0.0,2.447101e+06,2.447101e+06,5
171114,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4.000000,0.0,0.0,2.427111e+06,2.427111e+06,4
171115,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4.000000,0.0,0.0,4.979214e+06,4.979214e+06,4
171116,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4.000000,0.0,0.0,1.297024e+06,1.297024e+06,4
171117,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5.000000,0.0,0.0,3.272500e+06,3.272500e+06,5
171118,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5.000000,0.0,0.0,2.415867e+06,2.415867e+06,5
171119,2017-12-31,"ZMZ, LLC",9.969613e+19,4.000000,0.0,0.0,2.107293e+06,2.107293e+06,4
171120,2017-12-31,ZOREH MARASHI,5.685696e+19,4.000000,0.0,0.0,1.185458e+06,1.185458e+06,4
171121,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5.000000,0.0,0.0,1.445115e+06,1.445115e+06,5
171122,2017-12-31,ZUMA TRADING INC,9.976658e+19,3.000000,0.0,0.0,4.862138e+06,4.862138e+06,3

In [32]:
dfCrrIndustry=pd.merge(dfCustMaxCrrCom2,IndLookUpNoDup,on =['CUST_NAME'],how='left')

In [33]:
dfCrrIndustry

,DATE,CUST_NAME,FACILITY_NUM,CRR,Downgrade,Downgrade Notch,NET_COMMIT_AMT,OUT_BAL,max,RE_RISK_PROPERTY_TYPE,RE_STATE_NAME,RE_COUNTY_NAME
0,2005-03-31,"""CORAM DEO, LLC""",1.592124e+19,6.0,0.0,0.0,567600.000,567600.000,6,INDUSTRIAL,CALIFORNIA,NaN
1,2005-03-31,"""DP INDUSTRIAL LLC, A DELAWARE LTD. LIAB""",2.051581e+19,5.0,0.0,0.0,8131556.000,8131556.000,5,INDUSTRIAL,NaN,NaN
2,2005-03-31,"""GREAT WEST PROPERTIES, LLC""",3.341848e+19,6.0,0.0,0.0,545605.610,545605.610,6,INDUSTRIAL,CALIFORNIA,NaN
3,2005-03-31,"""MAJ, LLC""",5.648696e+19,5.0,0.0,0.0,1263000.000,1263000.000,5,INDUSTRIAL,CALIFORNIA,NaN
4,2005-03-31,1050 BATTERY STREET ASSOCIATES LLC,9.987780e+19,4.0,0.0,0.0,3048930.400,3048930.400,4,OFFICE,CALIFORNIA,SAN FRANCISCO
5,2005-03-31,"10519 E STOCKTON, LLC",9.987783e+19,5.0,0.0,0.0,3963908.940,3963908.940,5,INDUSTRIAL,CALIFORNIA,SACRAMENTO
6,2005-03-31,1060 SHERBOURNE ASSOCIATES LP,9.987785e+19,6.0,0.0,0.0,2715611.040,2715611.040,6,APARTMENT,CALIFORNIA,ORANGE
7,2005-03-31,12 STONES FAMILY LIMITED PARTNERSHIP,9.987830e+19,4.0,0.0,0.0,2025247.720,2025247.720,4,INDUSTRIAL,CALIFORNIA,ORANGE
8,2005-03-31,120 S DOHENY LLC,9.987914e+19,6.0,0.0,0.0,1802837.620,1802837.620,6,OFFICE,CALIFORNIA,LOS ANGELES
9,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6.0,0.0,0.0,630973.450,630973.450,6,RETAIL,CALIFORNIA,LOS ANGELES
10,2005-03-31,12K PROPERTIES LLC,9.987839e+19,6.0,0.0,0.0,630973.450,630973.450,6,OFFICE,CALIFORNIA,LOS ANGELES
11,2005-03-31,1340 OLD BAYSHORE ASSOCIATES,9.988132e+19,4.0,0.0,0.0,1044430.860,1044430.860,4,OFFICE,CALIFORNIA,SAN MATEO
12,2005-03-31,14023 NE 8TH STREET LLC,9.988593e+19,6.0,0.0,0.0,558725.940,558725.940,6,OFFICE,WASHINGTON,KING
13,2005-03-31,"1431 VIA PLATA, LLC",9.988599e+19,5.0,0.0,0.0,6730704.370,6730704.370,5,INDUSTRIAL,CALIFORNIA,LOS ANGELES
14,2005-03-31,144 NORTH SAN MATEO DRIVE LLC,9.988608e+19,5.0,0.0,0.0,535825.720,535825.720,5,OFFICE,CALIFORNIA,SAN MATEO
15,2005-03-31,1550 E MC FADDEN ENTERPRISES,9.988849e+19,8.0,0.0,0.0,702150.770,702150.770,8,INDUSTRIAL,CALIFORNIA,ORANGE
16,2005-03-31,1634 SW ALDER LLC,9.988270e+19,6.0,0.0,0.0,1178464.440,1178464.440,6,RETAIL,OREGON,MULTHOMAH
17,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.0,0.0,0.0,2595036.785,2595036.785,5,INDUSTRIAL,CALIFORNIA,ORANGE
18,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.0,0.0,0.0,2595036.785,2595036.785,5,OTHER REAL ESTATE SECURED,CALIFORNIA,ORANGE
19,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.0,0.0,0.0,2595036.785,2595036.785,5,NaN,CALIFORNIA,NaN
20,2005-03-31,17 PASTEUR INVESTORS LLC,9.988901e+19,5.0,0.0,0.0,2595036.785,2595036.785,5,NaN,CALIFORNIA,ORANGE
21,2005-03-31,1723 CLOVERFIELD PTNERS LLC,9.988904e+19,5.0,0.0,0.0,4481223.550,4481223.550,5,OFFICE,CALIFORNIA,LOS ANGELES
22,2005-03-31,17422 DERIAN,9.988906e+19,5.0,0.0,0.0,8127319.970,8127319.970,5,INDUSTRIAL,CALIFORNIA,ORANGE
23,2005-03-31,17834 BURBANK INVESTMENTS,9.988933e+19,3.0,0.0,0.0,2035612.970,2035612.970,3,APARTMENT,CALIFORNIA,VENTURA
24,2005-03-31,18061 FITCH L P,9.988938e+19,5.0,0.0,0.0,2842244.700,2842244.700,5,OFFICE,CALIFORNIA,ORANGE
25,2005-03-31,18061 FITCH L P,9.988938e+19,5.0,0.0,0.0,2842244.700,2842244.700,5,OTHER REAL ESTATE SECURED,CALIFORNIA,ORANGE
26,2005-03-31,"1811 QUAIL, LLC",9.988940e+19,6.0,0.0,0.0,2850000.000,2850000.000,6,OFFICE,CALIFORNIA,ORANGE
27,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5.0,0.0,0.0,5250000.000,5250000.000,5,RETAIL,CALIFORNIA,LOS ANGELES
28,2005-03-31,1873 WP PROPERTIES LLC,9.989030e+19,5.0,0.0,0.0,5250000.000,5250000.000,5,RETAIL,CALIFORNIA,LOS ANGELES (CA)
29,2005-03-31,1950 A KELLOGG AVENUE,5.793132e+17,6.0,0.0,0.0,127741.930,127741.930,6,OFFICE,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
295396,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6.0,0.0,0.0,5649675.805,5649675.805,6,INDUSTRIAL,CALIFORNIA,ALAMEDA (CA)
295397,2017-12-31,YOUNG'S HOLDINGS INC,9.941714e+19,6.0,0.0,0.0,5649675.805,5649675.805,6,INDUSTRIAL,HAWAII,HONOLULU (HI)
295398,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4.0,0.0,0.0,3528716.080,3528716.080,4,RETAIL,CALIFORNIA,SANTA CLARA
295399,2017-12-31,YOURITAN CONSTRUCTION COMPANY,9.942249e+19,4.0,0.0,0.0,3528716.080,3528716.080,4,RETAIL,CALIFORNIA,SANTA CLARA (CA)
295400,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.0,0.0,0.0,1989960.590,1989960.590,5,APARTMENT,CALIFORNIA,LOS ANGELES
295401,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.0,0.0,0.0,1989960.590,1989960.590,5,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
295402,2017-12-31,"YS PROPERTIES, LLC",9.944069e+19,5.0,0.0,0.0,1989960.590,1989960.590,5,RETAIL,CALIFORNIA,VENTURA (CA)
295403,2017-12-31,"YTURRALDE BUILDING, LLC",9.944095e+19,6.0,0.0,0.0,590047.040,590047.040,6,INDUSTRIAL,CALIFORNIA,SAN DIEGO (CA)
295404,2017-12-31,YUAN SHEN,8.344497e+19,3.0,1.0,2.0,1919701.680,1919701.680,3,APARTMENT,CALIFORNIA,SAN DIEGO
295405,2017-12-31,YUAN SHEN,8.344497e+19,3.0,1.0,2.0,1919701.680,1919701.680,3,APARTMENT,CALIFORNIA,SAN DIEGO (CA)
295406,2017-12-31,YUAN SHEN,8.344497e+19,5.0,0.0,0.0,4292901.620,4292901.620,5,APARTMENT,CALIFORNIA,SAN DIEGO
295407,2017-12-31,YUAN SHEN,8.344497e+19,5.0,0.0,0.0,4292901.620,4292901.620,5,APARTMENT,CALIFORNIA,SAN DIEGO (CA)
295408,2017-12-31,YULE3.SP.1.LLC,9.947724e+19,5.0,0.0,0.0,1125105.660,1125105.660,5,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
295409,2017-12-31,YUREN ZHANG,9.957227e+19,4.0,0.0,0.0,964348.840,964348.840,4,APARTMENT,CALIFORNIA,SAN DIEGO (CA)
295410,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5.0,0.0,0.0,2447100.590,2447100.590,5,APARTMENT,CALIFORNIA,SAN BERNARDINO
295411,2017-12-31,YVMHC LLC A CALIFORNIA,9.948691e+19,5.0,0.0,0.0,2447100.590,2447100.590,5,APARTMENT,CALIFORNIA,SAN BERNARDINO (CA)
295412,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4.0,0.0,0.0,2427110.770,2427110.770,4,APARTMENT,CALIFORNIA,LOS ANGELES
295413,2017-12-31,Z & A ASSOCIATES INC,9.949226e+19,4.0,0.0,0.0,2427110.770,2427110.770,4,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
295414,2017-12-31,"ZADRO PARTNERS, LLC",9.949760e+19,4.0,0.0,0.0,4979214.170,4979214.170,4,INDUSTRIAL,CALIFORNIA,ORANGE (CA)
295415,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4.0,0.0,0.0,1297023.540,1297023.540,4,APARTMENT,CALIFORNIA,LOS ANGELES
295416,2017-12-31,ZAMIR INVESTMENT LLC,9.951604e+19,4.0,0.0,0.0,1297023.540,1297023.540,4,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
295417,2017-12-31,ZIP-O-LOG MILLS INC,9.965038e+19,5.0,0.0,0.0,3272500.000,3272500.000,5,LAND,OREGON,LANE (OR)
295418,2017-12-31,"ZK LIVERMORE PROPERTIES, LLC",9.969488e+19,5.0,0.0,0.0,2415867.480,2415867.480,5,INDUSTRIAL,CALIFORNIA,ALAMEDA (CA)
295419,2017-12-31,"ZMZ, LLC",9.969613e+19,4.0,0.0,0.0,2107293.390,2107293.390,4,APARTMENT,CALIFORNIA,LOS ANGELES
295420,2017-12-31,"ZMZ, LLC",9.969613e+19,4.0,0.0,0.0,2107293.390,2107293.390,4,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
295421,2017-12-31,ZOREH MARASHI,5.685696e+19,4.0,0.0,0.0,1185458.470,1185458.470,4,APARTMENT,CALIFORNIA,LOS ANGELES
295422,2017-12-31,ZOREH MARASHI,5.685696e+19,4.0,0.0,0.0,1185458.470,1185458.470,4,APARTMENT,CALIFORNIA,LOS ANGELES (CA)
295423,2017-12-31,"ZUMA 8TH STREET, LLC",9.976717e+19,5.0,0.0,0.0,1445114.680,1445114.680,5,INDUSTRIAL,CALIFORNIA,ORANGE (CA)
295424,2017-12-31,ZUMA TRADING INC,9.976658e+19,3.0,0.0,0.0,4862138.210,4862138.210,3,APARTMENT,CALIFORNIA,SAN DIEGO
295425,2017-12-31,ZUMA TRADING INC,9.976658e+19,3.0,0.0,0.0,4862138.210,4862138.210,3,APARTMENT,CALIFORNIA,SAN DIEGO (CA)

In [ ]:
dfCrrIndustry

#### Calculate downgrade intensity from target full

In [204]:
customercounts=targetfull.groupby(['DATE'])['CUST_NAME'].agg(['count'])

In [205]:
customercounts

            count
DATE
2005-03-31   2884
2005-06-30   2853
2005-09-30   2819
2005-12-31   4882
2006-03-31   4838
2006-06-30   4837
2006-09-30   4880
2006-12-31   4916
2007-03-31   4921
2007-06-30   4969
2007-09-30   4972
2007-12-31   5061
2008-03-31   5111
2008-06-30   5133
2008-09-30   5094
2008-12-31   5067
2009-03-31   5022
2009-06-30   4881
2009-09-30   4741
2009-12-31   4642
2010-03-31   4560
2010-06-30   4533
2010-09-30   2455
2010-12-31   2409
2011-03-31   2400
2011-06-30   2438
2011-09-30   2487
2011-12-31   2554
2012-03-31   2586
2012-06-30   2493
2012-09-30   2460
2012-12-31   2396
2013-03-31   2325
2013-06-30   3320
2013-09-30   3601
2013-12-31   3531
2014-03-31   3459
2014-06-30   3465
2014-09-30   3476
2014-12-31   3536
2015-03-31   3563
2015-06-30   3573
2015-09-30   3587
2015-12-31   3598
2016-03-31   3655
2016-06-30   3656
2016-09-30   3633
2016-12-31   3594
2017-03-31   3571
2017-06-30   3544
2017-09-30   3467
2017-12-31   3335

In [206]:
downgradepercent=targetfull.groupby(['DATE'])['DowngradeMax'].agg(['mean'])

In [207]:
downgradepercent

                mean
DATE
2005-03-31  0.000000
2005-06-30  0.009460
2005-09-30  0.010284
2005-12-31  0.008601
2006-03-31  0.008679
2006-06-30  0.008061
2006-09-30  0.010449
2006-12-31  0.013626
2007-03-31  0.010158
2007-06-30  0.012676
2007-09-30  0.012266
2007-12-31  0.020150
2008-03-31  0.039515
2008-06-30  0.029801
2008-09-30  0.025319
2008-12-31  0.046961
2009-03-31  0.059327
2009-06-30  0.079680
2009-09-30  0.046816
2009-12-31  0.031445
2010-03-31  0.043412
2010-06-30  0.054698
2010-09-30  0.039919
2010-12-31  0.037360
2011-03-31  0.050000
2011-06-30  0.070550
2011-09-30  0.055086
2011-12-31  0.058340
2012-03-31  0.065739
2012-06-30  0.054152
2012-09-30  0.032520
2012-12-31  0.034641
2013-03-31  0.022366
2013-06-30  0.021386
2013-09-30  0.053596
2013-12-31  0.043047
2014-03-31  0.026308
2014-06-30  0.030303
2014-09-30  0.020713
2014-12-31  0.025735
2015-03-31  0.021050
2015-06-30  0.024629
2015-09-30  0.017285
2015-12-31  0.022790
2016-03-31  0.024077
2016-06-30  0.032823
2016-09-30  0.044041
2016-12-31  0.037563
2017-03-31  0.038645
2017-06-30  0.050790
2017-09-30  0.032593
2017-12-31  0.032084