In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import datetime
%matplotlib inline

In [2]:
os.chdir("Updated Material")

In [3]:
dfVariable=pd.read_excel("CRE Property Index Components.xlsx")

In [4]:
dfVariable

,Geography_Code,Geography_Name,Property_Code,Property_Name,Variable_Name,Variable_Description,_1982Q1,_1982Q2,_1982Q3,_1982Q4,...,_2016Q2,_2016Q3,_2016Q4,_2017Q1,_2017Q2,_2017Q3,_2017Q4,_2018Q1,_2018Q2,_2018Q4
0,ATLNA,Atlanta,APT0,Apartment,2+ Unit Permitting,Multifamily permit issuance,NaN,NaN,NaN,NaN,...,4003.000000,1605.000000,3387.000000,3080.000000,1036.000000,2667.000000,1258.000000,3380.000000,2465.000000,1767.864693
1,ATLNA,Atlanta,APT0,Apartment,Cap Rate Spread,Cap Rate minus 10y Tbond yield; 12-month trailing,NaN,NaN,NaN,NaN,...,0.040192,0.040433,0.039483,0.037375,0.037200,0.035200,0.035600,0.034708,0.031467,0.028200
2,ATLNA,Atlanta,APT0,Apartment,Census Vacancy Rate,Small sample of all units,NaN,NaN,NaN,NaN,...,0.076000,0.057000,0.064000,0.046000,0.071000,0.073000,0.088000,0.083000,0.054000,0.085000
3,ATLNA,Atlanta,APT0,Apartment,Employ. Growth,Total non-farm payrolls,NaN,NaN,NaN,NaN,...,0.029140,0.035507,0.029706,0.028790,0.025523,0.018522,0.015787,0.017412,0.018848,0.021768
4,ATLNA,Atlanta,APT0,Apartment,Excess Return,Return minus 10-Year Treasure bond yield,NaN,NaN,NaN,NaN,...,0.137750,0.114150,0.094875,0.083800,0.074775,0.070375,0.067075,0.067975,0.071275,0.071275
5,ATLNA,Atlanta,APT0,Apartment,Inst. Vacancy Rate,Prof. managed investment-grade units,NaN,NaN,NaN,NaN,...,0.049000,0.050000,0.054000,0.055000,0.054000,0.056000,0.059000,0.059000,0.057000,0.061408
6,ATLNA,Atlanta,APT0,Apartment,Rent Growth,Prof. managed investment-grade units,NaN,NaN,NaN,NaN,...,0.083137,0.075964,0.065665,0.051478,0.055005,0.045225,0.042288,0.046167,0.040677,0.046632
7,ATLNA,Atlanta,APT0,Apartment,Trans. Vol. (Bil. $),Billions of USD,NaN,NaN,NaN,NaN,...,6.818899,6.889640,8.780241,8.373011,8.766741,8.706353,7.702654,8.295973,7.546590,7.546590
8,BOSTN,Boston,APT0,Apartment,2+ Unit Permitting,Multifamily permit issuance,NaN,NaN,NaN,NaN,...,1795.000000,2656.000000,2212.000000,2169.000000,2085.000000,2659.000000,2813.000000,2275.000000,3150.000000,2660.867777
9,BOSTN,Boston,APT0,Apartment,Cap Rate Spread,Cap Rate minus 10y Tbond yield; 12-month trailing,NaN,NaN,NaN,NaN,...,0.027292,0.029533,0.033283,0.033875,0.033700,0.029000,0.026800,0.025408,0.023267,0.020000
10,BOSTN,Boston,APT0,Apartment,Census Vacancy Rate,Small sample of all units,NaN,NaN,NaN,NaN,...,0.034000,0.033000,0.048000,0.055000,0.039000,0.041000,0.056000,0.052000,0.033000,0.052000
11,BOSTN,Boston,APT0,Apartment,Employ. Growth,Total non-farm payrolls,NaN,NaN,NaN,NaN,...,0.015185,0.024025,0.015521,0.013779,0.015733,0.008831,0.008895,0.008936,0.019308,0.014496
12,BOSTN,Boston,APT0,Apartment,Excess Return,Return minus 10-Year Treasure bond yield,NaN,NaN,NaN,NaN,...,0.100000,0.095975,0.088350,0.076500,0.069800,0.062900,0.058475,0.057850,0.053975,0.053975
13,BOSTN,Boston,APT0,Apartment,Inst. Vacancy Rate,Prof. managed investment-grade units,NaN,NaN,NaN,NaN,...,0.031400,0.033200,0.034400,0.032300,0.032300,0.035800,0.038900,0.038500,0.036300,0.040071
14,BOSTN,Boston,APT0,Apartment,Rent Growth,Prof. managed investment-grade units,NaN,NaN,NaN,NaN,...,0.058883,0.044687,0.026575,0.017023,0.025665,0.021388,0.027804,0.030607,0.035218,0.037853
15,BOSTN,Boston,APT0,Apartment,Trans. Vol. (Bil. $),Billions of USD,NaN,NaN,NaN,NaN,...,3.616579,3.336021,2.807549,2.188166,2.386581,3.094126,2.880736,3.161469,2.737969,2.737969
16,CHICG,Chicago,APT0,Apartment,2+ Unit Permitting,Multifamily permit issuance,NaN,NaN,NaN,NaN,...,1768.000000,3215.000000,3315.000000,1955.000000,4957.000000,3178.000000,3480.000000,1173.000000,2883.000000,2436.256448
17,CHICG,Chicago,APT0,Apartment,Cap Rate Spread,Cap Rate minus 10y Tbond yield; 12-month trailing,NaN,NaN,NaN,NaN,...,0.039092,0.041433,0.041283,0.038275,0.036200,0.034400,0.033700,0.032508,0.029767,0.026500
18,CHICG,Chicago,APT0,Apartment,Census Vacancy Rate,Small sample of all units,NaN,NaN,NaN,NaN,...,0.053000,0.075000,0.076000,0.067000,0.080000,0.085000,0.049000,0.090000,0.069000,0.074000
19,CHICG,Chicago,APT0,Apartment,Employ. Growth,Total non-farm payrolls,NaN,NaN,NaN,NaN,...,0.010566,0.014141,0.009458,0.012206,0.011344,0.007101,0.003561,0.005285,0.009491,0.005416
20,CHICG,Chicago,APT0,Apartment,Excess Return,Return minus 10-Year Treasure bond yield,NaN,NaN,NaN,NaN,...,0.095500,0.081150,0.068300,0.056550,0.046075,0.038100,0.031850,0.027425,0.025300,0.025300
21,CHICG,Chicago,APT0,Apartment,Inst. Vacancy Rate,Prof. managed investment-grade units,NaN,NaN,NaN,NaN,...,0.042000,0.044000,0.047000,0.046000,0.047000,0.052000,0.055000,0.055000,0.051000,0.057245
22,CHICG,Chicago,APT0,Apartment,Rent Growth,Prof. managed investment-grade units,NaN,NaN,NaN,NaN,...,0.055414,0.047558,0.039975,0.028757,0.034633,0.033110,0.027708,0.027483,0.028912,0.035862
23,CHICG,Chicago,APT0,Apartment,Trans. Vol. (Bil. $),Billions of USD,NaN,NaN,NaN,NaN,...,3.793390,3.872267,4.257997,4.122700,4.043211,4.634817,4.872132,4.864531,4.918791,4.918791
24,DALLS,Dallas,APT0,Apartment,2+ Unit Permitting,Multifamily permit issuance,NaN,NaN,NaN,NaN,...,4674.000000,5651.000000,4742.000000,6900.000000,4197.000000,4683.000000,6055.000000,2915.000000,7586.000000,5268.834440
25,DALLS,Dallas,APT0,Apartment,Cap Rate Spread,Cap Rate minus 10y Tbond yield; 12-month trailing,NaN,NaN,NaN,NaN,...,0.041292,0.040233,0.039683,0.038975,0.037200,0.035200,0.032100,0.029708,0.027567,0.024300
26,DALLS,Dallas,APT0,Apartment,Census Vacancy Rate,Small sample of all units,NaN,NaN,NaN,NaN,...,0.057000,0.072000,0.092000,0.064000,0.080000,0.074000,0.066000,0.058000,0.078000,0.078000
27,DALLS,Dallas,APT0,Apartment,Employ. Growth,Total non-farm payrolls,NaN,NaN,NaN,NaN,...,0.034132,0.038970,0.037099,0.032060,0.029935,0.024263,0.025446,0.032224,0.034496,0.031844
28,DALLS,Dallas,APT0,Apartment,Excess Return,Return minus 10-Year Treasure bond yield,NaN,NaN,NaN,NaN,...,0.098050,0.085075,0.077475,0.071650,0.066900,0.064625,0.058275,0.053450,0.047050,0.047050
29,DALLS,Dallas,APT0,Apartment,Inst. Vacancy Rate,Prof. managed investment-grade units,NaN,NaN,NaN,NaN,...,0.040000,0.043000,0.044000,0.044000,0.045000,0.050000,0.055000,0.057000,0.055000,0.059327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,SEATL,Seattle,RET0,Retail,Const. Deliv. (Thous. SF),Put-in-place,NaN,NaN,NaN,NaN,...,NaN,NaN,278.600000,NaN,NaN,NaN,575.000000,NaN,NaN,620.000000
434,SEATL,Seattle,RET0,Retail,Excess Return,Return minus 10-Year Treasure bond yield,NaN,NaN,NaN,NaN,...,0.117675,0.116850,0.114575,0.102725,0.092050,0.082250,0.071850,0.062300,0.053050,0.053050
435,SEATL,Seattle,RET0,Retail,Trans. Vol. (Bil. $),Billions of USD,NaN,NaN,NaN,NaN,...,1.027785,0.891318,1.025185,0.980052,0.906449,1.003297,0.877829,1.038641,1.224054,1.224054
436,SEATL,Seattle,RET0,Retail,Vacancy Rate,Percent,NaN,NaN,NaN,NaN,...,NaN,NaN,0.048500,NaN,NaN,NaN,0.048976,NaN,NaN,0.046630
437,SFRAN,San Francisco,RET0,Retail,Cap Rate Spread,Cap Rate minus 10y Tbond yield; 12-month trailing,NaN,NaN,NaN,NaN,...,0.032092,0.036833,0.035083,0.026775,0.025500,0.023800,0.017100,0.015908,0.018267,0.015850
438,SFRAN,San Francisco,RET0,Retail,Const. Deliv. (Thous. SF),Put-in-place,NaN,NaN,NaN,NaN,...,NaN,NaN,47.000000,NaN,NaN,NaN,279.100000,NaN,NaN,100.000000
439,SFRAN,San Francisco,RET0,Retail,Excess Return,Return minus 10-Year Treasure bond yield,NaN,NaN,NaN,NaN,...,0.122725,0.115500,0.102225,0.091675,0.087550,0.082225,0.081125,0.081150,0.063500,0.063500
440,SFRAN,San Francisco,RET0,Retail,Rent Growth,Percent,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.020594,NaN,NaN,NaN,0.036199,NaN,NaN,0.035000
441,SFRAN,San Francisco,RET0,Retail,Trans. Vol. (Bil. $),Billions of USD,NaN,NaN,NaN,NaN,...,0.888499,0.677585,0.880037,1.973235,1.867092,1.786108,1.637373,0.524416,0.734318,0.734318
442,SFRAN,San Francisco,RET0,Retail,Vacancy Rate,Percent,NaN,NaN,NaN,NaN,...,NaN,NaN,0.016326,NaN,NaN,NaN,0.017535,NaN,NaN,0.017162
443,SJOSE,San Jose,RET0,Retail,Cap Rate Spread,Cap Rate minus 10y Tbond yield; 12-month trailing,NaN,NaN,NaN,NaN,...,0.042192,0.035033,0.032283,0.028175,0.025400,0.022200,0.024400,0.027308,0.025667,0.023250
444,SJOSE,San Jose,RET0,Retail,Const. Deliv. (Thous. SF),Put-in-place,NaN,NaN,NaN,NaN,...,NaN,NaN,596.800000,NaN,NaN,NaN,578.100000,NaN,NaN,450.000000
445,SJOSE,San Jose,RET0,Retail,Excess Return,Return minus 10-Year Treasure bond yield,NaN,NaN,NaN,NaN,...,0.087175,0.099700,0.107250,0.106350,0.088925,0.071875,0.060000,0.054275,0.056500,0.056500
446,SJOSE,San Jose,RET0,Retail,Rent Growth,Percent,NaN,NaN,NaN,NaN,...,NaN,NaN,0.007673,NaN,NaN,NaN,0.008529,NaN,NaN,0.015000
447,SJOSE,San Jose,RET0,Retail,Trans. Vol. (Bil. $),Billions of USD,NaN,NaN,NaN,NaN,...,0.679153,0.777317,0.758635,0.543684,0.431440,0.220618,0.223362,0.288432,1.169582,1.169582
448,SJOSE,San Jose,RET0,Retail,Vacancy Rate,Percent,NaN,NaN,NaN,NaN,...,NaN,NaN,0.091676,NaN,NaN,NaN,0.079568,NaN,NaN,0.077628
449,USTOT,United States,RET0,Retail,Cap Rate Spread,Cap Rate minus 10y Tbond yield; 12-month trailing,NaN,NaN,NaN,NaN,...,0.027467,0.029667,0.026100,0.021167,0.023567,0.021967,0.023500,0.017000,0.017300,0.018350
450,USTOT,United States,RET0,Retail,Const. Deliv. (Bil. 09 $),"Put-in-place, 2009 USD",NaN,NaN,NaN,NaN,...,31.861524,33.845447,35.197105,34.047133,35.280613,33.572165,32.419337,33.149174,31.998994,32.511042
451,USTOT,United States,RET0,Retail,Excess Return,Return minus 10-Year Treasure bond yield,NaN,NaN,NaN,NaN,...,0.128700,0.120350,0.105050,0.091350,0.078450,0.066200,0.057675,0.049950,0.042475,0.016696
452,USTOT,United States,RET0,Retail,Mall Rent Growth,Percent,NaN,NaN,NaN,NaN,...,0.026500,0.028500,0.026000,0.025500,0.024500,0.025000,0.024000,0.024000,0.024000,0.022000
453,USTOT,United States,RET0,Retail,Power Rent Growth,NaN,NaN,NaN,NaN,NaN,...,0.020000,0.019600,0.019600,0.019600,0.019600,0.020000,0.017000,0.017000,0.016000,0.015000
454,USTOT,United States,RET0,Retail,Retail Sales Growth,Retail Sales ex. Auto,NaN,NaN,NaN,NaN,...,0.025452,0.020392,0.030301,0.047925,0.036792,0.043185,0.058027,0.049211,0.062204,0.066824
455,USTOT,United States,RET0,Retail,Strip Rent Growth,NaN,NaN,NaN,NaN,NaN,...,0.018900,0.018900,0.018000,0.018300,0.017200,0.016900,0.018000,0.018000,0.017000,0.017000
456,USTOT,United States,RET0,Retail,Trans. Vol. (Bil. $),Billions of USD,NaN,NaN,NaN,NaN,...,73.969499,72.964108,68.003049,67.469527,63.034464,58.461894,55.240300,49.994289,56.051777,56.051777
457,USTOT,United States,RET0,Retail,Vacancy Rate,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.071000,NaN,NaN,NaN,0.070000,NaN,NaN,0.069000
458,WASDC,Washington,RET0,Retail,Cap Rate Spread,Cap Rate minus 10y Tbond yield; 12-month trailing,NaN,NaN,NaN,NaN,...,0.038992,0.047133,0.050183,0.039975,0.041600,0.041300,0.041600,0.043408,0.040067,0.037650
459,WASDC,Washington,RET0,Retail,Const. Deliv. (Thous. SF),Put-in-place,NaN,NaN,NaN,NaN,...,NaN,NaN,1200.000000,NaN,NaN,NaN,1200.000000,NaN,NaN,1400.000000
460,WASDC,Washington,RET0,Retail,Excess Return,Return minus 10-Year Treasure bond yield,NaN,NaN,NaN,NaN,...,0.141050,0.131700,0.113400,0.095475,0.077975,0.060300,0.051700,0.044025,0.037225,0.037225
461,WASDC,Washington,RET0,Retail,Trans. Vol. (Bil. $),Billions of USD,NaN,NaN,NaN,NaN,...,2.364969,2.248226,2.111142,2.037753,1.801094,1.707666,1.478779,1.238865,1.812786,1.812786
462,WASDC,Washington,RET0,Retail,Vacancy Rate,Percent,NaN,NaN,NaN,NaN,...,NaN,NaN,0.043000,NaN,NaN,NaN,0.039964,NaN,NaN,0.040924

In [57]:
pd.DataFrame(dfVariable['Variable_Name'].value_counts())

                           Variable_Name
Excess Return                         57
Trans. Vol. (Bil. $)                  52
Cap Rate Spread                       51
Rent Growth                           49
Vacancy Rate                          39
Const. Deliv. (Thous. SF)             36
Ofc. Employ. Growth                   13
Trade Emp. Growth                     13
Trans. Emp. Growth                    13
Mfg. Emp. Growth                      13
Employ. Growth                        13
Census Vacancy Rate                   13
Inst. Vacancy Rate                    12
Price Growth                          12
2+ Unit Permitting                    12
House Price to Income                 12
1+ Unit Permitting                    11
Leis. Emp. Growth                      8
RevPar Growth                          8
Occupancy Rate                         8
Const. Deliv. (Bil. 09 $)              4
Permit Valuation                       3
Retail Sales Growth                    1
Mall Rent Growth                       1
Res. Invest. Share of GDP              1
Strip Rent Growth                      1
IP Growth                              1
Power Rent Growth                      1
2+ Unit Starts                         1
Home Sales                             1
MPF Vacancy Rate                       1
1+ Unit Starts                         1
Mortgage Debt Growth                   1

In [9]:
list(dfVariable.columns)

['Geography_Code',
 'Geography_Name',
 'Property_Code',
 'Property_Name',
 'Variable_Name',
 'Variable_Description',
 '_1982Q1',
 '_1982Q2',
 '_1982Q3',
 '_1982Q4',
 '_1983Q1',
 '_1983Q2',
 '_1983Q3',
 '_1983Q4',
 '_1984Q1',
 '_1984Q2',
 '_1984Q3',
 '_1984Q4',
 '_1985Q1',
 '_1985Q2',
 '_1985Q3',
 '_1985Q4',
 '_1986Q1',
 '_1986Q2',
 '_1986Q3',
 '_1986Q4',
 '_1987Q1',
 '_1987Q2',
 '_1987Q3',
 '_1987Q4',
 '_1988Q1',
 '_1988Q2',
 '_1988Q3',
 '_1988Q4',
 '_1989Q1',
 '_1989Q2',
 '_1989Q3',
 '_1989Q4',
 '_1990Q1',
 '_1990Q2',
 '_1990Q3',
 '_1990Q4',
 '_1991Q1',
 '_1991Q2',
 '_1991Q3',
 '_1991Q4',
 '_1992Q1',
 '_1992Q2',
 '_1992Q3',
 '_1992Q4',
 '_1993Q1',
 '_1993Q2',
 '_1993Q3',
 '_1993Q4',
 '_1994Q1',
 '_1994Q2',
 '_1994Q3',
 '_1994Q4',
 '_1995Q1',
 '_1995Q2',
 '_1995Q3',
 '_1995Q4',
 '_1996Q1',
 '_1996Q2',
 '_1996Q3',
 '_1996Q4',
 '_1997Q1',
 '_1997Q2',
 '_1997Q3',
 '_1997Q4',
 '_1998Q1',
 '_1998Q2',
 '_1998Q3',
 '_1998Q4',
 '_1999Q1',
 '_1999Q2',
 '_1999Q3',
 '_1999Q4',
 '_2000Q1',
 '_2000Q2',
 '_2000Q3',
 '_2000Q4',
 '_2001Q1',
 '_2001Q2',
 '_2001Q3',
 '_2001Q4',
 '_2002Q1',
 '_2002Q2',
 '_2002Q3',
 '_2002Q4',
 '_2003Q1',
 '_2003Q2',
 '_2003Q3',
 '_2003Q4',
 '_2004Q1',
 '_2004Q2',
 '_2004Q3',
 '_2004Q4',
 '_2005Q1',
 '_2005Q2',
 '_2005Q3',
 '_2005Q4',
 '_2006Q1',
 '_2006Q2',
 '_2006Q3',
 '_2006Q4',
 '_2007Q1',
 '_2007Q2',
 '_2007Q3',
 '_2007Q4',
 '_2008Q1',
 '_2008Q2',
 '_2008Q3',
 '_2008Q4',
 '_2009Q1',
 '_2009Q2',
 '_2009Q3',
 '_2009Q4',
 '_2010Q1',
 '_2010Q2',
 '_2010Q3',
 '_2010Q4',
 '_2011Q1',
 '_2011Q2',
 '_2011Q3',
 '_2011Q4',
 '_2012Q1',
 '_2012Q2',
 '_2012Q3',
 '_2012Q4',
 '_2013Q1',
 '_2013Q2',
 '_2013Q3',
 '_2013Q4',
 '_2014Q1',
 '_2014Q2',
 '_2014Q3',
 '_2014Q4',
 '_2015Q1',
 '_2015Q2',
 '_2015Q3',
 '_2015Q4',
 '_2016Q1',
 '_2016Q2',
 '_2016Q3',
 '_2016Q4',
 '_2017Q1',
 '_2017Q2',
 '_2017Q3',
 '_2017Q4',
 '_2018Q1',
 '_2018Q2',
 '_2018Q4']

In [10]:
dfVariable2 = dfVariable.pivot_table(index=['_1982Q1','_1982Q2','_1982Q3','_1982Q4','_1983Q1','_1983Q2','_1983Q3','_1983Q4','_1984Q1','_1984Q2','_1984Q3','_1984Q4','_1985Q1','_1985Q2','_1985Q3','_1985Q4','_1986Q1','_1986Q2','_1986Q3','_1986Q4','_1987Q1','_1987Q2','_1987Q3','_1987Q4','_1988Q1','_1988Q2','_1988Q3','_1988Q4','_1989Q1','_1989Q2','_1989Q3','_1989Q4','_1990Q1','_1990Q2','_1990Q3','_1990Q4','_1991Q1','_1991Q2','_1991Q3','_1991Q4','_1992Q1','_1992Q2','_1992Q3','_1992Q4','_1993Q1','_1993Q2','_1993Q3','_1993Q4','_1994Q1','_1994Q2','_1994Q3','_1994Q4','_1995Q1','_1995Q2','_1995Q3','_1995Q4','_1996Q1','_1996Q2','_1996Q3','_1996Q4','_1997Q1','_1997Q2','_1997Q3','_1997Q4','_1998Q1','_1998Q2','_1998Q3','_1998Q4','_1999Q1','_1999Q2','_1999Q3','_1999Q4','_2000Q1','_2000Q2','_2000Q3','_2000Q4','_2001Q1','_2001Q2','_2001Q3','_2001Q4','_2002Q1','_2002Q2','_2002Q3','_2002Q4','_2003Q1','_2003Q2','_2003Q3','_2003Q4','_2004Q1','_2004Q2','_2004Q3','_2004Q4','_2005Q1','_2005Q2','_2005Q3','_2005Q4','_2006Q1','_2006Q2','_2006Q3','_2006Q4','_2007Q1','_2007Q2','_2007Q3','_2007Q4','_2008Q1','_2008Q2','_2008Q3','_2008Q4','_2009Q1','_2009Q2','_2009Q3','_2009Q4','_2010Q1','_2010Q2','_2010Q3','_2010Q4','_2011Q1','_2011Q2','_2011Q3','_2011Q4','_2012Q1','_2012Q2','_2012Q3','_2012Q4','_2013Q1','_2013Q2','_2013Q3','_2013Q4','_2014Q1','_2014Q2','_2014Q3','_2014Q4','_2015Q1','_2015Q2','_2015Q3','_2015Q4','_2016Q1','_2016Q2','_2016Q3','_2016Q4','_2017Q1','_2017Q2','_2017Q3','_2017Q4','_2018Q1','_2018Q2','_2018Q4'], columns='Variable_Name',values=)

DataError: No numeric types to aggregate

In [23]:
dfVariable2=pd.melt(dfVariable,id_vars=['Geography_Code','Geography_Name','Property_Code','Property_Name','Variable_Name'],value_vars=['_1982Q1','_1982Q2','_1982Q3','_1982Q4','_1983Q1','_1983Q2','_1983Q3','_1983Q4','_1984Q1','_1984Q2','_1984Q3','_1984Q4','_1985Q1','_1985Q2','_1985Q3','_1985Q4','_1986Q1','_1986Q2','_1986Q3','_1986Q4','_1987Q1','_1987Q2','_1987Q3','_1987Q4','_1988Q1','_1988Q2','_1988Q3','_1988Q4','_1989Q1','_1989Q2','_1989Q3','_1989Q4','_1990Q1','_1990Q2','_1990Q3','_1990Q4','_1991Q1','_1991Q2','_1991Q3','_1991Q4','_1992Q1','_1992Q2','_1992Q3','_1992Q4','_1993Q1','_1993Q2','_1993Q3','_1993Q4','_1994Q1','_1994Q2','_1994Q3','_1994Q4','_1995Q1','_1995Q2','_1995Q3','_1995Q4','_1996Q1','_1996Q2','_1996Q3','_1996Q4','_1997Q1','_1997Q2','_1997Q3','_1997Q4','_1998Q1','_1998Q2','_1998Q3','_1998Q4','_1999Q1','_1999Q2','_1999Q3','_1999Q4','_2000Q1','_2000Q2','_2000Q3','_2000Q4','_2001Q1','_2001Q2','_2001Q3','_2001Q4','_2002Q1','_2002Q2','_2002Q3','_2002Q4','_2003Q1','_2003Q2','_2003Q3','_2003Q4','_2004Q1','_2004Q2','_2004Q3','_2004Q4','_2005Q1','_2005Q2','_2005Q3','_2005Q4','_2006Q1','_2006Q2','_2006Q3','_2006Q4','_2007Q1','_2007Q2','_2007Q3','_2007Q4','_2008Q1','_2008Q2','_2008Q3','_2008Q4','_2009Q1','_2009Q2','_2009Q3','_2009Q4','_2010Q1','_2010Q2','_2010Q3','_2010Q4','_2011Q1','_2011Q2','_2011Q3','_2011Q4','_2012Q1','_2012Q2','_2012Q3','_2012Q4','_2013Q1','_2013Q2','_2013Q3','_2013Q4','_2014Q1','_2014Q2','_2014Q3','_2014Q4','_2015Q1','_2015Q2','_2015Q3','_2015Q4','_2016Q1','_2016Q2','_2016Q3','_2016Q4','_2017Q1','_2017Q2','_2017Q3','_2017Q4','_2018Q1','_2018Q2','_2018Q4'])

In [27]:
dfVariable2.to_excel('dfVariable2.xlsx', index  = True)

In [28]:
dfVariableDate=pd.read_excel("CRE Property Index Components Date.xlsx")

In [32]:
list(dfVariableDate.columns)

['Geography_Code',
 'Geography_Name',
 'Property_Code',
 'Property_Name',
 'Variable_Name',
 'Variable_Description',
 datetime.datetime(1982, 3, 31, 0, 0),
 datetime.datetime(1982, 6, 30, 0, 0),
 datetime.datetime(1982, 9, 30, 0, 0),
 datetime.datetime(1982, 12, 31, 0, 0),
 datetime.datetime(1983, 3, 31, 0, 0),
 datetime.datetime(1983, 6, 30, 0, 0),
 datetime.datetime(1983, 9, 30, 0, 0),
 datetime.datetime(1983, 12, 31, 0, 0),
 datetime.datetime(1984, 3, 31, 0, 0),
 datetime.datetime(1984, 6, 30, 0, 0),
 datetime.datetime(1984, 9, 30, 0, 0),
 datetime.datetime(1984, 12, 31, 0, 0),
 datetime.datetime(1985, 3, 31, 0, 0),
 datetime.datetime(1985, 6, 30, 0, 0),
 datetime.datetime(1985, 9, 30, 0, 0),
 datetime.datetime(1985, 12, 31, 0, 0),
 datetime.datetime(1986, 3, 31, 0, 0),
 datetime.datetime(1986, 6, 30, 0, 0),
 datetime.datetime(1986, 9, 30, 0, 0),
 datetime.datetime(1986, 12, 31, 0, 0),
 datetime.datetime(1987, 3, 31, 0, 0),
 datetime.datetime(1987, 6, 30, 0, 0),
 datetime.datetime(1987, 9, 30, 0, 0),
 datetime.datetime(1987, 12, 31, 0, 0),
 datetime.datetime(1988, 3, 31, 0, 0),
 datetime.datetime(1988, 6, 30, 0, 0),
 datetime.datetime(1988, 9, 30, 0, 0),
 datetime.datetime(1988, 12, 31, 0, 0),
 datetime.datetime(1989, 3, 31, 0, 0),
 datetime.datetime(1989, 6, 30, 0, 0),
 datetime.datetime(1989, 9, 30, 0, 0),
 datetime.datetime(1989, 12, 31, 0, 0),
 datetime.datetime(1990, 3, 31, 0, 0),
 datetime.datetime(1990, 6, 30, 0, 0),
 datetime.datetime(1990, 9, 30, 0, 0),
 datetime.datetime(1990, 12, 31, 0, 0),
 datetime.datetime(1991, 3, 31, 0, 0),
 datetime.datetime(1991, 6, 30, 0, 0),
 datetime.datetime(1991, 9, 30, 0, 0),
 datetime.datetime(1991, 12, 31, 0, 0),
 datetime.datetime(1992, 3, 31, 0, 0),
 datetime.datetime(1992, 6, 30, 0, 0),
 datetime.datetime(1992, 9, 30, 0, 0),
 datetime.datetime(1992, 12, 31, 0, 0),
 datetime.datetime(1993, 3, 31, 0, 0),
 datetime.datetime(1993, 6, 30, 0, 0),
 datetime.datetime(1993, 9, 30, 0, 0),
 datetime.datetime(1993, 12, 31, 0, 0),
 datetime.datetime(1994, 3, 31, 0, 0),
 datetime.datetime(1994, 6, 30, 0, 0),
 datetime.datetime(1994, 9, 30, 0, 0),
 datetime.datetime(1994, 12, 31, 0, 0),
 datetime.datetime(1995, 3, 31, 0, 0),
 datetime.datetime(1995, 6, 30, 0, 0),
 datetime.datetime(1995, 9, 30, 0, 0),
 datetime.datetime(1995, 12, 31, 0, 0),
 datetime.datetime(1996, 3, 31, 0, 0),
 datetime.datetime(1996, 6, 30, 0, 0),
 datetime.datetime(1996, 9, 30, 0, 0),
 datetime.datetime(1996, 12, 31, 0, 0),
 datetime.datetime(1997, 3, 31, 0, 0),
 datetime.datetime(1997, 6, 30, 0, 0),
 datetime.datetime(1997, 9, 30, 0, 0),
 datetime.datetime(1997, 12, 31, 0, 0),
 datetime.datetime(1998, 3, 31, 0, 0),
 datetime.datetime(1998, 6, 30, 0, 0),
 datetime.datetime(1998, 9, 30, 0, 0),
 datetime.datetime(1998, 12, 31, 0, 0),
 datetime.datetime(1999, 3, 31, 0, 0),
 datetime.datetime(1999, 6, 30, 0, 0),
 datetime.datetime(1999, 9, 30, 0, 0),
 datetime.datetime(1999, 12, 31, 0, 0),
 datetime.datetime(2000, 3, 31, 0, 0),
 datetime.datetime(2000, 6, 30, 0, 0),
 datetime.datetime(2000, 9, 30, 0, 0),
 datetime.datetime(2000, 12, 31, 0, 0),
 datetime.datetime(2001, 3, 31, 0, 0),
 datetime.datetime(2001, 6, 30, 0, 0),
 datetime.datetime(2001, 9, 30, 0, 0),
 datetime.datetime(2001, 12, 31, 0, 0),
 datetime.datetime(2002, 3, 31, 0, 0),
 datetime.datetime(2002, 6, 30, 0, 0),
 datetime.datetime(2002, 9, 30, 0, 0),
 datetime.datetime(2002, 12, 31, 0, 0),
 datetime.datetime(2003, 3, 31, 0, 0),
 datetime.datetime(2003, 6, 30, 0, 0),
 datetime.datetime(2003, 9, 30, 0, 0),
 datetime.datetime(2003, 12, 31, 0, 0),
 datetime.datetime(2004, 3, 31, 0, 0),
 datetime.datetime(2004, 6, 30, 0, 0),
 datetime.datetime(2004, 9, 30, 0, 0),
 datetime.datetime(2004, 12, 31, 0, 0),
 datetime.datetime(2005, 3, 31, 0, 0),
 datetime.datetime(2005, 6, 30, 0, 0),
 datetime.datetime(2005, 9, 30, 0, 0),
 datetime.datetime(2005, 12, 31, 0, 0),
 datetime.datetime(2006, 3, 31, 0, 0),
 datetime.datetime(2006, 6, 30, 0, 0),
 datetime.datetime(2006, 9, 30, 0, 0),
 datetime.datetime(2006, 12, 31, 0, 0),
 datetime.datetime(2007, 3, 31, 0, 0),
 datetime.datetime(2007, 6, 30, 0, 0),
 datetime.datetime(2007, 9, 30, 0, 0),
 datetime.datetime(2007, 12, 31, 0, 0),
 datetime.datetime(2008, 3, 31, 0, 0),
 datetime.datetime(2008, 6, 30, 0, 0),
 datetime.datetime(2008, 9, 30, 0, 0),
 datetime.datetime(2008, 12, 31, 0, 0),
 datetime.datetime(2009, 3, 31, 0, 0),
 datetime.datetime(2009, 6, 30, 0, 0),
 datetime.datetime(2009, 9, 30, 0, 0),
 datetime.datetime(2009, 12, 31, 0, 0),
 datetime.datetime(2010, 3, 31, 0, 0),
 datetime.datetime(2010, 6, 30, 0, 0),
 datetime.datetime(2010, 9, 30, 0, 0),
 datetime.datetime(2010, 12, 31, 0, 0),
 datetime.datetime(2011, 3, 31, 0, 0),
 datetime.datetime(2011, 6, 30, 0, 0),
 datetime.datetime(2011, 9, 30, 0, 0),
 datetime.datetime(2011, 12, 31, 0, 0),
 datetime.datetime(2012, 3, 31, 0, 0),
 datetime.datetime(2012, 6, 30, 0, 0),
 datetime.datetime(2012, 9, 30, 0, 0),
 datetime.datetime(2012, 12, 31, 0, 0),
 datetime.datetime(2013, 3, 31, 0, 0),
 datetime.datetime(2013, 6, 30, 0, 0),
 datetime.datetime(2013, 9, 30, 0, 0),
 datetime.datetime(2013, 12, 31, 0, 0),
 datetime.datetime(2014, 3, 31, 0, 0),
 datetime.datetime(2014, 6, 30, 0, 0),
 datetime.datetime(2014, 9, 30, 0, 0),
 datetime.datetime(2014, 12, 31, 0, 0),
 datetime.datetime(2015, 3, 31, 0, 0),
 datetime.datetime(2015, 6, 30, 0, 0),
 datetime.datetime(2015, 9, 30, 0, 0),
 datetime.datetime(2015, 12, 31, 0, 0),
 datetime.datetime(2016, 3, 31, 0, 0),
 datetime.datetime(2016, 6, 30, 0, 0),
 datetime.datetime(2016, 9, 30, 0, 0),
 datetime.datetime(2016, 12, 31, 0, 0),
 datetime.datetime(2017, 3, 31, 0, 0),
 datetime.datetime(2017, 6, 30, 0, 0),
 datetime.datetime(2017, 9, 30, 0, 0),
 datetime.datetime(2017, 12, 31, 0, 0),
 datetime.datetime(2018, 3, 31, 0, 0),
 datetime.datetime(2018, 6, 30, 0, 0),
 datetime.datetime(2018, 12, 31, 0, 0)]

In [33]:
dfVariable2

,Geography_Code,Geography_Name,Property_Code,Property_Name,Variable_Name,variable,value
0,ATLNA,Atlanta,APT0,Apartment,2+ Unit Permitting,_1982Q1,NaN
1,ATLNA,Atlanta,APT0,Apartment,Cap Rate Spread,_1982Q1,NaN
2,ATLNA,Atlanta,APT0,Apartment,Census Vacancy Rate,_1982Q1,NaN
3,ATLNA,Atlanta,APT0,Apartment,Employ. Growth,_1982Q1,NaN
4,ATLNA,Atlanta,APT0,Apartment,Excess Return,_1982Q1,NaN
5,ATLNA,Atlanta,APT0,Apartment,Inst. Vacancy Rate,_1982Q1,NaN
6,ATLNA,Atlanta,APT0,Apartment,Rent Growth,_1982Q1,NaN
7,ATLNA,Atlanta,APT0,Apartment,Trans. Vol. (Bil. $),_1982Q1,NaN
8,BOSTN,Boston,APT0,Apartment,2+ Unit Permitting,_1982Q1,NaN
9,BOSTN,Boston,APT0,Apartment,Cap Rate Spread,_1982Q1,NaN
10,BOSTN,Boston,APT0,Apartment,Census Vacancy Rate,_1982Q1,NaN
11,BOSTN,Boston,APT0,Apartment,Employ. Growth,_1982Q1,NaN
12,BOSTN,Boston,APT0,Apartment,Excess Return,_1982Q1,NaN
13,BOSTN,Boston,APT0,Apartment,Inst. Vacancy Rate,_1982Q1,NaN
14,BOSTN,Boston,APT0,Apartment,Rent Growth,_1982Q1,NaN
15,BOSTN,Boston,APT0,Apartment,Trans. Vol. (Bil. $),_1982Q1,NaN
16,CHICG,Chicago,APT0,Apartment,2+ Unit Permitting,_1982Q1,NaN
17,CHICG,Chicago,APT0,Apartment,Cap Rate Spread,_1982Q1,NaN
18,CHICG,Chicago,APT0,Apartment,Census Vacancy Rate,_1982Q1,NaN
19,CHICG,Chicago,APT0,Apartment,Employ. Growth,_1982Q1,NaN
20,CHICG,Chicago,APT0,Apartment,Excess Return,_1982Q1,NaN
21,CHICG,Chicago,APT0,Apartment,Inst. Vacancy Rate,_1982Q1,NaN
22,CHICG,Chicago,APT0,Apartment,Rent Growth,_1982Q1,NaN
23,CHICG,Chicago,APT0,Apartment,Trans. Vol. (Bil. $),_1982Q1,NaN
24,DALLS,Dallas,APT0,Apartment,2+ Unit Permitting,_1982Q1,NaN
25,DALLS,Dallas,APT0,Apartment,Cap Rate Spread,_1982Q1,NaN
26,DALLS,Dallas,APT0,Apartment,Census Vacancy Rate,_1982Q1,NaN
27,DALLS,Dallas,APT0,Apartment,Employ. Growth,_1982Q1,NaN
28,DALLS,Dallas,APT0,Apartment,Excess Return,_1982Q1,NaN
29,DALLS,Dallas,APT0,Apartment,Inst. Vacancy Rate,_1982Q1,NaN
...,...,...,...,...,...,...,...
68031,SEATL,Seattle,RET0,Retail,Const. Deliv. (Thous. SF),_2018Q4,620.000000
68032,SEATL,Seattle,RET0,Retail,Excess Return,_2018Q4,0.053050
68033,SEATL,Seattle,RET0,Retail,Trans. Vol. (Bil. $),_2018Q4,1.224054
68034,SEATL,Seattle,RET0,Retail,Vacancy Rate,_2018Q4,0.046630
68035,SFRAN,San Francisco,RET0,Retail,Cap Rate Spread,_2018Q4,0.015850
68036,SFRAN,San Francisco,RET0,Retail,Const. Deliv. (Thous. SF),_2018Q4,100.000000
68037,SFRAN,San Francisco,RET0,Retail,Excess Return,_2018Q4,0.063500
68038,SFRAN,San Francisco,RET0,Retail,Rent Growth,_2018Q4,0.035000
68039,SFRAN,San Francisco,RET0,Retail,Trans. Vol. (Bil. $),_2018Q4,0.734318
68040,SFRAN,San Francisco,RET0,Retail,Vacancy Rate,_2018Q4,0.017162
68041,SJOSE,San Jose,RET0,Retail,Cap Rate Spread,_2018Q4,0.023250
68042,SJOSE,San Jose,RET0,Retail,Const. Deliv. (Thous. SF),_2018Q4,450.000000
68043,SJOSE,San Jose,RET0,Retail,Excess Return,_2018Q4,0.056500
68044,SJOSE,San Jose,RET0,Retail,Rent Growth,_2018Q4,0.015000
68045,SJOSE,San Jose,RET0,Retail,Trans. Vol. (Bil. $),_2018Q4,1.169582
68046,SJOSE,San Jose,RET0,Retail,Vacancy Rate,_2018Q4,0.077628
68047,USTOT,United States,RET0,Retail,Cap Rate Spread,_2018Q4,0.018350
68048,USTOT,United States,RET0,Retail,Const. Deliv. (Bil. 09 $),_2018Q4,32.511042
68049,USTOT,United States,RET0,Retail,Excess Return,_2018Q4,0.016696
68050,USTOT,United States,RET0,Retail,Mall Rent Growth,_2018Q4,0.022000
68051,USTOT,United States,RET0,Retail,Power Rent Growth,_2018Q4,0.015000
68052,USTOT,United States,RET0,Retail,Retail Sales Growth,_2018Q4,0.066824
68053,USTOT,United States,RET0,Retail,Strip Rent Growth,_2018Q4,0.017000
68054,USTOT,United States,RET0,Retail,Trans. Vol. (Bil. $),_2018Q4,56.051777
68055,USTOT,United States,RET0,Retail,Vacancy Rate,_2018Q4,0.069000
68056,WASDC,Washington,RET0,Retail,Cap Rate Spread,_2018Q4,0.037650
68057,WASDC,Washington,RET0,Retail,Const. Deliv. (Thous. SF),_2018Q4,1400.000000
68058,WASDC,Washington,RET0,Retail,Excess Return,_2018Q4,0.037225
68059,WASDC,Washington,RET0,Retail,Trans. Vol. (Bil. $),_2018Q4,1.812786
68060,WASDC,Washington,RET0,Retail,Vacancy Rate,_2018Q4,0.040924

In [36]:
## wrong
pd.pivot_table(dfVariable2,values=['Variable_Name'])

ValueError: No group keys passed!

In [44]:
##long format to wide format for 'variable name'
dfVariable2_Wide = dfVariable2.pivot_table(index=['variable','Geography_Code','Geography_Name','Property_Code','Property_Name'], columns='Variable_Name', values='value')

In [56]:
pd.DataFrame(list(dfVariable2_Wide.columns))

                            0
0          1+ Unit Permitting
1              1+ Unit Starts
2          2+ Unit Permitting
3              2+ Unit Starts
4             Cap Rate Spread
5         Census Vacancy Rate
6   Const. Deliv. (Bil. 09 $)
7   Const. Deliv. (Thous. SF)
8              Employ. Growth
9               Excess Return
10                 Home Sales
11      House Price to Income
12                  IP Growth
13         Inst. Vacancy Rate
14          Leis. Emp. Growth
15           MPF Vacancy Rate
16           Mall Rent Growth
17           Mfg. Emp. Growth
18       Mortgage Debt Growth
19             Occupancy Rate
20        Ofc. Employ. Growth
21           Permit Valuation
22          Power Rent Growth
23               Price Growth
24                Rent Growth
25  Res. Invest. Share of GDP
26        Retail Sales Growth
27              RevPar Growth
28          Strip Rent Growth
29          Trade Emp. Growth
30         Trans. Emp. Growth
31       Trans. Vol. (Bil. $)
32               Vacancy Rate

In [46]:
dfVariable2_Wide.to_excel('dfVariable2Wide.xlsx', index  = True)

#### Switch from pivot table to dataframe

In [58]:
dfVariable2_Widedf=dfVariable2_Wide.reset_index().rename_axis(None,axis=1)

In [59]:
dfVariable2_Widedf

,variable,Geography_Code,Geography_Name,Property_Code,Property_Name,1+ Unit Permitting,1+ Unit Starts,2+ Unit Permitting,2+ Unit Starts,Cap Rate Spread,...,Price Growth,Rent Growth,Res. Invest. Share of GDP,Retail Sales Growth,RevPar Growth,Strip Rent Growth,Trade Emp. Growth,Trans. Emp. Growth,Trans. Vol. (Bil. $),Vacancy Rate
0,_1982Q1,ATLNA,Atlanta,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,_1982Q1,ATLNA,Atlanta,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,_1982Q1,ATLNA,Atlanta,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,_1982Q1,ATLNA,Atlanta,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,_1982Q1,BOSTN,Boston,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,_1982Q1,BOSTN,Boston,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,_1982Q1,BOSTN,Boston,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,_1982Q1,BOSTN,Boston,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,_1982Q1,BOSTN,Boston,OWN0,For-Sale,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,_1982Q1,BOSTN,Boston,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,_1982Q1,CHICG,Chicago,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,_1982Q1,CHICG,Chicago,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,_1982Q1,CHICG,Chicago,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,_1982Q1,CHICG,Chicago,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,_1982Q1,CHICG,Chicago,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,_1982Q1,DALLS,Dallas,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,_1982Q1,DALLS,Dallas,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,_1982Q1,DALLS,Dallas,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,_1982Q1,DALLS,Dallas,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,_1982Q1,DENVR,Denver,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,_1982Q1,ILEMP,Inland Empire,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,_1982Q1,ILEMP,Inland Empire,OWN0,For-Sale,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,_1982Q1,LSAGL,Los Angeles,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,_1982Q1,LSAGL,Los Angeles,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,_1982Q1,LSAGL,Los Angeles,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,_1982Q1,LSAGL,Los Angeles,OFC0,Office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,_1982Q1,LSAGL,Los Angeles,OWN0,For-Sale,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,_1982Q1,LSAGL,Los Angeles,RET0,Retail,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,_1982Q1,MIAMI,Miami,OWN0,For-Sale,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,_1982Q1,NYORK,New York,APT0,Apartment,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10554,_2018Q4,SDIGO,San Diego,OFC0,Office,NaN,NaN,NaN,NaN,0.03725,...,NaN,0.020998,NaN,NaN,NaN,NaN,NaN,NaN,2.541578,0.118787
10555,_2018Q4,SDIGO,San Diego,OWN0,For-Sale,3992.318771,NaN,NaN,NaN,NaN,...,0.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10556,_2018Q4,SDIGO,San Diego,RET0,Retail,NaN,NaN,NaN,NaN,0.02715,...,NaN,-0.020000,NaN,NaN,NaN,NaN,NaN,NaN,1.664430,0.046271
10557,_2018Q4,SEATL,Seattle,APT0,Apartment,NaN,NaN,5256.339667,NaN,0.01860,...,NaN,0.046552,NaN,NaN,NaN,NaN,NaN,NaN,4.114950,NaN
10558,_2018Q4,SEATL,Seattle,IND0,Industrial,NaN,NaN,NaN,NaN,0.01350,...,NaN,0.090000,NaN,NaN,NaN,NaN,0.040297,0.021000,0.962553,0.042432
10559,_2018Q4,SEATL,Seattle,OFC0,Office,NaN,NaN,NaN,NaN,0.02885,...,NaN,0.010861,NaN,NaN,NaN,NaN,NaN,NaN,4.216027,0.075428
10560,_2018Q4,SEATL,Seattle,OWN0,For-Sale,6776.092488,NaN,NaN,NaN,NaN,...,0.132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10561,_2018Q4,SEATL,Seattle,RET0,Retail,NaN,NaN,NaN,NaN,0.02845,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.224054,0.046630
10562,_2018Q4,SFRAN,San Francisco,APT0,Apartment,NaN,NaN,1926.493240,NaN,0.00650,...,NaN,0.036056,NaN,NaN,NaN,NaN,NaN,NaN,1.610031,NaN
10563,_2018Q4,SFRAN,San Francisco,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10564,_2018Q4,SFRAN,San Francisco,OFC0,Office,NaN,NaN,NaN,NaN,0.02755,...,NaN,0.037195,NaN,NaN,NaN,NaN,NaN,NaN,4.375410,0.077355
10565,_2018Q4,SFRAN,San Francisco,OWN0,For-Sale,2046.102976,NaN,NaN,NaN,NaN,...,0.096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10566,_2018Q4,SFRAN,San Francisco,RET0,Retail,NaN,NaN,NaN,NaN,0.01585,...,NaN,0.035000,NaN,NaN,NaN,NaN,NaN,NaN,0.734318,0.017162
10567,_2018Q4,SJOSE,San Jose,APT0,Apartment,NaN,NaN,2065.242980,NaN,0.01330,...,NaN,0.043039,NaN,NaN,NaN,NaN,NaN,NaN,1.112461,NaN
10568,_2018Q4,SJOSE,San Jose,IND0,Industrial,NaN,NaN,NaN,NaN,0.02840,...,NaN,0.050000,NaN,NaN,NaN,NaN,0.008000,0.005000,2.791184,0.055322
10569,_2018Q4,SJOSE,San Jose,OFC0,Office,NaN,NaN,NaN,NaN,0.02995,...,NaN,0.040676,NaN,NaN,NaN,NaN,NaN,NaN,4.776058,0.087713
10570,_2018Q4,SJOSE,San Jose,OWN0,For-Sale,2785.382370,NaN,NaN,NaN,NaN,...,0.150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10571,_2018Q4,SJOSE,San Jose,RET0,Retail,NaN,NaN,NaN,NaN,0.02325,...,NaN,0.015000,NaN,NaN,NaN,NaN,NaN,NaN,1.169582,0.077628
10572,_2018Q4,USTOT,United States,APT0,Apartment,NaN,NaN,NaN,80.47471,0.00970,...,NaN,0.024000,NaN,NaN,NaN,NaN,NaN,NaN,152.212809,NaN
10573,_2018Q4,USTOT,United States,HOT0,Hotel,NaN,NaN,NaN,NaN,0.03270,...,NaN,NaN,NaN,NaN,0.036,NaN,NaN,NaN,NaN,NaN
10574,_2018Q4,USTOT,United States,IND0,Industrial,NaN,NaN,NaN,NaN,0.01210,...,NaN,0.055000,NaN,NaN,NaN,NaN,0.008676,0.016606,73.709479,0.049000
10575,_2018Q4,USTOT,United States,OFC0,Office,NaN,NaN,NaN,NaN,0.01355,...,NaN,0.029888,NaN,NaN,NaN,NaN,NaN,NaN,118.560772,0.136708
10576,_2018Q4,USTOT,United States,OWN0,For-Sale,NaN,311.395335,NaN,NaN,NaN,...,0.059,NaN,0.03909,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10577,_2018Q4,USTOT,United States,RET0,Retail,NaN,NaN,NaN,NaN,0.01835,...,NaN,NaN,NaN,0.066824,NaN,0.017,NaN,NaN,56.051777,0.069000
10578,_2018Q4,WASDC,Washington,APT0,Apartment,NaN,NaN,4084.503651,NaN,0.02140,...,NaN,0.020437,NaN,NaN,NaN,NaN,NaN,NaN,7.996256,NaN
10579,_2018Q4,WASDC,Washington,HOT0,Hotel,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10580,_2018Q4,WASDC,Washington,IND0,Industrial,NaN,NaN,NaN,NaN,NaN,...,NaN,0.058821,NaN,NaN,NaN,NaN,0.029000,0.053000,3.752298,0.090912
10581,_2018Q4,WASDC,Washington,OFC0,Office,NaN,NaN,NaN,NaN,0.03455,...,NaN,0.016946,NaN,NaN,NaN,NaN,NaN,NaN,8.659220,0.174982
10582,_2018Q4,WASDC,Washington,OWN0,For-Sale,6872.866926,NaN,NaN,NaN,NaN,...,0.038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10583,_2018Q4,WASDC,Washington,RET0,Retail,NaN,NaN,NaN,NaN,0.03765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.812786,0.040924

In [71]:
pd.DataFrame(list(dfVariable2_Widedf['variable'].unique())).to_excel('DateLookup.xlsx', index  = True)

In [60]:
dfVariable2_Widedf.to_excel('dfVariable2Widedf.xlsx', index  = True)